- modules/core/graph/resolvers/streams.js
- modules/core/graph/schemas/streams.graphql
- modules/core/services/users.js
- modules/core/tests/graphSubs.spec.js
- modules/shared/index.js
Main changes: 
- Removes streamPermissionGranted and streamPermissionRevoked subs; they conceptually fallback on userStreamCreated/Deleted. 
- The userStreamCreated event payload will contain a `sharedBy` userId field in case you are notifying Y that X shared a stream with them. Same for userStreamDeleted - will contain a `revokedBy userId field. 
- renames tests to clarify a bit more what's being tested (ie, `A user (me) should be notified when a stream is created`).
> Stream Subscriptions Cleanup

- frontend/src/AppAuth.vue
- modules/auth/migrations/2020-05-29-apps.js
- modules/auth/strategies/google.js
- modules/core/graph/resolvers/streams.js
- modules/core/graph/schemas/streams.graphql
- modules/core/migrations/000-core.js
- modules/core/services/streams.js
- closes #39; doesn't implement schema directives (they are not valid for input types, thx graphql!), but implements db level constraints on max length (min length is not enforceable w/o nasty tricks)
- closes #46 - no special implementation tricks here.   
- user avatar is now automatically grabbed via google auth route
- closes #42, fixes #43 and closes #32 too with a simple `v-if` statement in the auth app.
> 🧹 Various Fixes & Improvements

- Dockerfile
- docker-compose.yaml
When starting the server via docker-compose currently the server starts up faster than the postgres
instance. This causes the server app to crash. The fix now adds a wait script that pings the
database and the cache containers unit they properly start up. This delays the server boot until all
deps are started.
this fixes #87
> Fix server container wait for database

- packages/frontend/src/components/ListItemPersonalAccessToken.vue
- packages/frontend/src/components/ListItemUserApp.vue
- packages/frontend/src/components/ServerInfoCard.vue
- packages/frontend/src/components/UserAuthorisedApps.vue
- packages/frontend/src/components/dialogs/BranchEditDialog.vue
- packages/frontend/src/components/dialogs/BranchNewDialog.vue
- packages/frontend/src/components/dialogs/EditStreamDialog.vue
- packages/frontend/src/components/dialogs/NewAppDialog.vue
- packages/frontend/src/components/dialogs/NewStreamDialog.vue
- packages/frontend/src/components/dialogs/StreamDescriptionDialog.vue
- packages/frontend/src/components/dialogs/StreamShareDialog.vue
- packages/frontend/src/components/dialogs/TokenDialog.vue
- packages/frontend/src/components/dialogs/UserDialog.vue
- packages/frontend/src/views/Branch.vue
- packages/frontend/src/views/Commit.vue
- packages/frontend/src/views/StreamMain.vue
- packages/frontend/src/views/Streams.vue
adds tracking in the frontend for all the stuff you'd expect and removes redundant tracking for pages that don't need it
we're now tracking
- streams: create, update, and delete
- branches: create, update, and delete
- commits: update
- user: update
- apps: create and delete
- tokens: create and delete
> 🛰 feat(telemetry): track actions & remove page track

- packages/viewer/src/modules/Converter.js
**Non-breaking changes**: Arcs and Circles had 2 different bugs that Izzy discovered at once!
> Viewer: Arc and Circle conversion fix

- packages/server/.env-example
- packages/server/modules/auth/strategies.js
- packages/server/modules/auth/strategies/azure-ad.js
Create a new strategy to enable authentication via Azure AD
You will need to create an App registration with the `id_token` permission added.
> feat(auth): Add Azure AD auth option

- packages/frontend/src/App.vue
- packages/frontend/src/components/Renderer.vue
- packages/frontend/src/components/SpeckleLoading.vue
- packages/frontend/src/router/index.js
- packages/frontend/src/views/EmbedViewer.vue
- packages/frontend/src/views/Stream.vue
- packages/frontend/src/views/StreamMain.vue
Viewer can now be embedded!! 🥳 It should work with public streams AND private streams **if** you are already logged in to the server (@didimitrie is this ok or is it bad security practice??)
**How does it work?**
Embed mode lives in it's own route => `YOUR_SERVER_URL/embed`. This route also accepts several query parameters:
- **stream**: The stream ID of the object to display
- **branch (optional)**: The branch to fetch the objects from
- **commit (optional)**: The specific commit id to display
- **object (optional)**: The specific object id to display
**IMPORTANT**: Do note that all optional parameters are mutually exclusive. Object has higher priority than commit and higher than branch
In any stream page, you can get the appropriate embed URL and iframe code from the Viewer toolbar: …
> Frontend: Viewer can now be embedded in iframe.

- packages/frontend/src/components/Renderer.vue
- packages/frontend/src/views/EmbedViewer.vue
Fixes specklesystems/admin#71
- Adds responsiveness to top buttons in EmbedView.vue
- Removes interaction events from detail tags
- Hides details by default when screen is small.
- Stream name and branch name are truncated to prevent overflow.
- In `Renderer.vue`, added a condition to remove "Selection Details" from the selection button, and swap it for an icon, when the screen is small
> Fix: Embed view improvements for small iframes/screens

- packages/viewer/src/modules/Converter.js
Fixes #270
Added `BoxToBufferGeometry` method in `converter.js`
Tested with several boxes of various units and positons.
Also opened some pre-existing complex streams to ensure no bboxes were being rendered as a side effect of this.
> fix(viewer): Adds box conversion to buffer geometry

- packages/frontend/src/components/GlobalsBuilder.vue
- packages/frontend/src/views/Globals.vue
- packages/frontend/src/views/StreamMain.vue
- removes create globals button on stream if you don't have permission + adds some text explaining why you can't create globals
- disables instead of hides the save button on globals page if you don't have permission (just to make it a bit more obvi. there is still text there also that tells you why you can't save. i tried a tooltip on the disabled button but decided against it as it looked v weird as the style is diff from in built button tooltips)
- hides commits to globals branch from the little warning on the main page you get when there's newer commits on a different branch 
closes #296
> fix(frontend): globals permisisons

- packages/server/modules/webhooks/graph/resolvers/webhooks.js
- packages/server/modules/webhooks/graph/schemas/webhooks.graphql
- packages/server/modules/webhooks/services/webhooks.js
started implementing a `webhooks` query (extension on `stream`) and the basic create, update, delete mutations. opening a pr for the purpose of discussion!
some questions:
1. should we change the name of the `events` column in `webhooks_config` to something else (triggers, actions, etc)? 
imo it's a bit confusing bc of the `webhooks_events` table. my intuition is that `events` on a webhook should return the history, not the actions that the webhook will be notified for. the services are also named as `dispatchStreamEvent` and `getLastWebhookEvents` for getting the history
2.  is there a reason for the `events` column beaing a json object? 
it seems simpler for it to be a list of strings eg `["branch_create", "commit_create", "stream_update"]`. this would also make it consistent with other …
> feat(webhooks): initial gql queries & mutations

- packages/frontend/src/components/SidebarStream.vue
- packages/frontend/src/components/admin/AdminCard.vue
- packages/frontend/src/components/settings/WebhookForm.vue
- packages/frontend/src/graphql/webhook.gql
- packages/frontend/src/graphql/webhooks.gql
- packages/frontend/src/router/index.js
- packages/frontend/src/views/settings/SettingsGeneral.vue
- packages/frontend/src/views/settings/SettingsWebhooks.vue
- packages/frontend/src/views/settings/StreamSettings.vue
- packages/server/modules/webhooks/graph/schemas/webhooks.graphql
- packages/server/modules/webhooks/services/webhooks.js
- packages/server/modules/webhooks/tests/webhooks.spec.js
- stole sidebar from admin panel
- added settings page visible if you are stream owner
- only verifying webhook urls by starting w http/s - is that cool? wasn't sure how much to enforce 
- blocked if you don't have access or stream doesn't exist
> feat(frontend): settings page for webhooks & details

- packages/frontend/src/views/Frontend_re.vue
for some reason, they work fine locally, but when built they're not aligned properly
> fix(frontend): hacks around css bug re bottom nav buttons

- packages/frontend/src/router/index.js
- packages/frontend/src/views/stream/Branch.vue
possibly we need to check the streamwrapper parsing logic (.NET & py) for getting branch names.
> fix(frontend): branches with / in their names work again now;

- packages/frontend/src/embed/EmbedApp.vue
- packages/frontend/src/embed/embedApp.js
Pretty much self explanatory. We should now get stats for all embed views.
> Embed: Adds matomo tracking under 'embed/view'

- packages/frontend/Dockerfile
- packages/objectloader/package-lock.json
When building the docker image, the viewer package was pulling the latest `ObjectLoader` from `npm` instead of using the local package.
Modified the Dockerfile in `frontend` to install it from the repo instead.
Special thanks to @cristi8 for the 2 liner quick fix!
> fix(docker): Build viewer with local ObjectLoader

- packages/server/modules/core/services/branches.js
- packages/server/modules/core/tests/branches.spec.js
> feat((server) branche ordering): query branches without cursor orders by createdAt

- packages/viewer/package.json
- packages/viewer/src/modules/converter/Converter.js
Fixes the P0 part of #444:
- Mesh faces with 3/4 cardinality indicators will now be converted as triangles/quads respecfully, previosuly they were ignored and only faces with 0/1 indicators would be converted.
- N-gon faces on a mesh will be ignored, previosuly, the entire mesh object would be ignored.
The seccond part of #444, Full N-gon conversion, is still not complete, and will likley require a triangulation function.
Has been tested in the example.html viewer and behaves expectedly.
> Updated viewer conversion to support 3,4 cardinality faces, and not throw exception when n-gon faces are present

- packages/objectloader/index.js
null type is an object, so nulls here were throwing:
`"TypeError: Cannot read property 'referencedId' of null"`
checking and continuing when nulls are encountered instead
was no one else encountering this/am i missing something?
this is currently borking sketchup as most new objects have nulls and thus can no longer be received
> fix(objectloader): check for nulls and continue

- packages/frontend/src/cleanup/components/viewer/Resource.vue
- packages/frontend/src/cleanup/components/viewer/ResourceGroup.vue
- packages/frontend/src/cleanup/pages/stream/CommitObjectViewer.vue
Based on user feedback from the forum (closes #522):
- keeps track of removed overlay resources and allows re-adding them
- allows for collapsing all loaded resources (if more than one)
> Improves loaded resources display in commit/object viewer

- packages/viewer/src/modules/converter/Converter.js
- packages/viewer/src/modules/converter/MeshTriangulationHelper.js
- Fixes issue with quad/n-gon only geometry (with a vertices or face count over `UInt16.MaxValue = 65535`) being displayed incorrectly in the viewer.
- The hotfix for this issue #551 fixed only Quad only geometry.
- This fix should also fix n-gon only geometry.
- Re-adds proper triangulation of concave quads (regressed in the hotfix)
- This fix works by Ensures that a `Uint32BufferAttribute` will be used (if needed) for face index buffer.
See discussion https://speckle.community/t/color-mesh-visualization-breaking-with-new-web-viewer-update/2282
- Also Fixes a somewhat unrelated issue with n-gon triangulation that would cause ear clipping to sometimes clip an external ear. This was caused by some wonky vector maths.
> Viewer: Fixed issue with n-gon trianguation of quad/n-gon only meshes leading to corrupted geometry in the viewer

- packages/server/modules/previews/index.js
set the cache-control header for preview images, to allow browser cache of max 1 week
> previews cache control

- .gitignore
- packages/fileimport-service/ifc/parser.js
- packages/fileimport-service/src/daemon.js
Fixes #454 
Changes the resulting structure of an imported IFC file:
- First 3 levels of the IFC file (Project, Site, Building) will have their `children` and `spatialChildren` extracted directly as properties of their parent, as opposed to having them in as items in an array.
- The child name will be used as the `key`. If two or more children have the same name, a suffix will be added to any subsequent element with that name.
- This behaviour can be customised in the `specialTypes` input of the `traverse` function.
Refactored the processing of `rawChildren` and `rawSpatialChildren` into a new function -> `processSubElements` that is also used now to extract the `propertySets` of any object.
Finally, I modified the detaching process so that things like `IfcOwnerHistory` will also be …
> IFC Service: Reshaping of properties + pset extraction

- packages/frontend/src/main/navigation/MainNav.vue
turned out to be a weird Vue/Vuetify bug, read more: https://github.com/vuetifyjs/vuetify/issues/10578#issuecomment-1082814438
> fix(frontend): fixing streams nav group activator disappearing occasionally

- .circleci/build.sh
- .circleci/config.yml
- .circleci/publish_helm_chart.sh
- ci: add get version job
- fix workspace folder
- version dependecies
- persist envvars to workspace
- set speckle version
- disable file based env var
- echo
- command
- echo speckle version
- save to workspace
- add to bash_env
- cleanup
- add workspace envvar persistence
- dot dot
- add image version to helm chart build
> unified build number in docker tagging

- package.json
- packages/fileimport-service/package.json
- packages/frontend/package.json
- packages/objectloader/package.json
- packages/preview-service/package.json
- packages/server/package-lock.json
- packages/server/package.json
- packages/viewer/package.json
- packages/webhook-service/package.json
i tested out node 14 locally and it still allowed me to use node 16 packages, so doesn't seem that this check is even strictly followed, but it at least shows what's expected
> chore: adding node version checks + migrating server lock back to new format

- packages/frontend/src/main/store/index.js
Fixes a bug spotted by @izzylys whereby filters of only `colorBy` props were not correctly set from url query params.
> fix(frontend): fixes filter setting of exclusive colorBy prop 

- .circleci/config.yml
- packages/server/bootstrap.js
> fix: throwing error if running tests without .env.test

- packages/frontend/src/main/components/stream/globals/GlobalsEntry.vue
- packages/frontend/src/main/pages/stream/TheGlobals.vue
closes #463 
tested it out locally on Edge & Firefox
> feat(frontend): globals editor explicit drag handles

- package.json
- packages/frontend/src/main/components/viewer/CommentAddOverlay.vue
- packages/frontend/src/main/components/viewer/CommentsOverlay.vue
- packages/frontend/src/main/components/viewer/ViewerBubbles.vue
- yarn.lock
1. Now that we're on yarn workspaces, we can finally use `three.js` as a normal import in `frontend` without webpack bundling three.js twice locally.
2. I used "resolutions" to get rid of some duplicate dependencies that got bundled twice in the frontend build. Some very small duplicates remain, because I'd rather a few extra kb gets bundled in than we complicate the dependency graph too much using "resolutions"
Regarding testing: I tried building every package locally (through `yarn build` from root) and it seemed to go through just fine.
> chore(frontend): fixing three.js imports & getting rid of some duplicate packages

- .husky/pre-commit
- packages/server/modules/comments/graph/resolvers/comments.js
- packages/server/modules/comments/services/index.js
- packages/server/modules/comments/tests/comments.spec.js
- packages/server/package.json
- yarn.lock
Frontend works the same as before (linkifies comment.text & renders the HTML through v-html), but from now on the backend runs comment.text through `sanitize-html` both before creating new comments and also when retrieving them (in case it's an older comment with HTML in it)
> feat(backend): comment reply text xss fix

- packages/frontend/src/main/components/common/UserAvatar.vue
- packages/frontend/src/main/dialogs/BranchEditDialog.vue
- packages/frontend/src/main/dialogs/NewBranch.vue
- packages/frontend/src/main/navigation/StreamNav.vue
- packages/frontend/src/main/pages/stream/TheBranch.vue
Fixed 3 bugs actually:
1. The branch entity remaining in the cache after it's deleted, causing issues later on (e.g. when creating a new one with the same name and trying to delete it). At first I tried to resolve this without refetching from server & just updating the Apollo cache, but the ApolloClientv2 cache eviction utilities are nonexistant (there are better ones in v3) so it was easier to refetch
2. The branch edit dialog component mutated its inputs which shouldn't be done. In this case it wasn't a mutation of the props, but the data that comes directly from the Apollo cache. So previously while you were changing the name of the branch, you were making direct changes to the apollo cache.
3. Fix for the issue Jedd mentioned once where the User Avatar hover menu closes once you …
> fix(frontend): branch stale cache bug when creating/deleting them

- packages/frontend/src/main/components/common/CommitPreviewCard.vue
- packages/frontend/src/main/components/common/PreviewImage.vue
- packages/frontend/src/main/components/common/StreamPreviewCard.vue
- packages/preview-service/routes/preview.js
- packages/server/modules/previews/index.js
changes:
- preview service generates full 360 images now
- preview image component loads on hover
- preview image component backwards compat with non-360 image angles
- adds optional angle arguments in all preview routes & removes superflous route
Quick demo:
https://user-images.githubusercontent.com/7696515/169804357-4a4ac3a9-3de2-475a-b257-e4adbfbb526e.mov
> feat(frontend): animated preview images

- packages/frontend/src/main/components/common/PreviewImage.vue
- packages/preview-service/bg_service/index.js
- packages/preview-service/package-lock.json
- packages/preview-service/package.json
- packages/preview-service/routes/preview.js
- yarn.lock
Frontend changes: 
- Prevents bouts of severe `yolo sweeping` DDoS-ing the server by 
- adding a 500ms timeout on hover
- cancelling image fetch request via an `AbortController` (TIL)
Preview service **major** changes (but not critical): previews for an object now generate one single image from the default angle (`0`) and a stitched 360 degree that can be requested via `all`. This reduces the amount of fetch requests needed to display the preview from 24 to 1. 
Here's an example 360: 
The extra padding between frames is to enable us to properly display them in a responsive rectangle.
> 3D previews fixes

- packages/frontend/src/main/components/viewer/ViewerFilters.vue
The embedded viewer either doesn't implement the event-hub or doesn't add it at mount time for the Viewer Filter component. Consequently, this is noisy with associated errors of accessing the $on event triggers for $eventHub.
This edit makes the addition of the $on event listener conditional on the $eventHub being instantiated.
> Silencing the noisy Embedded Viewer console log

- .circleci/config.yml
Turns out, i was dumb, and couldn't pass in commands to the minio container startup for some reason.
Now S3 storage can also be part of the integration tests
> Add minio container to the test deps

- packages/fileimport-service/knex.js
- packages/preview-service/knex.js
- packages/server/knexfile.js
- packages/webhook-service/src/knex.js
An issue arose after merging #805.
Turns out it doesn't play nice with streaming connections as per:
https://github.com/vitaly-t/pg-promise/issues/715
https://github.com/brianc/node-postgres/issues/1860
https://github.com/brianc/node-postgres/pull/2560
based on the [knex connection pool docs](https://knexjs.org/guide/#pool), setting the min connections to 0 should be good enough.
> Remove Query timeout

- .gitignore
In the event of an error in VSCode, the IDE produces log files in the .vscode directory.  These log files should
never be checked in to the project as they are specific to the error on the developer's local machine.
> chore(.gitignore): ignore VSCode log files

- workspace.code-workspace
Making helm one-click away in the VSCode workspace.
> docs(vscode workspace): adds Helm as a top-level to VSCode workspace

- utils/helm/speckle-server/Chart.yaml
Adds the Speckle cube logo to the Helm chart
Fixes helm lint warning.
> docs(helm chart): include logo

- utils/helm/speckle-server/templates/deployment-backend.yml
- utils/helm/speckle-server/templates/deployment-fileimport-service.yml
- utils/helm/speckle-server/templates/deployment-frontend.yml
- utils/helm/speckle-server/templates/deployment-monitor-deployment.yml
- utils/helm/speckle-server/templates/deployment-preview-service.yml
- utils/helm/speckle-server/templates/deployment-webhook-service.yml
- utils/helm/speckle-server/templates/services.yml
- utils/helm/speckle-server/values.yaml
`imagePullPolicy` can be configured.
Pod template keys are now in alphabetical order.
**Note**: based on top of https://github.com/specklesystems/speckle-server/pull/873
Fixes https://github.com/specklesystems/speckle-server/issues/869
> Configurable `imagePullPolicy`

- packages/frontend/Dockerfile
- packages/server/Dockerfile
this prevents breaking the existing deployments which do not provide this env variable
> fix(frontend container): add default value for FILE_SIZE_LIMIT_MB

- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/configmap-db-certificate.yml
- utils/helm/speckle-server/templates/fileimport_service/_helpers.tpl
- utils/helm/speckle-server/templates/fileimport_service/deployment.yml
- utils/helm/speckle-server/templates/fileimport_service/service.yml
- utils/helm/speckle-server/templates/frontend/_helpers.tpl
- utils/helm/speckle-server/templates/frontend/deployment.yml
- utils/helm/speckle-server/templates/frontend/service.yml
- utils/helm/speckle-server/templates/ingress.yml
- utils/helm/speckle-server/templates/monitoring/_helpers.tpl
- utils/helm/speckle-server/templates/monitoring/deployment.yml
- utils/helm/speckle-server/templates/monitoring/service.yml
- utils/helm/speckle-server/templates/namespace.yml
- utils/helm/speckle-server/templates/preview_service/_helpers.tpl
- utils/helm/speckle-server/templates/preview_service/deployment.yml
- utils/helm/speckle-server/templates/preview_service/service.yml
- utils/helm/speckle-server/templates/server/_helpers.tpl
- utils/helm/speckle-server/templates/server/deployment.yml
- utils/helm/speckle-server/templates/server/service.yml
- utils/helm/speckle-server/templates/servicemonitor.yml
- utils/helm/speckle-server/templates/test/_helpers.tpl
- utils/helm/speckle-server/templates/test/deployment.yml
- utils/helm/speckle-server/templates/webhook_service/_helpers.tpl
- utils/helm/speckle-server/templates/webhook_service/deployment.yml
- utils/helm/speckle-server/templates/webhook_service/service.yml
- utils/helm/speckle-server/values.yaml
Helm best practices recommend use of standard labels
https://helm.sh/docs/chart_best_practices/labels/#standard-labels
This PR adds these standard labels to all deployed resources.
This is an additive change that is not breaking.
There is some duplication of helper methods, but this allows future flexibility to move the separate components to their own sub-charts in the future.
Additional changes:
* allows `monitoring` and `test` pod resources to be configurable
fixes https://github.com/specklesystems/speckle-server/issues/864
> feat(helm chart): use standard helm labels on all pods and services

- packages/viewer/rollup.config.js
workaround for the following issue: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/771
essentially we no longer clean the `dist` folder between @speckle/viewer rebuilds, so that fork-ts-checker-webpack-plugin doesn't break and think the types no longer exist
this does make the viewer package build process a few seconds longer, but there's no other option
> fix(frontend): workaround for @speckle/viewer not found error when running dev server

- utils/helm/speckle-server/templates/frontend/deployment.yml
Follows on from https://github.com/specklesystems/speckle-server/issues/868 which introduced named ports.
If a port number is changed, it should not have to be updated in multiple places.  Instead the port should be by named reference.
> refactor(helm chart): use named ports where possible

- .circleci/get_version.sh
Branch names are being used for docker tags.  Docker tags only accept ascii letters and digits,
underscore, period and dash.  This changes sanitised branch names to conform to this.
> fix(circleci): branch names should be sanitised

- packages/frontend/nginx/templates/nginx.conf.template
- utils/helm/Makefile
- utils/helm/speckle-server/templates/fileimport_service/deployment.yml
- utils/helm/speckle-server/templates/frontend/deployment.yml
- utils/helm/speckle-server/templates/monitoring/deployment.yml
- utils/helm/speckle-server/templates/preview_service/deployment.yml
- utils/helm/speckle-server/templates/server/deployment.yml
- utils/helm/speckle-server/templates/test/deployment.yml
- utils/helm/speckle-server/templates/webhook_service/deployment.yml
Speckle pods should run with minimal privileges and capabilities to function.
To verify, run the following and follow the advisory guidance:
```shell
helm template my-speckle-server ./utils/helm/speckle-server \
--values ../iain_speckle_dev-values.yaml \
--namespace speckle | \
docker run -i kubesec/kubesec:v2 scan /dev/stdin
```
- kubesec schema has a [known issue](https://github.com/controlplaneio/kubesec/issues/315) that incorrectly throws an error for `seccompProfile`. `seccompProfile` should be commented out while running kubesec 🙄 
- empty directory (`emptyDir`) mounted at `/tmp` for all containers that write temporary files.  This allows root directory to be read only.
- tailored seccomp and appArmor profiles are not included, and will be provided as part of …
> feat(helm chart): add SecurityContext to pods and containers

- utils/helm/speckle-server/templates/servicemonitor.yml
- utils/helm/speckle-server/values.yaml
Currently Speckle assumes prometheus is deployed in the 'speckle' namespace and is deployed as a
release named 'kube-prometheus-stack'.  This commit introduces non-breaking changes that allow
custom values for these to be provided, defaulting to the current assumed values if they are not
provided.
fixes https://github.com/specklesystems/speckle-server/issues/863
> feat(helm chart): prometheus monitoring namespace and release name should be configurable

- .circleci/config.yml
- docker-compose-speckle.yml
- packages/server/modules/blobstorage/objectStorage.js
- utils/1click_image_scripts/template-docker-compose.yml
- utils/helm/speckle-server/templates/fileimport_service/deployment.yml
- utils/helm/speckle-server/templates/server/deployment.yml
- utils/helm/speckle-server/values.yaml
Can we add the ability to save objects to different regions rather than hardcode it? Some projects require data to be stored in a particular country.
> Allow save object to S3 in different region

- utils/helm/speckle-server/templates/frontend/deployment.yml
Frontend could not chown within an emptyDir with `rw` permissions; suspect the user is different from the directory owner, and escalation privileges were removed.
Until I can verify this, we'll revert to the prior good state.
- revert frontend securityContext and mounted emptyDir volumes.
> fix(frontend): frontend revert security context to prior permissions

- docker-compose-speckle.yml
- packages/fileimport-service/package.json
- utils/1click_image_scripts/template-docker-compose.yml
- utils/helm/speckle-server/templates/fileimport_service/deployment.yml
Fileimport service retreives blobs via the server storage API, and not directly from s3.  Fileimport
service no longer requires information or credentials about s3.
* remove S3 environment variables from fileimport
No requirements
Fileimport service was deployed and verified as working.
> fix(fileimport service): s3 is not required by fileimport service

- .circleci/build.sh
- .circleci/common.sh
- .circleci/config.yml
- .circleci/publish.sh
Although prevented in CircleCI configuration, a more robust method of preventing context being leaked is to prevent trusted steps being run on PRs from forks.
Amends CircleCI to separate build jobs (which are non-trusted steps) from publish jobs (which have secrets in them).
https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
> Build(CircleCI): Do not run publish step for PRs from forks

- .gitguardian.yml
Resolution provided by GitGuardian in response to https://github.com/GitGuardian/ggshield/issues/318
- amend .gitguardian file to comply with .gitguardian file specification
https://github.com/GitGuardian/ggshield/issues/318
> ci(gitguardian): the matches-ignore property should be a list and not a map

- workspace.code-workspace
To reduce likelihood of CRLF characters being incorporated, we wish to configure the project to use LF
only.
> style(vscode workspace): set EOL character to line feed (LF) symbol

- packages/objectloader/package.json
- packages/viewer/package.json
Since we want the libraries managed in this monorepo (viewer & objectloader) to be usable across multiple Node versions I've relaxed their "engine" constraints to support Node 14 and up.
> fix: relaxed engine constraint for libs

- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/fileimport_service/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/fileimport_service/networkpolicy.kubernetes.yml
- utils/helm/speckle-server/templates/monitoring/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/monitoring/networkpolicy.kubernetes.yml
- utils/helm/speckle-server/templates/preview_service/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/preview_service/networkpolicy.kubernetes.yml
- utils/helm/speckle-server/templates/server/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/server/networkpolicy.kubernetes.yml
- utils/helm/speckle-server/templates/tests/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/webhook_service/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/webhook_service/networkpolicy.kubernetes.yml
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
The domain name can be taken from the redis and postgres urls, so we can remove unnecessary values.  The user or service account that deploys helm must have permissions to view the secret.
Due to a copy & paste error, the PR for Cilium Network Policy introduced two additional values that are not being used for s3.  s3 can get the host or IP values from the endpoint.  This commit removes the superfluous values.
- removes `*.networkPolicy.externalToCluster.host` and `*.networkPolicy.externalToCluster.ip` from values.yaml
- fix: matchName for domain instead of matchPattern in speckle-server
- fix: typo in `protocol`
- fix: `"speckle.networkPolicy.domainFromUrl"` now parses domain with a port without error.
- fix: only allow monitoring ingress if monitoring is enabled.
Deployed to kubernetes …
> fix(helm chart): remove unnecessary values from helm chart

- utils/helm/speckle-server/templates/frontend/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/server/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/server/networkpolicy.kubernetes.yml
Server Egress to Apollo was blocked even if it was enabled.
- fix: Cilium Network Policy allows DNS lookup of Apollo studio API.
- fix: Cilium Network Policy allows egress to FQDN for apollo
- fix: Kubernetes Network Policy allows egress to everywhere if apollo is enabled.  This is because apollo do not document which CIDR or IP address their service is available at, and kubernetes network policies do not support domain names.  We have an open support ticket with Apollo to get their CIDR, if any, so this can be limited.
- fix: explicitly define use of TCP protocol for sentry
- fix: domain should match on name, not pattern.
- tidy: remove unnecessary whitespace.
> Helm Chart: Network Policies allow server egress to apollo

- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/server/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/server/networkpolicy.kubernetes.yml
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
Network Policies omitted to allow egress to email.  This PR allows egress to email.
- fix: if email is enabled, egress is allowed through kubernetes and cilium network policies
> fix(helm chart): allow egress from server to email server

- utils/helm/speckle-server/templates/server/networkpolicy.kubernetes.yml
Apollo responded to our support question, they confirmed that 34.120.83.176/32 is sufficient for
egress to usage-reporting.api.apollographql.com
- fix: CIDR for egress to Apollo
Support request 5645
> fix(helm chart server kubernetes network policy): update CIDR for Apollo

- utils/helm/speckle-server/templates/server/networkpolicy.cilium.yml
- utils/helm/speckle-server/templates/server/networkpolicy.kubernetes.yml
- utils/helm/speckle-server/values.yaml
Helm Chart Network Policies for server are not currently allowing egress to auth providers
- added egress to Cilium & Kubernetes Network Policies for the server to google, github and azure_ad
> fix(helm chart): allow egress to auth providers

- .circleci/config.yml
- .circleci/should_build.sh
CircleCI failed to build tagged commit as it was checked out in an orphaned state without a branch.
This commit allows tagged commits to be built.
- should build script will allow a build on semver tagged commits.
None
> fix(circleci): builds commits on detached branches

- packages/server/app.ts
The move from app.js to app.ts had broken `speckle_server_apollo_calls` prometheus metric and this metric was not being published.  This PR reverts the import of apolloPlugin to use the previous inline require.
- require apolloPlugin in server app.ts in an inline `require` call
> fix(server prometheus metrics): speckle_server_apollo_calls prometheus metric should be published

- packages/viewer-sandbox/src/Sandbox.ts
- packages/viewer/src/modules/DebugViewer.ts
- packages/viewer/src/modules/SpeckleRenderer.ts
This fixes VSM artifacts visible on some GPUs
- Increased the shadowmap bias
- Added slider for shadowmap bias for testing purposes
- Added slider for shadomap radius (smoothness)
Artifacts are no longer visible on devices where they were previously visible. Needs to be checked on more devices where the artifacts were visible
> Vsm artifacts

- utils/helm/speckle-server/templates/configmap-db-certificate.yml
- utils/helm/speckle-server/values.yaml
In some conditions we may wish to deploy to DB Certificate ConfigMap prior to the helm release.  In this case the `db.useCertificate` will be `true` as we wish the connection to the database to use it, but we do not wish to create the ConfigMap within the helm release.
If `db.useCertificate` is `true` and a value is provided for `db.certificate`, then a ConfigMap is created.
If `db.useCertificate` is `true` but no value is provided in the helm chart of `db.certificate`, then no ConfigMap should be created by the Helm Chart.
- additional logic for determining when to create the DB CA Certificate ConfigMap
Manually tested by deploying to server with and without the `db.certificate` field being empty.
ConfigMap was deployed when field was set with a value.
ConfigMap was not deployed when the …
> Only create configmap for DB certificate if certificate is provided in helm chart

- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/fileimport_service/deployment.yml
- utils/helm/speckle-server/templates/fileimport_service/serviceaccount.yml
- utils/helm/speckle-server/templates/monitoring/deployment.yml
- utils/helm/speckle-server/templates/monitoring/serviceaccount.yml
- utils/helm/speckle-server/templates/preview_service/deployment.yml
- utils/helm/speckle-server/templates/preview_service/serviceaccount.yml
- utils/helm/speckle-server/templates/server/deployment.yml
- utils/helm/speckle-server/templates/server/serviceaccount.yml
- utils/helm/speckle-server/templates/webhook_service/deployment.yml
- utils/helm/speckle-server/templates/webhook_service/serviceaccount.yml
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
Currently secrets have to be referenced from a single kubernetes Secret resource (default name 'server-vars').  This can be restrictive as all secrets have to be generated together, or the Secret patched (which can break declarative tooling). 
Additionally, when a Service Account permits a pod access to the single Secret the pod then has access to other secrets it may not need.  This does not align with the least privileges principle.
This PR allows each secret to be loaded from a separate kubernetes Secret.  This allows the Kubernetes Secrets to be generated separately, perhaps at different times in the deployment lifecycle or by different tooling. It allows Kubernetes Secrets to be granted to Pods individually, maintaining a least privileges principle.
If values for individual …
> feat(helm chart): secrets can be referenced from different kubernetes Secret resources

- packages/frontend/src/graphql/generated/graphql.ts
- packages/frontend/src/graphql/streams.js
- packages/frontend/src/main/lib/common/general/helpers/errorHelper.ts
- packages/frontend/src/main/pages/stream/TheSettings.vue
closes #981 
closes #838 
- refactored TheSettings.vue and optimized Apollo Cache usage to cut down on HTTP requests
- made the settings page auto-save pages
> feat(frontend): auto-save stream settings

- packages/frontend/src/config/apolloConfig.ts
- packages/frontend/src/graphql/generated/graphql.ts
- packages/frontend/src/helpers/typeHelpers.ts
- packages/frontend/src/main/components/common/CommitPreviewCard.vue
- packages/frontend/src/main/components/stream/ListItemCommit.vue
- packages/frontend/src/main/components/stream/commit/CommitMultiSelectToolbar.vue
- packages/frontend/src/main/dialogs/commit/CommitsBatchActionsDialog.vue
- packages/frontend/src/main/lib/stream/composables/commitMultiActions.ts
- packages/frontend/src/main/pages/TheCommits.vue
- packages/frontend/src/main/pages/stream/TheBranch.vue
- packages/server/assets/comments/typedefs/comments.gql
- packages/server/assets/core/typedefs/branchesAndCommits.graphql
- packages/server/assets/core/typedefs/streams.graphql
- packages/server/modules/blobstorage/tests/blobstorage.graph.spec.js
- packages/server/modules/comments/graph/resolvers/comments.js
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/streams.js
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/commits.js
- packages/server/modules/core/services/streams/streamAccessService.js
- packages/server/modules/shared/index.js
- packages/server/test/graphql/generated/graphql.ts
- Added selection capability to Branch Commit list view as well
- Added capability to batch delete commits from the "Your Commits" page (Move not possible, because there are commits from multiple streams there)
- Refactored the commit graph a bit: Got rid of CommitCollectionUser and CommitCollectionUserNode which were almost complete duplicates of Commit and CommitCollection, just with a few extra fields relating to the stream. Instead I added a `stream` field to `Commit` that relies on DataLoaders to ensure the streams are retrieved from DB in an efficient way. I also made this change in a sort of backwards compatible way, in that, even though the return type names now differ, you can query by the same fields as before.
- Fixed bug in `authorizeResolver()`, where the `isPublic` check …
> Various Batch Commit Action improvements

- packages/frontend/src/main/router/index.js
- packages/frontend/src/mixpanelManager.ts
closes https://github.com/specklesystems/admin/issues/336
> feat(frontend): tracking visited routes

- packages/server/app.ts
more info https://www.apollographql.com/docs/apollo-server/performance/cache-backends/#ensuring-a-bounded-cache
we don't use any of the server-side apollo caching functionality, so I don't anticipate any problems
> chore: securing apollo server cache against DDoS attacks

- packages/frontend/package.json
- packages/frontend/src/config/apolloConfig.ts
- packages/frontend/src/main/app.js
- packages/frontend/src/main/components/viewer/ViewerBubbles.vue
- packages/frontend/src/main/lib/common/text-editor/mentionSuggestion.js
- packages/server/modules/comments/graph/resolvers/comments.js
- yarn.lock
closes #902 
@didimitrie I converted the existing logic to this:
- Instead of 1) marking users without any recent updates as stale/hidden and 2) sending out an update about own position being done together in the same function - sendUpdateAndPrune() - I've split both of those algorithms apart.
- "Marking users without any recent updates as stale/hidden" still gets executed every 2 seconds, but doesn't trigger any web requests
- "Sending out an update about own position" (sendUpdateAndPrune()) is now done every 60s not every 2s. This cyclical update call could be disabled entirely, but this way we at least validate every 60s that the user is in fact still there. If we ever need to reduce request volume even more, I'd vote for removing it and relying on the beforeDestroy() and window unload …
> fix(frontend): viewer activity broadcast request volume greatly reduced

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/filtering/FilteringManager.ts
- packages/viewer/src/modules/tree/RenderTree.ts
When dealing with streams holding a large number of objects, filtering gets very slow. The main reason for this is the large redundancy we currently have in working with the stream's data tree. This pull request aims at reducing some of that redundancy.
#1094 Signals such a case where the data tree is dense and filtering is very slow
- Removed a lot of redundant walks inside the `populateGenericState `function of the `FilteringManager`. There is still some redundancy left, but I think that fixing that will require a more general solution.
- **Speedup X6** for the particular case reported in #1094
> Removing redundancy from filtering

- docker-compose-deps.yml
- packages/frontend/package.json
- packages/frontend/src/main/app.js
- packages/frontend/src/main/components/viewer/ObjectSelection.vue
- packages/frontend/src/main/navigation/StreamNav.vue
- packages/server/package.json
- yarn.lock
closes https://github.com/specklesystems/admin/issues/358
fixed vulnerabilities (all current High severity alerts):
- https://github.com/specklesystems/speckle-server/security/dependabot/148
- https://github.com/specklesystems/speckle-server/security/dependabot/147
- https://github.com/specklesystems/speckle-server/security/dependabot/132
- https://github.com/specklesystems/speckle-server/security/dependabot/129
- https://github.com/specklesystems/speckle-server/security/dependabot/101
thankfully most of these were used by various dev tools (easy to test - just run the tool), and only one required removing a Vue plugin and thus actual changes in the frontend
> fix: various dependabot vulnerability fixes

- packages/frontend/src/main/components/stream/commit/CommitShareBtn.vue
Fixed commit share buttons having black text on light theme. This is what it looks like after the fix:
> fix(frontend): fix commit share btn looking off in light theme

- packages/objectloader/src/index.js
adds a null check in the traversal func. @oguzhankoral was having trouble receiving stuff back in sketchup because of this 😓
> Adds an additional null check

- packages/viewer-sandbox/src/Sandbox.ts
- packages/viewer/src/modules/batching/MeshBatch.ts
- packages/viewer/src/modules/batching/PointBatch.ts
…anges were set. Implemented a draw range flattener for the PointBatch which avoids redundant draw calls, which in some cases could get into the tens of thousands killing performance entirely. Fixed an issue where gradient ramp index was not neing set correctly when it was 0
This https://github.com/specklesystems/speckle-server/issues/1272 was raised, describing two issues. One with performance when applying filters on a specific stream and another one where successive gradient filters were not being applied correctly. The reported bugs were a good catch since they can potentially affect any stream
- Fixed an issue with PointBatch auto fill draw ranges, where invalid ranges were set, and any points in that batch would not be rendered
- Implemented a draw range flatten-er for the …
> Fixed #1272

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/batching/Batcher.ts
- packages/viewer/src/modules/converter/Converter.ts
Fixed an older issue related to Tekla streams and IBO shuffling. We're now ignoring any render view which lacks vertex data and we're also displaying a warning when such objects are converted
Fixed an issue which has been popping in and out for a while now in Tekla streams. It was caused by objects with type `Mesh` with no vertex data. The viewer now gives out a warning whenever it encounters such objects and ignores them in the displaying process. This fixes #1366 
- Converte now warns about meshes with no vertex data
- Batcher ignores meshes with no vertex data
> Fix for #1366

- packages/server/assets/emails/templates/components/ctaButton.mjml
- packages/server/assets/emails/templates/components/footer.mjml
- packages/server/assets/emails/templates/components/head.mjml
- packages/server/assets/emails/templates/components/headerLogo.mjml
- packages/server/assets/emails/templates/speckleBasicEmailTemplate.mjml.ejs
- packages/server/assets/emails/templates/speckleBasicEmailTemplate.txt.ejs
- packages/server/modules/emails/services/emailRendering.ts
- packages/server/modules/emails/services/sending.ts
- packages/server/modules/emails/services/verification/request.ts
- packages/server/modules/emails/tests/emailTemplating.spec.ts
- packages/server/modules/notifications/services/handlers/activityDigest.ts
- packages/server/modules/notifications/services/handlers/mentionedInComment.ts
- packages/server/modules/notifications/services/handlers/newStreamAccessRequest.ts
- packages/server/modules/notifications/services/handlers/streamAccessRequestApproved.ts
- packages/server/modules/pwdreset/services/request.ts
- packages/server/modules/serverinvites/services/inviteCreationService.js
- workspace.code-workspace
This has been left half baked for a while. Now all outgoing emails should use the ejs mjml on the fly rendering.
Unforch my local server is refusing to send emails with mailjet, so I'd like to get this out to latest for a proper testing.
Once that is done, I'm gonna create an additional cleanup PR, that removes the traces of the old rendering system.
> refactor(server email templates): use the mjml ejs rendering for all emails

- packages/tailwind-theme/package.json
Fixes #1586 
Just ensuring `default` is the last option in each object seems to do the trick.
@fabis94 may want to double check this as I've only verified this is the case on my machine (Intel Mac) on both VSCode and Webstorm.
> fix(tailwind-theme): Move default to be last option on exports.

- docker-compose-speckle.yml
- utils/1click_image_scripts/template-docker-compose.yml
For speckle deployed via Docker Compose, there are conditions where the speckle server container becomes unresponsive but has not yet exited with a non-zero exit code. For example, this issue report https://github.com/specklesystems/speckle-server/issues/1649
This Pull Request introduces a health check to the pod which will cause non-responsive pods to be automatically restarted after 30s.
This is a workaround for the symptoms (unresponsiveness of the speckle-server pod), and not a fix for the root cause.
> feat(docker compose): healthcheck for speckle-server

- packages/frontend-2/lib/viewer/composables/serialization.ts
- packages/frontend-2/lib/viewer/composables/setup/postSetup.ts
Bugfixes:
- Diff Mode for Follower not ending when source stops the diff
Features:
- No longer triggering "zoom extents" on object load, if a thread is open
> fix(fe2): spotlight & zoom extents fixes

- packages/frontend-2/lib/common/composables/singleton.ts
- packages/frontend-2/lib/common/helpers/debugging.ts
- packages/frontend-2/lib/common/helpers/graphql.ts
- packages/frontend-2/lib/core/helpers/observability.ts
- packages/frontend-2/lib/projects/composables/modelManagement.ts
- packages/frontend-2/lib/projects/composables/previewImage.ts
- packages/frontend-2/lib/projects/composables/projectManagement.ts
- packages/frontend-2/lib/projects/composables/versionManagement.ts
+ Improved various singletons to use locks so that they can be used multiple times per page without bugs arising (easier code maintenance)
+ Improved troubleshooting DX for local apollo cache updates
> fix(fe2): invalid totalCount cache updates for project.versions, project.models and model.versions

- packages/frontend-2/components/project/model-page/versions/CardActions.vue
- packages/frontend/src/main/pages/stream/TheStream.vue
- packages/ui-components/src/components/form/select/Base.vue
- packages/ui-components/src/components/layout/Menu.stories.ts
- packages/ui-components/src/components/layout/Menu.vue
- packages/ui-components/src/helpers/layout/components.ts
- packages/ui-components/src/vue-tippy.d.ts
View Commit button broken: 
* The bug described could've already happened before guest roles, it seems. In either case, I don't see how it could've happened, because to get a broken notification button you have to be on a broken URL already.
* I added extra safeguards tho, so that even if the URL is broken, the notification URL should be valid
FE2 Delete versions:
* I don't think there's any bug here - versions can only be deleted by project owners or authors of those specific versions. But maybe that's not clear enough, so I added tooltips to the disabled select items.
> fix: improvements not really related to "guest role" launch

- packages/frontend-2/lib/common/composables/async.ts
- packages/frontend-2/nuxt.config.ts
- packages/ui-components/src/composables/common/async.ts
- packages/ui-components/src/lib.ts
moving stuff from fe2 to ui-components so we can use it in automate
> chore: moving writableAsyncComputed to ui-components

- packages/dui3/components/common/ModelCard.vue
- packages/dui3/components/form/select/Models.vue
- packages/dui3/components/form/select/Projects.vue
- packages/dui3/components/form/select/Versions.vue
- packages/dui3/lib/form/select/types.ts
- packages/dui3/pages/onboarding/receive.vue
- packages/dui3/pages/onboarding/send.vue
- packages/dui3/store/hostApp.ts
`FormSelectProjects` and `FormSelectModels` components now have optional `create` flag to provide Project and Model create functionality while searching. User need to provide at least 1 character to get create button. This is only available on `Send` onboarding for sure.
> Search or create component

- packages/dui3/components/common/ModelCard.vue
- packages/dui3/components/common/ModelReceiver.vue
- packages/dui3/components/common/ModelSender.vue
- packages/dui3/lib/bindings/definitions/IBasicConnectorBinding.ts
- packages/dui3/lib/bindings/definitions/IReceiveBinding.ts
- packages/dui3/lib/bindings/definitions/ISendBinding.ts
- packages/dui3/lib/bridge/sketchup.ts
- packages/dui3/lib/models/card.ts
- packages/dui3/lib/models/card/notification.ts
- packages/dui3/lib/models/card/progress.ts
- packages/dui3/lib/models/card/receiver.ts
- packages/dui3/lib/models/card/send.ts
- packages/dui3/pages/onboarding/receive.vue
- packages/dui3/pages/onboarding/send.vue
- packages/dui3/store/hostApp.ts
Host app can send multiple notifications i.e. one for succesful operations one for failed operations. We can show them sequentially now and store into card if they want to see them later again. Before notifications was disappered after timeout. Also some types extracted with better organization.
> Feat (dui3): Multiple notifications

- packages/frontend-2/lib/core/helpers/file.ts
- packages/frontend/src/main/lib/common/file-upload/fileUploadHelper.ts
- packages/server/modules/fileuploads/index.js
[Notion Ticket
](https://www.notion.so/speckle/446c312165c144cfbea3140935d6d27c?v=b6f6140d25e14672a40f3a50644129a7&p=220e94045c064a528ed5e26b8a39ee11&pm=s)
Iain noticed that you could not upload files with an uppercase character in the file extension. This problem existed in FE1 and FE2.
- Add `toLowercase` to the uploaded file extension when comparing the uploaded file with the allowed extension list.
- The above was done to the relevant file in both FE1 and FE2 respectively. 
- Change to server, remove "toLowercase" so the casing of the upload file will be consistent throughout the UI.
> Fix: Allow files with uppercase file formats. Maintain casing from upload in UI. 

- packages/dui3/components/common/ModelCard.vue
- packages/dui3/lib/bindings/definitions/IBasicConnectorBinding.ts
- packages/dui3/store/hostApp.ts
Previously we had only remove button for all cards.
Now,
1. Highlight > Selects objects stored in card and zoom selection
2. Remove > Remove card from both UI and host app state
3. Show notifications > Toggle button to see previous notifications (TBD)
> Feat (Dui3): model card buttons

- packages/frontend-2/components/auth/RegisterWithEmailBlock.vue
[Notion Ticket
](https://www.notion.so/speckle/446c312165c144cfbea3140935d6d27c?v=b6f6140d25e14672a40f3a50644129a7&p=c5f2b26a44844a8eaf0aea3819d891e8&pm=s)
Matteo reported that signups were not coming through to Mailchimp. 
Checking network tab during registration showed:
After changing "name" of the Checkbox from "test" to "newsletter":
Updated Checkbox name
Updated consent text to new text provided by Matteo. 
This was hard to test locally. With such a small (and obvious) change, I was hoping we could merge and test it properly on live?
> Update text and fix checkbox name

- packages/frontend-2/components/projects/Dashboard.vue
[NOTION TICKET](https://www.notion.so/speckle/446c312165c144cfbea3140935d6d27c?v=b6f6140d25e14672a40f3a50644129a7&p=a4e557c6e8634945b579ec1a226ba48b&pm=s)
The "Start Checklist" is displayed when the `hasDismissedChecklistForever` cookie is false. Currently clicking "Don't show again" sets this to true, but the expiration is set to session, so it reappears every new session. 
I have changed this so it now persists for 2 years from when you click the "Don't show again" button.
> Change expiration of hasDismissedChecklistForever to 2 years

- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/streams/clone.ts
- packages/server/modules/core/services/streams/onboarding.ts
- packages/server/modules/cross-server-sync/services/onboardingProject.ts
- ensures an onboarding stream is always created, regardless of whether a user went through the process before 
- keeps original dates for commits/versions, ensuring we always load the correct version during onboarding
- optimises stream cloning (obj duplication: from **25s to 270ms**)
> Onboarding Speedup

- packages/frontend-2/components/project/webhooks-page/CreateOrEditDialog.vue
"Choose Events" select in "Add new Webhook" does not overflow the dialog as it should.
Old:
New:
> Add mount-menu-on-body to Events select

- packages/frontend-2/components/onboarding/checklist/v1.vue
Responsive class for onboarding banner was dropped. Re-add.
> Fix desktop view of onboarding banner

- packages/frontend-2/components/viewer/anchored-point/Thread.vue
- packages/frontend-2/components/viewer/anchored-point/thread/NewReply.vue
Issue with alignment of add comment box in viewer. 
Fix by adding a background colour, and adding a relative class to a parent so it sits correctly.
> Viewer - New comment background/alignment fix

- packages/frontend-2/components/onboarding/checklist/v1.vue
- packages/frontend-2/components/tour/Onboarding.vue
- packages/frontend-2/components/tour/Segmentation.vue
- packages/frontend-2/composables/states.ts
There was an issue with the onboarding flow where the Tour would keep showing, after the user had already completed it. A refresh fixed this problem, but is very annoying for new users. 
If the user has completed the segmentation and tour, but not the checklist, the whole tour will continue to show when the user opens a model, until they refresh.
I added a new state called showSegmentation. This is default true, but is set to false when the user finishes the final step of segmentation.
Confirm that the user selections in Segmentation is captured by mixpanel. I don't see any graphql calls storing this.
> Bugfix - Segmentation Reappears after Completion - Add showSegmentation state

- packages/frontend-2/components/auth/third-party/LoginBlock.vue
- packages/frontend-2/composables/env.ts
- packages/frontend-2/lib/auth/composables/auth.ts
- packages/frontend-2/lib/auth/composables/passwordReset.ts
- packages/frontend-2/lib/core/composables/fileImport.ts
- packages/frontend-2/lib/core/composables/fileUpload.ts
- packages/frontend-2/lib/core/configs/apollo.ts
- packages/frontend-2/lib/viewer/composables/viewer.ts
- packages/frontend-2/nuxt.config.ts
- packages/frontend-2/pages/authn/verify/[appId]/[challenge]/index.vue
- packages/frontend-2/pages/developer-settings.vue
- packages/frontend-2/server/routes/graphql.ts
@iainsproat You can define a `NUXT_PUBLIC_BACKEND_API_ORIGIN` env var with this (optionally), to make the serverside use a different value from the clientside
> feat(fe2): alt apiOrigin for SSR

- packages/frontend-2/components/auth/LoginPanel.vue
- packages/frontend-2/components/auth/third-party/LoginBlock.vue
- packages/frontend-2/components/auth/third-party/LoginButtonGithub.vue
- packages/frontend-2/components/auth/third-party/LoginButtonOIDC.vue
- packages/frontend-2/lib/auth/helpers/strategies.ts
- packages/frontend-2/lib/common/generated/gql/graphql.ts
It was raised by @iainsproat that Aurecon could not log in to their server as they had enabled OIDC login, which is not supported in FE2. Instead, they got an empty login screen.
- Add Button component for OIDC
- Added OIDC to AuthStrategy ENUM
- Added OIDC to Login Page
- Added "v-if" so "Login with email..." text only appears when local login is true
NONE - unable to test locally. Enabling OIDC in env requires valid app data
> Add OIDC auth strategy button

- packages/frontend-2/components/header/NavBar.vue
- packages/frontend-2/components/header/NavLink.vue
- packages/frontend-2/components/header/NavNotifications.vue
- packages/frontend-2/components/viewer/explorer/NavbarLink.vue
Part of the feedback received from SOM was that they placed a lot of importance on the naming of models. They had an issue where we had a max-width and truncate set on the Model name in breadcrumbs. When a model name was longer than the max-width, we obscured a lot of the model name which made it hard for them getting context on where the nested model is. This happened, even when there was plenty of screen space in the title bar. 
There will be a larger project in future to look into further improvements for the breadcrumbs. 
Most of the edits are in:
- HeaderNavBar
- HeaderNavLink
The model name now has no max-width, and will fill the available space. The earlier items in the breadcrumb will also truncate on smaller screens. 
There is also a change in:
- HeaderNavNotifications
I fixed an …
> FE2 - Title Bar Improvements

- packages/frontend-2/components/project/page/models/Actions.vue
Really quick one - we were showing the Trash Icon for "Upload new Version".
I imported and added the correct version.
> Add ArrowUpTray Icon

- packages/server/logging/apolloPlugin.js
> add apollo query duration

- packages/frontend-2/plugins/002-healthMetrics.server.ts
- packages/frontend-2/server/middleware/001-logging.ts
- packages/server/logging/expressLogging.ts
> fix: request logs

- packages/frontend-2/lib/viewer/composables/ui.ts
In FE2 when clicking on any of the items highlighted in the image below
Which would make all the objects of the selected type to become 'selected', for a large number of objects the main thread would get blocked for tens of seconds. 
60% of the execution time was taken up by using `findAll` when going over very many string ids, to get the tree node from the viewer. In API 2.0, this is no longer needed. Instead you use `findId` which is incomparably faster since it's just one or two lookups. After making this change, the viewer overhead was completely gone. However there is still some FE2 related overhead, accounting for approx 30% of the total inital overhead. 
I'm leaving two profiler recordings, one before the change, one after the change. The FE2 related overhead is visible in both, …
> Remove `findAll` when matching ids

- packages/frontend-2/components/project/page/team/PermissionSelect.vue
[JIRA Ticket](https://spockle.atlassian.net/jira/software/c/projects/WBX/issues/WBX-56?filter=myopenissues)
Quick change to add mount-menu-on-body to the user role permission select in the manage project dialog.
> [WBX-56] - Bugfix - Menu to manage project members is cut off

- packages/frontend-2/components/header/NavBar.vue
- packages/frontend-2/components/header/NavShare.vue
- packages/frontend-2/components/viewer/AnchoredPoints.vue
After merging in Embed, Benjamin noticed we can potentially have 1 buttons in the headerbar. One is sized smaller, and looked like a bug. I have readjust the size of the Share button to sm to match the Sign in button. 
Also increased gap on items in headerbar on mobile. 
Also removed canPostComment condition in v-if on ViewerAnchoredPointNewThread to ensure user can still try to comment on embed, but will be asked to login.
> Headerbar Consistency - Post merge

- packages/frontend-2/.env.example
- packages/frontend-2/app.vue
- packages/frontend-2/components/error/page/Renderer.vue
- packages/frontend-2/error.vue
- packages/frontend-2/lib/auth/composables/activeUser.ts
- packages/frontend-2/lib/core/composables/appErrorState.ts
- packages/frontend-2/lib/core/composables/server.ts
- packages/frontend-2/lib/core/configs/apollo.ts
- packages/frontend-2/lib/core/helpers/observability.ts
- packages/frontend-2/nuxt.config.ts
- packages/frontend-2/plugins/001-logger.ts
- packages/frontend-2/server/lib/core/helpers/observability.ts
- packages/frontend-2/server/middleware/001-logging.ts
- packages/frontend-2/type-augmentations/server.d.ts
- packages/server/app.ts
- packages/server/logging/apolloPlugin.js
- packages/server/logging/expressLogging.ts
- packages/server/type-augmentations/express.d.ts
- Better error page when 1) api calls fail 2) you're being rate limited. Previously you got a vague message like "fetch failed" or "status code 429"
- Added userId to server & FE2 logs
- Added country & server request ID (the req.id of the initial SSR req) to FE2 logs
- Made FE2 log payloads more cohesive and alike irregardless of whether they come from the vue app or server side routes
-
> feat: various observability improvements

- packages/frontend-2/components/auth/RegisterPanel.vue
We have a "Or sign up with your email" in the login, displayed when third party auth strategies are defined. 
Currently, it still shows, even when no local strategy is defined, meaning the label shows, but not form. 
I updated the condition to also check for local strategies.
> Bugfix: Wrong Condition on Local Strategy Label

- packages/server/logging/expressLogging.ts
- packages/server/modules/auth/strategies/local.js
- packages/server/modules/auth/tests/auth.spec.js
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/graph/resolvers/streams.js
- packages/server/modules/core/helpers/server.ts
- packages/server/modules/core/services/ratelimiter.ts
- packages/server/modules/core/tests/ratelimiter.spec.ts
- Fixed path resolution so that the querystring is properly removed from the path, before looking for it in the rate limiter mapping object
- Made it so that you can omit the HTTP Verb from the limiter options definition to ensure the options apply to all verbs
- Removed the `RateLimitAction` enum because it wasn't very ergonomic to work with and didn't really bring much value - If you wanted to add a new action, you'd have to type it out 3 (!) times: As a key of the object, as a value of the same object, and then once again as a key in the "LIMITS" object. I made it so that available keys are resolved from the keys set in the LIMITS  object, which gives us equivalent type safety.
> fix(server): rate limiter path resolution

- packages/frontend-2/components/viewer/PreSetupWrapper.vue
The z-index on controls was z-20, with the new "pocket" (lower content area in viewer) at z-10. But the z-index wasn't being enforced as the position wasn't set. This caused the reset filters div to sit on top of the controls, blocking some functionality. 
Reported by Dim here:
https://spockle.atlassian.net/browse/WBX-284
-Add relative to 2 cases where z index was set without position
> [WBX-284] Bugfix - Controls Z-Index not being enforced

- packages/frontend-2/components/developer-settings/CreateApplicationSuccessDialog.vue
[JIRA TICKET
](https://spockle.atlassian.net/jira/software/c/projects/WBX/issues/WBX-281?filter=myopenissues)
User reported the hardcoded url. Updated to use NUXT_PUBLIC_BASE_URL.
- Use NUXT_PUBLIC_BASE_URL to build URL
- The hardcoded url was the FE1 string. I need to confirm that this was not intentional. It is as the docs suggest, so I need to make sure this also works with the FE2 url.
> [WBX-281] - 2049 Hardcoded URL in Create Application Success Dialog

- packages/frontend-2/components/viewer/explorer/NumericFilter.vue
Originally reported by Alex in discord:
https://github.com/specklesystems/speckle-server/assets/139135120/22b2e2ea-9456-4c35-8473-ef2a4cbfe071
I tidied up the NumericFilter.vue file, so it was more consistent and using flex better. 
I was unable to recreate the original problem, but I believe this will solve the issue.
> Bugfix - Tidy up numeric filters to prevent overflow issue

- packages/frontend-2/components/viewer/AnchoredPoints.vue
- packages/frontend-2/components/viewer/GlobalFilterReset.vue
- packages/frontend-2/components/viewer/PreSetupWrapper.vue
- packages/frontend-2/components/viewer/measurements/Options.vue
- packages/frontend-2/components/viewer/selection/Sidebar.vue
As part of another (merged) ticket, I created a "pocket" portal. This is the area in the viewer that can house tips or buttons. 
I created this pocket, as previously we were just adding these buttons throughout the app where needed. By using the portals, we can centralise the layout logic to ensure all buttons/tips have the correct positioning and z-indexs. 
It was noticed that when a user is following someone with filters applied, you can no longer click "Stop Following..". This is because this button is not part of the pocket. It was positioned absolutely, rather than using the portal.
I moved this button to the Pocket, and created new left and right pockets. I used grid to make sure these are always equal widths to ensure alignment.
> Move "Stop Following" button to the "Pocket"

- packages/frontend-2/components/viewer/Sidebar.vue
The sidebar was improved in another ticket. There was a merge conflict around this, which I think broke the alignment of the mobile/embed portal. The sidebar has been simplified, so it's the same view on mobile as embed, so we no longer need to check if embed is enabled, we can do it purely with breakpoints.
> Bugfix - Fix mobile/embed sidebar header alignment issue

- packages/frontend-2/components/common/EditableTitleDescription.vue
On Windows & Edge, there was a small bug where the title was clipping the bottom few pixels of some characters.
I added a small amount of padding to the textarea to fix this. Confirmed to work when testing on BrowserStack.
> Small bugfix - Windows showing clipped project titles

- packages/frontend-2/components/project/page/LatestItems.vue
- packages/frontend-2/components/project/page/discussions/Header.vue
- packages/frontend-2/components/project/page/latest-items/Models.vue
- packages/frontend-2/components/project/page/models/Header.vue
- packages/ui-components/src/components/layout/GridListToggle.vue
I've updated the Grid/List view toggle component to make it clearer which item is the active item. The old design made it appear as if the inactive item was the active item.
- The active item has the light background color, some spacing around it, and a shadow.
- Updated tippy to have one for each of the two toggle items. "Grid View" / "List View"
- Note: I've used a few `dark:` Tailwind classes to tweak the colors in dark mode. I've heard from Andrew we don't want to do this but it didn't work well in dark mode without it.
The item with the darker background below is the active item even though you'd think it's the white one.
> Update Grid/List view toggle component to make the active item clearer

- packages/frontend-2/components/projects/ProjectDashboardCard.vue
[Bug raised here](https://spockle.atlassian.net/browse/WBX-395)
Fix:
> Bugfix - Mobile Project cards not filling width of mobile

- packages/frontend-2/pages/projects/[id]/discussions.vue
- packages/frontend-2/pages/projects/[id]/models/index.vue
While the tabs navigation are being developed, I fixed up the models and discussions pages, so any links here would still work. 
This is a temporary solution until Tab navigation is complete. 
Update pages to use components in new location.
> Fix Projects and Discussions Pages

- packages/frontend-2/components/viewer/GlobalFilterReset.vue
I noticed a bug where the viewer would be skewed when a lot of comments were added, and a filter applied. 
This seems to stem from the animation added to the Reset Filters button. I have removed this, will investigate further in another ticket.
> Bugfix - Remove translate which caused problems in certain views

- packages/frontend-2/lib/projects/composables/projectPages.ts
- It was decided that List view should be the default view for models etc. 
- There is some cookie functionality, but this will not interfere. We check for the cookie, if it has been set to grid, the user will still get grid. If no preference for grid, we'll now show list. 
- Update useProjectPageItemViewType to default to List
> [WBX-389] Change default view to List from Grid

- packages/frontend-2/lib/common/helpers/route.ts
- packages/frontend-2/pages/projects/[id]/discussions.vue
- packages/frontend-2/pages/projects/[id]/models/index.vue
- Update projectDiscussionsRoute & allProjectModelsRoute so they go to project page. This is temporary until the Tab routing is done. 
- Add breadcrumbs to both models and discussions page, incase someone has a bookmark saved, they can still use breadcrumbs to navigate.
> Add breadcrumbs to discussions and models. Temp change to routing

- packages/frontend-2/components/viewer/Sidebar.vue
- packages/frontend-2/components/viewer/anchored-point/Thread.vue
- packages/frontend-2/components/viewer/selection/Sidebar.vue
- packages/ui-components/src/components/layout/Dialog.vue
- packages/ui-components/src/components/layout/DialogSection.vue
Some last testing to improve some items pre launch.
- Fixed a regression causing the mobile experience to be bad. When we changed the selection info to unfold by default, it caused ugliness on mobile. I've made it so it doesn't unfold by default on mobile
- Removed some absolute heights so the lower panel only uses the space it needs on mobile
- Fixed an Apple bug where they don't like dvh with max height
- Fixed an apple bug where icons where spanning too far in dialogs
> Pre FE2 launch - Last testing/improvements

- packages/frontend-2/components/projects/Dashboard.vue
Small change from testing. 
The "New Speckle" banner now has priority over the Feedback banner. Previously, a user who had not dismissed the feedback, would not see the New Speckle banner.
> FE2 - Give New Speckle Banner priority over Feedback Banner

- packages/frontend-2/components/viewer/resources/VersionCard.vue
- packages/frontend-2/lib/common/composables/reactiveCookie.ts
- packages/frontend-2/lib/core/configs/apollo.ts
- packages/frontend-2/lib/core/nuxt-modules/apollo/module.ts
- packages/frontend-2/package.json
- packages/ui-components/src/components/layout/Dialog.vue
- yarn.lock
Tested out a dev & prod build, also tested out various pages locally
> feat(fe2): upgrade to nuxt 3.11

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/batching/InstancedMeshBatch.ts
- packages/viewer/src/modules/batching/MeshBatch.ts
Fix for issues with draw ranges for more complex combination of filters. Current state to act as a patch. Several aspects of our batch implementations need a bit of attention
> Draw range error fix

- packages/frontend-2/components/projects/NewSpeckle/Dialog.vue
- packages/frontend/src/main/dialogs/NewSpeckle.vue
It was decided that pro Vimeo was worth the cost, as it gave us the option of a much cleaner embedded player. The first video we have moved to Vimeo is the "What's new in Speckle" video. 
- Replace FE1 YouTube link with Vimeo Embed
- Replace FE2YouTube link with Vimeo Embed
- Added a background div with spinner, which will show while the video loads
https://github.com/specklesystems/speckle-server/assets/139135120/527485c9-8c88-4abc-86a6-a5f270b0dd85
https://github.com/specklesystems/speckle-server/assets/139135120/c202a647-fffd-4e7f-ba91-40d3a878d461
> Replace YouTube video with Vimeo 

- packages/frontend-2/lib/viewer/composables/setup/selection.ts
[JIRA TICKET
](https://spockle.atlassian.net/browse/WBX-434)
When in measure mode, and perpendicular mode, you can double click to quick measure. This also triggers a zoom, which is not wanted. 
- Check measure mode is enabled
- Check Measurement Type is Perpendicular
- Return when both are not true
> feat(fe2): dont zoom out when quick measuring in perpendicular mode

- packages/frontend-2/components/common/EditableTitleDescription.vue
- packages/ui-components/src/components/form/select/Base.vue
Noticed a few minor 'improvements' that were highlighted in console. After Fabs work to remove all warnings and errors, this clears all messages. 
- Update `FormSelect` in `ui-components` to also add a "for" to labels
- Add title to textareas in `EditableTitleDescription"
> fix(fe2): fix console improvements around form elements

- packages/frontend-2/components/tour/Segmentation.vue
- packages/frontend-2/plugins/survicate.client.ts
Reported by Fabians in Discord, it seems the bg colour was dropped in the segmentation dialogs. I have readded
> fix(fe2): add bg-foundation to segmentation dialogs

- packages/frontend-2/server/plugins/001-startupTermination.ts
- yarn.lock
> fix(fe2): fix login not working due to unsupported regex on Safari

- packages/viewer/src/modules/batching/DrawRanges.ts
- packages/viewer/test/__snapshots__/draw-ranges.test.ts.snap
- packages/viewer/test/draw-ranges.test.ts
Undead patch No.1 for https://github.com/specklesystems/speckle-server/pull/2182
- Material index edges now read from forward or backward edges depending on the edge's starting node value
> #2182 Undead patch-1

- packages/frontend-2/components/projects/Dashboard.vue
- packages/frontend-2/plugins/survicate.client.ts
It was reported that users keep getting the onboarding checklist. While this is not a sure fix, this could fix the issue. We noticed that browsers only allow 400 day cookie expirations, and we were setting it to 999 days. Our cookie plugin already sets a year expiration when no expiration is defined, so this could potentially fix the issue on some browsers. If not, we are at least setting the cookies with an achievable cookie expiration date.
> bugfix(fe2): remove custom cookie expiration date

- packages/frontend-2/components/onboarding/checklist/v1.vue
- packages/frontend-2/components/tour/Onboarding.vue
We're getting rid of these two onboarding messages on mobile. It's not necessary to tell users to check it out again using another device. We can introduce better onboarding on mobile later.
> Remove mobile onboarding banners

- packages/dui3/store/accounts.ts
@didimitrie, we were calling it already in index.vue and await it. We do not necessarily call it in store. It caused some errors on Autocad that sqlite connection was trying to do it twice and they were borking each other. Removing this line seems like harmless, tested in Autocad and Sketchup.
> Chore (dui3): remove double call on refresh account

- packages/dui3/pages/index.vue
It is tested, and reason explained in comment.
> Fix (dui3): Null check id of documentInfo instead itself

- packages/ui-components/src/components/layout/Dialog.vue
DUI3 runs sometimes in an ancient chrome version (65), which does not support the following: 
- `inset` classes
- `dvh` units
This results in unscrollable dialogs in aforementioned ancient chrome version. 
Adds a tiny optional off prop to the layout dialog component, that then does the following: 
- `inset-0` becomes `top-0 bottom-0 right-0 left-0` 
- `dvh` units become `vh` units
cc @andrewwallacespeckle as this is something i'd like to merge in main too!
> fix(dui3/ui-components): optinal css fiddles for ancient chrome versions

- packages/dui3/lib/bindings/definitions/IBasicConnectorBinding.ts
- packages/dui3/pages/index.vue
This is needed for revit "Family Environment". We will render custom messages if any that send via connector instead default. If message null we render **"Welcome to Speckle! Please open a file to use this plugin."**
> Feat(dui3): Enable rendering custom message from DocumentInfo

- packages/frontend-2/components/auth/LoginPanel.vue
- packages/frontend-2/components/project/page/latest-items/comments/EmptyState.vue
- packages/frontend-2/components/viewer/AnchoredPoints.vue
- packages/frontend-2/components/viewer/anchored-point/NewThread.vue
- packages/frontend-2/components/viewer/anchored-point/Thread.vue
- packages/frontend-2/lib/viewer/composables/commentManagement.ts
There was a bug in the viewer where a user who was logged in, was still presented the login screen when trying to post a comment. This occurred when the user was on a public project, that they were not a collaborator in. 
I adjusted the conditions around canPostComment, so it fits better in every scenario. I also hid the 2 "New Comment" buttons when commenting was not possible, but the user was logged in.
> bugfix(fe2): Fix conditioning around posting comments in viewer

- packages/frontend-2/components/project/page/latest-items/comments/EmptyState.vue
- packages/frontend-2/components/viewer/comments/Comments.vue
There was a bug introduced in our recent changes to useCheckViewerCommentingAccess. 
When no discussions were present on a project, and you navigated to the discussions tab, you got a 500 error. 
- Simplified the Discussions Empty State component
> bugfix(fe2): Discussion EmptyState causing 500 error

- packages/frontend-2/components/viewer/explorer/TreeItem.vue
In scene explorer, we show the full model name, including nestings. This means the actual model name is often cut off. 
We show the shortened model name in the Models panel. We should shorten it in the same was in scene explorer. 
- Add getNestedModelHeader function
- User getNestedModelHeader with result of getHeaderAndSubheaderForSpeckleObject
> feat(fe2): Use shortened header in Scene Explorer

- packages/frontend-2/components/project/page/team/Block.vue
It was noticed that when a project contributor clicks the "Manage" button in the team block, they are taken to a Contributor page with no contributors, and an authentication error in console. A reload fixed this, suggesting it is not an authentication problem, but more likely to be some race condition. 
I have spent a bit of time troubleshooting this, but have not found the underlying issue. Some input from Fabians would be good here. 
In the meantime, I have changed the conditioning around the manage button, so only users with edit permissions can see the Manage button. Users without this permission can still go to settings>contributors, but they won't see the Manage button from the project page. 
- Change condition on "Manage" button from "activeUser" to "canEditProject".
> fix(fe2): "Manage" Button causes authentication error for user without edit permissions

- packages/frontend-2/components/viewer/selection/Object.vue
When a single item is selected, the object appears in the sidebar unfolded. When a new item is selected (using shift - so both items are now selected), the first item remains unfolded, but the second is folder. 
In the scenario, the first and second should be folded. Any time more than 1 item is selected, all items should be folded. 
- Add a watch to ViewerSelectionObject to update the fold state when a change has been made
> feat(fe2): Collapse all selected properties when new element is selected

- packages/frontend-2/components/automate/function/create-dialog/DetailsStep.vue
- packages/frontend-2/components/project/model-page/dialog/move-to/NewTab.vue
- packages/frontend-2/components/project/page/models/NewDialog.vue
- packages/frontend-2/components/project/page/models/NewModelStructureItem.vue
- packages/frontend-2/components/project/page/models/card/EditDialog.vue
- packages/frontend-2/components/projects/AddDialog.vue
- packages/frontend-2/components/viewer/resources/VersionCard.vue
2 Small changes to fe2. 
The first was reported by Matteo in discord. Because we call various inputs "name", autocomplete wrongly thinks these are the user’s name, rather than model/project/function etc. I updated these to be more accurate.
The second is something I noticed when working on another task. If you push a version through a connector, quite often you will see "A few seconds ago" as the time in the viewer. This copy is too long, and breaks onto 2 lines and looks poor. 
- Add "autocomplete='off'" to inputs with their name as name, even though it is not the users name. Autocomplete checks the name attribute, and ours cannot be easily changed without breaking changes. Instead, we will just turn off autocomplete for these inputs. 
- Stop "a few seconds ago" from breaking line
> fix(fe2): Use better input names to avoid triggering autocomplete. Stop "a few seconds ago" from breaking line

- packages/frontend-2/plugins/survicate.client.ts
Currently, Survicate does not support mapping custom attributes like distinctId to Mixpanel's distinct_id. This change updates the Survicate initialisation to set the user_id attribute, ensuring proper identification in Mixpanel.
- Map user_id to distinctId for Survicate-Mixpanel integration
> Fix(fe2): Map user_id for Survicate-Mixpanel integration

- packages/frontend-2/components/automate/function/Card.vue
- packages/frontend-2/components/project/page/automation/Functions.vue
- packages/frontend-2/components/project/page/automation/Models.vue
- packages/frontend-2/components/project/page/automation/Runs.vue
- packages/frontend-2/components/project/page/models/Card.vue
- packages/frontend-2/pages/projects/[id]/index/automations/[aid].vue
Fixed two bugs on the automation page:
1. The function and model cards didn't truncate properly
2. The function card didn't align with the run table next to it
> Overflow and alignment bugs on automation page

- packages/frontend-2/components/auth/LoginWithEmailBlock.vue
- packages/frontend-2/components/auth/RegisterWithEmailBlock.vue
> fix(fe2): pw being set as query param when login/register form submitted too early

- packages/frontend-2/components/automate/function/Card.vue
- packages/frontend-2/components/automate/function/CardView.vue
- packages/frontend-2/components/project/models/BasicCardView.vue
- packages/frontend-2/components/project/page/models/Card.vue
Follow up to this PR from yesterday: https://github.com/specklesystems/speckle-server/pull/2291
The way I fixed the truncation yesterday meant that the ··· menu on model cards got cut off because of overflow hidden. This PR fixes the truncation properly through better grid classes.
Note that I've also changed a bit how the models are displayed across breakpoints in the different cases. It's better now.
> Proper fix of model and function card truncation

- packages/frontend-2/middleware/requireValidAutomation.ts
- packages/frontend-2/middleware/requireValidFunction.ts
- packages/frontend-2/pages/functions/index.vue
- packages/server/modules/automate/errors/core.ts
- packages/server/modules/automate/graph/resolvers/automate.ts
- packages/server/modules/index.js
tl;dr; Even if a module is disabled, its GQL components (typedefs, resolvers) will still be loaded to avoid complexity on the client-side. So we must always ensure resolvers can handle the module being disabled.
> fix: extra safety for when automate is disabled

- packages/frontend-2/components/viewer/Controls.vue
During the Gendo integration, a z-index was added to the controls sidebar to aid in making it resizeable. This meant the lower control items were not visible. 
This is a quick change to remove this z-index, and fall back to the already declared z-10. 
@didimitrie It may be that this z-20 was needed, but I have done a good bit of testing and everything still seems to work. Maybe you can remember why it was needed?
Before:
After:
> fix: Remove z-index causing explode menu to be hidden

- packages/frontend-2/components/project/page/settings/webhooks/Webhooks.vue
A label has appeared in the Webhooks table, showing the Switch name. It has now been turned off.
> fix(fe2): hide switch label in webhooks

- packages/frontend-2/components/viewer/selection/Sidebar.vue
Add a Tooltip to the new "Open selection in new window" button in the selection info panel.
I'm not entirely sure why the tooltip would not work properly when applied to the button, but wrapping the button in a div, and applying v-tippy to this worked fine.
> feat(fe2): add tooltip to "Open selection in new window"

- packages/frontend-2/components/automate/function/CreateDialog.vue
- packages/frontend-2/components/automate/functions/page/Header.vue
- packages/frontend-2/middleware/requiresAutomateEnabled.ts
- packages/frontend-2/pages/functions/index.vue
- packages/server/modules/automate/clients/executionEngine.ts
- packages/server/modules/automate/graph/resolvers/automate.ts
> feat: check if user is fn author w/ exec engine

- packages/frontend-2/components/project/page/automations/Row.vue
Caught a small copy error when testing test automations. Currently each entry will say "triggered by [Model]" when this is not true for test automations.
Changed to "connected to" but open to any phrasing:
> Small fix: test automations are never triggered

- packages/frontend-2/components/viewer/Sidebar.vue
- Remove `h-18` - this is not a defined Tailwind height
- Match height in header spacer
> fix(fe2): set height of selection info header to avoid transparency issue

- packages/frontend-2/components/viewer/explorer/StringFilterItem.vue
- packages/frontend-2/components/viewer/explorer/TreeItem.vue
- packages/frontend-2/components/viewer/selection/Sidebar.vue
1. Make it possible to select hidden elements from the Scene Explorer and Filters. Behaviour when selecting: Show outline of element, open the selection info panel, but it’s still hidden.
2. Don’t deselect an element if you hide it from the Scene Explorer. Create the same experience as when you hide an element from the Selection Info panel.
- Remove hidden item check from setSelection
- Remove hidden item check from availableTargetIds
- removeFromSelection even if hidden
- Update "Hide/Unhide" sidebar text to make it more clear
> feat(fe2): Allow selection of hidden items from Scene Explorer

- packages/frontend-2/components/viewer/anchored-point/NewThread.vue
- packages/frontend-2/components/viewer/explorer/Filters.vue
- packages/frontend-2/components/viewer/explorer/StringFilterItem.vue
- packages/frontend-2/components/viewer/explorer/TreeItem.vue
- packages/frontend-2/components/viewer/resources/ModelCard.vue
- packages/frontend-2/components/viewer/resources/VersionCard.vue
- packages/frontend-2/components/viewer/views/Menu.vue
- packages/frontend-2/lib/viewer/composables/commentBubbles.ts
I've removed various 150ms hover transitions around the viewer so it feels more snappy to navigate. The motivation is PR #2322 which might hurt the performance a bit in some situations when merged, and these hover transitions make that more noticeable.
> Remove various hover transitions around the viewer

- packages/frontend-2/components/automate/automation/CreateDialog.vue
- packages/frontend-2/lib/automate/composables/jsonSchema.ts
Fixes bug where user can't proceed from step 2 in the Create Automation form if the function doesn't have any parameters. Nothing happened when clicking the Next button in this state:
> Fix automation creation form

- packages/frontend-2/components/automate/automation/create-dialog/SelectFunctionStep.vue
- packages/frontend-2/components/automate/function/Card.vue
- packages/frontend-2/components/automate/function/page/Header.vue
- packages/frontend-2/components/automate/function/page/Info.vue
- packages/frontend-2/components/automate/functions/page/Items.vue
- packages/frontend-2/components/project/page/automations/EmptyState.vue
This PR changes various little things to improve the UX of selecting or learning more about a function. 
1. Changes button copy to "Use in **an** automation" on a functions page (Jonathon suggestion)
2. Removes the "Learn more" and "Use" buttons on the function cards in the functions gallery and on the empty state of the Automations tab. Clicking the entire a card will instead take you to the full function page. It's a much cleaner layout and I think it's a better UX even from the Automations tab.
3. Updates the "Use" button on step 1 of the Create Automation flow:
3.1. From "Use" to "Select"
3.2 On click it becomes "✔︎ Selected"
3.3 Clicking again deselects
> Update use/select actions on functions

- packages/frontend-2/components/automate/automation/create-dialog/AutomationDetailsStep.vue
Aligns the styling of the project select input with the model input
> Don't tint projects select input

- packages/frontend-2/components/automate/runs/Table.vue
- packages/ui-components/src/components/layout/Table.vue
The button to view the run details isn't visible on the lg breakpoint on the automation page. I've decreased the table's general min width to fix this, but we need to follow up soon with a better responsive table behaviour. I've checked other tables in the product after this change and it doesn't introduce any problems.
> Adjust table so run details button is visible

- packages/dui3/lib/bindings/definitions/IAccountBinding.ts
- packages/dui3/lib/bindings/definitions/IBasicConnectorBinding.ts
- packages/dui3/lib/bindings/definitions/IBinding.ts
- packages/dui3/lib/bindings/definitions/IConfigBinding.ts
- packages/dui3/lib/bindings/definitions/IReceiveBinding.ts
- packages/dui3/lib/bindings/definitions/ISelectionBinding.ts
- packages/dui3/lib/bindings/definitions/ISendBinding.ts
- packages/dui3/store/hostApp.ts
I've created `IBindingSharedEvents` and extend all bindings event with it to enable setting toast notification from every binding
> Set global notification from bindings

- .circleci/config.yml
- .circleci/publish_fe2_sourcemaps.sh
- packages/frontend-2/components/projects/Dashboard.vue
- packages/frontend-2/nuxt.config.ts
- packages/frontend-2/package.json
- yarn.lock
generate source maps in prod build + allow devs to trigger errors (for now) through secret query param
> feat: sourcemaps + testing

- packages/dui3/lib/common/generated/gql/graphql.ts
- packages/frontend-2/components/automate/function/Card.vue
- packages/frontend-2/components/project/page/automations/Tab.vue
- packages/frontend-2/composables/globals.ts
- packages/frontend-2/lib/common/composables/graphql.ts
- packages/frontend-2/pages/functions/[fid].vue
- packages/frontend-2/pages/functions/index.vue
- packages/frontend-2/pages/projects/[id]/index.vue
- packages/frontend-2/pages/projects/[id]/index/automations/[aid].vue
- packages/server/.env-example
- packages/ui-components/src/components/common/loading/Bar.vue
- utils/eslint-projectwide.mjs
> fix(fe2): ugly function card hydration issue

- packages/frontend-2/components/viewer/views/Menu.vue
Ensures full view name is visible on hover when text is truncated.
- Add title attribute to buttons in ViewerViewsMenu
> fix(fe2): add `title` attribute to buttons in the view selection menu

- packages/dui3/lib/bindings/definitions/ITestBinding.ts
- packages/dui3/store/hostApp.ts
I should have done before. @JR-Morgan keen to trigger `shouldThrow` function from console to trigger some top level exceptions.
> Chore (dui3): include test binding to listen notifications

- packages/frontend-2/components/header/NavUserMenu.vue
- packages/frontend-2/components/project/CardImportFileArea.vue
- packages/frontend-2/lib/common/helpers/route.ts
This changes links from `/downloads` to `https://speckle.systems/features/connectors/` to point users in the right direction (desktop app). Also opens in a new tab now it's a link to the speckle website instead of the app
> Fix: Change /downloads links to https://speckle.systems/features/connectors/

- packages/frontend-2/components/form/file-upload/Progress.vue
- packages/frontend-2/components/form/file-upload/ProgressRow.vue
- packages/frontend-2/components/viewer/anchored-point/NewThread.vue
- packages/frontend-2/components/viewer/anchored-point/thread/Comment.vue
- packages/frontend-2/components/viewer/anchored-point/thread/CommentAttachments.vue
- packages/frontend-2/components/viewer/anchored-point/thread/NewReply.vue
- packages/frontend-2/components/viewer/comments/Editor.vue
There were some small UI/UX issues and differences between comments and replies on the viewer. This PR aligns them and fixes some of the UI issues (such as overlapping buttons).
Fixes https://linear.app/speckle/issue/WEB-450/improve-design-when-attaching-a-file-to-a-comment
> Fix: Improve comment/reply attachment styling 

- packages/frontend-2/components/viewer/explorer/StringFilterItem.vue
Currently, we parse the item value and display only the string after the last dot. This was deemed unnecessary, as it leads to loss of useful information and can cause different filters to appear identical. The change ensures the full item value is shown, avoiding these issues.
- Remove `item.value.split('.').reverse()[0]`
> feat(fe2): don't truncate filter name in StringFilterItem

- packages/frontend-2/lib/viewer/composables/setup.ts
- packages/frontend-2/lib/viewer/composables/setup/postSetup.ts
> fix(fe2): add newHasDoneInitialLoad to manage initial load of viewer

- packages/dui3/components/model/CardBase.vue
- packages/dui3/store/hostApp.ts
Otherwise we rely on connector devs to handle it for each connector. I would like to handle it UI, bc it is safest.
> Fix (dui3): Do not trigger highlight if baked object ids undefined

- packages/server/app.ts
- packages/server/modules/core/errors/ratelimit.ts
- packages/server/modules/core/graph/plugins/statusCode.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/streams.js
- packages/server/package.json
- yarn.lock
Currently GQL responses always return a status code of 200, even if its a rate limit or internal server error response. This new Apollo Server plugin I added responds w/ proper HTTP 401, 403, 429 & 500 status codes when those kinds of errors/issues pop up when processing a GQL request.
> fix(server): 401, 403, 429 & 500 status codes for GQL error responses

- packages/server/modules/core/graph/plugins/statusCode.ts
Kind of reverts specklesystems/speckle-server#2463
This introduces unnecessary error scenarios with Apollo Client and broken error messages, need to introduce this more carefully
> fix(server): only changing gql http status code on rate limiting

- packages/frontend-2/components/developer-settings/CreateTokenDialog.vue
- packages/frontend-2/components/error/page/ProjectInviteBanner.vue
- packages/frontend-2/components/form/select/Projects.vue
- packages/frontend-2/components/project/page/MoreActions.vue
- packages/frontend-2/components/projects/invite/Banner.vue
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/frontend-2/pages/onboarding.vue
- packages/frontend-2/pages/projects/[id]/index.vue
- packages/server/assets/accessrequests/typedefs/accessrequests.graphql
- packages/server/assets/activitystream/typedefs/activity.graphql
- packages/server/assets/auth/typedefs/apps.graphql
- packages/server/assets/blobstorage/typedefs/blobstorage.graphql
- packages/server/assets/comments/typedefs/comments.gql
- packages/server/assets/core/typedefs/branchesAndCommits.graphql
- packages/server/assets/core/typedefs/objects.graphql
- packages/server/assets/core/typedefs/streams.graphql
- packages/server/assets/core/typedefs/user.graphql
- packages/server/assets/fileuploads/typedefs/fileuploads.graphql
- packages/server/assets/serverinvites/typedefs/serverInvites.graphql
- packages/server/assets/webhooks/typedefs/webhooks.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/graph/resolvers/appTokens.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/test/graphql/generated/graphql.ts
Note that this includes fields still in use by DUI3 and Connectors/Manager
> chore(server): marking all old (non-FE2) GQL schema fields as deprecated

- packages/objectsender/package.json
- packages/objectsender/src/examples/browser/main.ts
- packages/objectsender/src/examples/browser/utils.ts
- packages/objectsender/src/index.ts
- packages/objectsender/src/utils/Decorators.ts
- packages/objectsender/src/utils/Serializer.ts
- packages/objectsender/tsconfig.json
- yarn.lock
Adds the ability for using decorators in class declarations to describe detached and chunkable fields.
```typescript
class RandomJoe extends Base {
@Detach()
@Chunkable(10)
numbers: number[]
constructor(props?: Record<string, unknown>) {
super(props)
this.numbers = times(100, () => 42)
}
}
```
The main reason why I am proposing is that I noticed while playing with the object sender that the frontend-2 assumes certain shapes. For example: Collection.elements will give me a nice UI, but Collection['@elements'] won't. I imagine there are other parts of the ecosystem that have those behaviours.
- Added @Detach() and @Chunkable(n) decorators
- Added examples of classes using the decorators
- Added a createCommit helper
https://www.typescriptlang.org/docs/handbook/decorators.html#metadata
> Object Sender: Adds @Detach and @Chunkable decorators

- packages/frontend-2/components/viewer/explorer/TreeItem.vue
We had previously hidden elements with the speckle_type `DisplayStyle` from the Scene Explorer. This task to do the same for these speckle_types:
- ProjectInfo
- RevitMaterial / Materials
- View
- View3D
- Updated `ViewerExplorerTreeItem` to include an array of types to be hidden
- Refactored `isAllowedType` function to check for these hidden types using substring matching
> refactor(fe2): remove certain revit elements from SceneExplorer

- packages/frontend-2/middleware/headers.global.ts
I found out some browsers are very particular about the type of quotes in the header, and won't accept `frame-ancestors "none"` so I had to change it to `frame-ancestors 'none'`
> Fix: Change quote type for header

- packages/server/modules/index.js
- packages/server/modules/workspacesCore/index.ts
We need to correctly initialize the new `workspaces` and `workspacesCore` modules in a license-safe way:
- Initialize `workspacesCore` in all cases
- Initialize `workspaces` _if_ environment variable `FF_WORKSPACES_MODULE_ENABLED` is true
- The license checks are not yet implemented and guaranteeing this is true but will in the future
PR corrects the logic in `getEnabledModuleNames()` and adds a minimal `index.ts` for `workspacesCore`.
> fix(workspaces): correctly initialize and import workspaces core module

- packages/frontend-2/components/project/page/InviteDialog.vue
- packages/frontend-2/components/project/page/settings/collaborators/Collaborators.vue
- packages/frontend-2/components/project/page/team/dialog/invite-user/EmailsRow.vue
- packages/frontend-2/components/project/page/team/dialog/invite-user/ServerUserRow.vue
Some small adjustments in the invite to project dialog to align the sizes. Button feels a bit big but it's the only one we have atm that matches the dropdown input. We can probably revisit this when we update the ui components.
> Fix: Adjust sizes in invite dialog

- packages/server/modules/automate/services/tracking.ts
- adds `durationInMilliseconds`
- uses `elapsed` because [we have it](https://github.com/specklesystems/speckle-server/blob/9fad4b2d587a4e2b0f15431983640d0783f5d141/packages/server/modules/automate/services/runsManagement.ts#L129) (happy to also do it with dayjs like existing, just saw this was available)
- technically undoes second-level rounding, can preserve if we want it
> chore(automate): track run duration in ms too

- packages/frontend-2/components/project/page/discussions/Results.vue
- packages/frontend-2/components/settings/server/ActiveUsers.vue
- packages/frontend-2/components/settings/server/PendingInvitations.vue
- packages/frontend-2/components/settings/server/Projects.vue
Following the comment on the settings modal PR this PR changes the tables that use infinite loading to use `usePaginatedQuery`, as well as the discussions page. 
There are a few more places where this can be done (dashboard and models), I will address these in a separate PR when I have some time in between things or when we touch these pages, which will be soon.
(also fixes some minor styling issues that I noticed in the search bar on the settings pages)
> Fix: Change server settings and discussion to usePaginatedQuery

- packages/frontend-2/utils/dateFormatter.ts
Small fix for the dateFormatter util, when rendering the prefix it would also show when the timeframe was 'days', resulting in an output of "on 5 days ago". This makes sure "day" is also excluded from using the prefix.
> Fix: Add 'day' to dateFormatter check

- packages/frontend-2/components/settings/Dialog.vue
- packages/ui-components/src/components/layout/Dialog.vue
There were some issues with DUI 3 and the modal being always being fullscreen on sm screensizes, this adds the options to specificy the fullscreen options (default on mobile, optional to show on all, only desktop or none)
> Feat: Add option to show modal not fullscreen on mobile

- packages/frontend-2/components/project/page/models/Card.vue
To fix this:
Added width classes to fix.
> hotfix(fe2): Add truncation to prevent long names overflowing

- packages/frontend-2/components/auth/third-party/LoginButtonBase.vue
Looked a bit off, fixed it to look like this (like the design):
> Fix: Adjust SSO button styling

- packages/frontend-2/components/settings/Dialog.vue
- packages/frontend-2/composables/globals.ts
- packages/frontend-2/lib/common/generated/gql/gql.ts
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/frontend-2/lib/settings/graphql/queries.ts
Abstracted this from the adding general workspaces branches, so it doesn't blocks adding other pages.
Fetches all the workspaces and adds them to the settings sidebar. Doesn't add any links to specific pages but they will be added in the related PRs. Will only be shown when the user has actual workspace so it won't show for any existing users (as they wont have workspaces)
> Feat: Add base for rendering workspaces items in the settings sidebar

- packages/viewer/src/modules/loaders/Speckle/SpeckleConverter.ts
Description in here: [CNX-115: Viewer: handle gracefully instances with elements that failed to convert](https://linear.app/speckle/issue/CNX-115/viewer-handle-gracefully-instances-with-elements-that-failed-to)
It's a one liner fix, that if @AlexandruPopovici sees it as safe, we can merge.
> feat(viewer): handles missing instance components gracefully

- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/management.ts
- packages/server/modules/workspaces/tests/integration/workspaces.graph.spec.ts
- Did not validate incoming changes to workspace name/desc
- But we should
- Validates
- Adds tests for these cases
- Moves authz to resolver level, since I'm here
> fix(workspaces): backend validation on workspace settings fields

- packages/frontend-2/app.vue
- packages/frontend-2/components/viewer/PreSetupWrapper.vue
Bilal requested this in discord. When you have multiple tabs from the same project open, it's hard to know which tab is which. 
This change adds the Model Name to the page title. If multiple models, it will say "Multiple models". 
This change also involved changing the trailing `- Speckle` to `| Speckle`.
> refactor(fe2): Update viewer page title to include model name

- packages/dui3/components/receive/Wizard.vue
- packages/dui3/components/send/Wizard.vue
- packages/dui3/components/wizard/ModelSelector.vue
Instead of creating new model cards, finds the existing one and patch it with important data before running send/receive operation.
Patching on send:
- `sendFilter`
- `isExpired`
Patching on receive:
- `selectedVersionId`
- `latestVersion`
SEND
RECEIVE
> Fix(dui3): Use existing cards for latter operations

- packages/frontend-2/Dockerfile
We enabled building sourcemaps even when not using them cause we were running into issues w/ sourcemaps not working, and thought that maybe the built file hashes are different if sourcemaps are enabled/disabled.
Sourcemaps did start working, but from a seemingly unrelated fix. Additionally, building sourcemaps and then deleting them still causes browsers to request them sometimes (cause they're referenced in the .js files) and the requests fail w/ a 500 not 404 error, probably because of the manual build output manipulation.
So lets try disabling them in the build again and hope that sourcemap collection in the separate CI job still works
> fix(fe2): dont build sourcemaps unnecessarily

- packages/dui3/store/hostApp.ts
We were looking solution on wrong garden.
It was sneaky.. (No escape press needed anymore)
The delay on the seeing first card at the beginning lead me to think on potential async/await issue with `await sendBinding.send` function. Sometimes we hit the send function too early and AutoCAD API doesn't like it as we doesn't like him. It was random. By sacrificing 500ms delay on acad send operation fixing the problem. 🤷‍♂️
Also there is no more delay at the begining. We see the card immediately.
> Fix(dui3): Autocad escape issue

- packages/dui3/pages/index.vue
CTA buttons in card had `z-10` index for a purpose. I have put footer buttons to `z-20`.
> Fix(dui3): z index of footer buttons

- packages/frontend-2/components/settings/Dialog.vue
- packages/frontend-2/components/settings/server/Projects.vue
Adds a event listener for close events, so the modal will be closed once a project is selected
> Fix: Add close event to settings modal

- packages/server/modules/core/rest/health.ts
Pods are placed in an unready state if the database connections are saturated for >20 seconds.
We currently have a situation where there are some long-running database queries. These cause the database connections available to a pod to be saturated for extended periods of time. This in turn causes the pod to be in an unready state. Over time, as the long-running queries accumulate, the number of pods which are unready increases. This eventually causes the entire cluster to be unavailable.
Currently the only way to recover is to restart the pod.
Including a check of saturated database connections in the liveness probe is a short-term hack to ensure affected pods are restarted whenever the encounter this issue.
> chore(liveness): fail liveness if db conns saturated for 10min

- packages/tailwind-theme/src/plugin.ts
Jonathon noticed the lack of a hover state in the Button. This was down to the wrong hex value being applied to as the "primary-focus" class. 
This has been updated to the correct value
> fix(tailwind-theme) Update primary focus hex value

- packages/server/modules/webhooks/domain/operations.ts
- packages/server/modules/webhooks/graph/resolvers/webhooks.js
- packages/server/modules/webhooks/repositories/webhooks.ts
- packages/server/modules/webhooks/services/webhooks.js
- packages/server/modules/webhooks/tests/webhooks.spec.js
> chore(webhooks): get webhook function refactor

- packages/frontend-2/components/dashboard/Sidebar.vue
- packages/frontend-2/components/header/NavBar.vue
- packages/frontend-2/components/project/page/models/Card.vue
- packages/frontend-2/components/project/page/models/Header.vue
- packages/frontend-2/components/project/page/models/StructureItem.vue
- packages/frontend-2/components/viewer/Controls.vue
- packages/frontend-2/components/viewer/PreSetupWrapper.vue
- packages/frontend-2/layouts/viewer.vue
Use NuxtLink. Move nested button that was causing hydration error to relatively positioned div, outside of the NuxtLink.
> fix(fe2): Use NuxtLink. Move nested button to relatively positioned div

- packages/frontend-2/components/project/page/models/Actions.vue
- packages/ui-components/src/components/layout/Menu.vue
Allows us to manually set the menu position. If not set, it will fall back to the old function.
> feature(ui-components): Add menuPosition prop to LayoutMenu

- packages/frontend-2/components/dashboard/Sidebar.vue
- packages/frontend-2/components/global/icon/Connectors.vue
Michal has designed a new icon, more fitting with the new design system, but also something known to our users. 
I added a "ml-px". It's one of those where although it is perfectly aligned with the other icons, it still looks slightly off to the eye, due to the shape of the icon. The slight margin lessens this effect.
> refactor(fe2): Replace IconConnectors with new version

- packages/server/app.ts
- if no data is being sent on a websocket connection then it was closed by nginx after 60s
- it is assumed to be better to keep alive the connection than have the overhead of closing and re-establishing the connection every 60s
- keepAlive parameter configured for websocket connections to graphql.
> fix(graphql websocket): keep alive websocket connections if idle

- packages/frontend-2/components/viewer/explorer/TreeItem.vue
Closes (for now!) [CNX-326: Frontend: clean the scene explorer](https://linear.app/speckle/issue/CNX-326/frontend-clean-the-scene-explorer).
tl;dr: we've been adding stuff to the object model, and the current filtering was not cutting it and made the whole scene explorer unusable in quite a few instances.
> feat(scene explorer): filters out noise from scene explorer (CNX-326)

- docker-compose-deps.yml
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/.env-example
- setup/db/11-docker_postgres_keycloack_init.sql
- setup/keycloak/speckle-realm.json
- setup/keycloak/speckle-users-0.json
Should work automatically for new local instances, but existing ones (w/ existing DB) will need to run the SQL init file manually before starting up keycloak.
**LOCAL SETUP**
1. For existing docker compose deployments, invoke SQL found in `setup/db/11-docker_postgres_keycloack_init.sql` in your DB client manually (as the speckle user). New docker compose deployments can skip this step.
2. yarn dev:docker:up
3. Copy OIDC strategy env vars from .env-example into .env (in `server`)
4. When logging in in FE2, use speckle:speckle or register a new keycloak account
> local OIDC provider for testing

- packages/server/knexfile.js
- knex should use pino logger as its internal logger
- knex should not compile sql on error in production environments as this may leak sensitive values
> fix(logging): knex should use pino logger and not compile sql on error in production

- packages/frontend-2/components/project/page/models/Card.vue
This div has child elements that have a z-index set, but because it doesn't have a a z-index itself it was overflowing on other elements
> Fix: z-index on project card

- packages/shared/src/automate/helpers/types.ts
Change `visualoverrrides` to `visualOverrides` for consistency.
`gradientValues` and `objectResults` are correct by convention. This removes potential confusion.
> fix(automate): corrected naming convention for `visualOverrides`: an as yet unused property on object result case

- packages/dui3/components/common/ModelNotification.vue
Trivial but it was unnecessarily too much.
py-2
py-1
> Chore(dui3): Decrease padding y 2 to 1 for model notification

- packages/frontend-2/components/projects/DashboardHeader.vue
- packages/frontend-2/components/promo-banners/Banner.vue
- packages/frontend-2/components/promo-banners/Wrapper.vue
- packages/frontend-2/lib/promo-banners/types.ts
Adding 2 banners to the PromoBanner component:
- Submit your proposal
- Early Bird Tickets
I also removed all functionality related to cookies. These will always be shown until they expire.
> feat(fe2): Add 2024 specklecon banners

- packages/ui-components/src/components/layout/sidebar/menu/group/Group.vue
Fix the alignment issue in the settings sidebar. 
Fix the chevron so it rotates correctly
> fix(fe2): Update Chevron Rotation. Add Margin for items with icon

- packages/frontend-2/components/workspaces/Promo/Banner.vue
We use Beta in the sidebar, but New in the banner. 
I updated NEW to BETA to reflect the new change
> fix(fe2): New to Beta in Explainer Banner

- packages/frontend-2/components/dashboard/Sidebar.vue
- packages/ui-components/src/components/layout/sidebar/menu/group/Group.vue
Move the "Add Workspace" button to the LayoutSidebarGroup, as per the designs.
> Add Plus CTA to SidebarGroup

- packages/dui3/components/form/json/EnumControlRenderer.vue
It was unsetting it if we select the same item. Which we do not handle undefined behavior on any setting. So, disabled it for now.
Related to: https://linear.app/speckle/issue/CNX-380/revit-unset-settings-causes-dependency-error
> Fix(dui3): disable allow unset for settings dropdown

- packages/frontend-2/components/settings/workspaces/Security.vue
Following https://linear.app/speckle/issue/WEB-1744/turning-on-domain-based-membership-policy-when-the-workspace-has-no
- Disable toggles when domainlist is empty
- Dont allow removal of last domain if policy is enabled
- Make sure domain discovery is turned off when the last domain is removed
> Fix: Disable removing of last domain if policy is on

- packages/frontend-2/components/project/page/Header.vue
If a project is in a workspace, we should show the breadcrumbs as:
/workspaces/WorkspaceName/ProjectName
If it's not in a workspace, it should be:
/projects/ProjectName
> feat(fe2): Add workspace to breadcrumbs

- packages/frontend-2/components/settings/SectionHeader.vue
- packages/frontend-2/components/settings/server/General.vue
- packages/frontend-2/components/settings/user/Developer.vue
- packages/frontend-2/components/settings/user/Emails.vue
- packages/frontend-2/components/settings/user/Notifications.vue
- packages/frontend-2/components/settings/user/Profile.vue
- packages/frontend-2/components/settings/user/email/ListItem.vue
- packages/frontend-2/components/settings/user/profile/Details.vue
- packages/frontend-2/components/settings/workspaces/General.vue
- packages/frontend-2/components/settings/workspaces/Security.vue
https://linear.app/speckle/issue/WEB-1750/divider-lines-hr-and-borders-in-the-settings-pages-should-use-outline
> fix(fe2): Update HR and borders in Settings Dialog

- packages/server/modules/workspaces/services/invites.ts
Slight copy change, based on feedback from Iain
https://linear.app/speckle/issue/WEB-1757/error-copy-the-target-email-is-not-matching-the-domain-policies
> fix(fe2): Update WorkspaceProtectedError

- packages/server/modules/workspaces/repositories/workspaces.ts
- packages/server/modules/workspaces/tests/integration/repositories.spec.ts
> fix(workspaces): dont leak guests

- packages/frontend-2/components/viewer/Controls.vue
Currently, when typing a comment, you can accidentally trigger the sidebar shortcuts. 
Now, we check if the user is typing a comment before we execute the shortcut action.
> fix(fe2): Don't trigger shortcuts while typing comments

- packages/frontend-2/components/project/model-page/versions/Card.vue
> fix(fe2): Actions menu on Version Card

- packages/frontend-2/components/settings/workspaces/General/DeleteDialog.vue
We had a problem where when you deleted a workspace from the settings dialog, you would still be on the deleted workspace's url. 
This caused the breadcrumbs to break, and made no sense. 
Now, if you are on the url of the workspace you just deleted, you will be redirected to the homeRoute.
> fix(fe2): Redirect to home on deletion of workspace if on the deleted workspace url

- packages/ui-components/src/components/layout/Menu.vue
I also removed the ring classes. Not sure that they were actually doing anything, but it's not in designs.
> fix(ui-components): Add border to LayoutMenu

- packages/frontend-2/components/project/page/models/Actions.vue
- packages/ui-components/src/components/layout/Menu.vue
When an item in the Model card actions is disabled, we do not give an indication of this in the UI. 
We should also add tooltip text explaining why it is disabled.
> fix(ui-components) Update LayoutMenu disabled states

- packages/frontend-2/lib/workspaces/composables/management.ts
Use the new modifyObjectField to update the cache, when a user has had their role set to null (removed).
> fix(fe2): Update cache after removing workspace members

- packages/frontend-2/pages/projects/[id]/index.vue
Bug noticed on a call with Michal. When you are on a discoverable project, with no role, it displays an empty tag.
> fix(fe2): Project page - only show role tag if you have a role

- packages/frontend-2/utils/dateFormatter.ts
> fix(fe2): Add 'just now' to isTimeframe check to prevent "Created on just now"

- packages/dui3/components/filter/Selection.vue
- packages/dui3/components/model/ActionsDialog.vue
- packages/dui3/components/model/Sender.vue
- packages/dui3/components/send/FiltersAndSettings.vue
- packages/dui3/components/send/Settings.vue
- packages/dui3/components/send/SettingsDialog.vue
- packages/dui3/components/wizard/ModelSelector.vue
- packages/dui3/components/wizard/ProjectSelector.vue
- packages/dui3/components/wizard/list/ModelCard.vue
- packages/dui3/lib/core/composables/updateConnector.ts
1. Change Filter Dialog
- Bring save button back
- "Settings" accordion only available on first send. Not available after model card created.
2. Settings Dialog on model card actions
3. Toast Notification on "Update available" not triggerred on dev mode
> Feat(dui3): CNX-401 bad ux settings vs selection and minors

- packages/ui-components/src/components/layout/Menu.vue
Previously, I swapped LayoutMenu to use a similar positioning technique as SelectBase. This uses teleport to move the menu to the body, to fix any z-index/overflow issues. 
This had some unintended consequences, including a bug reported on versions page. When you deleted or moved a version, the positions of the menus were not recalculated, meaning the menu was at a random location when you opened it. 
This PR makes mount-menu-on-body an optional prop (that defaults to false). Now we will only use this when it is needed (in a table or a dialog), and other LayoutMenus will work how they did previously.
> feat(ui-components): LayoutMenu - Make mount-menu-on-body optional prop

- packages/dui3/store/hostApp.ts
We upgrade the sender card settings on the init.
Another issue was, we were not awaiting the init functions like `void refreshDocumentModelStore()` in the `hostAppStore` and it was causing empty `documentModelStore` whenever we call `tryToUpgradeSettings()`. I have wrapped them into `async` init function and await them all.
> Feat(dui3): CNX-548 card settings backward and forward compatible

- packages/frontend-2/plugins/survicate.client.ts
The `/authn/verify/index` page is the only one in `/authn/` that needs the user to be logged in.
Right now, we show the Survicate NPS survey to logged-in users, but we don’t want it appearing on the verify page.
Regular page:
Authorize page:
> fix(fe2): Don't show survicate NPS on authorize application page

- packages/frontend-2/components/workspace/header/Header.vue
> fix(fe2): Always show workspace description read more on mobile

- packages/server/modules/activitystream/services/commentActivity.ts
- packages/server/modules/automate/graph/resolvers/automate.ts
- packages/server/modules/automate/index.ts
- packages/server/modules/automate/services/trigger.ts
- packages/server/modules/automate/tests/trigger.spec.ts
- packages/server/modules/cli/commands/download/commit.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/comments/domain/operations.ts
- packages/server/modules/comments/graph/resolvers/comments.ts
- packages/server/modules/comments/repositories/comments.ts
- packages/server/modules/comments/services/retrieval.ts
- packages/server/modules/core/domain/branches/operations.ts
- packages/server/modules/core/domain/commits/types.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/repositories/branches.ts
- packages/server/modules/core/services/commit/viewerResources.ts
- packages/server/modules/cross-server-sync/index.ts
> chore(server): core IoC 5 - getBranchLatestCommitsFactory

- packages/server/modules/core/domain/branches/operations.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/repositories/branches.ts
- packages/server/modules/core/services/branch/retrieval.ts
> chore(server): core IoC 8 - getProjectTopLevelModelsTreeFactory

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/services/streamActivity.ts
- packages/server/modules/serverinvites/graph/resolvers/serverInvites.ts
- packages/server/modules/serverinvites/services/coreFinalization.ts
> chore(activitystream): IoC 1 refactor addStreamInviteDeclined

- packages/frontend-2/components/tour/content/OverlayModel.vue
This is to remove the shadow from the button in the onboarding flow:
> fix(fe2): Update button style in onboarding flow

- packages/frontend-2/components/viewer/explorer/Filters.vue
> fix(fe2): Cannot access 'isRevitProperty' before initialization

- packages/frontend-2/components/singleton/Managers.vue
- packages/frontend-2/components/singleton/ToastManager.vue
- packages/frontend-2/plugins/portal.ts
- packages/ui-components/src/components/layout/Dialog.vue
Bit of a strange one.
Our toasts were not clickable when a dialog was open due to headless ui adding an inert attribute to the nuxt root. 
There also is a function in HeadlessUI which closes the dialog on click of any element outside the DialogPanel. 
My solution was:
- Added a `<div id="toast-target" />` inside DialogPanel in Dialog.vue.
- Updated ToastManager.vue to use Vue's Teleport:
- Renders toast inside #toast-target if it exists (when dialog is open).
- Otherwise, renders in the default location (body).
- This ensures toasts are always clickable and maintains consistent appearance/behaviour.
- This solution solves the issue without significantly altering existing dialog or toast logic.
> fix(fe2): Make toasts clickable when dialogs are open

- packages/server/modules/auth/middleware.ts
- packages/server/modules/auth/strategies.ts
- packages/server/modules/workspaces/rest/sso.ts
- Workspace SSO login would like to re-use existing steps/middleware of our auth flow
- They are currently only available in the auth module
- Exports middleware as factory functions
- Uses them in existing strategy builder, and in step required by SSO
> chore(auth): move common middleware to factory functions

- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/domain/commits/types.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/versions.ts
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/core/services/commits.js
- packages/server/modules/core/tests/commits.spec.js
> chore(server): core IoC 18 - updateCommitAndNotifyFactory

- packages/viewer/src/modules/LegacyViewer.ts
Fixes https://linear.app/speckle/issue/WEB-1958/visibility-issues-when-highlighting
- The highlight extension gets it's material cache reset when applying other filters by using the same approach as for selection
> TreeView Highlight Fix

- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/domain/commits/types.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/previews/index.ts
- packages/server/modules/previews/services/resultListener.ts
> chore(server): core IoC 25 - getObjectCommitsWithStreamIdsFactory

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/streams.js
- packages/server/modules/core/services/streams/favorite.ts
> chore(server): core IoC 39 - getFavoriteStreamsCollectionFactory

- packages/frontend-2/components/projects/DashboardHeader.vue
- Removed divide-y which was causing the unnecessary line between invites
- ProjectInviteBanner and WorkspaceInvitesBanner are 2 separate components. This causes a weird visual bug, where both have rounded borders, but there is no gap. I added a small gap to make this seem more intentional.
@benjaminvo The second part was out of scope of this ticket, so just want to run this past you before merging.
> fix(fe2): Border issues around invite banners

- packages/frontend-2/components/workspace/ProjectList.vue
This is to prevent the flash from the url in breadcrumbs, when you first load a workspace page.
> fix(fe2): Only show Workspace breadcrumb when workspace is loaded

- packages/shared/package.json
- packages/tailwind-theme/package.json
- utils/ensure-tailwind-deps.mjs
> feat(root): streaming ensure tailwind deps output

- packages/frontend-2/components/workspace/ProjectList.vue
- packages/frontend-2/components/workspace/header/Header.vue
- Moved the `Move projects` button down next to the `New projects` button and turned it into an actual button (white, similar to the invite button).
- The button still becomes hidden in <md breakpoint, and instead is added to the ... menu
- Kept it visible to Members and Guests but disabled. On hover show tooltip with: "Only admins can move projects into the workspace".
- Tooltips don't consistently work on buttons, so i wrapped the button in a div.
- Add "Move projects" button to Quickstart card
> refactor(fe2): Changes to Move Projects button

- packages/frontend/.vscode/settings.json
- packages/preview-service/.vscode/settings.json
- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/streams.js
- packages/server/modules/core/services/streams/favorite.ts
- packages/server/modules/core/tests/discoverableStreams.spec.ts
- packages/ui-components/.vscode/settings.json
- packages/viewer/.vscode/settings.json
> chore(server): core IoC #40 - favoriteStreamFactory

- packages/frontend-2/components/project/page/settings/collaborators/Row.vue
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/projects.ts
- packages/server/modules/workspaces/tests/unit/services/projects.spec.ts
- We do not want to allow workspace guests to be project owners. Reviewers and editors only.
- Adds this protection in backend (new service function)
- Adds this protection to frontend
> fix(workspaces): prohibit workspace guests from being project owners

- packages/frontend-2/components/settings/workspaces/members/TableHeader.vue
Instead of hiding the invite button to non workspace admins, we now show a disabled button, with a tooltip warning the user. 
I had to do this with a v-if, and the isAdmin state is initially false for all users on loading the dialog. The caching issue with tooltips meant the tooltip was always visible, even when the button was not disabled. The v-if pattern fixed this.
> refactor(fe2): Output disabled invite button to non-admins

- packages/frontend-2/lib/viewer/composables/setup/postSetup.ts
We make the viewer pretend it's a connector and send out receive events. Note, this is important for us to track to be able to get a picture of how much data is consumed in our viewer.
Thx to @fabis94 for the fast help this morning on this one.
> Adds viewer receive events

- packages/frontend-2/pages/index.vue
Ghost(old) site is now at v1.speckle.systems.
The tutorial cards in FE2 are using the Ghost API and is sending users to the old site. 
This is a temp change to replace the url given by the Ghost API, to the new Webflow site at speckle.systems.
It is important that permalinks match on both sites, and that any new articles are added to Ghost as well (even if its an empty story)
> feat(fe2): Temporary Ghost URL replacement until we swap to WebFlow API

- packages/preview-service/src/server/routes/api.ts
- packages/preview-service/src/server/routes/objects.ts
- packages/server/modules/core/rest/diffDownload.ts
- packages/server/modules/core/rest/download.js
I think the force closing of a DB is slightly wrong.
From my understanding, request close event is only called when a connection is forcefully closed.  Also, it seems the destroy needs to be called to ensure the DB connection goes back to the pool.  The found docs is slightly wrong
https://knexjs.org/faq/recipes.html#manually-closing-streams
https://github.com/knex/knex/issues/2324
> Add stream destroy where db streams are used on download

- packages/frontend-2/components/projects/DashboardHeader.vue
@benjaminvo I think there was a merge conflict in your papercuts branch. There was a slight change to the invite banners yesterday, which now makes the `space-y-3` class add spacing between each banner, rather than banner groups.
> fix(fe2): Remove spacing in invite banners

- packages/viewer/readme.md
Update the examples link in the viewer readme. Seems like a mistake that it links to a migration guide in Notion currently?
> Fix: Update examples link

- packages/ui-components/src/components/layout/Menu.vue
If the position of a LayoutMenu updates, the position for the dropdown did not update to reflect this. 
Now, when opening a LayoutMenu with mount-menu-on-body prop, we recalculate the bounding.
> fix(ui-components): Update bounding on opening of LayoutMenu when mountMenuOnBody

- packages/frontend-2/components/form/select/WorkspaceRoles.vue
- packages/frontend-2/components/settings/shared/ChangeRoleDialog.vue
- packages/frontend-2/components/settings/workspaces/members/GuestsTable.vue
- packages/frontend-2/components/settings/workspaces/members/MembersTable.vue
- packages/frontend-2/lib/workspaces/composables/management.ts
Adding SettingsSharedChangeRoleDialog to guests table, triggered by the actions menu. 
Also adding a prop to this, to allow us to hide items from the role select, in this case, hide guests role when editing a guest.
> feat(fe2): Add change role dialog to guests table

- packages/server/modules/auth/index.ts
- packages/server/modules/auth/middleware.ts
- packages/server/modules/auth/services/postAuth.ts
- packages/server/modules/auth/strategies/azureAd.ts
- packages/server/modules/auth/strategies/github.ts
- packages/server/modules/auth/strategies/google.ts
- packages/server/modules/auth/strategies/local.ts
- packages/server/modules/auth/strategies/oidc.ts
- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/domain/users/types.ts
- packages/server/modules/core/events/usersEmitter.ts
- packages/server/modules/core/services/users/management.ts
- packages/server/modules/shared/utils/mixpanel.ts
Matteo noticed that Sign Up MP events don't always fire: https://discord.com/channels/726756379083145269/1296758480606330880/1296853364251824200
Ultimately this seems to happen because the auth flow fails near the very end, but after the new user is already created. It's not clear to me why it fails (the one scenario happened because of a mismatched challenge, but how did that happen especially in the Google SSO flow?), but it is a problem that an authentication failure prevents post-sign up activities from firing.
So I refactored the logic to be more resilient - post-sign up tracking is now done pretty much right after user creation and it occurs independently from the actual sign in flow, so if the very last step fails - if a user was created, the event should be fired.
> fix(server): more resilient sign up tracking

- packages/frontend-2/components/workspace/invite/DiscoverableWorkspaceBanner.vue
When you have a discoverable workspace banner, and click join, now you are redirected to the workspace on success. 
This was the existing function, but it was hard coded to `workspace/id`, which doesn't exist anymore, we use slugs. I updated it to use workspaceRoute, and thanks to Chuck we now can get the slug from WorkspaceInviteDiscoverableWorkspaceBanner_LimitedWorkspace
> fix(fe2): Redirect to workspace when joined through discoverable banner

- packages/frontend-2/server/api/webflow.ts
The change gracefully handles missing Webflow API tokens and other error cases by returning an empty array instead of throwing errors, while logging appropriate messages for debugging and monitoring.
> fix(fe2): Handle no webflow api token errors more gracefully

- packages/server/modules/blobstorage/objectStorage.ts
> chore(server): easy js to ts migrations #2 - objectStorage.ts

- packages/viewer/src/modules/objects/SpeckleInstancedMesh.ts
- packages/viewer/src/modules/pipeline/Pipelines/Pipeline.ts
Coming as undead patch # 9 this PR adds support for overriding the batch material for instanced batches, and fixes the issues where some view modes did not work in streams with instances
> View Modes Support for Instances `undead-patch`

- packages/frontend-2/components/workspace/ProjectList.vue
Added the workspace name to the page title on the workspace page. 
Set it once we have the name available.
> fix(fe2): Add workspace name to workspace page title

- packages/viewer/src/modules/LegacyViewer.ts
Made sure `LegacyViewer` passes over an actual `Box3` object to the viewer
> Section Box Fix

- README.md
https://linear.app/speckle/issue/CNX-699/update-github-links-to-point-to-v3
> Update README.md to use new repo links

- packages/frontend-2/components/viewer/explorer/Filters.vue
Fixes a regression introduced by me in https://github.com/specklesystems/speckle-server/pull/2728 for navis properties. See https://discord.com/channels/726756379083145269/1301616425299083315/1301627216257613939 for the internal discussion and reporting
cc @jsdbroughton
> fix: fixes navis props missing from filtering

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/Intersections.ts
- packages/viewer/src/modules/World.ts
Selection would fail to work for streams where the bounds would contain 0 sized components. This PR fixes that
> WEB-2137: Selection Fix for 0 Component Size Streams

- packages/server/modules/accessrequests/tests/streamAccessRequests.spec.ts
- packages/server/modules/auth/tests/integration/registration.spec.ts
- packages/server/modules/automate/tests/automations.spec.ts
- packages/server/modules/blobstorage/tests/blobstorage.graph.spec.js
- packages/server/modules/comments/tests/comments.graph.spec.js
- packages/server/modules/comments/tests/comments.spec.js
- packages/server/modules/core/graph/dataloaders/index.ts
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/tests/apitokens.spec.ts
- packages/server/modules/core/tests/batchCommits.spec.ts
- packages/server/modules/core/tests/commitsGraphql.spec.ts
- packages/server/modules/core/tests/discoverableStreams.spec.ts
- packages/server/modules/core/tests/favoriteStreams.spec.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/modules/core/tests/usersAdminList.spec.ts
- packages/server/modules/core/tests/usersGraphql.spec.ts
- packages/server/modules/emails/tests/verifications.spec.ts
- packages/server/modules/serverinvites/tests/invites.spec.ts
- packages/server/modules/shared/helpers/graphqlHelper.ts
- packages/server/modules/shared/middleware/index.ts
- packages/server/modules/workspaces/graph/dataloaders/workspaces.ts
- packages/server/modules/workspaces/tests/integration/invites.graph.spec.ts
- packages/server/modules/workspaces/tests/integration/projects.graph.spec.ts
- packages/server/modules/workspaces/tests/integration/roles.graph.spec.ts
- packages/server/modules/workspaces/tests/integration/sso.graph.spec.ts
- packages/server/modules/workspaces/tests/integration/workspaces.graph.spec.ts
- packages/server/test/graphqlHelper.ts
So all of the preexisting dataloaders still exist but only use the main DB. If you want to spawn a set of loaders for your specific region, you have to do `ctx.loaders.forRegion({ db })` and then this set will use that new region DB.
Loaders of course won't be shared across regions. So if you do `ctx.loaders.streams.getStream.load()` and `ctx.loaders.forRegion({ db: regionDb }).streams.getStream.load()` these 2 will be 2 different queries in 2 different databases.
> feat(server): multi region support in dataloaders

- packages/server/modules/automate/services/authCode.ts
- Deep diving into automate auth for ongoing work, appear to have caught a bug
- The final part of the handshake - where automate asks speckle server if the auth code is real and valid:
- Correctly checks if the code exists at all
- Appears to be incorrectly asserting specific claims (user id, action) against itself, instead of the code automate has
- Validate stored auth code against incoming auth code from automate server, instead of itself (appears to be the intent of the code)
> fix(automate): fix possible auth error

- packages/dui3/lib/bindings/definitions/ISendBinding.ts
- packages/dui3/store/hostApp.ts
It was populating before `selectedObjectIds` on UI and it became visible only second highligh model after filter changed. Now I pass selectedObjectIds explicitly from host app to fix it.
> Fix(dui3): do not pass selectedobjectids from idmap

- packages/dui3/components/wizard/ProjectSelector.vue
- packages/dui3/lib/common/generated/gql/gql.ts
- packages/dui3/lib/common/generated/gql/graphql.ts
- packages/dui3/lib/graphql/mutationsAndQueries.ts
we can create again projects in workspace (initially some workspaces was throwing graphql errors for guests for sure and handled as bottom image)
also disabled items if user a guest
> Fix(diu3): align new graphql schema for workspaces

- packages/server/modules/core/graph/resolvers/branches.ts
> chore(multiregion): branches resolvers multiregion

- packages/frontend-2/components/projects/AddDialog.vue
https://github.com/user-attachments/assets/5fe70707-aee1-4319-993e-14ffda0da7a1
Gergo reported:
the create button is clickable until the modal goes away
so i can create as many projects, as fast as i click
Added a new state to track when the form has been first submitted. Also used vee-validates isSubmitting
> Prevent creation of multiple projects by multiple clicks

- packages/frontend-2/components/project/page/latest-items/comments/EmptyState.vue
- packages/frontend-2/components/viewer/comments/Comments.vue
[LINEAR TICKET](https://linear.app/speckle/issue/WEB-2087/new-discussion-button-doesnt-do-anything)
Now, we only show the button when an object is selected. If not, we show a message telling them to select something.
> fix(fe2): Only show "New Discussion" button when an object is selected

- packages/ui-components/src/components/layout/tabs/Horizontal.vue
[LINEAR TICKET](https://linear.app/speckle/issue/WEB-2000/update-width-of-nav-bar-active-indicator)
> fix(ui-components): Update tab underline width on content change

- packages/frontend-2/components/settings/user/developer/AccessTokens/AccessTokens.vue
- packages/ui-components/src/components/layout/Table.vue
[LINEAR TICKET](https://linear.app/speckle/issue/WEB-2054/personal-access-tokens-shows-empty-state-while-loading)
Bug reported by Jonathan. We now show a loading state to Personal Access Tokens table.
> refactor(fe2): Add loading state to Access Tokens

- packages/server/test/hooks.ts
this keeps causing flaky multiregion test breakages https://app.circleci.com/pipelines/github/specklesystems/speckle-server/14136/workflows/adbe28b7-c2bc-4967-ba05-f3aee4d682a0/jobs/231690/tests
maybe we don't need it?
> fix(server): remove flaky dblink_slot_create_or_drop calls in tests

- packages/server/test/hooks.ts
> fix(server): add delays in test pubsub cleanup

- packages/frontend-2/components/settings/workspaces/Billing.vue
> Feat: Adjust billing settings for Academia and Unlimited plans

- packages/frontend-2/components/automate/viewer/panel/FunctionRunRow.vue
We don't handle any formatting characters for function run status messages, so the result can be a bit hard to read.
Before:
After:
> fix(automate): handle newline in status messages

- packages/fileimport-service/ifc/import_file.js
- packages/fileimport-service/src/daemon.js
If the model (aka branch) ID was undefined, it was being passed as the string `'undefined'` and not as a falsy value.
A new branch was therefore not being created.
> fix(file import): handle undefined branch id

- packages/frontend-2/components/automate/viewer/panel/FunctionRunRowObjectResult.vue
- packages/shared/src/automate/helpers/types.ts
- We're adding a `SUCCESS` result level for objects and the frontend needs to support it. 
- Looks like this:
> fix(automate): support success object result level

- packages/dui3/lib/bridge/server.ts
- packages/dui3/lib/bridge/sketchup.ts
mostly for archicad to be able to send batches (100mb) sequentially instead of passing all JSON object to browser. There was huge performance penalty on `JSON.parse`
PS: Sketchup bridge still has some differences other that generic and server bridge, I would keep them separete till when we have more bandwidth to do it better
PS2: Changes are backward compatible, even if we merge this, nothing will be side effected.
also related to: https://github.com/specklesystems/speckle-sketchup/pull/397
validated with sketchup
> Feat(dui3): send batches sequentially from server bridges

- packages/frontend-2/components/automate/function/Card.vue
- packages/frontend-2/components/automate/function/page/Header.vue
- packages/frontend-2/components/automate/function/page/Info.vue
- packages/frontend-2/components/automate/function/page/InfoBlock.vue
- packages/frontend-2/components/automate/function/page/ParametersDialog.vue
- packages/frontend-2/components/automate/functions/page/Header.vue
- packages/frontend-2/components/automate/runs/Table.vue
- packages/frontend-2/components/automate/runs/trigger-status/Dialog.vue
- packages/frontend-2/components/automate/viewer/Panel.vue
- packages/frontend-2/components/automate/viewer/panel/FunctionRunRow.vue
- packages/frontend-2/components/common/CodeOutput.vue
- packages/frontend-2/components/common/prose/GithubReadme.vue
- packages/frontend-2/components/project/page/automation/Functions.vue
- packages/frontend-2/components/project/page/automation/Runs.vue
- packages/frontend-2/components/project/page/automations/Row.vue
- packages/frontend-2/components/project/page/automations/RunDialog.vue
- packages/frontend-2/components/settings/user/developer/AccessTokens/AccessTokens.vue
- packages/frontend-2/components/settings/user/developer/Applications/Applications.vue
- packages/frontend-2/components/settings/user/developer/AuthorizedApps.vue
- packages/frontend-2/components/settings/user/developer/Developer.vue
- packages/frontend-2/lib/automate/composables/runStatus.ts
- packages/ui-components/src/components/form/TextArea.vue
Bit more cleaning up of automate UI. Again, can be improved further, but just a start to align things a bit more with the other styles
> Fix: Clean up some more automate styling

- packages/viewer/src/index.ts
- packages/viewer/src/modules/Viewer.ts
- packages/viewer/src/modules/extensions/controls/SmoothOrbitControls.ts
Fixes the issue where zoom to cursor did not work properly if the viewer canvas was offset from (0,0) in the page
> WEB-1611: Zoom to Cursor Fix

- packages/server/modules/workspaces/errors/sso.ts
- packages/server/modules/workspaces/rest/sso.ts
- Invalid profiles from identity providers were throwing the same error as missing profiles, which was confusing and wrong.
> fix(sso): distinguish between missing and invalid sso user profile

- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/sso.ts
- packages/server/modules/workspaces/tests/unit/services/sso.spec.ts
- The backend logic used by the "Continue with SSO" button uses `findUserByEmail`, but this is implicitly only by _primary_ email.
- Users will want to continue with their company email regardless of if it's also their primary email
- `findUserByEmail` => `findEmail` then user user id
> fix(sso): continue with sso from any verified email

- packages/frontend-2/components/workspace/CreateDialog.vue
Default logo index was being randomized/reset on modal close, but set to 0 on first open. So nearly everyone was getting this lil guy as the default logo.
NO LONGER
> fix(workspaces): randomize first default logo

- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/clients/oidcProvider.ts
- packages/server/modules/workspaces/domain/sso/types.ts
- packages/server/modules/workspaces/errors/sso.ts
- packages/server/modules/workspaces/helpers/sso.ts
- packages/server/modules/workspaces/rest/sso.ts
- packages/server/modules/workspaces/services/sso.ts
- packages/server/modules/workspaces/tests/unit/helpers/sso.spec.ts
- packages/server/modules/workspaces/tests/unit/services/sso.spec.ts
- Use OIDC `state` parameter instead of our `?validate=true` business
- Appease Okta with these changes
- One callback, with middleware for setting/confirming access to `state`
- Update copy in FE form to drop `?validate=true`
- Also stop checking if sso provider email is verified because EntraId
> fix(sso): oidc state parameter

- packages/frontend-2/components/settings/workspaces/Billing.vue
- packages/frontend-2/lib/billing/helpers/constants.ts
- Make it clearer that the trial is free
- Also make it clearer that there's no payment due
> Update billing summary for trial plans

- packages/frontend-2/components/settings/Dialog.vue
Bug reported by @iainsproat in discord:
as a server admin, I'm able to see all workspace settings. (expected?)
The tooltip and menu on the left suggest that I need to sign in with SSO (bug)
I'm able to click on the greyed-out link anyway and it opens the page (expected?)
> fix(fe2): Allow server:admin access to all workspace settings

- packages/frontend-2/lib/settings/composables/management.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/management.ts
- packages/server/modules/workspaces/tests/helpers/creation.ts
- packages/server/modules/workspaces/tests/unit/services/management.spec.ts
- With paid workspaces, we want to add friction/intention behind adding seats. The current "discoverable workspaces" feature turns on by default, which was fine when access was free, but we'd like it to be on purpose now.
- Do not enable domain discovery by default when adding a domain
> fix(workspaces): no default discovery

- packages/frontend-2/components/settings/workspaces/General.vue
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/management.ts
- packages/server/modules/workspaces/tests/helpers/creation.ts
- packages/server/modules/workspaces/tests/integration/subs.graph.spec.ts
- packages/server/modules/workspaces/tests/unit/services/management.spec.ts
- SSO is currently configured with redirects specific to a workspace slug. If the slug changes, SSO breaks. If SSO breaks and your session expires, you're locked out.
- Disable slug edit on FE & BE if SSO is configured
> fix(sso): disable slug edit if sso enabled

- packages/frontend-2/components/settings/workspaces/General.vue
- packages/frontend-2/components/workspace/wizard/step/Details.vue
- packages/frontend-2/components/workspace/wizard/step/Invites.vue
- packages/frontend-2/components/workspace/wizard/step/Pricing.vue
- packages/frontend-2/components/workspace/wizard/step/Region.vue
- Update copy on the wizard steps
- Also append the slug URL to the helper text (including in settings)
> Update wizard copy

- packages/frontend-2/components/settings/workspaces/General.vue
- packages/ui-components/src/components/form/TextInput.vue
- packages/ui-components/src/composables/form/textInput.ts
Although we still want the default behaviour to be `break-words`, in the case of the slug, `break-all` is more appropriate. Now you can pass custom classes to the help text to achieve this.
> fix(fe2): Adjust word wrap of slug input help text

- .circleci/config.yml
- packages/server/package.json
- packages/shared/src/environment/index.ts
- packages/webhook-service/.vscode/launch.json
- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/frontend_2/deployment.yml
https://linear.app/speckle/issue/WEB-2301/multi-region-blobs-feature-flag
> feat(server/feature flags): adds multi-region blob storage ff

- packages/frontend-2/components/automate/functions/page/Header.vue
- We recently started redirecting all traffic from `automate.speckle.dev` to `app.speckle.systems/functions?automateBetaRedirect=true`
- This page is not ideal, it gives no further context, and it's not clear what the best redirect experience should be. But I want to get a clearer picture of how many people are actually affected before investing any time.
- Tracks a mixpanel event when people are redirected from `automate.speckle.dev`
> chore(automate): track redirects from beta site

- packages/frontend-2/components/common/tiptap/MentionList.vue
- packages/frontend-2/lib/core/tiptap/mentionExtension.ts
- packages/server/modules/core/graph/resolvers/users.ts
- packages/server/modules/core/tests/integration/users.graph.spec.ts
Follow up to #3635.
Now that you can only mention project collaborators I think it's safe to show the mention dropdown after typing a single character. Better UX.
> Trigger mention dialog after a single character

- packages/frontend-2/components/viewer/gendo/Panel.vue
Adds an MP event when a Gendo render is triggered. I also log the remaining renders left so we can track how many hit the limit or just try it a few times.
> Add Gendo Mixpanel event

- packages/server/app.ts
> feat(server): allow using frontend proxy in fe2 mode too

- packages/frontend-2/components/settings/workspaces/General/DeleteDialog.vue
- packages/server/modules/workspaces/services/management.ts
- We don't keep track of workspace deletion in mixpanel, so deleted workspaces are showing up in metrics when they maybe aren't relevant
- Set a mixpanel property on a workspace when deleted
> chore(workspaces): track deleted workspace in mixpanel

- packages/frontend-2/components/settings/workspaces/Billing.vue
Update this text to "Cancels" if the plan is cancelled:
This is consistent with what the user sees in the billing portal:
> Fix: Update text in biling settings if plan is cancelled

- packages/viewer-sandbox/src/Extensions/BoxSelection.ts
- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/index.ts
- packages/viewer/src/modules/objects/SpeckleRaycaster.ts
- packages/viewer/src/modules/objects/TopLevelAccelerationStructure.ts
Fixes issue https://linear.app/speckle/issue/WEB-2162/tas-only-shapecast-is-incorrect reported [here](https://speckle.community/t/some-questions-about-expanding-box-selection/14855/7)
- `intersectTASRange` now correctly receives all valid `BatchObject`s
- `intersectTASRange` only recieves a `BatchObject` **once**
- TAS shapecast now 4X times faster
- Additionally this seems to have fixed a very old issue that was also reported by Nickos, where the section outlines would sometimes not get properly generated for some objects
> Fixed TAS Shapecast

- packages/frontend-2/components/settings/workspaces/Billing.vue
- packages/frontend-2/lib/common/helpers/route.ts
Added links to documentation and support in billing settings. I also included Mixpanel tracking because I actually doubt anyone clicks it – but let's see :).
> Chore(workspaces): Add support links to billing settings

- packages/frontend-2/lib/viewer/helpers/shortcuts/shortcuts.ts
This updates the view mode names in the frontend. Thanks Claire for the suggestions.
For now I didn't update the naming of the objects etc so those are still aligned with the names coming from the viewer library. Confusing inconsistency – but maybe we're OK with that for now while naming might still be changing?
> Rename view modes

- packages/frontend-2/components/dashboard/tutorials/Card.vue
- packages/frontend-2/components/dashboard/tutorials/Wrapper.vue
- packages/frontend-2/lib/dashboard/helpers/types.ts
- packages/frontend-2/pages/index.vue
- packages/frontend-2/server/api/webflow.ts
> Feat: Change blog to tutorials

- packages/frontend-2/components/viewer/anchored-point/thread/NewReply.vue
This was caused by a race condition that is hard to consistently recreate, but I've changed it to ensure proper cleanup of the comment editor state when errors occur
> fix(fe2): Comment editor submission problem

- packages/ui-components/src/components/layout/tabs/Horizontal.vue
Workaround for the reactivity issue
> Fix: tooltip on members table

- packages/frontend-2/components/viewer/Controls.vue
- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/extensions/measurements/Measurement.ts
- packages/viewer/src/modules/extensions/measurements/MeasurementPointGizmo.ts
- packages/viewer/src/modules/extensions/measurements/MeasurementsExtension.ts
- packages/viewer/src/modules/extensions/measurements/PerpendicularMeasurement.ts
- packages/viewer/src/modules/extensions/measurements/PointToPointMeasurement.ts
Handles [WEB-2311](https://linear.app/speckle/issue/WEB-2311/measurement-tool-units-resets-to-meters-incorrectly) & [WEB-2399](https://linear.app/speckle/issue/WEB-2399/measurementtool-units-do-not-update-properly)
- `Measurement`'s `update` function now returns `Promise<void>` because it may contain a text which can only be updated asynchronous because of how troika-text (the library we use for text rendering) works
- Corrects units and precision are being set when a new measurement is created
> Measurements Units Fixes

- packages/frontend-2/components/settings/server/General.vue
- packages/frontend-2/components/settings/workspaces/General.vue
- packages/ui-components/src/components/form/TextArea.vue
We didn't have the label-postion prop in TextArea. I added it, and used this for server and workspace descriptions.
> chore(fe2): Add label-position prop to TextArea. Make descriptions TextArea

- packages/frontend-2/components/workspace/Avatar.vue
- packages/frontend-2/components/workspace/header/Header.vue
> Fix: Dont show tooltip on all workspace avatars

- packages/ui-components/src/components/layout/sidebar/menu/group/Group.vue
> Fix: Align settings sidebar with main sidebar

- packages/server/assets/core/typedefs/modelsAndVersions.graphql
- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/services/commitActivity.ts
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/test/graphql/generated/graphql.ts
> feat(server): ProjectVersionsUpdatedMessage.modelId always filled

- packages/frontend-2/components/invite/dialog/Server.vue
- packages/frontend-2/components/singleton/ToastManager.vue
- packages/frontend-2/lib/common/composables/toast.ts
- packages/frontend-2/lib/projects/composables/projectManagement.ts
- packages/frontend-2/lib/server/composables/invites.ts
- packages/ui-components/src/components/global/ToastRenderer.stories.ts
- packages/ui-components/src/components/global/ToastRenderer.vue
- packages/ui-components/src/stories/components/GlobalToast.vue
- packages/ui-components/src/stories/composables/toast.ts
- Revert back to old notification system of only triggering one notification at the time
- Add option to hide toasts in compostables, and handle them in the parent in the case of server invites
> Fix: Revert notification changes

- packages/frontend-2/components/viewer/Controls.vue
This is not a perfect solution, but it's better than it is currently. 
Right now, smaller screens clip the bottom of the viewer controls. You can see my screenshot above, and i'm on a decent mac, so others will definitely experience this. 
There was a weird `bg-green/0` class which i removed, and then added `overflow-y-auto` to the same div. 
Now, when the menu overflows the viewport, our custom scrollbar appears. This should have no affect on users with large screens, but allows other users to access lower items. 
@Mikehrn I discussed this one with Benjamin this morning and we talked about a larger rethink on this controls menu in the viewer. It's not worth spending time on a better solution right now, when this is all probably going to change pretty soon.
> fix(fe2): Make viewer controls scrollable when they overflow viewport

- packages/server/app.ts
- packages/server/modules/core/graph/plugins/logging.ts
`speckle_server_apollo_calls` was no longer present in the Prometheus metrics. It is not known when that metric stopped being produced.
This PR fixes the metric so that it is now available when Prometheus is scraped.
- the metric is initialized when the plugin is initialized, not when the module is loaded
- the metric is initialized with the Prometheus register being explicitly provided
- (we believe the bug that is being resolved is due to the metric being registered in a different Prometheus register than the one being served at `/metrics`)
Metric `speckle_server_apollo_calls` is now present when `/metrics` endpoint is queried:
> fix(metrics): speckle_server_apollo_calls built with correct register

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/SpeckleRenderer.ts
- packages/viewer/src/modules/Viewer.ts
Handles https://linear.app/speckle/issue/WEB-2417/shadows-dont-update-when-switching-versions. Shadowcatcher now updates when a new render tree is added to the scene or an existing one is removed even if there is no scene in the scene's bounds.
> WEB-2417: Shadowcatcher updates when switching versions

- packages/frontend-2/components/settings/workspaces/Projects.vue
Bug reported by Matteo in Discord. During a server slowdown, it showed no projects, but it was actually loading.
> fix(fe2): Add loading indicator to workspace projects table

- packages/frontend-2/components/workspace/ProjectList.vue
Added a flag to ensure workspace finalisation only occurs once, preventing duplicate invite emails from being sent during the creation flow.
> fix(fe2): prevent duplicate workspace invites during creation

- packages/frontend-2/layouts/withRightSidebar.vue
I noticed a hydration warning in console, so wrapped PortalTarget with ClientOnly to prevent SSR-related issues.
> fix(fe2): resolve PortalTarget SSR attribute inheritance warning

- packages/frontend-2/lib/viewer/composables/activity.ts
When testing multi-user interactions locally (like follow mode), the viewer would disconnect users as soon as their browser window lost focus. This made it difficult to test with multiple browser windows on the same machine.
This disables the disconnect-on-blur behaviour in development mode only, with no change to production. 
@fabis94 @Mikehrn I did this so Alex could test some things locally. It doesn't need to actually be merged unless you think it adds value.
> feat(viewer): disable disconnect-on-blur in development mode

- packages/server/app.ts
- packages/server/logging/expressLogging.ts
- packages/server/logging/knexMonitoring.ts
- packages/server/logging/requestContext.ts
- packages/server/modules/shared/helpers/envHelper.ts
- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
**Important note:** AsyncLocalStorage will likely cause some kind of performance overhead, but its hard to say how much. Considering the immense benefit this brings I think we should at the very least enable it temporarily when investigating DB & GQL query correlations
> feat(server): get request ctx from anywhere + log it w/ db operations

- packages/dui3/store/accounts.ts
I missed to cover this scenario
Tested the main functionality too, all good
BEFORE
AFTER - we have good old error properly without borking UI
> Fix(dui3): catch apollo error on initial workspaces enabled query

- packages/ui-components/src/components/form/Button.vue
- changing padding to py-0 from py-1 for default buttons
> changing padding to py-0 from py-1 for default buttons

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/app.ts
- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/dataloaders/index.ts
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/tests/graph.spec.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/package.json
- yarn.lock
ever since multi region dataloaders, they were not properly batching up SQL queries
for that big connectors query this reduced SQL counts from 121 to 42 locally, and that is with multiple regions, where each region has to have its own cache and query. so the number will be even lower for people with all data in the same region
edit: also introduced Stream/Project.collaborators dataloader, which cut that 42 SQL op count in half down to just 18
> fix(server): dataloader batching being broken

- packages/server/bootstrap.js
- packages/server/logging/knexMonitoring.ts
- packages/server/modules/core/patches/knex.ts
- packages/server/modules/shared/helpers/envHelper.ts
- packages/server/type-augmentations/knex.d.ts
- packages/shared/src/core/helpers/error.ts
- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
> feat(server): improving knex query stack traces

- packages/monitor-deployment/src/observability/metrics/inactiveReplicationSlots.ts
We have a noisy alert which triggers based on a Postgres internal operation creating a transiently inactive replication slot. The database monitoring metric which tracks inactive replication slots should only focus on slots used by speckle server.
> fix(monitor): amend inactive replication slot query to ignore non-speckle slots

- packages/shared/src/environment/index.ts
- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/frontend_2/deployment.yml
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
Add new feature flag for forcing user email verification. Disabled by default. 
This is the first time I've done this, so I'd appreciate a thorough review incase I missed anything.
> feat(server): Add force email verification feature flag

- packages/server/modules/core/graph/plugins/logging.ts
- packages/server/modules/core/graph/resolvers/commits.ts
- packages/server/modules/core/graph/resolvers/streams.ts
when limit === 0, there should be a lot less SQL queries
> feat(server): greatly optimizing Branch.commits & Query.streams, when limit=0

- packages/frontend-2/components/auth/LoginWithEmailBlock.vue
- packages/frontend-2/components/auth/PasswordResetFinalizationPanel.vue
- packages/frontend-2/components/auth/PasswordResetPanel.vue
- packages/frontend-2/components/auth/RegisterPanel.vue
- packages/frontend-2/components/auth/RegisterWithEmailBlock.vue
- packages/frontend-2/lib/auth/composables/passwordReset.ts
- packages/frontend-2/lib/common/generated/gql/graphql.ts
I made a few changes to these screens to align them with the other sign up screen, minor copy changes and added the password validation checks (personal papercut..)
> Fix: Align forgot password screens

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/assets/workspacesCore/typedefs/workspaces.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/domain/logic.ts
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/graph/mocks/workspaces.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/repositories/workspaces.ts
- packages/server/modules/workspaces/rest/sso.ts
- packages/server/modules/workspaces/services/management.ts
- packages/server/modules/workspaces/services/retrieval.ts
- packages/server/modules/workspaces/tests/helpers/creation.ts
- packages/server/modules/workspaces/tests/unit/services/domains.spec.ts
- packages/server/modules/workspaces/tests/unit/services/join.spec.ts
- packages/server/modules/workspaces/tests/unit/services/management.spec.ts
- packages/server/modules/workspaces/tests/unit/services/sso.spec.ts
- packages/server/modules/workspacesCore/domain/types.ts
- packages/server/modules/workspacesCore/helpers/db.ts
- packages/server/modules/workspacesCore/migrations/20250127110735_drop_default_logo_index.ts
- packages/server/test/graphql/generated/graphql.ts
- packages/server/test/speckle-helpers/workspaces.ts
- Field used to drive the default "space invader" logo for new workspaces.
- Has been disused for some time
- Drops it (RIP 🥲)
> chore(workspaces): drop defaultLogoIndex

- packages/frontend-2/components/viewer/selection/Object.vue
We don't want to remove the limit completely, incase there are thousand of items. It will be truncated, but the large item will still be in the dom
> fix(fe2): Up limit on objectKeys in ViewerSelectionObject

- packages/dui3/app.vue
- packages/dui3/store/hostApp.ts
In some cases in Revit, update notification is triggered and my guess on race condition since we were checking updates `onMounted` of `app.vue`. now it is safer and could fix the same issue in archicad
> Fix(dui3): unnecessary upgrade prompt for next gen connector after

- packages/dui3/lib/core/composables/updateConnector.ts
Since we do not have released version on ETABS and the exception was not handled, it caused the issue https://linear.app/speckle/issue/CNX-1144/installer-version-shows-documentless-state
> Fix(dui3): handle update connector errors

- packages/frontend-2/lib/viewer/composables/anchorPoints.ts
- packages/viewer/src/modules/queries/PointQuerySolver.ts
- packages/viewer/src/modules/queries/Query.ts
Handles https://linear.app/speckle/issue/WEB-2591/comment-bubbles-hang-on-on-the-screen-when-wasd-ing by handling https://linear.app/speckle/issue/WEB-2590/projection-query-should-report-out-of-frustum-somehow
- `PointQueryResult` now has an `inFrustum` property which tells if the result is in the camera's frustum
- The frontend uses this new property to determine if comment bubbles need to be occluded tested and displayed at all
- An extra advantage is that we won't be doing extra intersection tests for comment bubbles that are not in view
> Comment Bubbles WASD Fix

- packages/frontend-2/pages/settings/user/profile.vue
- packages/frontend-2/pages/settings/workspaces/[slug]/general.vue
Add the workspace ID to general settings, only for server admins, similar to how we show to user ID on the profile page. This will make live a lot easier when debugging or looking into issues.
> Feat: Show workspace ID for server admins

- packages/dui3/store/hostApp.ts
as same as send, it is a bit random and rare but sometime UI doesn't send command to acad for receive, seems like settimeout helps as it did with send before
> Fix(dui3): set timeout for autocad receive

- packages/ui-components/src/components/form/TextArea.vue
- packages/ui-components/src/components/form/TextInput.vue
It was reported that the new WASD changes to the viewer were being triggered when users where trying to type in a text area or text input. 
Added `@keydown.stop` to inputs to prevent this.
> fix(ui-components): stop keyboard event propagation in textarea/textinput to prevent triggering viewer controls

- packages/frontend-2/components/viewer/PreSetupWrapper.vue
@didimitrie I noticed this div appearing in embedded models. I'm guessing this shouldn't be here, so I removed it, but let me know if it serves a purpose i missed.
> fix(fe2): Remove debug loading code

- packages/server/modules/gatekeeper/graph/resolvers/index.ts
- Project creation was globally disabled in environments where billing was disabled (and some other combination of flags)
- This is only relevant in test environments
- Falls back to `readOnly: false` if billing integration is not enabled (see testing3 for current behavior)
> fix(billing): can't be read only if no billing

- packages/server/logging/logging.ts
- packages/server/modules/fileuploads/helpers/errors.ts
- packages/server/modules/fileuploads/services/resultListener.ts
When the server is notified by the file import service that a file upload status has changed, we now log the results of that status change.
- Log the results of file import status change
- Wrap any error changes in a new error type
> chore(server/logging): adds a log line on file upload status change

- packages/frontend-2/lib/projects/helpers/models.ts
- packages/server/modules/core/graph/resolvers/models.ts
Claire noticed a problem where models with spaces around slashes (e.g., "folder / subfolder") weren't displaying correctly in the tree view, though they appeared fine in card view.
My assumption is that this occurs when models are created through connectors/API, bypassing frontend sanitization.
I added model name sanitization to the backend for consistent handling of nested model names regardless of creation source.
I also added to the frontend sanitization to handle empty segments between slashes.
> feat(server): Sanitize nested model names

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/batching/InstancedMeshBatch.ts
- packages/viewer/src/modules/batching/MeshBatch.ts
- packages/viewer/src/modules/converter/Geometry.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleConverter.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleGeometryConverter.ts
Added support for custom vertex normals. Moved normal computation from batch level to object level, handling [WEB-596](https://linear.app/speckle/issue/WEB-596/split-normal-calculation) in the process
> Custom Vertex Normals Support

- packages/ui-components/src/components/form/TextInput.vue
> fix(ui-components): Add padding to text input when customIcon is defined

- packages/frontend-2/components/settings/Sidebar.vue
- packages/ui-components/src/components/layout/sidebar/menu/group/Group.vue
Adds support for nested groups items, also combines some of the template to avoid duplication
> Fix: Settings workspace sidebar groups styling

- packages/server/modules/core/services/ratelimiter.ts
If the response has already been sent, the ratelimiter middleware should not error and instead gracefully handle this case.
> fix(server/ratelimiter): gracefully handle response already sent

- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/index.ts
- packages/server/modules/workspacesCore/domain/events.ts
This removes the regular emit of workspace.metrics event for all workspaces. It has done its job, getting all existing ws states into mixpanel, so its not needed any more.
> feat(workspaces): remove regular workspace metrics tracking

- packages/server/app.ts
- packages/server/logging/index.ts
Part M of N of tidying up middleware; this paves the way to improve error handling in middleware.
- tidy app.ts by moving metrics route registration to responsible module
> refactor(server/metrics): register metrics route in Metrics module

- packages/frontend-2/components/onboarding/questions/Form.vue
- packages/frontend-2/lib/auth/composables/onboarding.ts
- packages/frontend-2/middleware/005-onboarding.global.ts
We should still show onboarding during signup flow. We just need to make sure it is skippable.
> fix(fe2): Ensure onboarding is still shown when no force FF is set

- packages/frontend-2/components/project/page/automation/Runs.vue
- packages/server/modules/automate/domain/operations.ts
- packages/server/modules/automate/graph/resolvers/automate.ts
- packages/server/modules/automate/helpers/types.ts
- packages/server/modules/automate/index.ts
- packages/server/modules/automate/services/trigger.ts
- Tried to check how test automations have been used, turns out we weren't tracking them explicitly.
- Adds `test` to possible sources for "Automation Run Triggered"
- Consolidates all mixpanel calls of this event to backend (removes single call from FE)
- Requires `source` type on backend service to make this possible
> chore(automate): track usage of test automations

- packages/server/modules/auth/defaultApps.ts
- packages/server/modules/auth/tests/apps.graphql.spec.js
- packages/server/modules/auth/tests/apps.spec.js
This pr adds a new first party app that will manage redirects for the new desktop authentication service. We cannot use the old port because manager needs it - therefore a new first party app is born.
> feat: adds a first party app for the desktop auth service

- packages/frontend-2/components/viewer/PreSetupWrapper.vue
We have an option in embed to toggle controls. The condition for this was removed at some point. I'm re-adding it here.
> fix(frontend): Check for showControls from useEmbed in Viewer

- packages/dui3/app.vue
to get rid of from "inert" dialog div -> kudos to @andrewwallacespeckle 
https://github.com/user-attachments/assets/9b473ac9-d47d-4bd4-8d09-5351a19b9823
> Fix(dui3): teleport toast manager to body by default

- packages/server/modules/core/repositories/objects.ts
Nikos reported this issue: https://www.notion.so/speckle/GQL-Material-Quantities-19db78fc7aa6800bbbfadc2a709bdb46
Given this kind of query:
```graphql
query Query($projectId: String!, $objectId: String!, $select: [String], $limit: Int!, $query: [JSONObject!] ) {
project(id: $projectId) {
object(id: $objectId) {
children(select: $select, limit: $limit, query: $query) {
totalCount
objects {
data
}
}
}
}
}
```
With these kind of params:
```json
{
"projectId": "e505b3cff9",
"objectId": "e2f99859d4f112d47e806fad6e6b94fc",
"select": [
"category",
"type",
"properties.\"Material Quantities\".*.materialName"
],
"limit": 2000,
"query": [
{
"field":"category",
"value":"Walls",
"operator":"="
}
],
}
```
If one of the selected fields ( "properties.\"Material Quantities\".*.materialName" in this case) …
> fix(server): Object.children() query data values missing sometimes

- packages/dui3/lib/bindings/definitions/ISendBinding.ts
- packages/dui3/store/hostApp.ts
It is needed for the connectors that send objects via REST API on connector side but do not have graphql logic on its SDK such as C++. It is asked by Ralph for Vectorworks
> Feat(dui3): trigger create version event

- packages/dui3/lib/common/generated/gql/graphql.ts
- packages/frontend-2/components/project/page/automations/Header.vue
- packages/frontend-2/components/project/page/automations/Tab.vue
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/test/graphql/generated/graphql.ts
- The header buttons on the automate tab are useless/confusing while the tab's gql query is loading
- Some users have interacted with it in this state, which leads to even more confusing behavior
- Hides the header until loading is finished
This can be safely tested with gql mocks.
> fix(automate): defer showing header until automate tab query finishes

- packages/frontend-2/components/project/page/settings/webhooks/CreateOrEditDialog.vue
- packages/frontend-2/components/project/page/settings/webhooks/Webhooks.vue
- packages/frontend-2/lib/projects/composables/webhooks.ts
- packages/ui-components/src/components/form/select/Multi.vue
- Reorder items in CreateOrEditDialog so triggers is higher, meaning there is less chance of the dropdown overflowing the dialog
- Use new FormSelectMulti
- Prevent the FormSelectMulti from jumping to the top of the option list on each selection
- Add a mapping function to map the old webhooks names to their new equivalent, without affecting functionality
> refactor(fe): Improve webhooks ux

- packages/server/test/hooks.ts
- Current multiregion test config appears to be a bit flaky during setup
- Re-introduces manual wait during setup/teardown processes
> chore(tests): multiregion test config waits

- packages/server/modules/workspaces/errors/sso.ts
- packages/server/modules/workspaces/rest/sso.ts
- When using workspace SSO, if the provider user already exists on the Speckle server, we cannot sign you in as them.
- The current error does not provide enough information.
- Tells user (post successful SSO auth flow) more specifically what has happened:
- Who they are currently signed in as
- Who they attempted to sign in as
> chore(sso): clearer sso user taken error

- packages/frontend-2/middleware/005-onboarding.global.ts
We should return from onboarding middleware early if on an authn page, incase it caused problems with auth flow.
> refactor(fe): Update onboarding middleware to not run on auth pages

- packages/dui3/components/filter/ListSelect.vue
- packages/dui3/components/filter/form/Select.vue
- packages/dui3/components/filter/revit/Views.vue
- packages/dui3/lib/models/card/send.ts
- packages/dui3/store/hostApp.ts
Well, we should have done this at the first place. I am triggered by navis saved sets and there will be more (in navis) single dropdown kind of send filters.
**Important note: I initially was testing with RevitViews. It works OK but I need to deal with backward compatibility etc to make sure it will work nicely with existing model cards.**
No more Revit Views changes
Related sharp connectors PR -> https://github.com/specklesystems/speckle-sharp-connectors/pull/619
> Feat(dui3) send filter form select

- packages/frontend-2/lib/core/helpers/observability.ts
- packages/frontend-2/plugins/001-logger.ts
- packages/shared/src/core/helpers/utility.ts
> feat(fe2): add extra metadata to seq logs for improved observability

- packages/frontend-2/components/connectors/Page.vue
I noticed a small misalignment on the connectors page between the search and the filter. 
Added size prop so they are both `h-8` and made filter `color=foundation` to match search input
> fix(fe): Alignment on connectors page filters

- packages/server/modules/automate/clients/executionEngine.ts
- In #4085 I made some changes to allow "array" query params. Because of a misunderstanding with lodash `isEmpty`, I was also accidentally omitting most search params.
- Breakage limited to new functions listing (we couldn't provide the `includeFeatured` param)
- Only run `isEmpty` against arrays in `getApiUrl`
Validated on `testing3`.
Before:
After:
> fix(automate): fix search param parsing

- packages/dui3/components/feedback/Dialog.vue
- packages/dui3/components/header/NavBar.vue
- packages/dui3/components/header/UserMenu.vue
- packages/dui3/layouts/default.vue
- packages/dui3/lib/core/composables/zapier.ts
- we have user menu by default now and feedback dialog available under it.
- zapier ping is tested https://discord.com/channels/726756379083145269/1292817871340306502/1346116096108789932
- theme switcher on main screen is removed and components vertically centered
- version info added at the bottom on main screen as text-tiny
> Feat(dui3): feedback survey + better user menu

- packages/shared/src/core/constants.ts
- packages/shared/src/workspaces/errors/index.ts
We use the `workspaces/join` and `workspaces/create` routes in frontend. 
We should block workspaces being created with this slug to avoid conflicts.
> feat(shared) Update validateWorkspaceSlug to check for blocked words

- packages/fileimport-service/ifc-dotnet/ifc-converter.csproj
Bumped the IFC importer nuget
We're having some fun re-designing the speckle-sharp-connectors CI right now, so the semver is a bit funky 😁 but I (and sourcelink) assure you its a newer version
> Bump IFC nuget

- packages/frontend-2/components/connectors/Page.vue
We have swapped the `/` for next gen connectors and v2 connectors will be in `/legacy-connectors`
> Chore(connectors): change url to legacy

- packages/dui3/store/hostApp.ts
Previosly we were losing the model cards on the document that we switched while operation is happening
> Fix(dui3): revit when moving between documents cards can get lost

- packages/frontend-2/components/settings/workspaces/billing/PricingTable/Plan.vue
From benjamin:
So to be clear: It shouldn't say "per seat/year" like the person writes in the email. We still want to display the monthly price, just with the yearly discount.
> fix(fe): show discounted monthly price when annual plan selected

- packages/dui3/components/accounts/Item.vue
- packages/dui3/components/accounts/Menu.vue
- packages/dui3/lib/bindings/definitions/IAccountBinding.ts
- packages/dui3/lib/bindings/definitions/IBasicConnectorBinding.ts
- packages/dui3/store/accounts.ts
- packages/dui3/store/hostApp.ts
There are some cases/facts that we need to test carefully
- I would like to get rid of from `defaultAccount`, previously we were relying on it but i wanna rely on `activeAccount` and did some changes for it
- What will happen once removed the only account we have
- Connectors should have this PR in -> https://github.com/specklesystems/speckle-sharp-connectors/pull/680
- There are some vue warns which i am curious I introduced them or not. Need to check later
> Feat(dui3): Remove account functionality

- packages/dui3/layouts/default.vue
Adds back a theme toggle in empty states:
> feat: reverts removal of theme toggle

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/services/streams/management.ts
- packages/server/modules/core/tests/integration/subs.graph.spec.ts
- packages/server/modules/core/tests/streams.spec.ts
- WIP auth work is complicated by `authorizeResolver` calls "buried" in services.
- Some of these are easy to hoist, some of these are in use in what are effectively "policies" already.
- Hoists easy-to-remove calls into resolvers
- Leaves "policy-like" calls for when we write those particular policies.
> chore(authz): hoist authorizeresolver

- packages/dui3/pages/index.vue
It was problematic with the files that someone else shared. Bc we were skipping by looking the accountId. Now we rely on the serverUrl.
> Fix: missing model cards on external files

- packages/server/modules/shared/utils/caching.spec.ts
- packages/server/modules/shared/utils/caching.ts
Added a new option to wrapWithCache:
```
/**
* Whether to always return the same promise instead of creating a new one for each call when the args are the same.
* This will avoid multiple calls to the resolver function on empty cache when they're invoked in short succession - the 2nd call
* will just await the 1st call's promise.
* Default: true
*/
```
Without this setting, assuming an empty cache, if you'd do a Promise.all() with multiple invocations of the same function with same args or (more realistically) if you'd have multiple GQL fields resolving the same fn with same args concurrently, each invocation would end up triggering the underlying resolver because there hasn't been enough time to cache the result yet.
With this setting, all of those invocations end up sharing the same …
> feat(server): wrapWithCache improved caching w/ shared promises

- packages/server/modules/gatekeeper/graph/resolvers/index.ts
- packages/server/modules/gatekeeper/tests/integration/workspace.graph.spec.ts
…ling limits
- Found a quirk with default model creation ("main")
- Opted to not count models without versions towards limits
> fix(workspaces): require models to have versions to count towards billing limits

- packages/dui3/store/hostApp.ts
Whenever user change the layer names, it was not updating the selected items. Now I trigger `RefreshSendFilters` in `LayerTableEvent` to be able to update send filter selected items and its summary.
> Feat(dui3): upgrade select send filters

- packages/frontend-2/components/viewer/anchored-point/Thread.vue
To fix bug where limits dialog is shown on resolving thread. The thread id stays in the url, which triggers this bug as it sees the thread as unavailable.
> fix(fe): Remove thread id from url when resolved

- packages/frontend-2/components/projects/MoveToWorkspaceAlert.vue
- packages/frontend-2/lib/common/helpers/route.ts
Updated the personal projects announcement. A separate PR will track the expand/collapse so the state is preserved.
> Feat: Update legacy projects announcement

- packages/frontend-2/lib/settings/composables/menu.ts
- packages/frontend-2/pages/settings/workspaces/[slug]/members.vue
Always show the seat change in a separate section alone in the top: 
In the admin menu: Hide the "Make guest…" action and move the "Revoke admin access…" up to the top of the second section.
> refactor(fe): Workspace member actions updates

- packages/dui3/components/wizard/list/ModelCard.vue
(defective screenshot in linear ticket)
> fix: revit 2022 model card display is now ok

- packages/dui3/components/wizard/ProjectSelector.vue
- packages/dui3/lib/bindings/definitions/IConfigBinding.ts
- packages/dui3/store/config.ts
Same as user selected account id. we have internal state and also store in DUI3Config.db as below for next session.
Related sharp PR https://github.com/specklesystems/speckle-sharp-connectors/pull/771
> Feat(dui3): store user selected workspace

- packages/server/modules/shared/command.ts
- packages/server/modules/shared/helpers/dbHelper.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
commandFactory replacement that does what it already did, but also:
* makes sure `db` is the actual transaction. this misleading aspect of the original caused many usages to not use the trx correctly
* also merges withOperationLogging into the logic
> chore(server): fixed/improved commandFactory

- packages/frontend-2/components/workspace/CreatePage.vue
We used to use the registeredThisSession, but this was caused  the alert to appear then disappear. 
Now, we just check for legacy projects. If the user has these, they will see the alert. If not, they are a new user.
> fix(fe): Only show Why am i seeing this when user has projects

- packages/frontend-2/components/settings/workspaces/billing/Page.vue
Move the banners on the Billing page below the section header
> Move banners on billing page

- packages/frontend-2/components/settings/shared/projects/index.vue
- Rename Contributors -> Project members
- Remove the visibliity type. For now it just adds confusion.
> Small updates to projects settings table

- packages/ui-components/src/components/form/TextArea.vue
- packages/ui-components/src/components/form/TextInput.vue
- packages/ui-components/src/composables/form/textInput.ts
Input and text area components have been updated to have 16px font size on mobile so that mobile browsers (Safari...) don't zoom on focus.
The font sizes in these components are really due for a clean up but I decided to do that later. For now I just added a mobile breakpoint change.
> Fix input zooming on mobile Safari

- packages/frontend-2/components/workspace/sidebar/FreePlanAlert.vue
- packages/ui-components/src/components/form/TextArea.vue
Two fixes to the workspace sidebar:
1. Fix the font size in the sm textarea
2. Tweak the copy in the Free banner
Text looked like this in the sm textarea...
> Fix: Tweak textarea font size and tweak some copy

- packages/server/modules/automate/graph/resolvers/automate.ts
- We were seeing an error on every automation create when accessing `currentRevision`
- It was because we were _always_ appending the project id (for multiregion) to the return value here, even though a `null` value was entirely valid
- Only append and return projectId if revision exists
> fix(automate): do not return invalid type for revisions

- packages/frontend-2/components/project/page/automations/Header.vue
- packages/frontend-2/pages/projects/[id]/index.vue
Moves the Automate beta badge into the Automations page and adds a hover tooltip. I thought the constant Beta badge in the project navigation took too much space and focus.
> Fix: Move Automate beta badge to the automations page

- packages/frontend-2/components/common/TitleDescription.vue
- packages/frontend-2/components/project/page/Header.vue
- packages/frontend-2/components/project/page/automations/Header.vue
- packages/frontend-2/components/project/page/collaborators/Collaborators.vue
- packages/frontend-2/components/project/page/discussions/Header.vue
- packages/frontend-2/components/project/page/models/Header.vue
- packages/frontend-2/pages/projects/[id]/index.vue
- packages/frontend-2/pages/projects/[id]/index/settings.vue
1. Smaller headings in tabs
2. Adjust spacings
3. Only show the workspace logo if viewing a project from a workspace you're not a member of + don't link to the workspace on click.
> Fix: Project page styling polish

- packages/frontend-2/components/automate/automation/CreateDialog.vue
- packages/frontend-2/components/project/page/automation/TestAutomationInfo.vue
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/frontend-2/pages/projects/[id]/index/automations/[aid].vue
- packages/server/assets/automate/typedefs/automate.graphql
- packages/server/modules/automate/graph/resolvers/automate.ts
- packages/server/modules/automate/repositories/automations.ts
- packages/server/modules/automate/services/automationManagement.ts
- packages/server/modules/automate/services/trigger.ts
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/test/graphql/generated/graphql.ts
- The current implementation of test automations is very much a "shortest path to do this at the time" kind of implementation
- The "requirement" to select a function, even though it has no effect, has confused users and Specklers alike
- We recently tried to let users at least select functions without versions here (i.e. test a function they just created) but this didn't work because the version requirement was hard-coded
- In working to fix that, I saw that it wasn't too much more work to drop the function requirement entirely here
- Omit functions when creating test automations (creates an automation with an empty functions array)
- This is already safe and handled by the UI (defensively written in case functions got deleted) and triggers (although test automations cannot be triggered) …
> feat(automate): create test automations without functions

- packages/server/modules/automate/repositories/automations.ts
- We added the ability to "delete" automations by flagging them as deleted. Queries for automations will omit deleted automations.
- In most cases, this correctly hides deleted automations and all of their associated resources.
- In some cases, we find our way to the automation from a "child" resource. For example, in this associated issue: "automation run => automation"
- We successfully queried the run, tried to access the automation, and returned null where that violates the gql schema
- Extra: you can see that this particular error only started happening after delete was merged late April 22
- Also omits automation runs from queries if the parent automation is deleted
> fix(automate): hide automation runs from deleted automations

- packages/frontend-2/lib/dashboard/helpers/connectors.ts
A vulnarability on archicad installer became a bad first impression. We are unlisting archicad as temporarily
> Chore: unlist archicad temporarily 

- packages/frontend-2/lib/dashboard/helpers/connectors.ts
Undoes the temporary change by @oguzhankoral in #4675
We now have a released a new version of Archicad that no longer triggers a false positive trigger by windows defender.
We've replaced the offending py2exe `exe` with a .NET8 equivalent `exe` https://github.com/specklesystems/connector-installers/pull/102
Old exe report: https://www.virustotal.com/gui/file/0a1f447b6986c808d3b1586121201220fd70586be5c2f92ccca11517f28f43de
New exe report: https://www.virustotal.com/gui/file/fb72c608e630a31d9443d35e06c5606757a2638b462c86e658ada3bc162469e6?nocache=1
Confident now that the new release is good after some testing by @JR-Morgan and @kekesidavid 
---
Tomorrow I'll look into removing the old releases from the feed
> Chore: re-list archicad temporarily

- packages/server/modules/multiregion/tests/e2e/projects.graph.spec.ts
- packages/server/modules/workspaces/repositories/projectRegions.ts
- packages/server/modules/workspaces/services/projectRegions.ts
- sometimes the project region move counts would fail to emit a `0` if the project had no resources of a certain type
- we recently guaranteed a `0` on counting moved project resources
- `0 !== undefined` and so some moves were still being flagged as "failed"
- Guarantees a zero when no resources of a type exist and when none were moved
- `0 === 0`
- Add test case for this
> fix(multiregion): guarantee zero counts on project region move

- packages/frontend-2/components/onboarding/questions/PlanSelect.vue
- packages/frontend-2/components/onboarding/questions/RoleSelect.vue
- packages/frontend-2/components/onboarding/questions/SourceSelect.vue
- packages/frontend-2/lib/auth/helpers/onboarding.ts
- packages/shared/src/onboarding/helpers/index.ts
- packages/ui-components/src/components/form/select/Base.vue
Requested by growth team. 
We now shuffle the answers to the onboarding questions to hopefully make it more accurate. 
Also removed the other option from the Role Select as requested. 
Also removed the overflow on large screens for Role Select.
> feat(fe): shuffle onboarding question options

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/assets/core/typedefs/permissions.graphql
- packages/server/assets/workspacesCore/typedefs/permissions.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/graph/resolvers/permissions.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/graph/resolvers/permissions.ts
- packages/server/test/graphql/generated/graphql.ts
- We're using these policies in the resolvers but did not expose them as gql permissions queries
- Does so
> fix(authz): expose canInvite gql queries

- packages/server/modules/automate/graph/resolvers/automate.ts
- packages/server/modules/automate/repositories/automations.ts
- Queries that search for automations are properly filtering out deleted automations
- Some queries (see attached issue) begin querying for run results directly from associated resources
- These services/repo functions were not filtering out runs for deleted automations
- Led to silly behavior:
- Deleted automations would still show their status in the donut on model cards
- Error from associated issue, if the deleted automation had any runs
- Filters out automation runs from deleted automations
> fix(automate): filter out deleted automation runs

- packages/frontend-2/components/projects/ProjectDashboardCard.vue
I don't have a local workspace I can recreate this on, but will confirm on app with Nikos.
> fix(fe): Add canCreateModel check to ProjectDashboardCard empty state

- packages/server/assets/workspacesCore/typedefs/workspaces.graphql
- packages/server/codegen.yml
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/repositories/workspaces.ts
- packages/server/modules/workspaces/tests/integration/repositories.spec.ts
- packages/server/modules/workspacesCore/helpers/graphTypes.ts
- packages/server/test/authHelper.ts
- packages/server/test/graphql/generated/graphql.ts
- The current discoverable workspaces list (seen when joining as a new user, and in the workspace switcher) can be overwhelming when there's several options.
- We want to (1) surface the most relevant ones and (2) give users confidence they're requesting to join the right ones
- Sort discoverable workspaces by total member count by default
- Emit workspace admins from `LimitedWorkspace` so FE can show who workspace admins are as well (cc @Mikehrn )
> feat(workspaces): sort discoverable workspaces by member count

- packages/frontend-2/components/pricingTable/Plan.vue
- packages/frontend-2/components/project/page/models/StructureItem.vue
- packages/frontend-2/components/settings/workspaces/billing/addOns/Card.vue
- packages/frontend-2/components/viewer/gendo/Panel.vue
- packages/frontend-2/components/workspace/wizard/step/AddOns.vue
- packages/frontend-2/package.json
- packages/frontend-2/pages/book-a-demo.vue
- packages/frontend-2/pages/settings/workspaces/[slug]/general.vue
- packages/frontend-2/pages/verify-email.vue
- packages/ui-components/package.json
- yarn.lock
Update to latest version of vue-tippy after Fabs fix. Remove all keys that were added to fix this bug.
> chore(fe): Update vue-tippy & remove legacy code

- packages/frontend-2/pages/book-a-demo.vue
Changing the copy a bit in the intro call step to hopefully get even more bookings:
> Fix: Improve copy in intro call step

- packages/server/modules/workspaces/events/eventListener.ts
- user_id does not get correlated to user, so when query by User on mixpanel, workspace create does not get recorded as his action
> fix: workspace create event relationship to user

- packages/server/modules/workspaces/services/tracking.ts
To have a synced workspaces number on mixpanel we need to know when was the last time it was synced as there are many that did not get the update at deletion moment, and those ones will never get updated anymore.
> feat: add lastSyncAt to workspaces

- packages/frontend-2/components/workspace/discoverableWorkspaces/Card.vue
- packages/frontend-2/components/workspace/discoverableWorkspaces/Modal.vue
Add dismissed event to the card, and remove the worskpace from the local ref of workspaces.
> fix(fe): Discoverable workspace card not dismissing

- .github/workflows/builds.yml
- Improved ci caching strategies for FE builds:
- FE build on pull request consumes different caches than FE on deploy 
- Sourcemaps stores a max cache
With this strategy: _(cache hit)_
https://github.com/specklesystems/speckle-server/actions/runs/15604028369
Without: _(both examples should be hits)_ 
(on main) https://github.com/specklesystems/speckle-server/actions/runs/15590454040/job/43908724547
(on pr) https://github.com/specklesystems/speckle-server/actions/runs/15590770112/job/43909051420
> feat(ci): improved caching around frontend2 builds

- packages/frontend-2/components/settings/workspaces/security/sso/Wrapper.vue
Fixed the SSO switch to display as enabled when a provider is configured.
> fix(fe): SSO switch now properly reflects enabled state

- packages/frontend-2/components/common/model/Select.vue
- packages/frontend-2/lib/projects/composables/versionManagement.ts
- packages/ui-components/src/components/form/select/Base.vue
Reported by @JR-Morgan in discord:
https://github.com/user-attachments/assets/8c21cc81-774d-481f-9781-36397dda1755
and:
```also, not a bug, but when you do move a version, It would be amazing if the notification had an option to navigate to the :modelid/versions page that the version was just moved to```
> fix(fe): Move version dialog overflow issue

- packages/server/modules/multiregion/tests/e2e/projects.graph.spec.ts
Temporary and quick fix for flaky test. Follow-up shortly with wait-free test.
Move to region does the following:
1. Copy project record to regional db
2. Copy project assets from one db to another (i.e. objects, branches, webhooks)
3. Assert copy was success
4. Update project region key in regional db
5. Delete project in main db
6. Await replication of 1 & 5
7. Re-instate records lost in 5 (project roles)
The flaky test in question:
- Polls for the project region key to be updated in the main db
- Asserts state of step 7
Often enough, the region key is updated before the roles are set, and so the test "fails".
Updating the region key later, or any other similar changes, requires moving several pieces around (but will be done). This `wait` is ugly but will allow us to safely wait for …
> fix(regions): fix for flaky move region test

- packages/server/modules/cli/commands/workspaces/set-plan.ts
- packages/server/modules/gatekeeper/services/workspacePlans.ts
- packages/server/modules/gatekeeper/tests/unit/workspacePlans.spec.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- workpaces with current ongoing subscriptions can't turned into non paid by admin mutation
> fix: avoid workpaces to turn free when susbscription is present

- .github/workflows/publish.yml
- .github/workflows/tests.yml
projectwide linter runs already:
- packages/objectloader
- packages/tailwind-theme
- packages/preview-frontend
- packages/preview-service
- packages/objectloader2
- packages/monitor-deployment
- packages/viewer-sandbox
- packages/objectsender
- packages/fileimport-service
- packages/shared
- packages/viewer
- packages/frontend-2
- packages/server
- packages/ui-components
- packages/ui-components-nuxt
- packages/webhook-service
So disabled the lint runs on:
- frontend job (nothing else to run so disabled the job)
- publish preview-service
- test-viewer 
- test-shared
- test-preview-service (nothing else to run so disabled the job)
- test-ui-component
- test-server
> fix(ci): deduplicated lint runs

- packages/frontend-2/lib/core/api/blobStorage.ts
Invoking the DL w/ fetch() and URL.createObjectUrl() makes it download the entire file in the background first, and then only start showing the download dialog at the end when it just has to move the in-memory downloadad file to the downloads folder.
The solution is to open the DL URL in a new tab, which makes the browser treat it as a standard download w/ accurately reported progress
> feat(fe): more accurate download reporting

- packages/frontend-2/lib/auth/composables/auth.ts
Because it's watching the computed obj the newVal !== oldVal because true and it's causing sometimes an unneeded resetAuth trigger
> Fix: Update auth watcher

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/users.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/projects.ts
- packages/server/modules/core/tests/integration/repositories/project.spec.ts
- packages/server/modules/core/tests/users.spec.ts
- packages/server/modules/core/tests/usersAdmin.spec.ts
- packages/server/modules/gatekeeper/graph/resolvers/index.ts
- packages/server/modules/workspaces/authz/loaders/index.ts
- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/graph/resolvers/regions.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/index.ts
- packages/server/modules/workspaces/services/tracking.ts
- packages/server/modules/workspaces/tests/integration/tracking.spec.ts
- packages/server/modules/workspaces/tests/integration/workspacesCreationState.spec.ts
- packages/server/modules/workspaces/tests/unit/services/projects.spec.ts
- Created new repo method for iterating over projects via userId or workspaceId _(filtering them)_
- This fixes iterating over all projects on user delete and hitting the timeout
> fix: getting all user projects on deletion and user filter

- packages/frontend-2/server/middleware/004-sharedArrayBufferHeaders.ts
- packages/server/modules/blobstorage/rest/router.ts
- packages/server/modules/previews/rest/router.ts
- packages/server/modules/shared/middleware/security.ts
Set `sharedArrayBufferHeaders=1` in querystring on viewer page, to enable
> feat(fe2): conditional cross origin isolation on viewer page

- packages/shared/src/authz/policies/project/canLoad.spec.ts
- packages/shared/src/authz/policies/project/canLoad.ts
allows specifying projects, that can be publicly loaded.
For now, this is just a baked in value, to provide a quick fix. It can be expanded with a loader and environment variables later down the line
> feat(authPolicies): add demo project as a publicly loadable override

- packages/frontend-2/components/projects/Add.vue
- packages/frontend-2/components/workspace/AddProjectMenu.vue
Fix hydration mismatch in ProjectsAdd component by using workspace slug instead of async workspace data for conditional rendering. The workspace GraphQL query completes at different times during SSR vs client hydration, causing this mismatch.
Switching to the workspace slug ensures consistent rendering.
> fix(fe): Add project menu hydration mismatch

- packages/objectloader2/src/types/functions.spec.ts
- packages/objectloader2/src/types/functions.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleLoader.ts
The logic for the viewer to log during debug mode was wrong
This pull request introduces enhancements to the `getFeatureFlag` function in `ObjectLoader2` to support an optional `useDefault` parameter, enabling more flexible handling of feature flags in both browser and non-browser environments. Additionally, related test cases and usage in other modules have been updated accordingly.
* [`packages/objectloader2/src/types/functions.ts`](diffhunk://#diff-7fe7db9d5a2f8056735e90b8b4c77df36ecb5f0165713d7e650b2fb8d155bd8eL63-R73): Modified the `getFeatureFlag` function to include a `useDefault` parameter, allowing the function to return `undefined` instead of a default value when `useDefault` is set to `false`. This change affects both non-browser and browser environments. …
> (fix) debug mode for viewer

- packages/objectloader2/src/core/interfaces.ts
- packages/objectloader2/src/core/objectLoader2.ts
- packages/objectloader2/src/core/stages/__snapshots__/serverDownloader.spec.ts.snap
- packages/objectloader2/src/core/stages/cacheReader.spec.ts
- packages/objectloader2/src/core/stages/cacheWriter.spec.ts
- packages/objectloader2/src/core/stages/memory/memoryDownloader.ts
- packages/objectloader2/src/core/stages/serverDownloader.spec.ts
- packages/objectloader2/src/core/stages/serverDownloader.ts
Currently, when processing a RawEncoding value, the whole item is undefined which doesn't save.  We want to save the fact we're not processing these so an undefined Item is saved
> OL2(fix) Make a returned RawEncoding value return an empty Item instead of a undefined item

- packages/server/modules/activitystream/repositories/index.ts
- packages/server/modules/activitystream/tests/integration/repository/activityStream.spec.ts
We got a couple of errors were some field is to long in activity_stream insertion. Without digging too much and assuming that all ids are 10 length, the only field possible to archieve this is message as it's built sometimes on filenames that can get quite long.
> fix: protect message of activity stream beeing to long

- packages/viewer/src/modules/extensions/sections/SectionTool.ts
This adds the ability to snap rotation to a 15-degree grid when holding the shift key during section box rotation.
Cursor and I made it so that the snapping always aligns to the standard grid (0°, 15°, 30°, 45°, ...) rather than snapping relative to the initial rotation position.
@AlexandruPopovici I'm unsure if you actually want this to be part of the sectiontool extension or if this snapping should instead be implemented in the frontend. Let me know...
> Snap section box rotation to nearest 15 degrees

- packages/viewer/src/modules/extensions/sections/SectionTool.ts
This PR makes it possible to undo and redo changes when using the section tool.
- Complete section tool state tracking including saving the rotation, translation, and movement of the section box. A new `SectionBoxState` interface is introduced for complete OBB state storage.
- Press `Cmd/Ctrl+Z` to undo an edit, and press `Cmd/Ctrl+Shift+Z` to redo. If you undo to a previous state, and then make a change to the section box, then this change becomes the last entry in the history timeline (all future edits are cleared).
- There's a history limit of 100 entries right now, but this can probably be increased or removed if it's an issue. I don't know. 
- Section outlines are also updated as you undo/redo.
> Feat: Support for undo/redo in section tool

- packages/server/modules/fileuploads/repositories/fileUploads.ts
fix a bug where file uploads with upper case letters in the extension would be queued, but not processed due to the way we're filtering jobs based on their file extension.
I've fixed it by ensuring that the jobs are always created with the lower cased file extension.
> fix(fileUpload): Ensure fileType is lowercase

- packages/server/modules/multiregion/services/queue.ts
No return here meant jobs fell through to "failed" in all cases, after work was successfully performed.
> fix(regions): return in project region move handler

- packages/frontend-2/components/viewer/compare-changes/ObjectGroup.vue
- packages/frontend-2/components/viewer/explorer/StringFilterItem.vue
Filter interactions were extremely slow due to `some().includes()` patterns.
Switched to `Set.has()` for faster lookups.
> fix(fe): replace nested loops in filter components

- packages/frontend-2/components/viewer/models/versions/Versions.vue
The version panel did not overflow correctly. Now overflows as expected, with simple-scrollbar
> fix(fe): Version panel overflow

- packages/frontend-2/components/viewer/anchored-point/Thread.vue
Simple one - just added `hide-tooltips` prop
> refactor(fe): Remove tooltips from floating comment avatars

- packages/frontend-2/components/viewer/Base.vue
- packages/frontend-2/lib/viewer/composables/setup/postSetup.ts
- packages/frontend-2/lib/viewer/composables/ui.ts
Remove sync between viewer state and fe ui on mount - this was needlessly complex and only went in because we knew this ticket was coming in a few days. 
Reset view mode between viewer sessions
> refactor(fe): reset view mode onBeforeUnmount

- packages/frontend-2/components/viewer/models/Card.vue
- packages/frontend-2/components/viewer/models/VirtualTreeItem.vue
https://linear.app/speckle/issue/WEB-3964/fit-object-to-view-on-double-click-in-models-tab
Zoom to fit when you double click on a tree item or a model card.
> feat(fe): models panel - zoom to fit on double click of model or tree item

- packages/frontend-2/components/viewer/anchored-point/Thread.vue
- packages/frontend-2/lib/viewer/composables/commentBubbles.ts
From ticket:
Objects stay selected after you close the comment window. When closing a comment we should also deselect the object connected to that comment.
> refactor(fe): deselect object when closing comment

- packages/frontend-2/components/viewer/models/Panel.vue
Adds a `CommonLoadingIcon` to the models panel which is shown based on `resourcesLoading` from `useInjectedViewerLoadedResources`
> feat(fe): add loading indicator to models panel

- packages/frontend-2/components/viewer/IsolateButton.vue
- packages/frontend-2/components/viewer/VisibilityButton.vue
- packages/frontend-2/components/viewer/anchored-point/NewThread.vue
- packages/frontend-2/components/viewer/anchored-point/Thread.vue
- packages/frontend-2/components/viewer/anchored-point/thread/CommentAttachments.vue
- packages/frontend-2/components/viewer/anchored-point/thread/NewReply.vue
- packages/frontend-2/components/viewer/comments/Panel.vue
- packages/frontend-2/components/viewer/compare-changes/Panel.vue
- packages/frontend-2/components/viewer/controls/Bottom.vue
- packages/frontend-2/components/viewer/controls/ButtonToggle.vue
- packages/frontend-2/components/viewer/controls/Left.vue
- packages/frontend-2/components/viewer/controls/Right.vue
- packages/frontend-2/components/viewer/filters/Panel.vue
- packages/frontend-2/components/viewer/filters/StringFilterItem.vue
- packages/frontend-2/components/viewer/models/Actions.vue
- packages/frontend-2/components/viewer/models/Card.vue
- packages/frontend-2/components/viewer/models/versions/Versions.vue
- packages/frontend-2/components/viewer/resources/VersionCard.vue
- packages/frontend-2/components/viewer/selection/Sidebar.vue
- packages/ui-components/src/components/form/Button.vue
A lot of tech debt around Buttons and Icons in the viewer. 
Replacing `<button>` with `<FormButton>`
Not longer passing Icons as strings. 
Swapping icons to lucide
> refactor(fe): Icons and Buttons throughout viewer

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/assets/core/typedefs/apitoken.graphql
- packages/server/modules/auth/defaultApps.ts
- packages/server/modules/core/domain/tokens/operations.ts
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/graph/resolvers/apitoken.ts
- packages/server/modules/core/services/tokens.ts
- PowerBI connector requires ability to:
- Create tokens for the given user
- Scope them to just a given project
- Ability to do this is largely written, just not exposed by the public API
- Make it available via gql
- Gives PowerBI default app `tokens:write` scope
> feat(tokens): enable resource limits for PAT creation

- packages/frontend-2/components/settings/workspaces/members/GuestsTable.vue
- packages/frontend-2/components/settings/workspaces/members/InvitesTable.vue
- packages/frontend-2/components/settings/workspaces/members/MembersTable.vue
**Fix workspace member list text color inconsistencies**
Make all workspace member list components use consistent dark text colors (text-foreground) instead of mixing light and dark colors across different elements.
> fix(frontend-2): make workspace member list text colors consistent

- packages/frontend-2/plugins/060-dataPreload.ts
Preload navigationWorkspaceSwitcherQuery to avoid empty workspace switcher on refresh.
> fix(fe): preload navigationWorkspaceSwitcherQuery

- packages/frontend-2/lib/auth/composables/auth.ts
- packages/frontend-2/pages/authn/login.vue
- packages/frontend-2/pages/settings/workspaces/[slug]/general.vue
- packages/server/modules/gatekeeper/graph/resolvers/index.ts
we used to just evict activeUser, but there's a bunch of user-specific keys like Workspace.seatType that got retained and caused weird cache pollution where if you logged out and logged in to a different account, the new account would have some values cached from the previous one
the correct thing to do is to evict the entire cache on log out
> fix(fe2): full cache reset on log out

- packages/frontend-2/components/workspace/wizard/Wizard.vue
- packages/frontend-2/lib/projects/composables/permissions.ts
I noticed that if you create a new workspace the "cant create" alert shows for a second while it's loading
> Fix: Dont show cantCreate reason while loading

- utils/helm/speckle-server/templates/objects/deployment.yml
- utils/helm/speckle-server/templates/objects/serviceaccount.yml
- utils/helm/speckle-server/templates/server/deployment.yml
- utils/helm/speckle-server/templates/server/serviceaccount.yml
Encryption key file was not being placed at expected location when `workspacesSSOEnabled` was enabled.
> chore(helm): mount encryption key file when `workspacesSSOEnabled` feature flag is enabled

- packages/frontend-2/components/viewer/saved-views/panel/View.vue
- packages/frontend-2/components/viewer/saved-views/panel/views/group/Inner.vue
Change the markup and group hover action so that lines correctly truncate.
Before:
After:
> Fix: Improve truncations for hover actions on view cards

- packages/frontend-2/lib/auth/composables/auth.ts
- packages/frontend-2/lib/core/composables/error.ts
- packages/frontend-2/lib/core/configs/apollo.ts
should make it so that we do a full app clear/reboot/reload in case of fatal GQL network errors, to avoid reload loops
> feat(fe2): more reslient app reboot on fatal network error

- packages/ifc-import-service/pyproject.toml
- packages/ifc-import-service/uv.lock
Bump specklepy to 3.0.5 to fix the issue with log template args being wrong in the sender function
https://github.com/specklesystems/specklepy/pull/449
> chore(ifc-import-service): Bump specklepy to 3.0.5

- packages/frontend-2/components/viewer/AnchoredPoints.vue
- packages/frontend-2/components/viewer/GlobalIsolationReset.vue
- packages/frontend-2/lib/viewer/composables/filtering/filtering.ts
Fix bug reported by dim in discord. We need to clear selection before hiding the object. 
Also added a "reset isolations" button cause it was easy to find yourself in a state where this was useful
> fix(fe): right click hide selection

- packages/frontend-2/components/viewer/filters/filter/Header.vue
- packages/frontend-2/components/viewer/models/Card.vue
- packages/frontend-2/lib/viewer/composables/setup/filters.ts
- packages/frontend-2/lib/viewer/composables/setup/highlighting.ts
- packages/frontend-2/lib/viewer/composables/setup/postSetup.ts
Selection, highlighting, and filtering systems were conflicting, causing objects to remain highlighted after deselection and losing state during filtering operations.
Implemented LegacyViewer's proven `preserveSelectionHighlightFilter` pattern to properly coordinate viewer extensions.
- Added preservation pattern (`filters.ts`) - Save/clear/restore selection & highlighting state during filtering, exactly like `LegacyViewer`
- Global highlight extension (`highlighting.ts`) - Single instance using `useScopedState`
- Smart selection sync (`postSetup.ts`) - Prevent redundant calls that corrupted material storage
- Removed hacky clears - Let preservation pattern handle coordination instead of fighting sync loops
- Direct extension coordination instead of circular frontend sync loops
- …
> feat(fe): preserveSelectionHighlightFilter

- packages/objectloader2/src/queues/batchingQueue.dispose.test.ts
- packages/objectloader2/src/queues/batchingQueue.ts
Some of the tests didn't pass because of the changed batching queue behavior: https://github.com/specklesystems/speckle-server/pull/5429
Tweaked it to still drain but not call the function when disposing
> Fix: BatchingQueue should still drain but not process when disposed

- packages/frontend-2/lib/viewer/helpers/filters/constants.ts
Bilal and Claire agree that we should remove `speckle_type` from the list of popular filter properties.
It is still available to filter on, but we don't want to push it
> fix(fe): remove speckle_type from FILTERS_POPULAR_PROPERTIES

- packages/frontend-2/lib/object-sidebar/helpers.ts
https://linear.app/speckle/issue/WEB-2993/open-in-new-tab-from-selection-info-uses-full-url-instead-of-object-id
> Fix: Extract object ID if URL is returned

- packages/shared/src/authz/policies/dashboard/canDelete.ts
- packages/shared/src/authz/policies/dashboard/canEdit.ts
- packages/shared/src/authz/policies/dashboard/canRead.ts
- packages/shared/src/authz/policies/workspace/canCreateDashboards.ts
use the admin override for some dashboarding permissions as requested by @jsdbroughton
> feat(policies): allow god mode admins to create dashboards

- packages/frontend-2/lib/viewer/composables/ui.ts
Originally reported by Claire in discord:
https://discord.com/channels/726756379083145269/1422565693215473811
Noticed this behavior - when you have federated models, and click on one of the models, it is added again on every click to the selection panel
> fix(fe): prevent duplicate object selection
