specklesystems/speckle-server

- packages/frontend-2/components/project/page/models/Actions.vue
> fix(fe2): Add view versions action menu item. Use mount-menu-on-body

- packages/server/app.ts
> chore(app): disable frontend proxy for fe2

- packages/server/modules/automate/rest/authGithubApp.ts
- packages/server/modules/automate/rest/logStream.ts
- packages/server/modules/blobstorage/index.js
- packages/server/modules/fileuploads/index.ts
- packages/server/modules/shared/authz.ts
- packages/server/modules/shared/domain/authz/operations.ts
- packages/server/modules/shared/domain/authz/types.ts
- packages/server/modules/shared/domain/operations.ts
- packages/server/modules/shared/test/authz.spec.js
> chore(server): shared IoC 2 - authz pipelines

- packages/server/modules/core/dbSchema.ts
- packages/server/modules/shared/repositories/roles.ts
- packages/server/modules/shared/repositories/scopes.ts
> chore(server): shared IoC 3 - repo cleanup

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/domain/types.ts
- packages/server/modules/activitystream/graph/resolvers/activity-new.ts
- packages/server/modules/activitystream/graph/resolvers/activity.js
- packages/server/modules/activitystream/repositories/index.ts
- packages/server/modules/activitystream/services/index.js
> Activitystream IoC 1 getResourceActivity

- packages/viewer/src/modules/batching/PointBatch.ts
Fixed bug reported here https://speckle.community/t/bug-when-re-showing-a-sketch-in-a-viewer-dev/13978 which has been plaguing us for a while with no means of reproducing it
> WEB-1941: Elusive Bug Fixed

- packages/server/modules/blobstorage/objectStorage.js
- packages/server/modules/shared/helpers/envHelper.ts
We should use the environment variables helper, rather than calling `process` directly in the file. This makes it clearer where data is coming from and reduces surprising side-effects.
Additionally, we tidy up the environment variables helper to use a meta helper method to convert environment variables to boolean.
> chore(server): Use helpers to get S3 environment variables

- packages/dui3/lib/core/composables/updateConnector.ts
> Chore(dui3): modifications on update notification

- packages/server/modules/workspacesCore/migrations/20240926112407_copy_workspace_slug.ts
> feat(workspaces): migrate slug to match the workspaceId

- packages/server/modules/core/domain/branches/operations.ts
- packages/server/modules/core/domain/branches/types.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/repositories/branches.ts
- packages/server/modules/core/services/branch/retrieval.ts
> chore(server): core IoC 6 - getPaginatedProjectModelsFactory

- packages/server/modules/core/domain/branches/operations.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/repositories/branches.ts
- packages/server/modules/core/services/branch/retrieval.ts
> chore(server): core IoC 7 - getProjectTopLevelModelsTreeFactory

- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/core/domain/branches/operations.ts
- packages/server/modules/core/graph/resolvers/branches.js
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/repositories/branches.ts
- packages/server/modules/core/services/branch/management.ts
- packages/server/modules/core/services/branches.js
- packages/server/modules/core/services/commit/batchCommitActions.ts
- packages/server/modules/core/services/streams/management.ts
- packages/server/modules/core/tests/batchCommits.spec.ts
- packages/server/modules/core/tests/branches.spec.js
- packages/server/modules/core/tests/commits.spec.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/modules/core/tests/users.spec.js
- packages/server/modules/cross-server-sync/index.ts
- packages/server/modules/cross-server-sync/services/project.ts
- packages/server/test/speckle-helpers/branchHelper.ts
> chore(server): core IoC 9 - createBranchAndNotifyFactory

- packages/server/modules/core/domain/branches/operations.ts
- packages/server/modules/core/graph/resolvers/branches.js
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/repositories/branches.ts
- packages/server/modules/core/services/branch/management.ts
- packages/server/modules/core/services/branches.js
- packages/server/modules/core/tests/branches.spec.js
> chore(server): core IoC 10 - updateBranchAndNotifyFactory

- packages/server/modules/activitystream/index.ts
- packages/server/modules/activitystream/services/summary.ts
- packages/server/modules/activitystream/tests/activitySummary.spec.ts
- packages/server/modules/cli/commands/activities/send.ts
> Activitystream IoC 2 sendActivityNotification

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/domain/types.ts
- packages/server/modules/activitystream/services/summary.ts
- packages/server/modules/activitystream/tests/activitySummary.spec.ts
- packages/server/modules/notifications/services/handlers/activityDigest.ts
- packages/server/modules/notifications/tests/activityDigest.spec.ts
> Activitystream IoC 3 createActivitySummary

- packages/server/modules/automate/tests/automations.spec.ts
- packages/server/modules/automate/tests/trigger.spec.ts
- packages/server/modules/core/domain/branches/operations.ts
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/repositories/branches.ts
- packages/server/modules/core/services/branches.js
- packages/server/modules/core/services/commit/management.ts
- packages/server/test/speckle-helpers/automationHelper.ts
> chore(server): core IoC 12 - remaining branches repo

- packages/server/modules/automate/graph/resolvers/automate.ts
- packages/server/modules/automate/index.ts
- packages/server/modules/automate/services/tracking.ts
- packages/server/modules/automate/services/trigger.ts
- packages/server/modules/automate/tests/trigger.spec.ts
- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/domain/commits/types.ts
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/commit/batchCommitActions.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/core/tests/batchCommits.spec.ts
> chore(server): core IoC 13 - getCommit(s)Factory

- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/services/commits.js
- packages/server/modules/core/tests/commits.spec.js
- packages/server/modules/core/tests/users.spec.js
- packages/server/modules/previews/index.js
> chore(server): core IoC 14 - getCommitById cleanup

- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/commit/batchCommitActions.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/core/services/commits.js
- packages/server/modules/core/tests/commits.spec.js
> chore(server): core IoC 15 - deleteCommitAndNotifyFactory

- packages/server/modules/activitystream/services/commentActivity.ts
- packages/server/modules/cli/commands/download/commit.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/comments/graph/resolvers/comments.ts
- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/domain/commits/types.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/commit/retrieval.ts
- packages/server/modules/core/services/commit/viewerResources.ts
- packages/server/modules/cross-server-sync/index.ts
> chore(server): core IoC 16 - getSpecificBranchCommitsFactory

- packages/viewer-sandbox/src/Sandbox.ts
> Button for turning on section tool prop visibility

- packages/server/modules/auth/repositories/apps.ts
> fix(serverApps): delete was deleting app tokens for all users

- packages/server/modules/cli/commands/download/commit.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/comments/tests/comments.graph.spec.js
- packages/server/modules/comments/tests/comments.spec.js
- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/events/versionsEmitter.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/versions.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/core/services/commits.js
- packages/server/modules/core/services/streams/clone.ts
- packages/server/modules/core/tests/branches.spec.js
- packages/server/modules/core/tests/commits.spec.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/modules/core/tests/users.spec.js
- packages/server/modules/cross-server-sync/index.ts
- packages/server/modules/cross-server-sync/services/commit.ts
- packages/server/modules/stats/tests/stats.spec.ts
- packages/server/test/speckle-helpers/commitHelper.ts
> chore(server): core IoC 17 - createCommitByBranchIdFactory

- packages/server/modules/activitystream/services/commentActivity.ts
- packages/server/modules/comments/graph/resolvers/comments.ts
- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/commit/viewerResources.ts
> chore(server): core IoC 21 - getCommitsAndTheirBranchIdsFactory

- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/streams/clone.ts
> chore(server): core IoC 22 - cloning related commit repo fns

- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/commit/retrieval.ts
- packages/server/modules/core/services/commits.js
> chore(server): core IoC 23 - getPaginatedBranchCommitsFactory

- packages/server/modules/core/domain/commits/operations.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/versions.ts
- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/services/commit/batchCommitActions.ts
> chore(server): core IoC 24 - batchMoveCommitsFactory

- packages/server/modules/activitystream/services/commentActivity.ts
- packages/server/modules/cli/commands/download/commit.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/comments/graph/resolvers/comments.ts
- packages/server/modules/core/domain/objects/operations.ts
- packages/server/modules/core/domain/objects/types.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/repositories/objects.ts
- packages/server/modules/core/services/commit/viewerResources.ts
- packages/server/modules/cross-server-sync/index.ts
> chore(server): core IoC 26 - getStreamObjectsFactory

- packages/server/modules/cli/commands/download/commit.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/comments/tests/comments.graph.spec.js
- packages/server/modules/comments/tests/comments.spec.js
- packages/server/modules/core/domain/objects/operations.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/objects.ts
- packages/server/modules/core/graph/resolvers/versions.ts
- packages/server/modules/core/repositories/objects.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/core/tests/branches.spec.js
- packages/server/modules/core/tests/commits.spec.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/modules/core/tests/users.spec.js
- packages/server/modules/cross-server-sync/index.ts
- packages/server/modules/cross-server-sync/services/commit.ts
- packages/server/modules/stats/tests/stats.spec.ts
- packages/server/test/speckle-helpers/commitHelper.ts
> chore(server): core IoC 27 - getObjectFactory

- packages/dui3/lib/bridge/generic-v2.ts
- packages/dui3/lib/bridge/server.ts
- packages/dui3/lib/bridge/sketchup.ts
- packages/dui3/package.json
- packages/dui3/plugins/00.bindings.ts
- yarn.lock
Tested all kind of bridges on revit, rhino, autocad, archicad and sketchup
> Fix(dui3): bridges for archicad

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/domain/streams/types.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/versions.ts
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/core/tests/commits.spec.js
> chore(server): IoC 30 - getCommitStream(s)Factory

- packages/server/modules/accessrequests/index.ts
- packages/server/modules/accessrequests/services/eventListener.ts
- packages/server/modules/accessrequests/tests/projectAccessRequests.spec.ts
- packages/server/modules/accessrequests/tests/streamAccessRequests.spec.ts
- packages/server/modules/activitystream/services/streamActivity.ts
- packages/server/modules/cli/commands/download/commit.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/domain/streams/types.ts
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/cross-server-sync/index.ts
- packages/server/modules/cross-server-sync/services/commit.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
> chore(server): IoC 31 - getStreamCollaboratorsFactory

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleGeometryConverter.ts
Objects of speckle type `Box` now get their base plane basis applied as rotation
> Box Rotation

- packages/server/modules/activitystream/tests/activitySummary.spec.ts
- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/streams.js
- packages/server/modules/core/services/streams/management.ts
- packages/server/modules/core/services/users.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/management.ts
> chore(server): IoC 33 - deleteStreamAndNotifyFactory

- packages/server/modules/comments/tests/comments.graph.spec.js
- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/streams.js
- packages/server/modules/core/services/streams/management.ts
- packages/server/modules/core/services/streams/onboarding.ts
- packages/server/modules/core/tests/streams.spec.ts
> chore(server): IoC 34 - updateStreamAndNotifyFactory

- packages/frontend-2/components/projects/invite/Banner.vue
Old copy felt a bit clumsy and I also didn't like the use of "team" here.
> Update copy in project invite banner

- packages/server/modules/cli/commands/stream/clone.ts
- packages/server/modules/comments/domain/operations.ts
- packages/server/modules/comments/repositories/comments.ts
- packages/server/modules/core/domain/branches/operations.ts
- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/repositories/branches.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/streams/clone.ts
- packages/server/modules/core/services/streams/onboarding.ts
- packages/server/modules/cross-server-sync/index.ts
- packages/server/modules/cross-server-sync/services/onboardingProject.ts
> chore(server): IoC 36 - createOnboardingStreamFactory

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/streams/discoverableStreams.ts
> chore(server): core IoC 37 - getDiscoverableStreamsFactory

- .circleci/config.yml
> fix(ci): running yarn install twice to avoid weird CI install issues

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/admin.ts
- packages/server/modules/core/services/streams.js
- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/projects.ts
> chore(server): core IoC 38 - legacyGetStreamsFactory

- packages/server/logging/expressLogging.ts
- packages/server/modules/core/helpers/server.ts
This PR logs query parameters to provide greater insight into requests. This is necessary as we had a bug which occurred on an endpoint, but only for specific query parameters. Identifying the common element between the failing requests was frustrated by lack of insight in the logs.
- query parameters are sanitised and logged
`curl -k http://127.0.0.1:3000/auth/login\?param1\=value1\&data\=foobar\&code\=secret` results in:
> feat(logging): log request query params, redacting sensitive data

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/services/streamActivity.ts
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/services/streams/management.ts
> Activitystream IoC 1 addStreamUpdatedActivity

- .circleci/config.yml
> fix(ci): same node img in all CI steps

- utils/ensure-tailwind-deps.mjs
> feat(root): improved ensure tailwind deps reporting

- .circleci/config.yml
- packages/ui-components/package.json
> fix(ci): increase vuln scan job resource class

- packages/frontend-2/components/projects/AddDialog.vue
- packages/frontend-2/components/projects/WorkspaceSelect.vue
- Disable workspace selector when user has no workspaces
- Remove old button for "New workspace"
- Update workspace selector placeholder text to show "No workspaces" when there are none
> feat(fe2): Change workspace selector empty state

- packages/frontend-2/components/header/NavUserMenu.vue
- packages/frontend-2/components/project/page/settings/collaborators/Row.vue
- packages/frontend-2/components/settings/server/ActiveUsers.vue
- packages/frontend-2/components/settings/server/PendingInvitations.vue
- packages/frontend-2/components/settings/workspaces/members/GuestsTable.vue
- packages/frontend-2/components/settings/workspaces/members/InvitesTable.vue
- packages/frontend-2/components/settings/workspaces/members/MembersTable.vue
- packages/frontend-2/components/viewer/anchored-point/thread/Comment.vue
- packages/frontend-2/components/workspace/invite/dialog/UserRow.vue
- packages/ui-components/src/components/user/Avatar.vue
> Feat: Tooltips on avatar

- .circleci/config.yml
> chore(ci): cleanup circleci from recent junk

- packages/server/modules/activitystream/index.ts
- packages/server/modules/core/domain/scheduledTasks/operations.ts
- packages/server/modules/core/domain/scheduledTasks/types.ts
- packages/server/modules/core/repositories/scheduledTasks.ts
- packages/server/modules/core/services/taskScheduler.ts
- packages/server/modules/core/tests/scheduledTasks.spec.ts
- packages/server/modules/webhooks/index.ts
> chore(server): core IoC #43 - scheduleExecutionFactory

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/domain/streams/types.ts
- packages/server/modules/core/loaders.ts
- packages/server/modules/core/repositories/streams.ts
> chore(server): core IoC #44 - remaining streams dataloaders

- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/repositories/streams.ts
> chore(server): core IoC #45 - getDiscoverableStreamsPage rename

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/graph/resolvers/streams.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/projects.ts
> chore(server): core IoC #46 - getUserStreamsPageFactory

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/branches.js
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/branch/management.ts
- packages/server/modules/core/tests/branches.spec.js
- packages/server/modules/core/tests/streams.spec.ts
> chore(server): core IoC #47 - markBranchStreamUpdatedFactory

- packages/server/modules/cli/commands/download/commit.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/comments/tests/comments.graph.spec.js
- packages/server/modules/comments/tests/comments.spec.js
- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/versions.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/core/tests/branches.spec.js
- packages/server/modules/core/tests/commits.spec.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/modules/core/tests/users.spec.js
- packages/server/modules/cross-server-sync/index.ts
- packages/server/modules/stats/tests/stats.spec.ts
- packages/server/test/speckle-helpers/commitHelper.ts
> chore(server): core IoC #48 - markCommitStreamUpdatedFactory

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/services/commitActivity.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/services/commit/batchCommitActions.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/core/tests/commits.spec.js
> Activitystream IoC 2 addCommitMovedActivity

- packages/server/modules/auth/index.ts
- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/graph/resolvers/users.js
- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/services/users.js
- packages/server/modules/core/tests/integration/createUser.spec.ts
- packages/server/modules/core/tests/integration/updateUser.spec.ts
- packages/server/modules/core/tests/integration/userEmails.graph.spec.ts
- packages/server/modules/core/tests/users.spec.js
> chore(server): core IoC #52 - legacyGetUserFactory

- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/services/users.js
- packages/server/modules/core/services/users/adminUsersListService.js
- packages/server/modules/core/tests/graph.spec.js
- packages/server/modules/core/tests/integration/userEmails.spec.ts
- packages/server/modules/core/tests/usersAdmin.spec.js
> chore(server): core IoC #53 - legacyGetPaginatedUsers(Count)Factory

- packages/server/modules/auth/index.ts
- packages/server/modules/auth/middleware.ts
- packages/server/modules/auth/strategies.ts
- packages/server/modules/automate/index.ts
- packages/server/modules/automate/services/tracking.ts
- packages/server/modules/core/graph/resolvers/branches.js
- packages/server/modules/core/services/users.js
- packages/server/modules/core/tests/integration/createUser.spec.ts
- packages/server/modules/core/tests/users.spec.js
- packages/server/modules/workspaces/rest/sso.ts
> chore(server): core IoC #54 - deleting getUserById (duplicate)

- packages/server/modules/auth/index.ts
- packages/server/modules/auth/strategies/azureAd.ts
- packages/server/modules/auth/strategies/github.ts
- packages/server/modules/auth/strategies/google.ts
- packages/server/modules/auth/strategies/oidc.ts
- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/services/users.js
- packages/server/modules/core/services/users/management.ts
- packages/server/modules/core/tests/users.spec.js
> chore(server): core IoC #56 - findOrCreateUserFactory

- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/services/users.js
- packages/server/modules/core/tests/integration/findUsers.spec.ts
- packages/server/modules/core/tests/integration/userEmails.spec.ts
- packages/server/modules/emails/graph/resolvers/index.ts
- packages/server/modules/pwdreset/rest/index.ts
- packages/server/modules/pwdreset/services/finalize.ts
- packages/server/modules/pwdreset/services/request.ts
- packages/server/modules/serverinvites/repositories/serverInvites.ts
> chore(server): core IoC #57 - getUserByEmailFactory

- packages/server/modules/auth/index.ts
- packages/server/modules/auth/strategies/azureAd.ts
- packages/server/modules/auth/strategies/github.ts
- packages/server/modules/auth/strategies/google.ts
- packages/server/modules/auth/strategies/local.ts
- packages/server/modules/auth/strategies/oidc.ts
- packages/server/modules/auth/tests/auth.spec.js
- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/graph/resolvers/users.js
- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/services/users.js
- packages/server/modules/core/tests/integration/userEmails.spec.ts
- packages/server/modules/core/tests/users.spec.js
- packages/server/scripts/streamObjects.js
> chore(server): core IoC #58 - legacyGetUserByEmailFactory

- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/services/users/adminUsersListService.js
- packages/server/modules/core/tests/integration/userEmails.spec.ts
- packages/server/modules/core/tests/usersAdmin.spec.js
> chore(server): core IoC #59 - legacyGetPaginatedUsersCount rename fix

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/services/commitActivity.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/graph/resolvers/versions.ts
- packages/server/modules/core/services/commit/batchCommitActions.ts
> Activitystream IoC 1 addCommitMovedActivity

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/graph/resolvers/users.js
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/services/streams/management.ts
- packages/server/modules/core/services/users.js
- packages/server/modules/core/services/users/management.ts
- packages/server/modules/core/tests/users.spec.js
- packages/server/modules/core/tests/usersAdmin.spec.js
- packages/server/modules/workspaces/services/management.ts
> chore(server): core IoC #62 - deleteUserFactory

- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/graph/resolvers/users.js
- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/services/users.js
- packages/server/modules/core/tests/usersAdmin.spec.js
> chore(server): core IoC #63 - getUserRoleFactory

- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/graph/resolvers/users.js
- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/services/users.js
- packages/server/modules/core/services/users/management.ts
- packages/server/modules/core/tests/graph.spec.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/modules/core/tests/users.spec.js
- packages/server/modules/core/tests/usersAdmin.spec.js
> chore(server): core IoC #64 - changeUserRoleFactory

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/services/commitActivity.ts
- packages/server/modules/core/graph/resolvers/commits.js
- packages/server/modules/core/services/commit/batchCommitActions.ts
- packages/server/modules/core/services/commit/management.ts
- packages/server/modules/core/tests/commits.spec.js
> Activitystream IoC 2 addCommitDeletedActivity

- packages/server/modules/activitystream/services/commitActivity.ts
- packages/server/modules/core/services/commit/management.ts
> Activitystream IoC 3 addCommitReceivedActivity

- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/graph/resolvers/admin.ts
- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/services/admin.ts
- packages/server/modules/core/tests/integration/findUsers.spec.ts
- packages/server/modules/core/tests/integration/userEmails.spec.ts
> chore(server): core IoC #65 - adminUserListFactory

- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/repositories/users.ts
- packages/server/modules/core/tests/integration/userEmails.spec.ts
- packages/server/modules/emails/rest/index.ts
- packages/server/modules/emails/services/verification/finalize.ts
> chore(server): core IoC #66 - markUserAsVerifiedFactory

- packages/viewer/src/index.ts
- packages/viewer/src/modules/loaders/OBJ/ObjConverter.ts
- packages/viewer/src/modules/loaders/OBJ/ObjGeometryConverter.ts
- packages/viewer/src/modules/loaders/OBJ/ObjLoader.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleConverter.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleGeometryConverter.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleLoader.ts
… classes from the loader system are now protected instead of private in order to properly extend them
Updated visibility of class members across the loader system for better extension support. Also `RenderTree` wasn't exported, and now it is
> Loaders Visibility Update

- packages/server/modules/core/graph/resolvers/users.ts
> chore(server): core IoC #69 (nice) - users resolvers to TS

- packages/server/modules/auth/repositories/index.ts
- packages/server/modules/blobstorage/tests/blobstorage.integration.spec.js
- packages/server/modules/core/domain/tokens/operations.ts
- packages/server/modules/core/domain/tokens/types.ts
- packages/server/modules/core/graph/resolvers/appTokens.ts
- packages/server/modules/core/helpers/token.ts
- packages/server/modules/core/repositories/tokens.ts
- packages/server/modules/core/services/tokens.ts
- packages/server/modules/fileuploads/tests/fileuploads.integration.spec.ts
- packages/server/test/authHelper.ts
> chore(server): core IoC #70 - createTokenFactory

- packages/server/modules/auth/rest/index.ts
- packages/server/modules/auth/services/serverApps.ts
- packages/server/modules/auth/tests/apps.graphql.spec.js
- packages/server/modules/auth/tests/apps.spec.js
- packages/server/modules/automate/graph/resolvers/automate.ts
- packages/server/modules/automate/index.ts
- packages/server/modules/automate/services/trigger.ts
- packages/server/modules/automate/tests/trigger.spec.ts
- packages/server/modules/core/domain/tokens/operations.ts
- packages/server/modules/core/domain/tokens/types.ts
- packages/server/modules/core/graph/resolvers/appTokens.ts
- packages/server/modules/core/repositories/tokens.ts
- packages/server/modules/core/services/tokens.ts
- packages/server/modules/core/tests/apitokens.spec.ts
> chore(server): core IoC #71 - createAppTokenFactory

- packages/server/modules/auth/rest/index.ts
- packages/server/modules/core/domain/tokens/operations.ts
- packages/server/modules/core/repositories/tokens.ts
- packages/server/modules/core/services/tokens.ts
> chore(server): core IoC #74 - revokeTokenByIdFactory

- packages/server/modules/core/domain/tokens/operations.ts
- packages/server/modules/core/graph/resolvers/apitoken.js
- packages/server/modules/core/repositories/tokens.ts
- packages/server/modules/core/services/tokens.ts
- packages/server/modules/core/tests/users.spec.js
> chore(server): core IoC #75 - revokeUserTokenByIdFactory

- packages/server/modules/auth/repositories/index.ts
- packages/server/modules/core/domain/tokens/operations.ts
- packages/server/modules/core/graph/resolvers/apitoken.ts
> chore(server): core IoC #77 - apitoken resolvers to TS

- packages/server/modules/auth/tests/auth.spec.js
- packages/server/modules/auth/tests/integration/registration.spec.ts
- packages/server/modules/core/domain/server/operations.ts
- packages/server/modules/core/graph/resolvers/server.js
- packages/server/modules/core/repositories/server.ts
- packages/server/modules/core/services/generic.js
> chore(server): core IoC #79 - updateServerInfoFactory

- packages/server/codegen.yml
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/graph/resolvers/server.ts
- packages/server/modules/core/helpers/graphTypes.ts
> chore(server): core IoC #81 - server resolvers to TS

- packages/viewer-sandbox/src/Sandbox.ts
- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/batching/Batcher.ts
- packages/viewer/src/modules/tree/RenderTree.ts
Fixes https://linear.app/speckle/issue/WEB-2025/issue-with-overlaying-same-instances. When building the batches, we now pass the `subtreeId` of the passed in render tree to the `findId` function in order to make sure we get the correct nodes. This is needed because multiple identical ids (but unique nodes) can coexist in the tree at once either via instances, either when diffing.
> WEB-2025-Overlay-Instances

- packages/server/codegen.yml
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/graph/resolvers/branches.js
- packages/server/modules/core/graph/resolvers/branchesNew.ts
- packages/server/modules/core/helpers/graphTypes.ts
> chore(server): core IoC #82 - (most) branches resolvers to TS

- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/frontend_2/deployment.yml
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
> feat(helm): add gatekeeper module feature flag

- packages/server/modules/activitystream/tests/activity.spec.js
- packages/server/modules/cli/commands/download/commit.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/comments/tests/comments.graph.spec.js
- packages/server/modules/comments/tests/comments.spec.js
- packages/server/modules/core/domain/objects/operations.ts
- packages/server/modules/core/domain/objects/types.ts
- packages/server/modules/core/helpers/types.ts
- packages/server/modules/core/repositories/objects.ts
- packages/server/modules/core/services/objects.js
- packages/server/modules/core/services/objects/management.ts
- packages/server/modules/core/tests/branches.spec.js
- packages/server/modules/core/tests/commits.spec.js
- packages/server/modules/core/tests/objects.spec.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/modules/core/tests/users.spec.js
- packages/server/modules/cross-server-sync/index.ts
- packages/server/modules/cross-server-sync/services/commit.ts
- packages/server/package.json
- packages/server/test/speckle-helpers/commitHelper.ts
- yarn.lock
> chore(server): core IoC #88 - createObjectFactory

- packages/server/modules/core/domain/objects/operations.ts
- packages/server/modules/core/repositories/objects.ts
- packages/server/modules/core/rest/upload.ts
- packages/server/modules/core/services/objects.js
- packages/server/modules/core/services/objects/management.ts
- packages/server/modules/core/tests/objects.spec.js
- packages/server/modules/core/utils/chunking.ts
> chore(server): core IoC #89 - createObjectsBatchedFactory

- packages/server/modules/core/domain/objects/operations.ts
- packages/server/modules/core/domain/objects/types.ts
- packages/server/modules/core/rest/upload.ts
- packages/server/modules/core/services/objects.js
- packages/server/modules/core/services/objects/management.ts
> chore(server): core IoC #90 - createObjectsBatchedAndNoClosuresFactory

- packages/server/modules/core/domain/objects/operations.ts
- packages/server/modules/core/domain/objects/types.ts
- packages/server/modules/core/graph/resolvers/objects.ts
- packages/server/modules/core/services/objects.js
- packages/server/modules/core/services/objects/management.ts
- packages/server/modules/core/tests/objects.spec.js
- packages/server/modules/core/tests/streams.spec.ts
- packages/server/modules/stats/tests/stats.spec.ts
- packages/server/test/speckle-helpers/commitHelper.ts
> chore(server): core IoC #91 - createObjectsFactory

- packages/server/modules/core/domain/objects/operations.ts
- packages/server/modules/core/repositories/objects.ts
- packages/server/modules/core/rest/download.js
- packages/server/modules/core/services/objects.js
- packages/server/modules/core/tests/objects.spec.js
- packages/server/modules/previews/index.ts
- packages/server/modules/previews/services/management.ts
> chore(server): core IoC #92 - getFormattedObjectFactory

- packages/server/modules/core/domain/objects/operations.ts
- packages/server/modules/core/repositories/objects.ts
- packages/server/modules/core/rest/download.js
- packages/server/modules/core/services/objects.js
- packages/server/modules/core/tests/objects.spec.js
> chore(server): core IoC #93 - getObjectChildrenStreamFactory

- packages/server/modules/gatekeeper/index.ts
- packages/server/modules/gatekeeper/rest/billing.ts
> fix(gatekeeper): fix billing router initialization

- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
> feat(helm): configure stripe secrets from the helm chart

- packages/server/modules/gatekeeper/rest/billing.ts
> feat(gatekeeper): fail fast if the environment is misconfigured for billing

- packages/server/modules/core/services/objects.js
- packages/server/modules/core/tests/objects.spec.js
> chore(server): core IoC #96 - delete getObjects

- packages/server/modules/core/domain/objects/operations.ts
- packages/server/modules/core/repositories/objects.ts
- packages/server/modules/core/rest/diffDownload.ts
- packages/server/modules/core/services/objects.js
> chore(server): core IoC #97 - getObjectsStreamFactory

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/domain/types.ts
- packages/server/modules/activitystream/services/commentActivity.ts
- packages/server/modules/cli/commands/download/commit.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/comments/graph/resolvers/comments.ts
- packages/server/modules/comments/services/management.ts
- packages/server/modules/cross-server-sync/index.ts
> Activitystream Ioc 1 addReplyAddedActivity 

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/services/branchActivity.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/core/graph/resolvers/branchesNew.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/services/branch/management.ts
- packages/server/modules/core/tests/commits.spec.js
- packages/server/modules/cross-server-sync/index.ts
- packages/server/modules/fileuploads/index.ts
- packages/server/modules/fileuploads/services/resultListener.ts
> Activitystream IoC 2 addBranchCreatedActivity

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/services/branchActivity.ts
- packages/server/modules/core/graph/resolvers/branchesNew.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/services/branch/management.ts
- packages/server/modules/core/tests/branches.spec.js
> Activitystream IoC 3 addBranchUpdatedActivity

- packages/server/modules/core/graph/resolvers/commitsNew.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/services/commit/retrieval.ts
> chore(server): core IoC #100 - rename

- packages/server/modules/core/domain/users/operations.ts
- packages/server/modules/core/graph/resolvers/admin.ts
- packages/server/modules/core/services/admin.ts
> chore(server): core IoC #101 - adminInviteListFactory

- packages/server/modules/activitystream/domain/operations.ts
- packages/server/modules/activitystream/services/branchActivity.ts
- packages/server/modules/core/graph/resolvers/branchesNew.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/services/branch/management.ts
- packages/server/modules/core/tests/branches.spec.js
- packages/server/modules/core/tests/streams.spec.ts
> Activitystream IoC 4 addBranchDeletedActivity

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/resolvers/admin.ts
- packages/server/modules/core/services/admin.ts
> chore(server): core IoC #102 - adminProjectListFactory

- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/rest/authUtils.js
- packages/server/modules/core/rest/diffDownload.ts
- packages/server/modules/core/rest/download.js
- packages/server/modules/core/scopes.ts
- packages/server/modules/core/services/streams/auth.ts
> chore(server): core IoC #103  - validatePermissionsReadStream

- packages/server/modules/core/rest/download.ts
- packages/server/modules/core/rest/speckleObjectsStream.ts
> chore(server): core IoC #105 - remaining js rest to ts

- packages/frontend-2/components/viewer/explorer/StringFilter.vue
It is frustrating having to constantly click view more, and it only load in 10 items. 
I've upped the count to 30.
> refactor(fe2): Update StringFilter.vue read more count

- utils/helm/speckle-server/templates/frontend_2/deployment.yml
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
Rename token>key for WEBFLOW_API_TOKEN
> fix(helm): Update webflow api key name for consistency

- utils/helm/speckle-server/templates/frontend_2/deployment.yml
> fix(fe2): Update deployment.yml

- packages/webhook-service/src/main.js
I made this a single PR since it is very small.
I know that to be precise we should also migrate dependencies that are not `db` related (like the logger), I just ignored them for now since I would really like to move quickly to the next step of the project.
cc @gjedlicska
> webhook-service  refactor multiregion

- packages/fileimport-service/ifc/api.js
- packages/fileimport-service/ifc/index.js
- packages/fileimport-service/src/daemon.js
> Fileimport IoC 1 ServerAPI refactor multiregion

- packages/frontend-2/components/viewer/gendo/Panel.vue
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/frontend-2/lib/gendo/graphql/queriesAndMutations.ts
- packages/server/assets/gendo/typedefs/gendo.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/gendo/graph/resolvers/index.ts
- packages/server/modules/gendo/helpers/types/index.ts
- packages/server/modules/gendo/index.ts
- packages/server/modules/gendo/rest/index.ts
- packages/server/test/graphql/generated/graphql.ts
> chore(server): gendo IoC #1 - prep/cleanup before getting started

- packages/server/assets/gatekeeper/typedefs/gatekeeper.graphql
> feat(gatekeeper): add all plan statuses

- packages/server/modules/blobstorage/domain/operations.ts
- packages/server/modules/blobstorage/services/management.ts
- packages/server/modules/gendo/domain/operations.ts
- packages/server/modules/gendo/domain/types.ts
- packages/server/modules/gendo/graph/resolvers/index.ts
- packages/server/modules/gendo/repositories/index.ts
- packages/server/modules/gendo/services/index.ts
> chore(server): gendo IoC #2 - createRenderRequestFactory

- packages/server/modules/gendo/domain/operations.ts
- packages/server/modules/gendo/graph/resolvers/index.ts
- packages/server/modules/gendo/repositories/index.ts
- packages/server/modules/gendo/services/index.ts
> chore(server): gendo IoC #4 - getLatestVersionRenderRequestsFactory

- packages/server/assets/core/typedefs/user.graphql
- packages/server/assets/gendo/typedefs/gendo.graphql
- packages/server/codegen.yml
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/gendo/domain/operations.ts
- packages/server/modules/gendo/graph/resolvers/index.ts
- packages/server/modules/gendo/helpers/types/graphTypes.ts
- packages/server/modules/gendo/repositories/index.ts
- packages/server/modules/gendo/services/index.ts
- packages/server/test/graphql/generated/graphql.ts
> chore(server): gendo IoC #5 - getVersionRenderRequestFactory

- packages/fileimport-service/ifc/import_file.js
- packages/fileimport-service/ifc/index.js
> Fileimport IoC 2 parseAndCreateCommit

- packages/frontend-2/components/viewer/Controls.vue
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/test/graphql/generated/graphql.ts
Minor thing: These lowercase keyboard shortcuts annoyed me.
> Fix: Uppercase keyboard shortcuts

- packages/viewer/src/modules/pipeline/Passes/DepthPass.ts
- packages/viewer/src/modules/pipeline/Passes/GeometryPass.ts
- packages/viewer/src/modules/pipeline/Passes/NormalsPass.ts
- packages/viewer/src/modules/pipeline/Passes/StencilMaskPass.ts
- packages/viewer/src/modules/pipeline/Passes/StencilPass.ts
- packages/viewer/src/modules/pipeline/Passes/ViewportPass.ts
> Pen View Selection While Sectioning Fix

- packages/dui3/components/filter/ListSelect.vue
> fix(dui3): force getting fresh send filters

- packages/server/modules/core/tests/integration/scheduledTasks.spec.ts
- packages/server/modules/gatekeeper/tests/unit/checkout.spec.ts
> test: fix flaky tests

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/World.ts
Issue made apparent by the forum [post](https://speckle.community/t/issue-with-section-box-geometry-dissapears-when-i-click-the-section-box/14709)  with the stream [version](https://app.speckle.systems/projects/817c4e8daa/models/f0601ef5f9@80db5ff26a) 
Fixed an issue with computing a relative offset box where the origin of the input box was not taken into account and the resulting offset box would be whack
> Relative Offset Box Fix

- packages/frontend-2/components/viewer/dataviewer/Object.vue
> fix(frontend): explorer will now correctly display false prop values as false, rather than null

- packages/dui3/components/common/ProjectModelGroup.vue
- packages/dui3/lib/common/generated/gql/graphql.ts
Also fixes the issues resulting from not committing generated files :/ 
Before: 
After:
> feat(dui3): clearer project groups when collapsed

- packages/server/modules/core/dbSchema.ts
- packages/server/modules/core/helpers/types.ts
- packages/server/modules/core/migrations/20241101055531_project_region.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/notifications/tests/activityDigest.spec.ts
> feat(projects): add project regions, default to null

- packages/frontend-2/components/dashboard/Sidebar.vue
> Update SpeckleCon banner copy

- packages/dui3/store/accounts.ts
- Attempting to access content in an SSO-protected workspace without a valid SSO session now throws a specific error
- We'd like to tell users how to fix this with a nice little toast
- Tells users with a nice little toast
> fix(sso): toast on expired sso session

- packages/server/modules/workspaces/tests/integration/regions.graph.spec.ts
> fix(server): failing workspace regions test

- packages/viewer-sandbox/src/Sandbox.ts
- packages/viewer/src/index.ts
> Viewer Exports Updated & Debug Normal Pass in the Sandbox

- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/fileimport_service/deployment.yml
- utils/helm/speckle-server/templates/monitoring/deployment.yml
- utils/helm/speckle-server/templates/objects/deployment.yml
- utils/helm/speckle-server/templates/preview_service/deployment.yml
- utils/helm/speckle-server/templates/server/deployment.yml
- utils/helm/speckle-server/templates/webhook_service/deployment.yml
The Helm Chart attempted to mount the volume at `/`. Root is protected and read-only, so we must mount a volume to a sub-directory.
We can also use the `path` parameter of the volume, to place the secret contents at a particular path
We can see the file is mounted at the expected path, and the contents are as expected:
> fix(helm chart): root is read-only so mount volume to specific directory

- packages/server/modules/automate/graph/resolvers/automate.ts
- packages/server/modules/automate/rest/authGithubApp.ts
- packages/server/modules/automate/tests/automations.spec.ts
- packages/server/modules/cli/commands/download/project.ts
- packages/server/modules/core/index.ts
- packages/server/modules/cross-server-sync/domain/operations.ts
- packages/server/modules/cross-server-sync/services/project.ts
- packages/server/modules/multiregion/dbSelector.ts
- packages/server/modules/shared/redis/redis.ts
- packages/server/modules/workspaces/rest/sso.ts
> fix(redis): make redis client singleton from a module

- packages/frontend-2/components/dashboard/Sidebar.vue
Removing SpeckleCon banner from FE2.
> fix(fe2) Remove Specklecon banner

- packages/server/assets/workspacesCore/typedefs/workspaces.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/domain/sso/operations.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/repositories/sso.ts
- packages/server/modules/workspaces/services/management.ts
- packages/server/modules/workspaces/tests/integration/sso.spec.ts
- packages/server/test/graphql/generated/graphql.ts
- No more hotel california
- Allows deletion of workspace sso provider directly
- Deletes workspace sso provider on workspace delete
> feat(sso): delete sso

- packages/dui3/components/common/ProjectModelGroup.vue
- packages/dui3/components/model/CardBase.vue
Code is more cleaner now, we were doing redundant patching for nothing
> Fix(dui3): cleanup and fix dialog reactivity

- packages/shared/src/core/constants.ts
Changing the source app abbreviation from TEKLAS to TKL for Tekla Structures.
Related to: https://linear.app/speckle/issue/CNX-745/change-source-app-abbreviation-from-teklas-to-tkl-or-something-else
> CNX-745 Change Source App Abbreviation from TEKLAS to TKL

- packages/dui3/components/send/Wizard.vue
- packages/dui3/components/wizard/ModelSelector.vue
> Chore(dui3): improve existing model card error

- packages/frontend-2/components/workspaces/Promo/Page.vue
> Update copy on workspace page

- packages/server/modules/core/repositories/commits.ts
- packages/server/modules/core/tests/commits.spec.js
> fix(commits): add streamId to legacyCommitsQuery

- packages/server/codegen.yml
- packages/server/modules/comments/graph/resolvers/comments.ts
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/graph/resolvers/common.ts
- packages/server/modules/core/services/richTextEditorService.ts
> feat(server): SmartTextEditorValue.attachments multiregion support

- packages/preview-service/src/clients/knex.ts
> fix(preview-service): main region db client selector

- packages/fileimport-service/obj/import_file.py
- packages/fileimport-service/src/daemon.js
- packages/fileimport-service/stl/import_file.py
Fixes obj & stl file importers which were broken by https://github.com/specklesystems/speckle-server/pull/3523
> fix(fileimport): stl & obj importer expect correct number of args

- packages/server/modules/notifications/services/handlers/mentionedInComment.ts
there was only 1 required change
> feat(server): notifications multiregion prep

- packages/dui3/lib/common/generated/gql/graphql.ts
- packages/frontend-2/components/billing/Alert.vue
- packages/frontend-2/components/settings/workspaces/Billing.vue
- packages/frontend-2/components/settings/workspaces/billing/PricingTable/Desktop.vue
- packages/frontend-2/components/settings/workspaces/billing/PricingTable/Header.vue
- packages/frontend-2/lib/billing/helpers/constants.ts
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/frontend/src/graphql/generated/graphql.ts
- packages/server/assets/gatekeeper/typedefs/gatekeeper.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/gatekeeper/clients/stripe.ts
- packages/server/modules/gatekeeper/domain/workspacePricing.ts
- packages/server/modules/gatekeeper/services/subscriptions.ts
- packages/server/modules/gatekeeper/stripe.ts
- packages/server/modules/gatekeeper/tests/unit/checkout.spec.ts
- packages/server/modules/gatekeeper/tests/unit/featureAuthorization.spec.ts
- packages/server/modules/gatekeeper/tests/unit/subscriptions.spec.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/test/graphql/generated/graphql.ts
> feat(gatekeeper): rename workspace plans

- packages/viewer/src/modules/loaders/Speckle/SpeckleConverter.ts
tl;dr: introducing new class that requires same treatment as builtelements elements.
> feat: adds compat for upcoming dui3 changes

- packages/frontend-2/components/settings/workspaces/Billing.vue
- packages/frontend-2/components/settings/workspaces/billing/PricingTable/Desktop.vue
- packages/frontend-2/components/settings/workspaces/billing/PricingTable/Header.vue
- packages/frontend-2/components/settings/workspaces/billing/PricingTable/PricingTable.vue
- packages/frontend-2/components/workspaces/Promo/Page.vue
> Feat: Add pricing table to promo page

- packages/server/modules/cli/commands/workspaces/set-plan.ts
- packages/server/modules/gatekeeper/domain/workspacePricing.ts
- packages/server/modules/gatekeeper/migrations/20241126084242_workspace_plan_rename.ts
> fix(gatekeeper): migrate plan rename

- utils/helm/speckle-server/templates/objects/serviceaccount.yml
- utils/helm/speckle-server/templates/server/serviceaccount.yml
> fix(helm chart): allow service account access to gendo secret

- packages/viewer/src/index.ts
- packages/viewer/src/modules/Viewer.ts
- packages/viewer/src/modules/materials/Materials.ts
- packages/viewer/src/modules/materials/SpeckleMaterial.ts
- packages/viewer/src/modules/objects/SpeckleMesh.ts
Non speckle materials no longer throw an error
> WEB-2171: Non-Speckle Materials Fix

- packages/viewer/src/index.ts
- packages/viewer/src/modules/Viewer.ts
- packages/viewer/src/modules/extensions/SelectionExtension.ts
`SelectionExtension` now clears it's selected objects state when clearing the selection. It also does not allow for duplicate selected nodes anymore
> WEB-1683: Selection Extension Fixes

- packages/server/modules/gatekeeper/clients/stripe.ts
> fix(gatekeeper): parse cancellation date properly

- packages/frontend-2/components/settings/workspaces/security/sso/Wrapper.vue
> feat(fe2): Add SSO indicator to Wrapper

- packages/frontend-2/components/settings/workspaces/security/sso/DeleteDialog.vue
- packages/frontend-2/components/settings/workspaces/security/sso/Wrapper.vue
> fix(sso): delete via id

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/assets/gatekeeper/typedefs/gatekeeper.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/gatekeeper/errors/billing.ts
- packages/server/modules/gatekeeper/graph/resolvers/index.ts
- packages/server/modules/gatekeeper/services/subscriptions.ts
- packages/server/modules/gatekeeper/tests/unit/subscriptions.spec.ts
- packages/server/test/graphql/generated/graphql.ts
> feat(gatekeeper): upgrade workspace plan

- packages/tailwind-theme/src/plugin.ts
- packages/tailwind-theme/src/preset.ts
- packages/ui-components/src/components/common/Alert.vue
- packages/ui-components/src/stories/styling/semantic-colors/SemanticColors.vue
> Fix: Update alerts

- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/frontend_2/deployment.yml
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
The Helm Chart should have consistent pluralisation of `workspaces` (it is plural). The Helm Chart should have consistent treatment of acronyms (fully capitalised).
- required changes to Speckle's deployments have already been made
> fix(helm chart): consistent spelling of workspaces

- packages/server/modules/workspacesCore/migrations/20241202183039_workspace_start_trial.ts
> feat(workspaces): all workspaces start trial now

- packages/frontend-2/components/settings/workspaces/security/sso/Form.vue
> fix(sso): keep secrets secret

- packages/frontend-2/components/settings/workspaces/billing/PricingTable/Plan.vue
- packages/frontend-2/components/settings/workspaces/billing/PricingTable/PricingTable.vue
Makes spacings in the pricing component more consistent with surrounding elements
> Minor spacing changes to be consistent

- packages/frontend-2/components/settings/server/Regions.vue
- packages/frontend-2/components/settings/server/regions/AddEditDialog.vue
- packages/frontend-2/lib/multiregion/composables/management.ts
> fix(fe2): minor default region setting ui issues

- packages/frontend-2/components/project/page/automations/EmptyState.vue
- There are no supported public functions, but we're still showing old ones here on accident.
- Drop the section
- Link to workspace functions instead of closed beta blog post
> fix(automate): drop public functions

- packages/server/modules/multiregion/dbSelector.ts
> feat(multiRegion): do not recreate the pub subs in production

- packages/server/modules/gatekeeper/services/checkout.ts
> feat(gatekeeper): lower checkout session expiry

- packages/frontend-2/pages/workspaces/[slug]/sso/index.vue
> fix(fe2): Align /sso logo to center

- packages/frontend-2/components/automate/automation/CreateDialog.vue
- packages/frontend-2/components/automate/function/CreateDialog.vue
- packages/frontend-2/components/automate/functions/page/Header.vue
- packages/frontend-2/components/project/page/automations/EmptyState.vue
- We have two multi-step flows involved in creating something in automate: functions and automations
- We don't have good insight into how they're performing
- Adds a bucket of mixpanel events so we can start generating funnel metrics
> chore(automate): function and automation creation funnel events

- packages/frontend-2/components/settings/workspaces/billing/PricingTable/Plan.vue
@benjaminvo This is one of those scenarios where this can't be tested locally, when you've used the CLI for billing. We are safe to push to on to app/latest though and check there.
> fix(fe2): Upgrading from annual to monthly billing tooltip

- packages/frontend-2/components/project/page/automations/EmptyState.vue
I want to speak with the people
> chore(automate): add in-app demo calendar link

- packages/server/db/migrations.ts
- we were logging the same error twice
- but the logging at the top level did not include additional information logged at the deeper level.
- the error is logged at the top level, so we do not need to log deeper
- instead of logging at the deep level, we wrap the error with the additional information and then throw. The top level will log the error with the additional information.
> fix(logging): remove duplicate log

- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
> fix(workspaces): make sure to return from switch statement

- packages/frontend-2/components/automate/runs/StatusBadge.vue
- packages/frontend-2/lib/automate/composables/runs.ts
> Fix: Update Automate run label colors

- packages/ui-components/src/components/common/Badge.vue
Update badge to use correct text colour.
> fix(fe2): Adjust badge text colour

- packages/frontend-2/components/settings/workspaces/General.vue
- packages/frontend-2/components/workspace/sidebar/About.vue
- packages/ui-components/src/components/form/TextArea.vue
> refactor(fe2): Editable Description field in workspace sidebar

- packages/frontend-2/components/billing/Alert.vue
- packages/frontend-2/components/workspace/ProjectList.vue
- packages/frontend-2/components/workspace/sidebar/Members.vue
Commit messages tell the story
> Fix(workspace): Tiny polishing in new workspace homepage

- packages/frontend-2/components/invite/dialog/CancelInvite.vue
- packages/frontend-2/components/project/page/settings/collaborators/Row.vue
> Feat: Add confirmation dialog for pending invite cancelation

- packages/frontend-2/components/settings/server/ActiveUsers.vue
> Feat: Add ID for server admins in users table

- packages/server/modules/gatekeeper/services/trialEmails.ts
> feat(server): track wp trial expiratiom email sends

- packages/frontend-2/components/billing/Alert.vue
- packages/frontend-2/components/dashboard/Sidebar.vue
- packages/frontend-2/components/settings/Dialog.vue
- packages/frontend-2/components/settings/workspaces/Billing.vue
- packages/frontend-2/components/settings/workspaces/billing/PricingTable/Plan.vue
- packages/frontend-2/components/workspace/header/Header.vue
Trial expired state was not being reflected correctly on the billing state, some parts are similar to trial and some exceptions. This also makes adjustments for the cancelled state (active subscription that is manually cancelled), it's not 100% as I need to verify with Gergö wether downgrading is possible or not. It's not a relevant scenario yet but will make it easier to adjust later.
> Fix: Updates to trial expired state in billing settings

- packages/frontend-2/lib/common/composables/serverInfo.ts
> Fix: Order server permission list ABC

- packages/frontend-2/components/auth/PasswordResetPanel.vue
- packages/frontend-2/components/auth/RegisterPanel.vue
- packages/frontend-2/pages/authn/forgotten-password.vue
Some minor fixes, changing alert to CommonAlert and some copy changes
> Fix: Small UI fixes for auth screens

- packages/frontend-2/components/viewer/Controls.vue
Quick revert fix. Will return to this today.
> fix(fe2): Update Controls.vue overflow

- packages/server/logging/knexMonitoring.ts
> feat(db): elevate db query message log level

- packages/viewer/src/modules/extensions/CameraController.ts
Using `NearPlaneCalculation.ACCURATE` in the camera controller
> Enabled accurate near plane calculation

- packages/dui3/lib/bindings/definitions/ISendBinding.ts
- packages/dui3/store/hostApp.ts
Need to be tested by @kekesidavid
Call `triggerCancel(modelCardId)` from archicad
> Feat(dui3): CNX-837 cancel send from host app

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/frontend-2/lib/core/composables/error.ts
- packages/frontend-2/lib/core/helpers/observability.ts
- packages/frontend-2/pages/index.vue
- packages/frontend-2/plugins/001-logger.ts
- packages/frontend-2/plugins/002-rum.ts
- packages/frontend-2/type-augmentations/nuxt.d.ts
logger calls w/ any level can be sent to Seq if they've got `important: true` set
> feat(fe2): allow logging CSR non-errors to seq

- packages/server/modules/core/graph/resolvers/projects.ts
> fix(server): inject the right event emitter to project creation

- packages/server/modules/multiregion/regionConfig.ts
> fix(multiRegion): do not look for a multi region config, if there should be none

- packages/server/logging/knexMonitoring.ts
- packages/server/logging/requestContext.ts
- packages/server/modules/core/graph/plugins/logging.ts
> feat(server): add db metrics to GQL finished log entries

- packages/server/modules/core/rest/static.ts
> feat(server): ping endpoint

- packages/frontend-2/components/viewer/gendo/Dialog.vue
- packages/frontend-2/components/viewer/gendo/Item.vue
- packages/frontend-2/components/viewer/gendo/List.vue
- packages/ui-components/src/components/layout/Dialog.vue
- Change "Set View" to "Reset View"
- Improve scroll of render images
- Improved loading indicator
> refactor(fe2): General UX improvments

- packages/dui3/components/wizard/ProjectSelector.vue
- packages/dui3/store/accounts.ts
I should have done it initially like this, it caused small lag at the init which was annoying. now it is better
> Fix(dui3): lag on init for readonly check

- packages/frontend-2/components/viewer/gendo/Panel.vue
When a user is not logged in, or on app, Gendo generation will be disabled.
We now show better alerts for this.
> feat(gendo): Show more information when Gendo is disabled

- packages/frontend-2/app.vue
- packages/frontend-2/lib/common/composables/reactiveCookie.ts
> fix(fe2): less frequent cookie-fix invocation

- packages/server/assets/workspacesCore/typedefs/workspaceJoinRequests.graphql
- packages/server/assets/workspacesCore/typedefs/workspaces.graphql
- packages/server/codegen.yml
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/shared/command.ts
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/graph/resolvers/workspaceJoinRequests.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/repositories/workspaceJoinRequests.ts
- packages/server/modules/workspaces/services/workspaceJoinRequestEmails/approved.ts
- packages/server/modules/workspaces/services/workspaceJoinRequestEmails/received.ts
- packages/server/modules/workspaces/services/workspaceJoinRequests.ts
- packages/server/modules/workspaces/tests/integration/workspaceJoinRequests.spec.ts
- packages/server/modules/workspacesCore/domain/types.ts
- packages/server/modules/workspacesCore/helpers/graphTypes.ts
- packages/server/test/graphql/generated/graphql.ts
> feat(workspaces): approve join request

- packages/server/assets/workspacesCore/typedefs/workspaceJoinRequests.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/graph/resolvers/workspaceJoinRequests.ts
- packages/server/modules/workspaces/services/workspaceJoinRequestEmails/denied.ts
- packages/server/modules/workspaces/services/workspaceJoinRequests.ts
- packages/server/modules/workspaces/tests/integration/workspaceJoinRequests.spec.ts
- packages/server/test/graphql/generated/graphql.ts
> Deny workspace join request

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/extensions/FilteringExtension.ts
- packages/viewer/src/modules/extensions/ViewModes.ts
- packages/viewer/src/modules/pipeline/Passes/BasitPass.ts
Handles WEB-2475. Shaded view mode no longer eats up cpu time on large streams
- FilteringExtension now emits the filtering state changed event when reseting the filtering state
- BasitPass no longer applies the per vertex color indices each frame
- ViewModes extension now listens for filtering state changes and have any active BasitPass reset it's color indices on a filtering reset event. Not great, not terrible but it avoids us having to double cache the per vertex color indices.
> Shaded Mode large streams fix

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/frontend-2/pages/settings/workspaces/[slug]/billing.vue
@gjedlicska Not sure about the copy, if it needs to be something else lmk
> Feat: Add link to email for invoiced plans

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/pipeline/Passes/BasitPass.ts
- packages/viewer/src/modules/pipeline/Pipelines/ArcticViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/BasitViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/DefaultPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/EdgesPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/MRT/MRTEdgesPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/MRT/MRTPenViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/MRT/MRTShadedViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/PenViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/ShadedViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/TAAPipeline.ts
Handles https://linear.app/speckle/issue/WEB-2491/section-outlines-should-be-properly-depth-tested and another issue:
- Section outlines are no longer visible behind other geometry. They are depth tested now for all view modes
- Shaded mode aka BastiMode now properly updates the section planes
> Section Outlines Depth Testing

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/materials/shaders/speckle-basic-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-depth-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-displace.vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-ghost-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-normal-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-standard-colored-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-standard-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-text-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-viewport-vert.ts
Handles https://linear.app/speckle/issue/WEB-2182/mangled-geometry-on-intel-xe-when-using-rte
Workaround for the trouble we've been having lately with the integrated intel Xe GPUs. Like the one mentioned here https://app.speckle.systems/projects/bdd828221e/models/eb99326dc3. 
Before:
After:
> Intel IrisXe Fix

- packages/server/modules/emails/migrations/20250120145453_add_code_column_to_email_verifications.ts
- packages/server/modules/emails/migrations/20250123133749_remove_unique_email_verifications.ts
- We found our database has dirty data so for now we decided to remove the constraint.
https://seq.speckle.systems/#/login?to=%2Fevents%3Fsignal%3Dsignal-101,signal-345%26filter%3D@EventType%2520%253D%2520ToEventType('Failed%2520to%2520start%2520server.%2520Exiting%2520with%2520non-zero%2520exit%2520code...')%26from%3D2025-01-22T16:20:00.000Z%26to%3D2025-01-22T16:30:00.000Z
> fix(emails): remove unique constraint from email_verifications

- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- Role was incorrectly being returned as full acl object instead of just role string
> fix(workspaces): return role as string

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/assets/core/typedefs/modelsAndVersions.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/graph/resolvers/models.ts
- packages/server/modules/core/helpers/types.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/test/graphql/generated/graphql.ts
> chore(server): fix nullable type for model author

- packages/server/modules/auth/index.ts
- packages/server/modules/core/graph/resolvers/userEmails.ts
- packages/server/modules/core/tests/integration/userEmails.graph.spec.ts
- packages/server/modules/emails/repositories/index.ts
- packages/server/modules/emails/services/verification/request.old.ts
- packages/server/modules/emails/services/verification/request.ts
> fix(emails): add ff for new email verification flow

- packages/shared/src/environment/index.ts
- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/templates/frontend_2/deployment.yml
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
Added a new feature flag to force onboarding. We want to force app users to go through our onboarding process, but this shouldn't happen on self-hosted servers.
> feat: add force onboarding feature flag

- packages/frontend-2/components/viewer/gendo/List.vue
- packages/frontend-2/components/viewer/gendo/Panel.vue
- packages/frontend-2/components/viewer/selection/Object.vue
The loading state was causing the subscription to stop running.
> fix(gendo): Fix GendoList subscription

- packages/viewer/src/modules/materials/shaders/speckle-basic-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-depth-normal-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-depth-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-displace.vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-ghost-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-line-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-normal-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-point-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-standard-colored-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-standard-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-text-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-viewport-vert.ts
Found a workaround for the RTE issues we've been having on macOS and iOS after Apple made some updates. Fixes https://linear.app/speckle/issue/WEB-470/far-off-origin-geometries-broken-again-on-apple
**Before:**
**After:**
Also fixes MRTDepthNormal pass for intel Xe integrated GPU
> RTE Fix for MacOS and iOS

- packages/frontend-2/components/form/select/ProjectRoles.vue
- packages/frontend-2/components/settings/user/developer/AccessTokens/CreateDialog.vue
- packages/frontend-2/components/settings/user/developer/Applications/CreateEditDialog.vue
- packages/frontend-2/lib/common/helpers/validation.ts
- packages/ui-components/src/components/form/select/Base.vue
- packages/ui-components/src/components/form/select/Multi.stories.ts
- packages/ui-components/src/components/form/select/Multi.vue
- packages/ui-components/src/helpers/common/validation.ts
- packages/ui-components/src/lib.ts
We need a new Multi select component for the onboarding flow. 
We have had problems in the past with multi selects, where they close after every click. This has been reported numerous times, and the problem was from Headlessui. 
I have added this new component, without headlessui, but heavily based on the existing FormSelectBase.
> feat(ui-components): New FormSelectMulti component

- packages/frontend-2/components/viewer/gendo/Panel.vue
Dont merge until around end of the day, as the contest runs until 12am
> [DONT MERGE] Feat: Remove Gendo Contest link

- packages/frontend-2/components/settings/Sidebar.vue
- packages/frontend-2/components/settings/workspaces/General/DeleteDialog.vue
- packages/frontend-2/components/settings/workspaces/General/EditSlugDialog.vue
- packages/frontend-2/components/settings/workspaces/General/LeaveDialog.vue
- packages/frontend-2/pages/settings/workspaces/[slug]/general.vue
Fix various hydration issues, that potential result in incorrect rendering
> Fix: Hydration issues on general settings page

- packages/dui3/components/report/Base.vue
WARNING STATE
FAIL STATE
SUCCESS STATE
> Fix(dui3): eport shows success despite more warning items than

- packages/dui3/pages/index.vue
TODO: replace with correct link once announcement is out and merge
> Message at the top for bundled disclaimer

- packages/ui-components/src/components/user/AvatarEditor.vue
Bug reported by Nikos in discord:
> fix(fe2): Fix broken logic and add 3xl variant to AvatarEditable

- packages/server/modules/automate/index.ts
- With public functions incoming we'd like to track performance of automate relative to the type of function being run (and also specific functions)
- Adds function information to finished runs
- Validated event works in `testing3`:
> chore(automate): mixpanel metrics by function id and type

- packages/frontend-2/components/viewer/PreSetupWrapper.vue
> fix(fe2): embed loading bar position fix

- packages/objectloader/src/index.js
- packages/objectloader/types/index.d.ts
I need to have it in powerbi visual instead stringfy and parse again
> Chore(objectloader): Create from objects instead parsing JSON

- packages/server/modules/workspaces/rest/sso.ts
- We'd like more insight into _what_ OIDC providers are sending when they are misconfigured.
> chore(sso): more logs for missing profile data

- packages/dui3/components/accounts/Menu.vue
- packages/dui3/pages/index.vue
could be temp button till we decide account add flow
https://github.com/user-attachments/assets/1e549bfc-4532-4142-a9e1-c719c7df6c9a
> Feat(dui3): Add account via manager button

- packages/frontend-2/components/settings/workspaces/security/sso/Form.vue
- packages/server/modules/workspaces/domain/sso/logic.ts
- packages/server/modules/workspaces/domain/sso/types.ts
- packages/server/modules/workspaces/helpers/sso.ts
- packages/server/modules/workspaces/rest/sso.ts
- packages/server/modules/workspaces/services/sso.ts
- We've learned more about how Entra ID can behave.
- Attempt fallback to `upn` if `email` is not present
- Fix SSO validation redirects to new settings page urls
> fix(sso): azure upn fallback

- packages/server/modules/workspaces/services/sso.ts
- We're no longer just checking the `.email` claim
- Checks for resolved email when checking for existing user emails
> fix(sso): check emails correctly

- packages/viewer/src/modules/loaders/Speckle/SpeckleGeometryConverter.ts
Empty normals array in the speckle object means no normals, viewer needs to calculate them
> Empty normals fix

- .circleci/config.yml
- packages/server/package.json
- packages/shared/src/environment/index.ts
> chore: all CI server test jobs have all FFs on by default

- packages/server/modules/workspaces/rest/sso.ts
- packages/server/modules/workspaces/services/sso.ts
- email casing strikes again
- lowercases emails coming in from SSO provider before comparing against known user emails
> fix(sso): lowercase emails for sso

- packages/dui3/components/accounts/Menu.vue
- packages/dui3/components/accounts/SignInFlow.vue
- packages/dui3/components/home/NoAccountsPanel.vue
- packages/dui3/lib/core/composables/desktopService.ts
- packages/dui3/pages/index.vue
many ❤️
this functionality will be in usage whenever we start to bundle desktop services with connectors. it is backward compatible. safe to merge
> Feat(dui3): auth via desktop services

- packages/frontend-2/components/billing/Alert.vue
- packages/tailwind-theme/src/plugin.ts
- packages/ui-components/src/components/common/Alert.vue
- packages/ui-components/src/components/common/Badge.vue
- packages/ui-components/src/components/layout/tabs/Horizontal.vue
- packages/ui-components/src/components/layout/tabs/Vertical.vue
> Feat: New dark mode blue

- packages/server/modules/workspaces/rest/sso.ts
- Witnessing strange behavior earlier in the SSO flow and would like to know more.
> chore(sso): more sso logs

- packages/frontend-2/components/automate/automation/CreateDialog.vue
- packages/frontend-2/components/project/page/automation/FunctionSettingsDialog.vue
> fix(fe2): gqlgen breaks when using satisfies operator

- packages/frontend-2/components/project/CardImportFileArea.vue
Did this not in the UI component because some components that use FileZoneUpload dont need this behavior
> Fix: Add click to fileupload area

- .circleci/build_publish_fe2_sourcemaps.sh
> fix: ensure datadog gets git info w/ sourcemaps

- packages/server/modules/workspaces/errors/sso.ts
- Make error message a bit clearer:
> chore(sso): improve misconfigured log

- packages/frontend-2/.env.example
- packages/frontend-2/components/common/TransitioningContents.vue
- packages/frontend-2/lib/core/errors/base.ts
- packages/frontend-2/lib/core/helpers/observability.ts
- packages/frontend-2/lib/projects/composables/previewImage.ts
- packages/frontend-2/nuxt.config.ts
> feat(fe2): less spammy FE2 logging

- packages/frontend-2/lib/core/configs/apollo.ts
- packages/frontend-2/lib/core/helpers/observability.ts
- packages/frontend-2/middleware/002-redirects.global.ts
> fix(fe2): a few reported FE2 error scenarios improved/fixed

- packages/frontend-2/lib/core/helpers/observability.ts
- packages/frontend-2/plugins/001-logger.ts
> fix(fe2): more adjustments to FE2 error reporting

- packages/server/modules/gatekeeper/domain/billing.ts
- packages/server/modules/gatekeeper/migrations/20250224141824_create_workspace_seats_table.ts
> chore(gatekeeper): add workspace_seats table and types

- packages/server/modules/gatekeeper/repositories/workspaceSeat.ts
> feat(workspaces): count workspace seats by type

- packages/server/modules/automate/clients/executionEngine.ts
- packages/server/modules/automate/graph/resolvers/automate.ts
- packages/server/modules/automate/index.ts
- packages/server/modules/automate/services/authCode.ts
- packages/server/modules/automate/services/automationManagement.ts
- packages/server/modules/automate/services/functionManagement.ts
- packages/server/modules/core/graph/dataloaders/index.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
> fix(server/automate): logger should have request context and request ID sent to execution engine

- packages/server/modules/workspaces/services/workspaceJoinRequests.ts
- Event not emitted when joining a workspace via join request
- This should be part of he update workspace role service anyways
- Adds event
> fix(workspaces): emit role updated on join request approved

- packages/frontend-2/middleware/requireDiscoverableWorkspaces.ts
- packages/frontend-2/pages/workspaces/join.vue
Add new middleware to redirect users with no discoverable workspaces to the create page.
> feat(fe): Redirect users with no discoverable workspaces to create page

- packages/frontend-2/middleware/requireDiscoverableWorkspaces.ts
When a user is on the join page, and get approved, we should redirect away from join page to allow them to use the app.
> feature(fe): Redirect users from join page when request is accepted

- packages/frontend-2/middleware/004-emailVerification.global.ts
- packages/frontend-2/middleware/005-onboarding.global.ts
- packages/frontend-2/middleware/006-workspace.global.ts
No current problem here, but I'm doing this to be safe with SSO. Update our auth pattern to include sso paths.
> feat(fe): Ensure no middleware for sso

- packages/preview-service/src/main.ts
> fix(preview-service): timeout was already in milis

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/frontend-2/lib/core/composables/error.ts
- packages/frontend-2/lib/core/configs/apollo.ts
> fix(fe2): error state logger being undefined

- packages/frontend-2/Dockerfile
- packages/frontend-2/package.json
- packages/viewer/rollup.config.js
> chore: better viewer sourcemaps in datadog

- packages/frontend-2/Dockerfile
- packages/objectloader/rollup.config.js
- packages/viewer/rollup.config.js
> chore: fix objectloader sourcemaps in datadog

- packages/frontend-2/lib/auth/helpers/onboarding.ts
- packages/shared/src/onboarding/helpers/index.ts
- packages/ui-components/src/components/form/select/Multi.vue
Mirna also asked if we could up the max-height on these Selects, so that on larger screens we don't use a scroll.
> refactor(fe): Update labels of Onboarding Plans to align with marketing site

- packages/dui3/lib/bridge/sketchup.ts
> Fix(sketchup): sketchup bridge upload data

- packages/frontend-2/components/automate/automation/CreateDialog.vue
- We already track events throughout the automation creation flow. But we'd like to compare how this performs differently for different public functions, now that they're out.
- Includes function id in automation creation mixpanel events, once known.
> chore(automate): include function id in automation creation funnel

- packages/preview-service/src/jobProcessor.ts
- packages/preview-service/src/main.ts
- packages/server/modules/previews/resultListener.ts
Removed promise.race from job, the browser will be closed anyhow.
Added some logging changes for better structure
> fix(previews): logging and promise fixes

- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
> chore(gatekeeper): add default values for new plans

- packages/preview-service/src/config.ts
- packages/preview-service/src/main.ts
- utils/helm/speckle-server/templates/preview_service/deployment.yml
- utils/helm/speckle-server/templates/preview_service/service.yml
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
- remove obsolete references to metricsPort
- allow listen Host to be configured
> fix(preview service): expose metrics port via helm chart

- packages/server/modules/previews/domain/operations.ts
- packages/server/modules/previews/repository/previews.ts
- packages/server/modules/previews/rest/router.ts
- packages/server/modules/previews/services/createObjectPreview.ts
- packages/server/modules/previews/services/management.ts
- packages/server/modules/previews/tests/unit/createObjectPreview.spec.ts
We are seeing multiple requests for the same preview in the preview service job queue.
The period between querying the database for data about a preview (and receiving no data) until inserting data about the preview (which has just been requested) may be sufficiently long to allow a race condition.
Addresses https://linear.app/speckle/issue/WEB-2807/jobs-get-queued-multiple-times
This PR amends the order in which the preview job is created; we try to insert into the database before we create a job request.
We have amended the insertion to return a message if unsuccessful, allowing us to exit early prior to creating the job request.
> fix(preview service): attempt to prevent duplicate jobs

- packages/server/modules/workspaces/errors/sso.ts
- packages/server/modules/workspaces/services/sso.ts
- packages/server/modules/workspaces/tests/unit/services/sso.spec.ts
- Caught another issue when using sso provider emails to look for invites - email capitalization strikes again!
- Sanitizes incoming email before search
> fix(sso): email capitalization again

- packages/preview-service/src/jobProcessor.ts
> fix(preview service): remove need for speckle shared in frontend

- packages/preview-service/src/jobProcessor.ts
> fix(preview service): use correct units for metrics

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/batching/LineBatch.ts
- packages/viewer/src/modules/materials/Materials.ts
Fixed the issue where ghosted lines would not appear transparent in some cases
Before
After
> Ghosted Lines

- packages/dui3/components/common/ProjectModelGroup.vue
no more flushing error at first
> Fix(dui3): fix red flash on model card

- packages/frontend-2/components/viewer/Base.vue
- packages/frontend-2/lib/viewer/composables/activity.ts
- packages/frontend-2/lib/viewer/composables/serialization.ts
- packages/frontend-2/lib/viewer/composables/setup/dev.ts
- packages/frontend-2/type-augmentations/window.d.ts
> feat(fe2): better viewer activity observability

- packages/frontend-2/components/viewer/PreSetupWrapper.vue
- packages/frontend-2/lib/viewer/composables/activity.ts
- packages/frontend-2/lib/viewer/composables/serialization.ts
- packages/frontend-2/lib/viewer/composables/setup.ts
- packages/frontend-2/lib/viewer/composables/setup/dev.ts
- packages/frontend-2/type-augmentations/window.d.ts
- packages/server/modules/auth/tests/helpers/registration.ts
> feat(fe2): more viewer debugging improvements

- packages/server/modules/auth/tests/helpers/registration.ts
> fix(server): fix registration test email provider

- packages/frontend-2/lib/dashboard/helpers/connectors.ts
> Fix: Minor connectors page copy changes

- packages/server/modules/gatekeeper/domain/billing.ts
- packages/server/modules/gatekeeper/events/eventListener.ts
- packages/server/modules/gatekeeper/graph/resolvers/index.ts
- packages/server/modules/gatekeeper/repositories/workspaceSeat.ts
- packages/server/modules/gatekeeper/services/subscriptions.ts
- packages/server/modules/gatekeeper/tests/unit/subscriptions.spec.ts
- packages/server/modules/gatekeeperCore/domain/events.ts
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/graph/resolvers/workspaceJoinRequests.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/join.ts
- packages/server/modules/workspaces/services/management.ts
- packages/server/modules/workspaces/services/projects.ts
- packages/server/modules/workspaces/services/workspaceJoinRequests.ts
- packages/server/modules/workspaces/services/workspaceSeat.ts
- packages/server/modules/workspaces/tests/helpers/creation.ts
- packages/server/modules/workspaces/tests/integration/workspaceSeat.graph.spec.ts
- packages/server/modules/workspaces/tests/integration/workspaceSeat.spec.ts
- packages/server/modules/workspaces/tests/integration/workspaces.graph.spec.ts
- packages/server/modules/workspaces/tests/unit/events/eventListener.spec.ts
- packages/server/modules/workspaces/tests/unit/services/management.spec.ts
- packages/server/modules/workspaces/tests/unit/services/projects.spec.ts
- packages/server/modules/workspacesCore/domain/events.ts
> chore(server): refactor seat updated to be its own event

- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/assets/workspacesCore/typedefs/workspaces.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/domain/types.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/repositories/workspaces.ts
- packages/server/test/graphql/generated/graphql.ts
This is under the assumptions that createdAt equals the join date
> Feat: Add createdAt to workspace team WorkspaceCollaborator

- packages/server/modules/workspaces/repositories/workspaceJoinRequests.ts
- packages/server/modules/workspaces/tests/integration/workspaceJoinRequests.graph.spec.ts
> fix(workspaces): filter out dismissed join requests

- packages/frontend-2/components/project/page/settings/collaborators/Collaborators.vue
- packages/frontend-2/components/settings/shared/projects/index.vue
- packages/frontend-2/lib/common/helpers/route.ts
- packages/frontend-2/nuxt.config.ts
- packages/frontend-2/pages/projects/[id]/index.vue
- packages/frontend-2/pages/projects/[id]/index/collaborators.vue
- packages/frontend-2/pages/projects/[id]/index/settings.vue
- packages/frontend-2/pages/projects/[id]/index/settings/collaborators.vue
> Feat: Move project collaborators to own tab

- packages/viewer/src/modules/extensions/controls/SmoothOrbitControls.ts
Fixes an issue where incorrect offsets were retrieved in setups where the viewer was in a parent with a relative position. Issue signaled [here](https://speckle.community/t/how-to-fix-zooming-to-the-cursor-after-resizing-the-speckle-viewer/17084/3) and also in an older thread that seem to not be able to find anymore.
> Relative Parent Offset Fix

- packages/frontend-2/components/pricingTable/Plan.vue
- packages/frontend-2/components/pricingTable/PricingTable.vue
- packages/frontend-2/components/settings/workspaces/billing/Page.vue
- packages/frontend-2/components/settings/workspaces/billing/PricingTable/Plan.vue
- packages/frontend-2/components/settings/workspaces/billing/Summary.vue
- packages/frontend-2/components/settings/workspaces/billing/UpgradeDialog.vue
- packages/frontend-2/lib/billing/helpers/plan.ts
- packages/frontend-2/lib/billing/helpers/prices.ts
- packages/frontend-2/lib/workspaces/composables/plan.ts
- packages/shared/src/workspaces/helpers/plans.ts
Some small fixes
- Redirect to checkout if no active subscription 
- Update plan naming
- Update button text
> Fix: Various pricing plan fixes

- packages/server/modules/core/graph/resolvers/projects.ts
> fix(server): project access fix for discoverable projects

- packages/frontend-2/components/viewer/anchored-point/Thread.vue
> refactor(fe): Improve accuracy of comment context warning

- packages/server/assets/workspacesCore/typedefs/workspaces.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/repositories/workspaces.ts
- packages/server/modules/workspaces/tests/helpers/creation.ts
- packages/server/modules/workspaces/tests/integration/workspaces.graph.spec.ts
- packages/server/test/graphql/generated/graphql.ts
> feat(workspaces): add filter by seatType in workspace team

- packages/viewer/src/index.ts
- packages/viewer/src/modules/extensions/ViewModes.ts
- packages/viewer/src/modules/pipeline/Passes/EdgesPass.ts
- packages/viewer/src/modules/pipeline/Passes/ShadedPass.ts
- packages/viewer/src/modules/pipeline/Pipelines/BasitViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/EdgesPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/MRT/MRTEdgesPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/MRT/MRTPenViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/MRT/MRTShadedViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/PenViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/ShadedViewPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/TechnicalViewPipeline.ts
- Basit pass and pipeline have been renamed to Shaded
- Viewer now exports all implemented passes
- Viewer now exports the pass option types as well as defaults
> Viewer API export update

- packages/viewer/src/modules/pipeline/Passes/ShadowcatcherPass.ts
Fixed an issue where the shadowcatcher would not seemingly update unless the scene changed it's size when calling `updateShadowcatcher`
> Shadowcatcher 🛸 Update Fix

- .circleci/multiregion.test-ci.json
- packages/server/modules/workspaces/tests/integration/projects.graph.spec.ts
- packages/server/multiregion.test.example.json
> chore: back to 1 extra region in tests

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/LegacyViewer.ts
…ndered. This allows correct shadows after de-selecting outline only selections. Also re-enabled stream loading in th sandbox
- When resetting the selection, the shadowmap is re-rendered. This allows correct shadows after de-selecting outline only selections. 
- Also re-enabled stream loading in th sandbox
> Hidden Outline Only Objects Shadows Fix

- packages/viewer/src/modules/converter/Geometry.ts
Fix for merging indices inside `Geometry`. Unused by the viewer currently, but still needs fixing
> Merging Indices Fix

- packages/viewer-sandbox/index.html
- packages/viewer-sandbox/src/Sandbox.ts
- packages/viewer-sandbox/src/main.ts
- packages/viewer-sandbox/src/style.css
Vibez based developement of the loading widget thing
> Sandbox Loading Widget

- packages/server/assets/workspacesCore/typedefs/workspaces.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/services/domains.ts
- packages/server/modules/workspaces/tests/unit/services/domains.spec.ts
- packages/server/test/graphql/generated/graphql.ts
- We have decided we like slugs more than ids
- Uses slug instead of id
> fix(workspaces): domain compliance by slug

- packages/ui-components/src/components/common/Badge.vue
> fix(ui-components): Update badgeColorClasses to check for color classes

- packages/server/modules/automate/services/trigger.ts
- packages/server/modules/automate/tests/trigger.spec.ts
- There's a technically-correct but hard to understand error when you try to trigger an automation with a model that has no version
- Changes it
> chore(automate): improve error message

- packages/frontend-2/components/form/select/SeatType.vue
- packages/frontend-2/components/form/select/WorkspaceRoles.vue
- packages/frontend-2/components/settings/workspaces/members/GuestsTable.vue
- packages/frontend-2/components/settings/workspaces/members/MembersTable.vue
- packages/frontend-2/components/settings/workspaces/members/TableSeatType.vue
- packages/frontend-2/components/settings/workspaces/members/actions/LeaveWorkspaceDialog.vue
- packages/frontend-2/components/settings/workspaces/members/actions/Menu.vue
- packages/frontend-2/components/settings/workspaces/members/actions/RemoveFromWorkspaceDialog.vue
- packages/frontend-2/components/settings/workspaces/members/actions/SeatTransitionCards.vue
- packages/frontend-2/components/settings/workspaces/members/actions/UpdateAdminDialog.vue
- packages/frontend-2/components/settings/workspaces/members/actions/UpdateSeatTypeDialog.vue
- packages/frontend-2/lib/settings/composables/menu.ts
- packages/frontend-2/lib/settings/helpers/constants.ts
- packages/frontend-2/lib/settings/helpers/types.ts
- packages/frontend-2/lib/workspaces/composables/plan.ts
- packages/ui-components/src/components/layout/tabs/Horizontal.vue
https://linear.app/speckle/issue/WEB-2946/update-things-in-member-settings
List compiled by Benjamin. Some items are blocked, I will come back to these.
> feat(fe): Update various workspace member settings items

- packages/fileimport-service/requirements.txt
> feat(fileimport): move back to previous python-util version

- packages/server/modules/core/graph/resolvers/versions.ts
- packages/server/modules/gatekeeper/index.ts
- packages/shared/src/environment/index.ts
> feat(gatekeeper): disable workspace plan migrations

- packages/frontend-2/lib/common/generated/gql/gql.ts
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/assets/workspacesCore/typedefs/permissions.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/graph/resolvers/permissions.ts
- packages/server/test/graphql/generated/graphql.ts
- packages/shared/src/authz/domain/context.ts
- packages/shared/src/authz/policies/project/canMoveToWorkspace.spec.ts
- packages/shared/src/authz/policies/project/canMoveToWorkspace.ts
- It's still useful to check if a project move to workspace is allowed even before we know the specific project we're trying to move.
- Allow optional project id
> fix(authz): allow optional project id

- packages/server/modules/auth/defaultApps.ts
> feat(auth): add worksapce read scope to desktop apps

- packages/frontend-2/components/project/page/models/StructureItem.vue
- packages/frontend-2/components/viewer/explorer/Filters.vue
- packages/frontend-2/components/viewer/explorer/NumericFilter.vue
- packages/frontend-2/components/viewer/explorer/StringFilter.vue
- packages/frontend-2/components/viewer/explorer/StringFilterItem.vue
- packages/frontend-2/lib/common/generated/gql/gql.ts
- packages/frontend-2/lib/common/generated/gql/graphql.ts
Should still work with longer lists, but I dont have a good model to test, will test on latest
> Feat: Add search for filter values

- packages/preview-service/readme.md
> chore(preview-service): update README

- packages/server/modules/gatekeeper/services/subscriptions/upgradeWorkspaceSubscription.ts
- packages/shared/src/core/helpers/error.ts
> fix(gatekeeper): fix yearly upgrade not working

- packages/server/modules/previews/resultListener.ts
> chore(server/logging): more metadata to preview consumption log

- packages/frontend-2/components/header/nav/Bar.vue
- packages/frontend-2/components/project/model-page/Header.vue
- packages/frontend-2/components/project/page/Header.vue
- packages/frontend-2/components/project/page/collaborators/Collaborators.vue
- packages/frontend-2/components/projects/Dashboard.vue
- packages/frontend-2/components/projects/ProjectDashboardCard.vue
- packages/frontend-2/components/viewer/PreSetupWrapper.vue
- packages/frontend-2/components/workspace/CreatePage.vue
- packages/frontend-2/components/workspace/ProjectList.vue
- packages/frontend-2/components/workspace/header/Header.vue
- packages/frontend-2/middleware/004-onboarding.global.ts
> Fix: FF cleanup and some smaller fixes

- packages/frontend-2/components/workspace/sidebar/Sidebar.vue
- packages/frontend-2/lib/common/generated/gql/gql.ts
- packages/frontend-2/lib/common/generated/gql/graphql.ts
> Feat: Add upgrade banner

- packages/frontend-2/components/pricingTable/Plan.vue
- packages/frontend-2/components/settings/workspaces/billing/addOns/AddOns.vue
- packages/frontend-2/components/settings/workspaces/billing/upgradeDialog/Summary.vue
- packages/frontend-2/components/settings/workspaces/billing/upgradeDialog/UpgradeDialog.vue
- packages/frontend-2/lib/workspaces/composables/activeWorkspace.ts
> Feat: Also show upgrade modal on free plans

- packages/frontend-2/components/billing/TransitionCards.vue
- packages/frontend-2/components/settings/workspaces/members/actions/SeatTransitionCards.vue
- packages/frontend-2/components/settings/workspaces/members/actions/UpdateAdminDialog.vue
- packages/frontend-2/components/settings/workspaces/members/actions/UpdateSeatTypeDialog.vue
Changes detailed here:
https://www.figma.com/design/CFVYfzYSyUdTVnrlFUEcUZ/Workspace-is-everything?node-id=2548-72517&m=dev
> feat(fe): updates to seat change and admin change modals

- packages/server/modules/gatekeeper/services/upgrades.ts
> fix(gatekeeper): fix subscription upgrades

- packages/shared/src/core/helpers/timeConstants.ts
> fix(shared): not using #lodash alias

- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/services/projects.ts
> fix(workspaces): use the correct new plan check and seat rules

- packages/frontend-2/components/header/nav/notifications/WorkspaceInvite.vue
- packages/frontend-2/lib/projects/composables/projectManagement.ts
- packages/frontend-2/lib/workspaces/composables/limits.ts
- packages/frontend-2/lib/workspaces/composables/management.ts
I will probably create some middleware for this on the workspace home and projects page, but this is a quick fix for now
> Fix: Update active workspace after accepting invite

- packages/server/modules/gatekeeper/graph/resolvers/index.ts
> fix(gatekeeper): only return available seats if there are some

- packages/frontend-2/components/pricingTable/Plan.vue
- packages/frontend-2/components/projects/Dashboard.vue
- packages/frontend-2/components/promo-banners/Workspace.vue
- packages/frontend-2/components/settings/workspaces/billing/Page.vue
- packages/frontend-2/components/settings/workspaces/billing/addOns/AddOns.vue
- packages/frontend-2/components/settings/workspaces/billing/addOns/Card.vue
- packages/frontend-2/components/settings/workspaces/billing/upgradeDialog/Summary.vue
- packages/shared/src/workspaces/helpers/features.ts
Various copy changes, mainly around billing. The commit history tells the changes.
There's more copy to update but I will do that in a [separate issue](https://linear.app/speckle/issue/WEB-3071/update-various-copy).
> Feat: Various copy updates

- packages/frontend-2/lib/settings/composables/menu.ts
- packages/server/modules/gatekeeper/rest/billing.ts
- packages/server/modules/gatekeeper/services/planMigration.ts
- packages/server/modules/multiregion/services/queue.ts
- packages/server/modules/shared/command.ts
- packages/server/modules/shared/helpers/dbHelper.ts
- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/rest/sso.ts
plus: fix for workspace new plan migration causing knex pool connection leak on failures
plus: fixed withTransaction API, the DX wasn't great
> fix(fe2): not being able to remove member from workspace

- packages/frontend-2/components/connectors/Card.vue
- packages/frontend-2/lib/dashboard/helpers/connectors.ts
This was merged as a hotfix, cherry-picked it for merging back
> Feat: Enable Blender connector download

- packages/viewer/src/modules/extensions/CameraController.ts
> fix(viewer-lib): Fixed '3d' canonical view

- packages/frontend-2/components/settings/workspaces/members/actions/RemoveFromWorkspaceDialog.vue
- packages/frontend-2/components/settings/workspaces/members/actions/UpdateAdminDialog.vue
- packages/frontend-2/components/settings/workspaces/members/actions/UpdateRoleDialog.vue
- packages/frontend-2/components/settings/workspaces/members/actions/UpdateSeatTypeDialog.vue
From testing - noticed this can take a while, so I added loading states.
> feat(fe): Add loading states to member update actions

- packages/frontend-2/lib/workspaces/composables/management.ts
This should be on all updates, not just when making admin
> fix(fe): Fix remove admin cache update

- packages/frontend-2/components/common/prose/GithubReadme.vue
- packages/frontend-2/lib/common/composables/markdown.ts
- packages/server/modules/automate/graph/mocks/automate.ts
Improve rendering of the function readme.
- Inline code styling with proper background, border, and padding
- Improved list formatting for both ordered and unordered lists
- Horizontal scrolling with custom scrollbar for code blocks
> feat(automate): improve font rendering in function readme

- packages/viewer/src/modules/converter/Geometry.ts
- packages/viewer/src/modules/tree/NodeRenderView.ts
Issue reported on the forum [here](https://speckle.community/t/bug-finding-valid-bounding-box/17612/4)
- The aabb is created only when not existing. This is to keep the different significance of having a null|undefined bounding box as opposed to an empty one
- `computeAABB` no longer nukes the aaabb if no position attribute exists on the render view
- `GeometryData`'s `attributes must hold a POSITION attribute if it exists
> fix(viewer-lib): Fixes to how render view bounding boxes are computed

- packages/server/modules/shared/utils/caching.ts
> fix(server): reduced cache layer logging noise

- packages/server/modules/core/authz/loaders/index.ts
- packages/shared/src/authz/domain/loaders.ts
- packages/shared/src/authz/domain/projects/operations.ts
- packages/shared/src/authz/fragments/workspaces.ts
- packages/shared/src/authz/policies/project/canMoveToWorkspace.spec.ts
- packages/shared/src/authz/policies/project/canMoveToWorkspace.ts
> fix(shared): canMoveToWorkspace should check model limits

- packages/server/modules/gatekeeper/services/subscriptions/upgradeWorkspaceSubscription.ts
It's something everyone should do tbh
> fix(billing): update db subcription expiry date on upgrade

- packages/frontend-2/components/project/page/collaborators/Collaborators.vue
- packages/frontend-2/components/project/page/collaborators/GeneralAccessRow.vue
- packages/frontend-2/components/settings/workspaces/members/GuestsTable.vue
- packages/frontend-2/components/settings/workspaces/members/MembersTable.vue
- packages/frontend-2/lib/projects/helpers/components.ts
Improving the copy in People settings and on the Collaborators page.
> Update copy in People settings and Collaborators page

- packages/frontend-2/middleware/004-onboarding.global.ts
It was not updated if you came from a direct URL
> Fix: Update workspace switcher in settings

- packages/server/modules/workspaces/events/eventListener.ts
We'd like this behavior to handle a frontend issue. But it's unclear how this change might affect other expected behavior (but tests look ok!).
cc @Mikehrn
> fix(authz): prevent workspace role downgrade while processing project invite

- packages/frontend-2/components/settings/workspaces/members/GuestsTable.vue
- packages/frontend-2/components/settings/workspaces/members/MembersTable.vue
- packages/frontend-2/components/settings/workspaces/members/actions/UpdateRoleDialog.vue
I'm still working on the new docs. I will add back the links later today when I'm done writing them.
> Remove links to docs until they're written

- packages/server/modules/gatekeeper/services/planMigration.ts
> fix(server): workspace migration failing for userless workspaces

- packages/dui3/components/model/CreateDialog.vue
- packages/dui3/components/project/create/PersonalDialog.vue
- packages/dui3/components/project/create/WorkspaceDialog.vue
Enable queries for app.speckle.systems
> Feat(dui3): workspaces post release

- packages/frontend-2/components/error/page/GenericUnauthorizedBlock.vue
Ill do a better fix later, but this will fix it for now
> Fix: update nav on goHome

- packages/server/modules/core/index.ts
- packages/server/modules/core/repositories/server.ts
> fix(server): not caching serverInfo to redis

- packages/dui3/lib/bridge/server.ts
To speed up the receive process.
We have now another functionality that calls desktop service for gsm converter.
> Feat(dui3): archicad receieve by desktop service

- packages/frontend-2/components/viewer/anchored-point/thread/Comment.vue
This allows for empty comments being submitted with an attachment.
> fix(fe): Fix isLimited condition for comments

- packages/server/assets/gatekeeperCore/typedefs/gatekeeper.graphql
> feat(server): allow ws sub info to members

- packages/server/assets/core/typedefs/projects.graphql
- packages/server/modules/core/domain/streams/operations.ts
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/core/graph/resolvers/projects.ts
- packages/server/modules/core/repositories/streams.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/tests/integration/projects.graph.spec.ts
- packages/server/test/graphql/generated/graphql.ts
> feat(server): allow activeUser.query to retrieve implicitly accessible projects

- packages/server/assets/workspacesCore/typedefs/projects.graphql
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/graph/dataloaders/workspaces.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/repositories/workspaces.ts
- packages/server/modules/workspacesCore/graph/resolvers/workspacesCore.ts
- packages/server/test/graphql/generated/graphql.ts
> feat(server): ProjectCollaborator.workspaceRole

- packages/frontend-2/components/projects/ProjectDashboardCard.vue
Feedback from Mirna to remove the ... from the "Move project..." button.
> Remove ... from move button

- packages/frontend-2/components/pricingTable/Addon.vue
- packages/frontend-2/components/pricingTable/Plan.vue
- packages/frontend-2/components/workspace/wizard/step/Pricing.vue
> feat(fe): Add addon cards to workspace wizard plan selection page

- packages/frontend-2/components/project/page/collaborators/GeneralAccess.vue
- packages/frontend-2/components/project/page/collaborators/Row.vue
@benjaminvo Can you test the label alignment on your browser once this is released?
> Fix: Minor project collaborator fixes

- packages/server/modules/shared/authz.ts
> fix(server): blob read should not require write scope

- packages/frontend-2/components/pricingTable/Plan.vue
- packages/frontend-2/components/workspace/wizard/Wizard.vue
- packages/frontend-2/components/workspace/wizard/step/AddOns.vue
- packages/frontend-2/lib/workspaces/composables/wizard.ts
- packages/frontend-2/lib/workspaces/helpers/types.ts
> Feat: Add unlimited add on step in creation wizard

- packages/frontend-2/pages/workspaces/[slug]/index.vue
Minor class changes to paddings to align a bit better, there is a large padding at the bottom that is not needed
> Fix: Workspace dashboard padding update

- packages/server/modules/blobstorage/index.ts
- packages/server/modules/blobstorage/tests/blobstorage.integration.spec.ts
- packages/server/modules/fileuploads/rest/routes.ts
- packages/server/modules/shared/authz.ts
> tests(integration/blobs): can anonymously get blob from public project

- packages/frontend-2/components/invite/dialog/project/Project.vue
- packages/frontend-2/components/invite/dialog/project/Row.vue
- packages/frontend-2/components/invite/dialog/shared/SelectUsers.vue
- packages/frontend-2/lib/invites/helpers/helpers.ts
@benjaminvo After some thinking, I thought of a way to handle the pasted input rather than making it a seperate flow. It allows you to paste a list of emails in any input (it will perserve other input you already have), parse the list and get all valid emails from it
> Feat: Bulk invites for projects and workspaces

- .circleci/config.yml
Introduce aliases for images etc, for easy changing options between jobs etc
> CI(config): introduce aliases

- packages/viewer/src/modules/extensions/FilteringExtension.ts
Fixes an issue with isolating when providing non atomic object ids.
> fix(viewer-lib): Possible fix for isolating with non atomic ids provided

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleGeometryConverter.ts
> chore(viewer-lib): Enabled usage of text v3. Temporary passthrough

- packages/server/modules/core/dbSchema.ts
- packages/server/modules/serverinvites/domain/operations.ts
- packages/server/modules/serverinvites/domain/types.ts
- packages/server/modules/serverinvites/graph/resolvers/serverInvites.ts
- packages/server/modules/serverinvites/repositories/serverInvites.ts
- packages/server/modules/serverinvites/services/creation.ts
- packages/server/modules/serverinvites/services/operations.ts
- packages/server/modules/serverinvites/services/processing.ts
- packages/server/modules/serverinvites/services/projectInviteManagement.ts
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/domain/types.ts
- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/repositories/projects.ts
- packages/server/modules/workspaces/repositories/workspaces.ts
- packages/server/modules/workspaces/services/invites.ts
- packages/server/modules/workspaces/tests/helpers/creation.ts
- packages/server/modules/workspaces/tests/integration/invites.graph.spec.ts
Reverts specklesystems/speckle-server#4634
> Revert "feat(server): workspace project invites as implicit workspace invites"

- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/services/projectRegions.ts
- Caught a failure on moving a project to a region. Leading theory but not enough information available to confirm.
- Log resource counts during final move confirmation
> fix(multiregion): more logs for move region failure

- packages/server/modules/core/dbSchema.ts
- packages/server/modules/serverinvites/domain/operations.ts
- packages/server/modules/serverinvites/domain/types.ts
- packages/server/modules/serverinvites/graph/resolvers/serverInvites.ts
- packages/server/modules/serverinvites/repositories/serverInvites.ts
- packages/server/modules/serverinvites/services/creation.ts
- packages/server/modules/serverinvites/services/operations.ts
- packages/server/modules/serverinvites/services/processing.ts
- packages/server/modules/serverinvites/services/projectInviteManagement.ts
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/domain/types.ts
- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/repositories/projects.ts
- packages/server/modules/workspaces/repositories/workspaces.ts
- packages/server/modules/workspaces/services/invites.ts
- packages/server/modules/workspaces/tests/helpers/creation.ts
- packages/server/modules/workspaces/tests/integration/invites.graph.spec.ts
Reverts specklesystems/speckle-server#4671
> Revert "Revert "feat(server): workspace project invites as implicit workspace invites""

- packages/server/modules/multiregion/services/queue.ts
For completeness - added some logs for when the multiregion job completes successfully.
> chore(multiregion): job success logs

- .circleci/config.yml
Executing without cache might be faster than using the cache all the time.
> feat(ci): 3249 remove yarn cache

- packages/shared/src/environment/multiRegionConfig.ts
> fix(shared): support busted knex typing in node16 moduleResolution

- .devcontainer/postCreateCommand.sh
- .gitguardian.yml
- packages/dui3/.env.example
- packages/fileimport-service/.env.example
- packages/frontend-2/.env.example
- packages/monitor-deployment/.env.example
- packages/preview-service/.env.example
- packages/server/.env.example
- packages/server/readme.md
- packages/shared/src/observability/index.ts
- workspace.code-workspace
> fix: disable pino-pretty in inspector to avoid freezes

- package.json
- packages/frontend-2/package.json
- yarn.lock
> feat: update datadog cli to hopefully fix node22 issue in ci

- .circleci/config.yml
> chore: vuln scan increased resources to fix memory issue

- packages/viewer/src/modules/pipeline/Passes/DepthNormalPass.ts
- packages/viewer/src/modules/pipeline/Pipelines/EdgesPipeline.ts
- Outlines of hidden objects are no longer visible
Before:
After:
> Hidden objects outlines fix

- packages/dui3/tailwind.config.mjs
- packages/tailwind-theme/README.md
- packages/tailwind-theme/src/index.ts
- packages/tailwind-theme/src/plugin.ts
- packages/tailwind-theme/src/preset.ts
- packages/ui-components/tailwind.config.cjs
> fix(tailwind-theme): remove default exports to fix comp w/ dui3

- .circleci/config.yml
> chore(config): Increased publish-npm step resource size to 'large'

- packages/server/modules/gatekeeper/graph/resolvers/index.ts
> fix(server): we should default to a viewer seat in the rare cases of no seat assigned to the user

- packages/objectloader2/src/operations/downloaders/__snapshots__/serverDownloader.spec.ts.snap
- packages/objectloader2/src/operations/downloaders/serverDownloader.spec.ts
- packages/objectloader2/src/operations/downloaders/serverDownloader.ts
> try allocating fewer strings

- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/graph/resolvers/workspaceJoinRequests.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/rest/sso.ts
- packages/server/modules/workspaces/services/invites.ts
- packages/server/modules/workspaces/services/join.ts
- packages/server/modules/workspaces/services/management.ts
- packages/server/modules/workspaces/services/projects.ts
- packages/server/modules/workspaces/services/sso.ts
- packages/server/modules/workspaces/services/workspaceJoinRequests.ts
- packages/server/modules/workspaces/services/workspaceSeat.ts
- packages/server/modules/workspaces/tests/helpers/creation.ts
- packages/server/modules/workspaces/tests/integration/workspaceJoinRequests.spec.ts
- packages/server/modules/workspaces/tests/unit/services/join.spec.ts
- packages/server/modules/workspaces/tests/unit/services/management.spec.ts
- packages/server/modules/workspaces/tests/unit/services/sso.spec.ts
- packages/server/modules/workspacesCore/migrations/20250514092509_add_missing_seats.ts
> fix(server): seats sometimes not created on role create

- packages/frontend-2/components/form/json/Form.vue
- packages/frontend-2/package.json
- yarn.lock
- #4728 fixed but incorrectly diagnosed a problem with ajv types
- TIL `yarn dedupe`
- `yarn dedupe ajv`
> chore(deps): dedupe ajv

- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/events/eventListener.ts
- packages/server/modules/workspaces/repositories/workspaces.ts
Enhanced metrics around info push for mixpanel 
Added counts around:
- projects
- models
- editors 
- viewers 
on a workspace level and unified undefined values as null
> feat(workspaces): mixpanel update more attributes

- packages/server/modules/core/helpers/types.ts
- packages/server/modules/core/migrations/20250514125149_remove_streams_ispublic_isdiscoverable.ts
- packages/server/modules/core/services/projects.ts
- packages/server/modules/core/tests/integration/projectRepositories.spec.ts
- packages/server/modules/notifications/tests/activityDigest.spec.ts
post visibility migration cleanup
> chore(server): remove unused stream isPublic/isDiscoverable fields

- packages/server/modules/gatekeeper/graph/resolvers/index.ts
- packages/server/modules/gatekeeper/services/checkout/startCheckoutSession.ts
- packages/server/modules/gatekeeper/services/subscriptions/manageSubscriptionDownscale.ts
- packages/server/modules/gatekeeper/services/subscriptions/upgradeWorkspaceSubscription.ts
- packages/server/modules/workspaces/services/projects.ts
- packages/server/modules/workspaces/services/workspaceSeat.ts
- packages/server/modules/workspaces/tests/integration/workspaceSeat.spec.ts
- packages/server/modules/workspaces/tests/integration/workspaces.graph.spec.ts
- packages/server/modules/workspaces/tests/unit/services/management.spec.ts
- packages/server/modules/workspaces/tests/unit/services/projects.spec.ts
- packages/server/modules/workspaces/tests/unit/services/workspaceSeat.spec.ts
> fix(server): fallback to viewer if no seat found

- packages/viewer-sandbox/src/Sandbox.ts
- packages/viewer/src/modules/pipeline/Passes/EdgesPass.ts
- packages/viewer/src/modules/pipeline/Pipelines/EdgesPipeline.ts
- packages/viewer/src/modules/pipeline/Pipelines/PenViewPipeline.ts
> fix(viewer-lib): Outline opacity is now correctly applied

- packages/server/modules/fileuploads/domain/operations.ts
- packages/server/modules/fileuploads/migrations/20250514131509_add_modelId_foreign_to_file_uploads.ts
- packages/server/modules/fileuploads/repositories/fileUploads.ts
- packages/server/modules/fileuploads/rest/nextGenRouter.ts
- packages/server/modules/fileuploads/services/management.ts
- packages/server/modules/fileuploads/tests/integration/fileuploadsV2.spec.ts
- Fixing an issue around the nextGen file upload @deprecated field in branchname propagating to frontend, now is set to the modelName, and answered as is to FE to keep consistency
- Added fk to file_uploads modelId
> fix(fileimport): nextGen fileimport improvements

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleConverter.ts
Rendermaterial proxies can reference parents of instance data which will not be the parents of the actual instances, meaning the instances cannot naturally inherit the render materials. This PR bakes rendermaterial data into instance data at convert time
**Before:**
**After:**
> fix(viewer-lib): Fixes WEB-3432

- packages/frontend-2/components/dashboard/Promo.vue
- packages/frontend-2/components/dashboard/Sidebar.vue
> feat(fe): sidebar promo banner for specklecon

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/extensions/ViewModes.ts
- packages/viewer/src/modules/pipeline/Passes/ShadedPass.ts
The view modes extension now automatically computes a relative size depth bias and applies it to the edge passes
**Before:**
**After:**
> Relative depth bias for outlines

- packages/viewer/src/modules/loaders/Speckle/SpeckleLoader.ts
> fix(viewer-lib): Loader disposes of the object loader correctly

- packages/objectloader2/src/helpers/cachePump.spec.ts
- packages/objectloader2/src/helpers/cacheReader.spec.ts
- packages/objectloader2/src/operations/downloaders/serverDownloader.spec.ts
- packages/objectloader2/src/operations/downloaders/serverDownloader.ts
> fix serverDownloader disposal.  Correct linting errors

- packages/frontend-2/lib/viewer/composables/setup/postSetup.ts
- packages/viewer-sandbox/src/Sandbox.ts
- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/index.ts
- packages/viewer/src/modules/extensions/ExplodeExtension.ts
Section outlines are now synced when exploding
**Before:**
https://github.com/user-attachments/assets/33053b89-18ea-450d-a45f-9eb17808940c
**After:**
https://github.com/user-attachments/assets/02603905-04d1-4e8c-9cd9-6abfff300a1f
> Explode + Outlines

- packages/server/modules/gatekeeper/graph/resolvers/index.ts
> fix(embed): use correct id

- README.md
We recently (https://github.com/specklesystems/speckle-server/pull/4793) updated `yarn build:public` command to include additional steps (these were formerly `yarn` postinstall steps).
This PR updates the README to include `yarn build:public` which is now required.
> docs(README): include additional postinstall instruction in README

- utils/helm/speckle-server/templates/fileimport_service/deployment.yml
- utils/helm/speckle-server/templates/fileimport_service/serviceaccount.yml
> fix(fileimports): missing redis url from env vars

- packages/viewer-sandbox/src/main.ts
> fix(sandbox): Load a valid stream

- packages/frontend-2/components/viewer/PreSetupWrapper.vue
use loadedVersion for limits dialog and improve resource string handling
> fix(fe): use loadedVersion for limits dialog and improve resource string handling

- packages/frontend-2/components/projects/MoveToWorkspaceAlert.vue
- packages/frontend-2/components/viewer/resources/PersonalLimitAlert.vue
> feat(frontend): more personal project limits copy changes

- codecov.yml
> chore(codecov): relax threshold

- packages/objectloader2/.npmignore
> fix(objectloader2): stop excluding build from package

- packages/objectloader2/src/helpers/cachePump.disposal.spec.ts
- packages/objectloader2/src/helpers/cachePump.spec.ts
- packages/objectloader2/src/helpers/cachePump.ts
- packages/objectloader2/src/operations/objectLoader2.ts
Should stop the write loop when dispose is called
> fix (OL2): Dispose pump inline with the rest when disposing to kill loop

- packages/objectloader2/src/index.ts
- packages/objectloader2/src/operations/objectLoader2Factory.ts
Should allow external people to use memory database
> Add createFromUrl that can use memory database

- packages/frontend-2/lib/dashboard/helpers/connectors.ts
Updates the links to connector docs in the connector download page.
> Fix: Update docs links to connectors

- packages/frontend-2/components/settings/ConfirmDialog.vue
- packages/frontend-2/pages/settings/workspaces/[slug]/security.vue
Added a new Settings confirmation dialog that can be used in various settings.
> feat(fe): Add generic settings confirm dialog

- packages/frontend-2/lib/billing/helpers/plan.ts
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/server/assets/gatekeeperCore/typedefs/gatekeeper.graphql
- packages/server/modules/cli/commands/workspaces/set-plan.ts
- packages/server/modules/core/graph/generated/graphql.ts
- packages/server/modules/cross-server-sync/graph/generated/graphql.ts
- packages/server/modules/gatekeeper/graph/resolvers/index.ts
- packages/server/modules/gatekeeper/services/subscriptions.ts
- packages/server/modules/gatekeeper/services/subscriptions/manageSubscriptionDownscale.ts
- packages/server/modules/gatekeeper/services/subscriptions/upgradeWorkspaceSubscription.ts
- packages/server/modules/gatekeeper/services/upgrades.ts
- packages/server/modules/gatekeeper/services/workspacePlans.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/test/graphql/generated/graphql.ts
- packages/shared/src/workspaces/helpers/features.ts
- packages/shared/src/workspaces/helpers/plans.spec.ts
- packages/shared/src/workspaces/helpers/plans.ts
introduces a new workspace plan that will have more features than anyone else
> feat(gatekeeper): intoduce the enterprise plan

- .circleci/config.yml
- ignore circleci in all actions
> feat(ci): disable circle ci

- packages/frontend-2/components/project/CardImportFileArea.vue
- packages/frontend-2/components/project/page/models/NewDialog.vue
- packages/frontend-2/lib/core/api/fileImport.ts
- packages/frontend-2/lib/core/composables/fileImport.ts
- packages/server/modules/fileuploads/domain/operations.ts
- packages/server/modules/fileuploads/index.ts
- packages/server/modules/fileuploads/repositories/fileUploads.ts
- packages/server/modules/fileuploads/rest/router.ts
- packages/server/modules/fileuploads/services/resultListener.ts
@iainsproat moved to creating model beforehand like you suggested
> fix: create model before uploading file

- packages/frontend-2/components/header/WorkspaceSwitcher/WorkspaceSwitcher.vue
- packages/frontend-2/components/header/nav/notifications/Notifications.vue
> fix(fe2): implicit workspace invite fixes

- .github/workflows/builds.yml
> fix: bump the machine

- packages/server/modules/gatekeeper/clients/stripe.ts
- packages/server/modules/gatekeeper/index.ts
- packages/server/modules/gatekeeper/services/subscriptions/manageSubscriptionDownscale.ts
- packages/server/modules/gatekeeper/tests/unit/subscriptions.spec.ts
> fix(gatekeeper): removed duplicated event

- packages/frontend-2/components/automate/function/CreateDialog.vue
- Automate repo-org association logic is correct, but FE did not provide the value if selected
- Does so
Testable on testing2
> fix(automate): include selected org when making a function

- packages/fileimport-service/src/controller/daemon.ts
- packages/server/knexfile.ts
- packages/server/modules/core/utils/dbNotificationListener.ts
- packages/server/modules/multiregion/domain/types.ts
- packages/server/modules/multiregion/regionConfig.ts
- packages/server/modules/multiregion/utils/blobStorageSelector.ts
- packages/server/modules/multiregion/utils/regionSelector.ts
- packages/shared/package.json
- packages/shared/src/environment/db.ts
- packages/shared/src/package.json
> chore: log listen/notify connection strings

- packages/server/modules/core/utils/dbNotificationListener.ts
> fix(server): shouldnt use main region config if FF off

- packages/viewer/src/modules/Shadowcatcher.ts
Disabled shadowcatcher depth writing
> WEB-1717: Text and Shadowcatcher 🛸 blending fix

- packages/server/Dockerfile
> fix(server/dockerfile): bump node version to 22

- packages/server/modules/gatekeeper/clients/checkout/createCheckoutSession.ts
short change to allow companies adding the VAT number during checkout
> feat(billing): allow tax id collection during checkout

- packages/server/modules/auth/services/serverApps.ts
> chore(tokens): small cleanup of error message

- packages/frontend-2/components/project/page/models/Actions.vue
- packages/shared/src/blobs/index.ts
- packages/ui-components/src/components/form/select/Base.vue
- packages/ui-components/src/components/layout/Menu.stories.ts
- packages/ui-components/src/components/layout/Menu.vue
- packages/ui-components/src/composables/layout/menu.ts
> feat(ui-components): proper LayoutMenu mount on body support + fixes

- packages/fileimport-service/Dockerfile
- packages/fileimport-service/requirements.txt
> feat(ifc): bump ifc deps

- packages/frontend-2/components/error/page/GenericErrorBlock.vue
- packages/frontend-2/components/error/page/Renderer.vue
- packages/frontend-2/lib/auth/composables/auth.ts
- packages/frontend-2/pages/error.vue
> feat(fe2): improved auth error logging

- packages/frontend-2/components/header/nav/UserMenu.vue
- packages/frontend-2/layouts/loginOrRegister.vue
- packages/frontend-2/lib/core/composables/error.ts
Copies this into the users clipboard (For sharing w/ us):
```
Reference: #q1Eskz4wjtpZRvJAS4zAr | #1f714efd-b6e1-496e-8adf-46ceebc5ef48 | 2025-07-16T14:03:41.157Z | URL: http://localhost:8081/workspaces/fabiano | Ref ID: fe-error-8TZkJ1CLi532RGtExa27r | User ID: 3503a7af62
```
> feat(fe2): more accessible error reference

- .github/workflows/tests.yml
On ci failure preview-service uploads logs as artifacts
> feat(ci): upload logs on failure

- packages/server/package.json
- yarn.lock
old version has been failing to install for the preview service. lets see if this works
> chore(server): bump sharp to fix CI

- packages/frontend-2/lib/core/composables/error.ts
- packages/server/observability/components/knex/knexMonitoring.ts
> feat: a couple of logging improvements

- packages/objectloader2/src/core/objectLoader2.ts
- packages/objectloader2/src/deferment/MemoryCache.ts
MemoryCache wasn't disposing and not stopping the clean up timer
> OL2 (fix) dispose cache as it should

- packages/server/modules/core/graph/resolvers/users.ts
- packages/server/modules/core/migrations/20250722150843_lowercaseify_all_user_emails.ts
- packages/server/modules/workspaces/services/management.ts
> fix(server): incorrectly dealing w/ different email casing

- packages/server/modules/gatekeeper/clients/checkout/createCheckoutSession.ts
> feat(gatekeeper): update stripe checkout session params for anrok

- packages/server/assets/core/typedefs/modelsAndVersions.graphql
this unblocks the metrics report of the PowerBi connector
> feat(versions): allow markingReceived for versions with a streams:read

- packages/ifc-import-service/pyproject.toml
- packages/ifc-import-service/uv.lock
- utils/helm/speckle-server/templates/_helpers.tpl
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
> feat(helm): add the rhino file importer feature flag to the chart

- packages/ifc-import-service/uv.lock
> fix(ifc-importer): need to lock packages

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/batching/Batcher.ts
- packages/viewer/src/modules/batching/MeshBatch.ts
- packages/viewer/src/modules/converter/Geometry.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleGeometryConverter.ts
- packages/viewer/src/modules/materials/shaders/speckle-basic-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-depth-normal-id-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-depth-normal-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-displace.vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-ghost-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-normal-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-standard-colored-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-standard-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-text-vert.ts
- packages/viewer/src/modules/materials/shaders/speckle-viewport-vert.ts
Instances that have negative scaling transforms now flip their normals either in the shader when instanced rendering, either when building the mesh batch if demoted from instanced rendering by the batcher
> WEB-3947-Mirrored-Instances-Normals-Fix

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/batching/Batcher.ts
- packages/viewer/src/modules/materials/Materials.ts
Fixes [WEB-3853: Color Proxies for Text](https://linear.app/speckle/issue/WEB-3853/color-proxies-for-text)
> chore(viewer-lib): Text color proxies

- packages/viewer/src/modules/pipeline/Pipelines/ShadedViewPipeline.ts
Fixes  [WEB-3487: Shaded Mode Shows Outlines of Hidden Objects](https://linear.app/speckle/issue/WEB-3487/shaded-mode-shows-outlines-of-hidden-objects)
> fix(viewer-lib): Shaded Mode no longer shows outlines of hidden objects

- packages/shared/src/environment/index.spec.ts
- packages/shared/src/environment/index.ts
- utils/helm/speckle-server/values.schema.json
- utils/helm/speckle-server/values.yaml
> fix(shared): parseFeatureFlags should ignore empty string values

- packages/viewer/src/modules/extensions/measurements/MeasurementsExtension.ts
> fix(viewer-lib): Measurements should now work better on touchscreens

- packages/frontend-2/package.json
- yarn.lock
> chore(fe): Update Lucide library version

- packages/server/modules/acc/domain/constants.ts
- packages/server/modules/automate/services/tracking.ts
- Function had to be updated to reflect changes in API
- Error demoted to warning is only in a path used to fetch emails for logging. It's ok not to find the email (and was causing trouble with the function)
> chore(acc): bump acc importer function

- packages/frontend-2/components/automate/viewer/Panel.vue
- packages/frontend-2/components/viewer/layout/SidePanel.vue
Remove wrapper div causing overflow issues. 
Add simple-scrollbar to this panel
> fix(fe): Automate panel scroll

- packages/frontend-2/lib/viewer/composables/activity.ts
**30s debounced disconnect**
Window unfocus now waits 30 seconds before showing "left" notification
**Instant disconnect on close**
Browser close/navigation still triggers immediate disconnect
**Multi-tab notification fix**
No duplicate join/leave messages when same user has multiple tabs open
**Smart session tracking**
Only shows "left" when user's last session disconnects, "joined" only for genuinely new users
> refactor(fe): viewer activity improvements

- packages/frontend-2/components/header/nav/Bar.vue
> fix(fe): Workspace switcher nav bar alignment

- packages/frontend-2/components/viewer/controls/Bottom.vue
> refactor(fe): Update explode tooltip text

- packages/server/modules/acc/domain/constants.ts
> chore(acc): bump importer function version

- packages/frontend-2/nuxt.config.ts
- packages/frontend-2/public/robots.txt
https://discord.com/channels/726756379083145269/1405128660695908402
> chore: fe2 disable search indexing

- packages/frontend-2/components/viewer/saved-views/panel/View.vue
- packages/frontend-2/components/viewer/saved-views/panel/views/group/Inner.vue
> feat(fe): styling of empty group span and v-tippy position

- packages/frontend-2/lib/viewer/composables/activity.ts
- packages/server/modules/comments/graph/resolvers/comments.ts
- packages/server/modules/shared/utils/subscriptions.ts
> fix: various activity broadcast issues

- packages/frontend-2/components/viewer/saved-views/panel/View.vue
> fix(fe2): disable set as home view if private view

- packages/frontend-2/components/preview/Image.vue
- packages/frontend-2/lib/auth/errors/errors.ts
- packages/frontend-2/lib/automate/errors/automations.ts
- packages/frontend-2/lib/core/api/blobStorage.ts
- packages/frontend-2/lib/core/configs/apollo.ts
- packages/frontend-2/lib/core/errors/base.ts
- packages/frontend-2/lib/core/helpers/observability.ts
- packages/frontend-2/lib/projects/composables/previewImage.ts
- packages/frontend-2/lib/viewer/extensions/PassReader.ts
- packages/frontend-2/nuxt.config.ts
- packages/frontend-2/plugins/010-logger.ts
- packages/frontend-2/server/lib/core/helpers/observability.ts
- packages/preview-service/src/jobProcessor.ts
- yarn.lock
> fix(fe2): more fixes and performance improvements

- packages/frontend-2/pages/verify-email.vue
> feat(fe2): error reference copy on email verify page

- packages/frontend-2/composables/logging.ts
- packages/frontend-2/lib/auth/composables/auth.ts
- packages/frontend-2/lib/common/composables/async.ts
- packages/frontend-2/lib/common/helpers/debugging.ts
- packages/frontend-2/lib/common/helpers/graphql.ts
- packages/frontend-2/lib/common/helpers/route.ts
- packages/frontend-2/lib/viewer/composables/setup/embed.ts
useLogger() shouldnt be used in scopes where we aren't sure if useNuxtApp() is available
> fix(fe2): nuxt state being missing in some cases

- packages/frontend-2/components/preview/Image.vue
> fix(fe2): another attempt at fixing preview img hydration mismatches

- packages/frontend-2/components/header/nav/notifications/ProjectInvite.vue
- packages/frontend-2/lib/projects/composables/projectManagement.ts
- packages/frontend-2/lib/workspaces/composables/management.ts
> fix(fe2): project invite decline bugs

- packages/frontend-2/Dockerfile
> chore(fe2): disable prod verbose mismatch logging

- packages/frontend-2/lib/core/configs/apollo.ts
We are having slowdowns on FE. Testing to see if this is the culprit.
> fix(fe): comment batchhttplink code to troubleshoot performance issues

- .github/workflows/builds.yml
- .github/workflows/get-version.yml
- .github/workflows/manual-trigger-test-deployment.yml
- .github/workflows/npm.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
- packages/fileimport-service/Dockerfile
- packages/preview-service/Dockerfile
https://github.com/useblacksmith/build-push-action/releases/tag/v2
> chore: bumb blacksmith build and push action version

- packages/server/modules/viewer/domain/operations/savedViews.ts
- packages/server/modules/viewer/repositories/savedViews.ts
- packages/server/modules/viewer/services/savedViewsManagement.ts
- packages/server/modules/viewer/tests/integration/savedViewsCrud.graph.spec.ts
> feat(server): savedView.updatedAt prevent change on visibility update

- utils/helm/speckle-server/templates/_helpers.tpl
> fix(helm): use correct casing for sso flag value

- packages/frontend-2/components/project/page/models/Tab.vue
Reverts specklesystems/speckle-server#5259
> Revert "Always support drag and drop in the Models panel "

- packages/frontend-2/components/project/CardImportFileArea.vue
> fix(frontend): missing ifc file type when rhino importer is enabled

- packages/frontend-2/components/viewer/controls/Left.vue
- packages/frontend-2/components/viewer/selection/KeyValuePair.vue
- packages/frontend-2/lib/viewer/composables/setup.ts
- packages/frontend-2/lib/viewer/composables/setup/panels.ts
- packages/frontend-2/lib/viewer/helpers/sceneExplorer.ts
> fix(fe2): prevent filters tab open on property filter state apply

- packages/frontend-2/components/viewer/saved-views/panel/Groups.vue
- packages/frontend-2/components/viewer/saved-views/panel/views/Group.vue
- packages/frontend-2/lib/viewer/helpers/savedViews/cache.ts
- packages/server/modules/viewer/errors/savedViews.ts
- packages/server/modules/viewer/services/savedViewsManagement.ts
- packages/server/modules/viewer/tests/integration/savedViewsCrud.graph.spec.ts
> feat: show ungrouped saved view group as disclosure

- packages/frontend-2/components/dashboard/Sidebar.vue
Update link to Changelog from the product sidebar
> Fix: Update changelog link

- packages/viewer/src/modules/extensions/CameraController.ts
Fixes https://linear.app/speckle/issue/WEB-4136/glitchy-edges-when-loading-a-home-view
https://github.com/user-attachments/assets/dc9ccc00-cc92-4731-a812-4cdc4521bcf0
https://github.com/user-attachments/assets/7efad2d6-9266-4d0b-8ead-9a654d5ea76e
> Home View Glitch Fix

- yarn.lock
> chore: fix various ui-components build related vulns

- yarn.lock
> chore: vite vuln bump

- packages/frontend-2/lib/viewer/composables/filtering/filtering.ts
- packages/frontend-2/lib/viewer/composables/serialization.ts
- packages/server/modules/comments/services/data.ts
- packages/server/modules/core/graph/generated/graphql.ts
- packages/shared/src/viewer/helpers/state.spec.ts
- packages/shared/src/viewer/helpers/state.ts
> feat(fe2): filter color serialization

- packages/frontend-2/components/automate/viewer/panel/FunctionRunRowObjectResult.vue
FunctionRunRowObjectResult.vue
- Colourise gradient results by default
- Fix isolation
> fix(fe): automate results refactor

- .github/workflows/deployment-tests.yml
- .github/workflows/release.yml
- tests/deployment/helm/values/minio.values.yaml
- tests/deployment/helm/values/postgres.values.yaml
- tests/deployment/helm/values/valkey.values.yaml
github.com/bitnami/charts/issues/35164
> ci(deployment test): bitnami helm charts should now use bitnamilegacy image repository

- packages/viewer-sandbox/src/main.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleConverter.ts
> fix(viewer-lib): Added support for non directly displayable objects as instances

- packages/server/modules/viewer/errors/savedViews.ts
- packages/server/modules/viewer/graph/resolvers/savedViews.ts
- packages/server/modules/viewer/repositories/savedViews.ts
- packages/server/modules/viewer/tests/integration/savedViewsCrud.graph.spec.ts
> fix(server): a couple of saved views positioning fixes

- packages/server/modules/auth/domain/const.ts
- packages/server/modules/auth/services/passportService.ts
- packages/server/modules/auth/strategies/google.ts
do not allow signups with gmail accounts
> block gmail signups

- package.json
- yarn.lock
> chore: bump form-data to 4.0.4

- yarn.lock
> chore: bump koa to 2.16.2

- yarn.lock
> chore: bump devalue to 5.3.2

- utils/helm/speckle-server/templates/_helpers.tpl
fix no private email featureflag in the helm chart
> fix(helm): server was incorrectly referencing the featureflat and was

- .github/workflows/release.yml
- packages/objectloader2/src/core/objectLoader2.spec.ts
- packages/objectloader2/src/core/stages/cacheReader.spec.ts
- packages/objectloader2/src/core/stages/cacheWriter.spec.ts
- packages/objectloader2/src/core/stages/serverDownloader.spec.ts
- packages/objectloader2/src/deferment/defermentManager.test.ts
- packages/objectloader2/src/queues/batchingQueue.dispose.test.ts
- packages/objectloader2/src/queues/batchingQueue.test.ts
- packages/objectloader2/src/queues/batchingQueue.ts
replaces https://github.com/specklesystems/speckle-server/pull/5558
> OL2 (fix) Fixes tests and batchingqueue during exceptions and adds isErrored concept to drain

- packages/frontend-2/components/automate/viewer/panel/FunctionRunRowObjectResult.vue
Adding logs to see what's going on with the automate result rows.
> debug(fe): add debug logs to automate row results

- packages/frontend-2/lib/viewer/composables/setup/coloring.ts
When multiple numeric filters were applied and coloring was enabled on one filter, previously filtered objects would reappear with colors. This happened because the coloring logic only considered the colored filter's range, ignoring other active filters.
Modified `setNumericColorFilter` to only color objects that are in the final filtered set (intersection of all active filters).
> fix(fe): ensure numeric filter coloring respects all active filters

- .github/workflows/tests.yml
- packages/server/package.json
- yarn.lock
Debugging CI errors with apolo rover, and bumped the version
> feat: add debug, bumped rover version

- packages/frontend-2/components/viewer/saved-views/panel/view/EditDialog.vue
- packages/frontend-2/plugins/eventBus.ts
> fix(fe2): saved view edit dialog broken

- packages/frontend-2/lib/viewer/composables/savedViews/subscriptions.ts
> fix(fe2): views not showing up ungrouped after group delete

- packages/server/modules/activitystream/domain/types.ts
- packages/server/modules/activitystream/events/workspaceListeners.ts
- packages/server/modules/workspaces/domain/operations.ts
- packages/server/modules/workspaces/graph/resolvers/workspaces.ts
- packages/server/modules/workspaces/repositories/workspaces.ts
- packages/server/modules/workspaces/services/management.ts
- packages/server/modules/workspaces/services/workspaceCreationState.ts
- packages/server/modules/workspaces/tests/integration/repositories.spec.ts
- packages/server/modules/workspaces/tests/unit/events/eventListener.spec.ts
- packages/server/modules/workspacesCore/domain/events.ts
Workspace delete is recorded in activity for clearer history
> feat(activity): record delete workspace activity

- packages/frontend-2/lib/common/composables/dom.ts
- packages/frontend-2/package.json
- yarn.lock
> chore: bump dompurify to fix xss vuln

- packages/frontend-2/pages/workspaces/[slug]/dashboards/[id].vue
- packages/frontend-2/plugins/intercom.client.ts
> Feat: Open dashboards in edit mode

- packages/frontend-2/components/presentation/PageWrapper.vue
- packages/frontend-2/components/presentation/viewer/Setup.vue
- packages/frontend-2/components/presentation/viewer/Wrapper.vue
- packages/frontend-2/lib/common/generated/gql/graphql.ts
- packages/frontend-2/lib/viewer/composables/setup.ts
- packages/frontend-2/lib/viewer/composables/setup/postSetup.ts
> fix(fe2): flashing loader on federated presentation load

- packages/frontend-2/lib/viewer/composables/setup/postSetup.ts
> fix(fe2): more stable presentation loader

- packages/objectloader2/src/index.ts
- packages/viewer/src/modules/loaders/Speckle/SpeckleLoader.ts
just some legwork to expose the object loader attribute masking argument
> feat(viewer): expose object loader attribute masking to the viewer

- .github/instructions/frontend-core.instructions.md
- .github/instructions/graphql-patterns.instructions.md
- .github/instructions/review-guide/frontend.instructions.md
- .github/instructions/review-guide/general.instructions.md
- .github/instructions/review-guide/server.instructions.md
- .github/instructions/tailwind-design-system.instructions.md
- .github/instructions/vue-patterns.instructions.md
cloned from the cursor ones + added extra lines based on our review guide
> chore: create copilot instruction files
