modules/auth/graph/schemas/apps.graphql, modules/core/graph/schemas/apitoken.graphql, modules/core/graph/schemas/branchesAndCommits.graphql, modules/core/graph/schemas/streams.graphql
Just modifies the gql specs to cast dates to the `DateTime` type ✨
=> fix(dates): consolidates date formatting to ISO strings

modules/core/services/streams.js, modules/core/tests/branches.spec.js, modules/core/tests/commits.spec.js, modules/core/tests/graph.spec.js, modules/core/tests/graphSubs.spec.js
just a quick refactor! tests all still work fine and I also tested it out manually in the explorer
=> refactor(branch): rename default branch to `main`

.eslintrc.json, .prettierignore, modules/core/graph/resolvers/apitoken.js, modules/core/graph/resolvers/commits.js, modules/core/graph/resolvers/objects.js, modules/core/graph/resolvers/users.js, modules/core/graph/schemas/branchesAndCommits.graphql, modules/core/graph/schemas/streams.graphql, modules/core/services/commits.js, modules/core/services/streams.js, modules/core/tests/commits.spec.js
Not sure my query update is 👌, but it does work now...
=> feat(gql): adds missing fields to getCommitById & removes realObject

modules/core/rest/download.js, modules/core/rest/upload.js, modules/core/services/objects.js, modules/core/tests/rest.spec.js
Server upload route now accepts gzipped payloads alongside plain ones. The behaviour is controlled by the `ContentType` header set by the client on each multipart upload.
=> Gzipped uploads and mimetypes

.eslintrc.json, modules/core/graph/resolvers/branches.js, modules/core/graph/resolvers/commits.js, modules/core/graph/resolvers/streams.js, modules/core/graph/schemas/branchesAndCommits.graphql, modules/core/services/branches.js, modules/core/services/commits.js, modules/core/services/streams.js, modules/core/tests/branches.spec.js, modules/core/tests/commits.spec.js, modules/core/tests/graph.spec.js, modules/core/tests/graphSubs.spec.js, modules/core/tests/streams.spec.js
- closes #44 (via a resolver guard)
- closes #38 (implemented fallbacks for defaults)
- closes #35 (guards against this at the service level)
=> Maintenance PR

packages/server/app.js, packages/server/modules/core/rest/download.js
Does two things:
- correctly path resolves static assets 
- adds cors on object download route
=> fix(server): adds cors on object download route

.dockerignore, .gitignore, Dockerfile
This is an attempt to fix #83 
The build now succeeds, but it takes quite a while to finish. Also the result for the frontend quite large ~1.6MB
The I haven't tested the result yet, hence the WIP status. 
@didimitrie could you point me to some sample data to test the viewer running in the docker container?
=> WIP: Viewer in docker

.gitignore, packages/server/readme.md
Hi! I tried to launch the server today and faced the issue that it does not play nicely with node v14. So here is a small PR to help others avoid this trouble!
=> Specify supported node version

packages/frontend/src/components/UserAvatarAuthoriseApp.vue, packages/frontend/src/views/auth/AuthorizeApp.vue
adds user info in app authorization view
=> fix(frontend): closes #74

.circleci/config.yml
frontend sometimes takes longer than 10min with no output
=> increased timeout for circleci building

packages/server/modules/serverinvites/services/index.js
`invite=xxx` -> `inviteId=xxx`
=> fix(server): fixes invite link in emails

packages/frontend/src/components/ErrorBlock.vue, packages/frontend/src/components/SearchBar.vue, packages/frontend/src/components/SidebarStream.vue, packages/frontend/src/components/SourceAppAvatar.vue, packages/frontend/src/components/UserAvatar.vue, packages/frontend/src/router/index.js, packages/frontend/src/views/Branches.vue, packages/frontend/src/views/Commit.vue, packages/frontend/src/views/Frontend.vue, packages/frontend/src/views/Stream.vue, packages/frontend/src/views/StreamMain.vue, packages/frontend/src/views/Streams.vue, packages/frontend/src/vue-apollo.js, packages/viewer/package-lock.json
Closes #175 and #105 and updates some app icons/names.
=> Frontend improvements

packages/viewer/src/modules/Converter.js
Partially fixes https://github.com/specklesystems/speckle-sharp/issues/339
=> Viewer: Curve conversion improvements

packages/server/modules/auth/strategies.js, packages/server/modules/auth/strategies/github.js, packages/server/modules/auth/strategies/google.js, packages/server/modules/auth/strategies/local.js, packages/server/modules/serverinvites/services/index.js
- Fixes #205 
- Also does a fly-by fix of #167
=> Server: Invite flow fix

packages/frontend/src/components/ObjectListViewer.vue, packages/frontend/src/components/ObjectSimpleViewer.vue, packages/frontend/src/components/Renderer.vue, packages/frontend/src/views/Commit.vue, packages/frontend/src/views/StreamMain.vue, packages/objectloader/package.json, packages/viewer/example/example.html, packages/viewer/package.json, packages/viewer/src/assets/example.html, packages/viewer/src/modules/InteractionHandler.js
=> Frontend & Viewer improvements

packages/frontend/package-lock.json, packages/frontend/package.json, packages/frontend/src/components/Renderer.vue, packages/frontend/src/views/Frontend.vue, packages/frontend/src/views/Stream.vue, packages/frontend/src/views/Streams.vue, packages/viewer/package.json, packages/viewer/src/modules/Converter.js, packages/viewer/src/modules/InteractionHandler.js, packages/viewer/src/modules/SceneObjectManager.js
Closes #193! Sample commit with named views [here](https://latest.speckle.dev/streams/05e81a6d0e/commits/a7a09c7d97). This will work once this is merged and latest picks it up.
=> Named View Support

packages/frontend/src/components/ObjectSimpleViewer.vue, packages/frontend/src/components/ObjectSpeckleViewer.vue, packages/frontend/src/components/Renderer.vue, packages/frontend/src/components/SidebarStream.vue, packages/frontend/src/components/dialogs/StreamEditDialog.vue, packages/frontend/src/views/Object.vue, packages/frontend/src/views/Profile.vue, packages/frontend/src/views/ProfileUser.vue, packages/frontend/src/views/Stream.vue, packages/frontend/src/views/auth/AuthorizeApp.vue, packages/viewer/src/app.js, packages/viewer/src/modules/Converter.js, packages/viewer/src/modules/InteractionHandler.js, packages/viewer/src/modules/SceneObjectManager.js
Meshes with vertex colours will now be... colourful (closes #218)! Note, render materials take precedence, so if one is present, the mesh will use that rather than its vertex colours. 
Includes other small fixes:
=> Adds Mesh Colours Support 🌈

packages/viewer/package.json, packages/viewer/src/modules/Converter.js
Hotfix viewer. Needs a release to propagate to xyz 😬
=> fix(viewer): accounts for empty arrays when dechunking

packages/server/modules/core/graph/resolvers/users.js, packages/server/modules/core/graph/schemas/user.graphql, packages/server/modules/core/scopes.js
Changes to discuss post standup and planning session!
=> feat(account deletion): adds extra private scope for profile deletion & adds gql resolver guards

packages/server/modules/serverinvites/services/index.js, packages/server/modules/serverinvites/tests/serverInvites.spec.js
fixes an async fumble and also adds integration tests for invites 🎉
=> fix(server): invite message promise fix

packages/frontend/src/components/GlobalsBuilder.vue, packages/frontend/src/components/GlobalsEntry.vue
lol was causing unclear deserialisation issues
bc it's an invalid character and i forgot!
=> fix(frontend): remove slash in globals sample

packages/frontend/src/views/StreamMain.vue
Fix: wrong sourceApp icon on stream main page
=> Dev/frontend: minor UI fix

packages/preview-service/routes/objects.js, packages/preview-service/routes/preview.js, packages/server/modules/core/rest/diffDownload.js, packages/server/modules/core/rest/download.js, packages/server/modules/core/services/objects.js
& adding passthrough for bigger (500k) buffers
=> feat(server): increasing highwatermark in db stream

packages/frontend/src/components/Renderer.vue
=> feat(frontend): Viewer always shows embed button in top-right corner

packages/frontend/src/views/admin/AdminPanel.vue
Fixes #334
Added loading state and fix admin check to prevent incorrect flashing (and disappearance) of the admin panel.
=> fix(frontend): Admin panel flashed wrong state on hard reload

packages/server/modules/core/graph/resolvers/branches.js, packages/server/modules/core/tests/graph.spec.js
- check `streamId` against branch `id` on branch update and delete mutations 
- add test cases for this case of mismatched stream and branch ids
=> fix(server): verify streamId on branch mutations

packages/frontend/src/components/SidebarStream.vue, packages/frontend/src/components/settings/WebhookForm.vue, packages/frontend/src/router/index.js, packages/frontend/src/views/settings/SettingsWebhooks.vue, packages/frontend/src/views/settings/StreamSettings.vue, packages/server/modules/webhooks/graph/resolvers/webhooks.js, packages/server/modules/webhooks/graph/schemas/webhooks.graphql, packages/server/modules/webhooks/tests/webhooks.spec.js
fix my oopsies!
- fix scope issue in graphql spec
- authorize resolvers 
- change routing for settings to `settings/stream/:streamId/`
- update tests so the non-admin user is used
=> fix(server): webhooks perms and routing

packages/server/modules/webhooks/graph/resolvers/webhooks.js, packages/server/modules/webhooks/tests/webhooks.spec.js
forgot to push this commit before merge ah sorry!!!
=> fix(server): webhooks mutations tests

CONTRIBUTING.md, packages/frontend/src/components/GettingStartedSteps.vue, packages/frontend/src/components/dialogs/AppNewDialog.vue, packages/objectloader/readme.md, packages/server/app.js, packages/server/modules/auth/strategies/github.js, packages/server/modules/auth/strategies/google.js, packages/server/modules/auth/tests/apps.spec.js, packages/server/modules/core/graph/schemas/streams.graphql, packages/server/modules/core/migrations/000-core.js, packages/server/modules/core/roles.js, packages/server/modules/core/services/objects.js, packages/server/modules/core/tests/objects.spec.js, packages/server/modules/core/tests/rest.spec.js, packages/server/modules/pwdreset/tests/pwdrest.spec.js, packages/server/modules/shared/index.js, packages/viewer/src/modules/Converter.js, packages/viewer/src/modules/external/TransformControls.js
Found via `codespell -q 3 -L optio,promisses,usera`
=> Fix various typos

packages/frontend/src/views/stream/Stream_re_re.vue
=> fix(frontend): correct branch url in share dialog

packages/ifc-parser/package-lock.json, packages/ifc-parser/package.json, packages/ifc-parser/src/api.js, packages/ifc-parser/src/index.js
Adds extra services to generate a one-time use api token for the given user, which is then revoked after the commit is created (simpler than actually registering this service as a trusted app on the server).
=> feat(ifc): uses gql api to create commit, thus generating activity

packages/server/modules/auth/defaultApps.js, packages/server/modules/core/rest/diffDownload.js, packages/server/modules/core/rest/diffUpload.js, packages/server/modules/core/rest/download.js, packages/server/modules/core/rest/upload.js
=> fix(server/cors): enables cors on upload endpoints

packages/frontend/src/components/SearchBar.vue, packages/frontend/src/graphql/commit.gql, packages/frontend/src/views/stream/Commit.vue, packages/server/modules/core/tests/rest.spec.js
=> fix(frontend): replace streamid with streamId in frontend gql query

packages/frontend/src/auth-helpers.js, packages/frontend/src/components/dialogs/ServerInviteDialog.vue, packages/frontend/src/components/dialogs/StreamInviteDialog.vue, packages/frontend/src/views/admin/AdminInvites.vue, packages/frontend/src/views/auth/Login.vue, packages/frontend/src/views/auth/Registration.vue, packages/frontend/src/views/auth/ResetPasswordRequest.vue
=> fix(frontend): add common robust email validator to frontend email fields

packages/viewer/src/modules/converter/Converter.js
tested old and new and all seems well! 
closes #489
=> feat(viewer): check for old & new block transforms

packages/frontend/src/cleanup/components/common/Viewer.vue
Thanks to magic brainz from @cristi8 "hai ma"
=> Hotfix frontend

packages/frontend/src/cleanup/pages/stream/CommitObjectViewer.vue
=> fix(frontend): camera setting in units + double encoding (thx @cristi8)

packages/frontend/src/embed/EmbedApp.vue, packages/frontend/src/embed/EmbedViewer.vue, packages/frontend/src/main/components/auth/Strategies.vue, packages/frontend/src/main/layouts/Auth.vue, packages/frontend/src/main/layouts/Main.vue, packages/frontend/src/main/router/index.js
fixes and fiddles for better analytics
=> fix(frontend): thx @teocomi for the sharp eyes 👀

packages/viewer/readme.md, packages/viewer/src/modules/FilteringManager.js
=> [Viewer] Allow using original material with colorBy

packages/server/.mocharc.js, packages/server/modules/activitystream/tests/activity.spec.js, packages/server/modules/auth/tests/apps.spec.js, packages/server/modules/auth/tests/appsGrapql.spec.js, packages/server/modules/auth/tests/auth.spec.js, packages/server/modules/core/index.js, packages/server/modules/core/tests/branches.spec.js, packages/server/modules/core/tests/commits.spec.js, packages/server/modules/core/tests/generic.spec.js, packages/server/modules/core/tests/graph.spec.js, packages/server/modules/core/tests/graphSubs.spec.js, packages/server/modules/core/tests/init.spec.js, packages/server/modules/core/tests/objects.spec.js, packages/server/modules/core/tests/rest.spec.js, packages/server/modules/core/tests/streams.spec.js, packages/server/modules/core/tests/users.spec.js, packages/server/modules/core/tests/usersAdmin.spec.js, packages/server/modules/emails/tests/verifications.spec.js, packages/server/modules/pwdreset/tests/pwdrest.spec.js, packages/server/modules/serverinvites/tests/serverInvites.spec.js, packages/server/modules/stats/tests/stats.spec.js, packages/server/modules/webhooks/tests/webhooks.spec.js, packages/server/test/helpers.js, packages/server/test/hooks.js
drop db migration before and after hooks, add helpers and root hooks
fix #531
=> Rework test hooks

packages/viewer/package.json, packages/viewer/src/modules/InteractionHandler.js
see relevant discussion here:
https://speckle.community/t/camera-positioning-in-speckle-viewer/2394/10
=> feat(viewer): adds a zoom to object id function

packages/viewer/src/modules/converter/Converter.js
Fixed issue with Brep conversion expecting single displayValue
Fixed issue with Curve conversion not handling detached plolyline displayValue
=> Fixed converter issues 2.4.0

.circleci/config.yml, .pre-commit-config.yaml, packages/server/modules/core/tests/rest.spec.js, packages/server/readme.md, readme.md
- ci(pre-commit): add pre-commit ci badge
- ci(pre-commit ci): add eslint extra dependencies
- test(server test): remove to short timeout from rest tests
- ci(pre-commit ci): add eslint as dependenency
- ci(circle ci): remove linting from circle ci since its moved to pre-commit ci
- docs(readme): add pre-commit badge to top level readme
=> preCommitCi

packages/frontend/src/embed/EmbedViewer.vue, packages/frontend/src/embed/embedApp.js, packages/frontend/src/embed/speckleQueries.js, packages/frontend/src/main/components/viewer/ViewerFilters.vue, packages/frontend/src/main/components/viewer/ViewsDisplay.vue, packages/frontend/src/main/dialogs/ShareStreamDialog.vue, packages/frontend/src/plugins/helpers.js, packages/frontend/src/plugins/vuetify.js
Various other paper cuts hopefully going away. Needs testing on latest post-merge, as i'm not serving the embed app, but running off the main one via a small hack in the router. 
Closes #683, #671 and other little things along the way.
=> Embedded viewer fixes & improvements

packages/frontend/src/main/components/stream/globals/GlobalsBuilder.vue, packages/frontend/src/main/pages/stream/TheGlobals.vue
As reported on the forum: https://speckle.community/t/globals-not-appearing-in-web-ui/2746/4
=> Hotfix globals

packages/webhook-service/src/webhookCaller.js
Fixes issue #742 (https://github.com/specklesystems/speckle-server/issues/742#issue-1226421536)
=> Additional HTTP response codes acceptable.

packages/preview-service/routes/preview.js
fixed the linting error https://results.pre-commit.ci/run/github/255673761/1653894937.ppQxFVvgThqePL35tQsgqA
=> fix(preview service): there is no need to double promise a preview

packages/frontend/src/main/components/common/CommitPreviewCard.vue, packages/frontend/src/main/components/stream/ListItemCommit.vue, packages/frontend/src/main/dialogs/CommitEdit.vue, packages/frontend/src/main/navigation/StreamNav.vue, packages/frontend/src/main/pages/stream/TheBranch.vue, packages/frontend/src/main/pages/stream/TheComments.vue, packages/frontend/src/main/pages/stream/TheStreamHome.vue, packages/frontend/src/main/toolbars/StreamToolbar.vue
- layout improvements for stream home (re too wide preview images cc @izzylys)
- "move commit" display bug fix (forgot to test in light mode, was visible only in dark mode previously)
- comments empty states fixes
=> More Quick Frontend Fixes 😅

packages/frontend/src/main/components/comments/CommentEditor.vue, packages/frontend/src/main/components/comments/CommentThreadAttachmentPreview.vue, packages/frontend/src/main/components/comments/CommentThreadReply.vue, packages/frontend/src/main/components/comments/CommentThreadReplyAttachments.vue, packages/frontend/src/main/components/comments/CommentThreadViewer.vue, packages/frontend/src/main/components/viewer/CommentsOverlay.vue, packages/frontend/src/main/pages/stream/CommitObjectViewer.vue, packages/server/modules/blobstorage/index.js, packages/server/modules/shared/authz.js
- layout regressions in comments
- permissions on public streams public blobs
=> Minor fixes

.github/PULL_REQUEST_TEMPLATE/PR_TEMPLATE.md
A PR template provides helpful prompts, particularly for new contributors. This may help reduce the number of rejected PRs or PRs that have to be reworked, and should help ease the burden when reviewing PRs.
- PR template
Can be merged without other actions 🟢
Not applicable, as you're looking at the results in this here PR 😄
Manual validation - I was able to create this PR using the revised template
=> Fix: adds a PR template

utils/helm/speckle-server/templates/deployment-fileimport-service.yml
=> fix(helm chart): fix not quoted config value

utils/helm/speckle-server/templates/deployment-backend.yml, utils/helm/speckle-server/templates/deployment-fileimport-service.yml, utils/helm/speckle-server/templates/deployment-frontend.yml, utils/helm/speckle-server/templates/deployment-monitor-deployment.yml, utils/helm/speckle-server/templates/deployment-preview-service.yml, utils/helm/speckle-server/templates/deployment-webhook-service.yml, utils/helm/speckle-server/templates/services.yml
Named ports improve flexibility and reduce configuration errors
Fix https://github.com/specklesystems/speckle-server/issues/868
=> style(helm chart): define named ports on pods and target them in Services

.gitguardian.yml, packages/frontend/src/bootstrapper.ts, packages/frontend/src/main/components/comments/CommentThreadViewer.vue, packages/frontend/src/main/pages/auth/TheRegistration.vue
- Fixed Comment Thread Archive modal not appearing
- Fixed Password Too Weak message during registration appearing when it shouldn't
- Added Gitguardian config so that we can ignore the warning about our mixpanel token
=> fix(frontend): various minor FE fixes + gitguardian config

utils/helm/speckle-server/templates/frontend/deployment.yml
Nginx needs to bind to port 80 which requires root permissions
=> fix(frontend): frontend currently cannot run as non-root

packages/fileimport-service/Dockerfile, packages/frontend/Dockerfile, packages/preview-service/Dockerfile, packages/server/Dockerfile, packages/webhook-service/Dockerfile, utils/monitor-deployment/Dockerfile, utils/test-deployment/Dockerfile
This reverts commit 7fe41b1fb26bdbf40abee5dc6c296a1c5bd3456b.
=> Revert "perf(Docker images): production images are based on distroless (#899)

packages/viewer/src/modules/batching/MeshBatch.ts
Fixes the issue with selected objects going invisible
=> Fixed the issue with selected objects going invisible

packages/frontend/src/main/components/feed/LatestBlogposts.vue, packages/frontend/src/main/dialogs/BranchEditDialog.vue, packages/frontend/src/main/pages/TheFeed.vue, packages/frontend/src/main/pages/stream/CommitObjectViewer.vue, packages/frontend/src/sass/variables.scss
- fixes viewer controls blocking mouse input around it
- fixes the latest blogposts block, made it not fixed and thus got rid of the extra scrollbar
- fixed branch edit dialog reloading w/o saving on enter
=> fix(frontend): some styling issues

packages/frontend/src/main/components/common/NoDataPlaceholder.vue
=> feature(frontend): dl manager link now leads to releases page

utils/helm/speckle-server/templates/fileimport_service/deployment.yml, utils/helm/speckle-server/templates/frontend/deployment.yml, utils/helm/speckle-server/templates/monitoring/deployment.yml, utils/helm/speckle-server/templates/preview_service/deployment.yml, utils/helm/speckle-server/templates/server/deployment.yml, utils/helm/speckle-server/templates/webhook_service/deployment.yml
Kube Linter recommended explicitly setting this property.  This is the default value for this property, so no change in behaviour.
Partially addresses https://github.com/specklesystems/speckle-server/issues/925
- deployment rollout strategy explicitly defined
No requirements
Has been deployed to a server and verified it rolled out correctly.
=> refactor(helm chart): explicitly define the deployment rollout strategy

packages/server/modules/core/graph/resolvers/users.js
=> fix(server): put emails behind elevated privileges

packages/server/modules/core/tests/commits.spec.js, packages/server/modules/core/tests/usersAdminList.spec.ts
=> fix(server): hopefully fixing some flaky tests

packages/frontend/src/main/layouts/TheMain.vue, packages/frontend/src/main/lib/core/composables/dom.ts, packages/frontend/src/sass/variables.scss
=> fix(frontend): ugly side bar scrollbar & version being truncated

packages/frontend/src/main/pages/stream/CommitObjectViewer.vue, packages/frontend/src/main/toolbars/MultipleResourcesToolbar.vue
closes #1060 
looks like this now:
=> fix(frontend): multiple resource viewer toolbar/navbar incorrect

packages/frontend/src/main/components/common/SourceAppAvatar.vue
Adds missing appnames and colors
=> feat(frontend): adds missing appnames and colors

packages/frontend/src/main/components/common/NoDataPlaceholder.vue
=> feat: manager download link

utils/test-deployment/run_tests.py
=> fix(test-deployment container): fix frontend readiness tests with new vite bundling changes

packages/frontend/src/main/pages/stream/TheUploads.vue
fixing TheUploads.vue being broken
=> fix(frontend): stream uploads page error fix

packages/frontend/src/main/lib/common/text-editor/mentionSuggestion.js
Comment mentions currently broken on latest - red errors in the console
=> fix(frontend): comment mentions broken post-vite

packages/frontend/package.json, packages/frontend/src/main/components/comments/CommentThreadReply.vue, packages/frontend/src/main/components/comments/CommentThreadReplyAttachments.vue, packages/frontend/src/main/components/viewer/CommentsOverlay.vue, packages/frontend/src/main/components/viewer/ViewerBubbles.vue, packages/frontend/src/main/layouts/TheAuth.vue, packages/frontend/src/main/pages/common/NotFound.vue, packages/frontend/src/main/pages/common/TheError.vue, packages/frontend/src/main/pages/onboarding/TheOnboarding.vue, packages/frontend/src/main/pages/stream/TheEmbed.vue, packages/frontend/src/main/pages/stream/TheStream.vue, packages/frontend/src/plugins/vuetify.js, yarn.lock
=> fix(frontend): comment link & attachment styling in both themes

packages/frontend/src/main/components/viewer/CommentsOverlay.vue
=> feat(frontend): auto-focus on 1st comment in embed slideshow mode

.circleci/config.yml
=> Always build, except when branch (not main) does not have PR

packages/preview-service/routes/preview.js, packages/server/modules/auth/errors/index.ts, packages/server/modules/auth/rest/index.js, packages/server/modules/auth/strategies.js, packages/server/modules/blobstorage/index.js, packages/server/modules/shared/helpers/envHelper.ts
closes https://github.com/specklesystems/admin/issues/365
fixes:
https://app.snyk.io/org/didimitrie/project/6b6df7b1-a47a-4dda-86b0-e035e269c54d#issue-19277a6c-f14a-4727-90e7-0b621ef027fc
https://app.snyk.io/org/didimitrie/project/6b6df7b1-a47a-4dda-86b0-e035e269c54d#issue-68c66c51-ceb6-4441-9029-198601b49922
https://app.snyk.io/org/didimitrie/project/6b6df7b1-a47a-4dda-86b0-e035e269c54d#issue-d1d6b922-2900-414e-ab97-cdf9901fc7c9
https://app.snyk.io/org/didimitrie/project/6b6df7b1-a47a-4dda-86b0-e035e269c54d#issue-83fbfea5-8d08-4383-aad7-33fc5144b014
=> fix: various security alert fixes

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/converter/GeometryConverter.ts
This fixes #1219 
The cause for the issue was not because the art was contained by a polycurve, and it was more general. When the arc has an angle of PI, the directions from start and end to origin face away from each other, making the cross product return 0, and we end up with an incorrect orthonormal basis.
=> Fixed #1219

packages/frontend/src/main/components/viewer/ViewsDisplay.vue, packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/objects/SpeckleCameraControls.ts
- Fixed a frontend issue which was making views not work
- Fixed a viewer issue which was making object selection animation dolly not have a smooth animation
=> 2.10.1-undead-patch

packages/preview-service/routes/preview.js
Fixes the issue where the preview-service generates the screenshot from a single angle each time
Added `waitForAnimation` in the generation loop. This should have been there, but forgot to add it in the last commit
=> Added a missing wait in the screenshot generation loop

packages/fileimport-service/ifc/import_file.js
=> fix(fileimports): fix IFC file imports commit message

packages/frontend/src/main/components/viewer/CommentAddOverlay.vue, packages/frontend/src/main/components/viewer/CommentsOverlay.vue, packages/frontend/src/main/components/viewer/ViewerControls.vue, packages/frontend/src/main/lib/core/composables/dom.ts, packages/viewer/src/modules/SpeckleRenderer.ts, packages/viewer/src/modules/Viewer.ts, packages/viewer/src/modules/context/CameraHanlder.js, packages/viewer/src/modules/objects/SpeckleCameraControls.ts
Fixed the issue with comment bubbles not working in orthographic mode and some additional fixes
- Comment bubbles now working in orthographic mode
- Added orthographic mode in (by uncommenting what was already there)
- Fixed an issue with progressive AO and orthographic mode zooming in
- @didimitrie : Please check if there are any other situations where the comment bubbles are not working with orthographic. I tested to be best of my abilities, but I might have missed some scenarios or edge cases.
=> Orthographic Mode with working comment bubbles

packages/frontend-2/assets/css/tailwind-setup/semantic-colors.css, packages/frontend-2/components/form/CardButton.vue, packages/frontend-2/components/form/TextInput.vue, packages/frontend-2/components/projects/DashboardEmptyState.vue
=> feat(fe2): dark mode theme is now in thx @caluxlopez

packages/frontend/src/main/lib/auth/services/authService.ts, packages/frontend/src/main/lib/auth/utils/postAuthRedirectManager.ts, packages/frontend/src/main/router/index.js, packages/frontend/src/plugins/authHelpers.js, packages/frontend/src/plugins/helpers.ts
refactored post-auth redirect functionality a bit, made it more resilient and solved bug where guests couldn't add account to desktop manager
=> fix(frontend): post-auth redirects fixed

packages/server/modules/accessrequests/tests/streamAccessRequests.spec.ts, packages/server/test/notificationsHelper.ts
fixing notification-related tests being flaky
=> fix(server): access request test flakiness

packages/frontend/src/main/components/common/SourceAppAvatar.vue
Syncing the addition of Navisworks Connector to the Speckle Family.
Frontend/Components/SourceAppAvatar
=> Enhancement: Adds Navisworks to the application avatars

packages/viewer-sandbox/src/Sandbox.ts, packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/batching/MeshBatch.ts, packages/viewer/src/modules/materials/Materials.ts
Some GPUs (like the 3070) did not consistently sample when reading from texel edges while using the Nearest filtering. This led to horrible artifacts when using the colored filter
- Ramp index is now shifted to the each texel center so that no inconsistencies can occur
Before:
After:
=> Fixed #1267 by properly sampling the ramp texels in their centers

packages/webhook-service/src/knex.js, packages/webhook-service/src/main.js
=> feat(webhooks): remove double json stringifying of the webhook payload

.circleci/config.yml
We had missed bumping the node version used in the test-server step of CircleCI, this PR fixes that.
=> chore(circleci): bump dependency image versions

packages/fileimport-service/ifc/parser_v2.js
=> fix(ifc parser): make sure the commit root object is a Speckle Base

packages/fileimport-service/ifc/parser_v2.js
=> fix(ifc parser): replace empty children arrays with elements

packages/server/modules/blobstorage/index.js
=> fix(server blobs): make sure not implemented blobs delete endpoint returns 501

packages/frontend/src/main/components/viewer/CommentAddOverlay.vue, packages/frontend/src/main/components/viewer/CommentsOverlay.vue, packages/viewer-sandbox/src/main.ts, packages/viewer/src/IViewer.ts, packages/viewer/src/index.ts, packages/viewer/src/modules/SpeckleRenderer.ts, packages/viewer/src/modules/Utils.ts, packages/viewer/src/modules/Viewer.ts, packages/viewer/src/modules/queries/IntersectionQuerySolver.ts, packages/viewer/src/modules/queries/PointQuerySolver.ts, packages/viewer/src/modules/queries/Queries.ts, packages/viewer/src/modules/queries/Query.ts
Updated the existing queries. Separated PointQueries from IntersectionQueries
- Separated PointQueries from IntersectionQueries
- Each Query type now has it's own QueryResult type
- Update the Utils interface to include the optional parameters in it's functions
- Query id is now optional since it's currently not used
=> Queries update

packages/server/modules/auth/defaultApps.js
=> feat(server default apps): add powerbi as a default app on the servers

packages/fileimport-service/ifc/parser_v2.js, packages/fileimport-service/ifc/utils.js, packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/SpeckleRenderer.ts, packages/viewer/src/modules/batching/Batcher.ts, packages/viewer/src/modules/batching/MeshBatch.ts, packages/viewer/src/modules/materials/Materials.ts, packages/viewer/src/modules/materials/SpeckleDisplaceMaterial.ts, packages/viewer/src/modules/materials/shaders/speckle-basic-vert.ts, packages/viewer/src/modules/materials/shaders/speckle-displace-frag.ts, packages/viewer/src/modules/materials/shaders/speckle-displace.vert.ts, packages/viewer/src/modules/pipeline/Pipeline.ts, packages/viewer/src/modules/pipeline/StencilMaskPass.ts, packages/viewer/src/modules/pipeline/StencilPass.ts
Added stencil on-top outlines for selected objects.#1332
- Implemented a stencil prepass and a stencil mask pass. Currently only used for outlines
-  I went through all my test streams and the outlines seem to be working fine with the other existing features (filtering, sectioning, etc). However, some more testing would be good
=> Outlines in Selection (FE2)

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/SpeckleRenderer.ts, packages/viewer/src/modules/batching/Batcher.ts, packages/viewer/src/modules/batching/MeshBatch.ts, packages/viewer/src/modules/materials/Materials.ts, packages/viewer/src/modules/materials/SpeckleDisplaceMaterial.ts, packages/viewer/src/modules/materials/shaders/speckle-basic-vert.ts, packages/viewer/src/modules/materials/shaders/speckle-displace-frag.ts, packages/viewer/src/modules/materials/shaders/speckle-displace.vert.ts, packages/viewer/src/modules/pipeline/Pipeline.ts, packages/viewer/src/modules/pipeline/StencilMaskPass.ts, packages/viewer/src/modules/pipeline/StencilPass.ts
Added stencil on-top outlines for selected objects.#1332
- Implemented a stencil prepass and a stencil mask pass. Currently only used for outlines
-  I went through all my test streams and the outlines seem to be working fine with the other existing features (filtering, sectioning, etc). However, some more testing would be good
=> Outlines in Selection

packages/frontend/src/main/components/viewer/ObjectSelection.vue
=> fix(frontend): viewer object properties not being scrollable

packages/frontend/src/main/components/viewer/ObjectSelection.vue, packages/viewer/src/modules/tree/RenderTree.ts
=> fix(frontend): viewer dragging not working in some cases

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/batching/Batcher.ts, packages/viewer/src/modules/tree/NodeRenderView.ts
Fixes an issue recently introduced which breaks all streams with points
- Added simpler displayable geometry validation instead of checking it's aabb which is 0 for points
=> 2.12.1-undead-patch

packages/server/modules/core/tests/generic.spec.js, packages/server/modules/shared/authz.ts, packages/server/modules/shared/helpers/envHelper.ts, packages/server/modules/shared/index.js, packages/server/modules/shared/test/authz.spec.js, utils/helm/speckle-server/templates/server/deployment.yml, utils/helm/speckle-server/values.schema.json, utils/helm/speckle-server/values.yaml, utils/helm/test-values.yml
=> feat(server): add switchable admin authz override

packages/server/modules/auth/strategies/oidc.js
make sure the passport authentication works on the same request scope for auth and callback
fix #1374
=> fix(server auth): fix oidc stategy

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/converter/Converter.ts, packages/viewer/src/modules/converter/GeometryConverter.ts
This makes the viewer ignore curves with no display value instead of crashing
=> Ignoring curves with no display values

packages/server/modules/core/graph/resolvers/streams.js
=> feat(server): add admin override to otheruser steams query

packages/server/modules/core/tests/generic.spec.js
=> fix(server authz tests): force wait until env vars are reloaded in authz tests

packages/frontend-2/components/form/select/Base.vue, packages/frontend-2/components/layout/Dialog.vue, packages/frontend-2/components/project/VisibilitySelect.vue, packages/frontend-2/components/projects/AddDialog.vue, packages/frontend-2/components/viewer/resources/LoadedVersionCardVersion2.vue, packages/frontend-2/lib/viewer/composables/setup.ts
=> feat(fe2): styling changes & some fixes

packages/frontend-2/components/project/page/MoreActions.vue
=> feat(fe2): minor copy edits

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/converter/Converter.ts, packages/viewer/src/modules/converter/GeometryConverter.ts, packages/viewer/src/modules/tree/WorldTree.ts
…he concept of nesteNodes in NodeData interface, but I'm wary of using it extensively
Fixes #1220 . The polycurve segments which can be any (line-type) displayable object were added as children to the polycurve object. At geometry generation time, the polycurve object created it's own geometry based off the children segments, but also the children segments created their own segment geometries. To the best of my understanding, polyline segments are *not* to be treated as individual objects, but rather building blocks for the polycurve itself. That's why I've added the polycurve segments as *nestedNodes* which will not get traversed by any tree walking, and the only geometry created will be the polycurve's. 
- Polycurve segments are nested nodes now, instead of children nodes
- Added …
=> Polycurve elements geometry only created once

packages/server/modules/core/tests/generic.spec.js
=> fix(test): make sure users are created sequentially

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/SpeckleRenderer.ts, packages/viewer/src/modules/queries/IntersectionQuerySolver.ts, packages/viewer/src/modules/queries/Query.ts
I noticed an issue while running [this stream](https://latest.speckle.dev/streams/7d051a6449/commits/03d53878ee) in firefox. It seemed slower than usual. Investigation lead to the occlusion queries executed for each comment bubble. Specifically, not the intersection tests themselves since those are lightning fast, but searching in the tree in order to fetch the occluding node for the result of the query. Occlusion queries should not do this at all, so I changed their query result to only return the id of the occluding object (which is instantaneous to fetch). If users want the entire speckle object, they can still get it via the API by using the provided speckle id. **This sped up occlusion queries by 30-100x** especially in firefox, which was slower than chrome
- …
=> Alex/Faster Occlusion Queries

packages/server/modules/pwdreset/services/request.ts
=> fix: (server password reset): email mjml was missing mj tags

packages/frontend-2/components/viewer/resources/ModelCard.vue, packages/frontend-2/components/viewer/resources/VersionCard.vue
=> feat(fe2): minor fixes in viewer model card + version card

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/SpeckleRenderer.ts
Addresses issue #1475 
- Line-based geometry is not rendered anymore in the shadowcatcher pass
=> Disabled rendering of line-based geometry in the shadowcatcher pass

packages/server/modules/auth/strategies.js, packages/server/modules/shared/utils/mixpanel.ts
https://github.com/specklesystems/admin/issues/381
=> feat(server): awaitable track calls

packages/frontend-2/components/project/models-page/Header.vue, packages/frontend-2/layouts/loginOrRegister.vue, packages/frontend-2/lib/auth/composables/auth.ts, packages/frontend-2/middleware/dashboard-redirect.ts
=> feat(fe2): minor hacks with @fabis94 

packages/server/modules/shared/middleware/index.ts
=> fix(server): logging ipv6 catches

utils/helm/speckle-server/values.yaml
The "v" prefix in the image tags was dropped after version 2.3.3. If users try to update their version numbers but maintain the v prefix, they will have issues pulling images and will receive ImagePullBackOff errors.
=> chore(helm): matches docker_image_tag current image version and syntax

docker-compose-deps.yml, packages/server/.env-example, packages/server/modules/auth/defaultApps.js, packages/server/modules/auth/tests/apps.spec.js, packages/server/modules/auth/tests/appsGrapql.spec.js, packages/server/modules/shared/helpers/envHelper.ts, utils/helm/speckle-server/templates/server/deployment.yml, utils/helm/speckle-server/values.schema.json, utils/helm/speckle-server/values.yaml
=> feat(server): add speckle automate as a configurable default app

packages/frontend-2/components/connectors/Card.vue, packages/frontend-2/components/connectors/VersionsDownloadDialog.vue
cc @teocomi minor changes post discussion!
=> feat(fe2): styling fixes

packages/frontend-2/lib/auth/composables/onboarding.ts, packages/frontend-2/lib/common/helpers/utils.ts, packages/frontend-2/pages/onboarding.vue, packages/server/modules/comments/helpers/types.ts, packages/server/modules/comments/services/data.ts, packages/shared/src/core/helpers/utility.ts
=> fix onboarding & legacy data map issue

packages/viewer-sandbox/src/Sandbox.ts, packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/Assets.ts, packages/viewer/src/modules/materials/Materials.ts
Numeric filters (filtering by any property which is numeric) now works for lines as well. Chosen implementation aimed to reduce the risk of regression, rather than doing it the best possible way.
- Numeric filters now work for line-based geometries the same way they work for meshes
- Added a function in `Assets` which can provide ImageData from a Texture
=> Added support for numeric line fiters

packages/viewer-sandbox/src/Sandbox.ts, packages/viewer/src/IViewer.ts, packages/viewer/src/modules/SpeckleRenderer.ts, packages/viewer/src/modules/Viewer.ts, packages/viewer/src/modules/objects/SpeckleBatchBVH.ts, packages/viewer/src/modules/objects/SpeckleMesh.ts, packages/viewer/src/modules/tree/NodeRenderView.ts
The explosion range is automatically computed instead of provided in the API when exploding
- Explosion range is computed automatically when exploding based on the current world size
- Fixed an issue where meshes with no face data were causing errors. They're ignored now
- Fixed an issue where the TAS did not correctly report the total bounds, due to a bug in the BVH library
- Added direct BAS indexing by the TAS in the shapecast function improving shapecasting total speed
=> #1554 Auto explode range

packages/fileimport-service/Dockerfile, packages/frontend/Dockerfile, packages/preview-service/Dockerfile, packages/server/Dockerfile, packages/webhook-service/Dockerfile
=> chore: ensuring react ttypes are always stubbed

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/Viewer.ts, packages/viewer/src/modules/batching/Batcher.ts, packages/viewer/src/modules/converter/Converter.ts, packages/viewer/src/modules/filtering/FilteringManager.ts, packages/viewer/src/modules/tree/RenderTree.ts
Fixing the current issues with instances, where if you click one, every instance of that kind in the scene gets selected. Also, fixing selection issues with blocks.
=> Instance/Block Selection Fixes

packages/dui3/lib/core/configs/apollo.ts, packages/frontend-2/components/singleton/AppErrorStateManager.vue, packages/frontend-2/components/singleton/Managers.vue, packages/frontend-2/lib/core/composables/appErrorState.ts, packages/frontend-2/lib/core/configs/apollo.ts, packages/frontend/src/config/apolloConfig.ts, packages/frontend/src/graphql/comments.ts, packages/frontend/src/main/App.vue, packages/frontend/src/main/lib/core/utils/appErrorStateManager.ts, packages/shared/src/observability/index.ts, workspace.code-workspace
=> feat: stopping subscriptions at >100 errors per minute

packages/server/modules/core/graph/resolvers/commits.js, packages/server/modules/core/helpers/graphTypes.ts
commit authorId-s can be null, if a server user is deleted.
We keep the commit on the server, so we need to be able to
return null values for commit author name and avatar
=> fix(server commits graphql): fix commit author null error

packages/frontend-2/components/viewer/anchored-point/Thread.vue, packages/frontend-2/lib/common/composables/window.ts
=> feat(fe2): improved thread dragging

packages/server/Dockerfile, utils/helm/speckle-server/templates/server/deployment.yml
the server helm deployment only overrides if inspect is needed
=> fix(server helm / dockerfile): remove entrypoint from dockerfile

packages/viewer-sandbox/src/Sandbox.ts, packages/viewer/src/modules/Differ.ts
Fixes an issue where diffing would fail for objects with no applicationId and parents with no applicationId. Now we go up the parent chain until we find an applicationId, and if there is none we consider the object added or removed depending on the diffing direction
=> Diffing-applicationId-fix

packages/frontend-2/components/onboarding/checklist/v1.vue, packages/frontend-2/components/onboarding/dialog/AccountLink.vue, packages/frontend-2/components/onboarding/dialog/Base.vue, packages/frontend-2/components/onboarding/dialog/FirstSend.vue, packages/frontend-2/components/onboarding/dialog/Manager.vue, packages/frontend-2/components/tour/Segmentation.vue, packages/frontend-2/lib/auth/helpers/onboarding.ts
Adds onboarding videos, last segmentation edits, and refactors onboarding checklist popups to use default dialog base component.
=> feat(fe2): onboarding checklist, segmentation checkup & intro videos

packages/frontend-2/components/viewer/AnchoredPoints.vue, packages/frontend-2/components/viewer/anchored-point/NewThread.vue, packages/frontend-2/components/viewer/anchored-point/Thread.vue, packages/frontend-2/components/viewer/comments/ListItem.vue, packages/frontend-2/lib/viewer/composables/commentBubbles.ts, packages/frontend-2/lib/viewer/composables/setup.ts, packages/frontend-2/lib/viewer/composables/setup/comments.ts, packages/frontend-2/lib/viewer/composables/ui.ts
=> fix(fe2): comment viewerState not loading correctly

packages/server/modules/core/graph/resolvers/branches.js
TL;DR: related to https://github.com/specklesystems/speckle-sharp/issues/2640, we agreed: 
- keep the stream wrapper without API calls in .net/py
- from the old gql endpoints, introduce a fallback for getting branches by id if they're not found by name
- this is a stopgap forward compatibility measure that should be removed post transition to fe2
=> feat(server): allows getting branches by name or id from the same api endpoint

packages/viewer-sandbox/src/Sandbox.ts, packages/viewer/src/modules/materials/SpeckleBasicMaterial.ts, packages/viewer/src/modules/materials/SpeckleDepthMaterial.ts, packages/viewer/src/modules/materials/SpeckleDisplaceMaterial.ts, packages/viewer/src/modules/materials/SpeckleMaterial.ts, packages/viewer/src/modules/materials/SpeckleNormalMaterial.ts, packages/viewer/src/modules/materials/SpeckleShadowcatcherMaterial.ts, packages/viewer/src/modules/materials/SpeckleStandardColoredMaterial.ts, packages/viewer/src/modules/materials/SpeckleStandardMaterial.ts, packages/viewer/src/modules/materials/SpeckleTextMaterial.ts
https://github.com/specklesystems/speckle-server/issues/1653
This PR fixes the performance issues while using transparent(PLAIN) diffing mode. The cause was more rooted than originally thought. Three.js forces deep cloning of everything inside the material's `userData`. That's where we keep our custom uniforms, including textures. So deep copying texture data was the cause for the performance hit, and since we don't need the textures to be deep copied we've stopped three.js from doing this.
Additionally, we're copying material data in many other scenarios, so this change _will help with performance overall, not just for diffing_
- `userData` is no longer being deep copied
- Moved the definition of `Uniforms` to the base `SpeckleMaterial` class (unrelated to the issue at hand)
=> Alex/#1653 Transparent Diffing Performance

packages/server/modules/activitystream/services/commitActivity.ts, packages/server/modules/cli/commands/download/commit.ts, packages/server/modules/core/services/commit/management.ts
=> add FE2 terminology to commit create webhook

packages/frontend-2/components/auth/LoginPanel.vue, packages/frontend-2/components/auth/third-party/LoginBlock.vue, packages/frontend-2/components/header/NavBar.vue, packages/frontend-2/components/popups/SignIn.vue, packages/frontend-2/components/tour/Segmentation.vue, packages/frontend-2/components/tour/content/OverlayModel.vue, packages/frontend-2/layouts/viewer.vue, packages/frontend-2/lib/auth/composables/onboarding.ts, packages/frontend-2/lib/auth/helpers/onboarding.ts, packages/frontend-2/lib/viewer/composables/setup/selection.ts, packages/frontend-2/lib/viewer/composables/viewer.ts, packages/frontend-2/pages/onboarding.vue
=> FE2 Polish

packages/frontend-2/lib/auth/composables/passwordReset.ts, packages/frontend-2/lib/common/composables/graphql.ts, packages/frontend-2/lib/common/helpers/graphql.ts, packages/frontend-2/lib/core/configs/apollo.ts, packages/frontend-2/middleware/auth.ts, packages/frontend-2/middleware/dashboard-redirect.ts, packages/frontend-2/middleware/guest.ts, packages/frontend-2/middleware/onboarding.global.ts, packages/frontend-2/middleware/requireValidModel.ts, packages/frontend-2/middleware/requireValidProject.ts, packages/frontend-2/pages/authn/reset-password.vue, packages/frontend-2/plugins/dev.ts, packages/frontend/src/config/apolloConfig.ts, packages/frontend/src/helpers/errorHelper.ts, packages/frontend/src/main/app.js, packages/frontend/src/plugins/authHelpers.js
=> fix(fe2 & fe1): log out on invalid auth token on any GQL call

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/converter/Converter.ts, packages/viewer/src/modules/tree/RenderTree.ts
…Instances
This PR adds support for hosted elements on the `BlockInstance` speckle type. The hosted elements behave the same way they behave for the `RevitInstance` type
Example stream:  https://latest.speckle.dev/streams/e258b0e8db/commits/00e165cc1c
- Block instances now parse the hosted elements with their potential infinitely deep nesting
=> Hosted Elements on BlockInstances

packages/server/assets/core/typedefs/branchesAndCommits.graphql, packages/server/logging/logging.ts, packages/server/modules/cli/commands/download/commit.ts, packages/server/modules/cli/services/download/commit.ts, packages/server/modules/core/dbSchema.ts, packages/server/modules/core/graph/generated/graphql.ts, packages/server/modules/core/graph/resolvers/commits.js, packages/server/modules/core/migrations/20230713094611_create_streams_meta_table.ts, packages/server/modules/core/repositories/commits.ts, packages/server/modules/core/repositories/streams.ts, packages/server/modules/core/tests/discoverableStreams.spec.ts, packages/server/modules/shared/helpers/envHelper.ts, packages/server/test/graphql/generated/graphql.ts, packages/shared/rollup.config.js
+ Some other minor fixes/improvements
Cross-server commit/version download CLI command now supports FE2 urls and syncing in comments as well
=> feat(server): improved cross-server commit/version download

packages/server/assets/accessrequests/typedefs/accessrequests.graphql, packages/server/assets/activitystream/typedefs/activity.graphql, packages/server/assets/auth/typedefs/apps.graphql, packages/server/assets/comments/typedefs/comments.gql, packages/server/assets/core/typedefs/apitoken.graphql, packages/server/assets/core/typedefs/branchesAndCommits.graphql, packages/server/assets/core/typedefs/server.graphql, packages/server/assets/core/typedefs/streams.graphql, packages/server/assets/core/typedefs/user.graphql, packages/server/assets/emails/typedefs/emails.graphql, packages/server/assets/notifications/typedefs/notificationPreferences.graphql, packages/server/assets/serverinvites/typedefs/serverInvites.graphql, packages/server/assets/webhooks/typedefs/webhooks.graphql, packages/server/modules/core/graph/directives/hasRole.js, packages/server/modules/core/graph/generated/graphql.ts
=> refactor(server graphlq): migrate hasRole directive to hasServerRole

packages/server/modules/core/graph/resolvers/users.js, packages/server/modules/core/services/users.js, packages/server/modules/core/tests/graph.spec.js, packages/server/modules/core/tests/users.spec.js, packages/server/modules/core/tests/usersAdmin.spec.js, packages/server/modules/shared/helpers/envHelper.ts
=> feat(server): implement switch user role to guest

packages/server/modules/core/services/streams/streamAccessService.js, packages/server/modules/core/tests/streams.spec.ts
=> feat(server): guests cannot own stream projects

utils/helm/speckle-server/templates/frontend_2/deployment.yml, utils/helm/speckle-server/values.schema.json, utils/helm/speckle-server/values.yaml
=> fix: missing helm chart values for new onboarding stream sync

packages/server/assets/accessrequests/typedefs/accessrequests.graphql, packages/server/assets/activitystream/typedefs/activity.graphql, packages/server/assets/auth/typedefs/apps.graphql, packages/server/assets/comments/typedefs/comments.gql, packages/server/assets/comments/typedefs/viewer.gql, packages/server/assets/core/typedefs/branchesAndCommits.graphql, packages/server/assets/core/typedefs/modelsAndVersions.graphql, packages/server/assets/core/typedefs/streams.graphql, packages/server/assets/core/typedefs/user.graphql, packages/server/assets/emails/typedefs/emails.graphql, packages/server/assets/notifications/typedefs/notificationPreferences.graphql, packages/server/assets/serverinvites/typedefs/serverInvites.graphql, packages/server/modules/core/graph/resolvers/objects.js, packages/server/modules/core/graph/resolvers/projects.ts, packages/server/modules/core/graph/resolvers/streams.js, packages/server/modules/core/graph/resolvers/users.js, packages/server/modules/core/tests/streams.spec.ts
=> allow guest access to selected gql resources

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/filtering/FilteringManager.ts
#1738 The issues was caused by `getDescendantIds` from `FilteringManager` not providing correct ids, and leading to incorrect visibility state. This PR attempts to fix this issue
- `getDescendantIds` no longer relies on the object's `__closure` to gather ids. Instead we're using available tree functions
=> Fixed #1738

packages/fileimport-service/ifc/api.js, packages/server/.vscode/launch.json, packages/server/modules/core/rest/upload.js, packages/server/modules/core/services/objects.js, packages/server/modules/core/tests/chunking.spec.ts, packages/server/modules/core/utils/chunking.ts
=> feat(server objects): add insertion object chunking logic

packages/server/modules/activitystream/services/branchActivity.ts, packages/server/modules/activitystream/services/commentActivity.ts, packages/server/modules/activitystream/services/commitActivity.ts, packages/server/modules/activitystream/services/streamActivity.ts, packages/server/modules/comments/graph/resolvers/comments.js, packages/server/modules/core/graph/directives/hasRole.js, packages/server/modules/core/graph/resolvers/branches.js, packages/server/modules/core/graph/resolvers/commits.js, packages/server/modules/core/graph/resolvers/objects.js, packages/server/modules/core/graph/resolvers/projects.ts, packages/server/modules/core/graph/resolvers/server.js, packages/server/modules/core/graph/resolvers/streams.js, packages/server/modules/core/graph/resolvers/users.js, packages/server/modules/core/rest/authUtils.js, packages/server/modules/core/tests/favoriteStreams.spec.js, packages/server/modules/core/tests/generic.spec.js, packages/server/modules/core/tests/streams.spec.ts, packages/server/modules/shared/authz.ts, packages/server/modules/shared/errors/index.ts, packages/server/modules/shared/index.js, packages/server/modules/shared/roles.js, packages/server/modules/shared/test/authz.spec.js, packages/server/modules/stats/graph/resolvers/stats.js
=> refactor(server): use auth pipeline server role validator for gql auth

.graphqlrc, docker-compose-speckle.yml, packages/fileimport-service/ifc/index.js, packages/fileimport-service/knex.js, packages/fileimport-service/obj/import_file.py, packages/fileimport-service/package.json, packages/fileimport-service/stl/import_file.py, packages/frontend-2/lib/common/generated/gql/graphql.ts, packages/frontend-2/lib/common/helpers/roles.ts, packages/frontend/.vscode/launch.json, packages/frontend/apollo.config.js, packages/preview-service/Makefile, packages/preview-service/knex.js, packages/preview-service/readme.md, packages/server/.env-example, packages/server/app.ts, packages/server/knexfile.js, packages/server/modules/auth/tests/apps.spec.js, packages/server/modules/cli/commands/bull/monitor.ts, packages/server/modules/core/services/generic.js, packages/server/modules/cross-server-sync/graph/generated/graphql.ts, packages/server/modules/emails/utils/transporter.ts, packages/server/readme.md
=> fix(monorepo): make sure to use 127.0.0.1 instead of localhost

packages/frontend-2/lib/core/composables/mp.ts, packages/frontend/src/mixpanelManager.ts
Add users to groups for better analytics
=> feat: add users to groups

packages/dui3/lib/bindings/definitions/IBasicConnectorBinding.ts, packages/dui3/pages/onboarding/v1.vue, packages/dui3/store/hostApp.ts
=> feat(dui3): fixes onboarding filter discriminator, now app independent

packages/frontend-2/components/server-management/CardRow.vue, packages/frontend-2/lib/common/generated/gql/graphql.ts, packages/frontend-2/lib/server-management/helpers/types.ts, packages/frontend-2/pages/server-management/active-users.vue, packages/frontend-2/pages/server-management/index.vue, packages/frontend-2/pages/server-management/pending-invitations.vue, packages/frontend-2/pages/server-management/projects.vue, packages/server/modules/core/tests/usersAdminList.spec.ts, packages/server/modules/serverinvites/migrations/20230907131636_migrate_invites_to_lower_precision_timestamps.ts, packages/server/modules/serverinvites/repositories/index.js
Fixes a few frontend and backend issues around infinite loading.
- Update queryServerInvites from '<' to '>'
- Backend fixes around getInvitesBaseQuery
- Add CommonLoadingBar to Users, Projects and Invites tables - This is a temporary measure and should be addressed in future in [this ticket](https://www.notion.so/speckle/We-Like-Tasks-36d66170974b46298bb3d9b02a241437?p=2bf871c271d243a5bcd2d3a2035b9b55&pm=s)
- Add new UI feature showing the user when they are "up-to-date" with the latest version.
=> Fe2 server management bugfixes

packages/fileimport-service/ifc/parser_v2.js
=> fix ifc argb material calculation

packages/server/modules/core/migrations/000-core.js
I know i'm changing the migration, but its a default value change. Should be safe.
=> feat(server): change default name of a server

packages/frontend-2/components/onboarding/checklist/v1.vue, packages/frontend-2/components/projects/Dashboard.vue, packages/frontend-2/components/projects/ProjectDashboardCard.vue
=> fix(fe2): made onboarding bar load in SSR

packages/dui3/components/common/ModelCard.vue, packages/dui3/store/hostApp.ts, packages/ui-components/src/components/common/loading/ProgressBar.vue
Some cancellation css and timeout added.
=> Chore (DUI3): cancellation

packages/shared/src/core/constants.ts
=> feat: add source app name const

packages/ui-components/src/components/layout/Dialog.vue, packages/ui-components/tailwind.config.cjs
Hotfix to remove bg-white and replace with semantic colours.
=> Fixes to dialog Semantic Colours

packages/ui-components/src/components/layout/Dialog.vue
Reverting of change around max-width breakpoint modifiers. Something to come back to in future.
=> Revert removing of max-width breakpoint modifiers

packages/frontend-2/components/projects/AddDialog.vue, packages/ui-components/src/components/form/select/Base.stories.ts, packages/ui-components/src/components/form/select/Base.vue, packages/ui-components/src/components/layout/Dialog.vue
=> feat(ui-components): ability to mount select box menu to body to avoid overflow issues

packages/frontend-2/components/project/page/models/StructureItem.vue, packages/frontend-2/lib/common/composables/window.ts, packages/frontend-2/lib/projects/composables/models.ts
=> feat(fe2): save expanded state for model structured item cards

packages/frontend-2/components/common/EmptySearchState.vue, packages/frontend-2/components/common/EmptyState.vue, packages/frontend-2/components/form/ButtonSecondaryViewAll.vue, packages/frontend-2/components/preview/Image.vue, packages/frontend-2/components/project/models-page/Header.vue, packages/frontend-2/components/project/page/LatestItems.vue, packages/frontend-2/components/project/page/models/CardView.vue, packages/frontend-2/components/project/page/models/ListView.vue, packages/frontend-2/package.json, yarn.lock
=> feat(fe2): showing view all in certain model views

packages/server/modules/core/repositories/branches.ts, packages/server/modules/core/tests/branches.spec.js
=> feat: branch delete now deletes commits too

utils/helm/speckle-server/values.schema.json, utils/helm/speckle-server/values.yaml
=> bump model defaults

packages/server/modules/automations/graph/resolvers/automations.ts, packages/server/modules/automations/repositories/automations.ts, packages/server/modules/automations/services/management.ts
=> feat: debug log status updates

packages/frontend/codegen.yml, packages/frontend/src/graphql/branch.js, packages/frontend/src/graphql/generated/graphql.ts, packages/server/modules/shared/helpers/envHelper.ts
=> bump fe1 branch query limit and disregard broken pagination logic

packages/viewer-sandbox/src/Sandbox.ts, packages/viewer/src/modules/SpeckleRenderer.ts, packages/viewer/src/modules/measurements/Measurements.ts, packages/viewer/src/modules/pipeline/SpecklePass.ts
Added a `visible` option to `MeasurementsOptions` which can show/hide measurements
=> Measurements visibility option

packages/frontend-2/lib/automations/composables/automationsStatus.ts, packages/frontend-2/lib/common/composables/singleton.ts, packages/frontend-2/lib/projects/composables/modelManagement.ts, packages/frontend-2/lib/projects/composables/projectManagement.ts, packages/frontend-2/lib/projects/composables/versionManagement.ts
=> fix(fe2): optimizing useLock composable & usages

packages/frontend/src/graphql/fragments/streams.ts, packages/frontend/src/graphql/generated/graphql.ts, packages/frontend/src/graphql/streams.js, packages/frontend/src/main/components/stream/uploads/FileProcessingItem.vue, packages/frontend/src/main/lib/common/apollo/helpers/apolloOperationHelper.ts, packages/frontend/src/main/pages/stream/TheUploads.vue, packages/server/assets/fileuploads/typedefs/fileuploads.graphql, packages/server/modules/core/graph/generated/graphql.ts, packages/server/modules/cross-server-sync/graph/generated/graphql.ts, packages/server/modules/fileuploads/graph/resolvers/fileUploads.ts, packages/server/modules/fileuploads/repositories/fileUploads.ts, packages/server/modules/fileuploads/services/management.ts, packages/server/modules/fileuploads/services/resultListener.ts, packages/server/modules/shared/utils/subscriptions.ts, packages/server/test/graphql/generated/graphql.ts
=> fix(fe1): super spammy stream file uploads page requests

packages/server/modules/cross-server-sync/services/commit.ts, packages/server/modules/cross-server-sync/services/project.ts
=> fix(server): onboarding stream clone url parsing issue

packages/frontend-2/components/project/CardImportFileArea.vue, packages/frontend-2/lib/core/api/fileImport.ts, packages/server/modules/comments/services/management.ts
fix(fe2): clearer error msg on failed upload
fix(fe2): missing project.commentThreads access w/ admin override
=> a couple of random FE2 fixes reported on Discord

packages/shared/src/observability/index.ts, packages/shared/src/observability/pinoClef.ts
=> feat: format log messages as clef

packages/preview-service/package.json, yarn.lock
Pinned the viewer version for the preview-service to the last viewer version before the API 2.0 merge as a temporary solution until the preview service is updated to use API 2.0
=>  preview-service <-> viewer API 2.0

packages/server/app.ts
=> feat: add graphql subscription metrics

.circleci/config.yml
=> feat: publish from the testing branch

packages/preview-service/package.json, yarn.lock
Updates the `preview-service` viewer version to the correct one
=> Updated viewer version for preview service

packages/viewer-sandbox/src/Extensions/BoxSelection.ts, packages/viewer-sandbox/src/Extensions/ExtendedSelection.ts, packages/viewer-sandbox/src/Sandbox.ts, packages/viewer-sandbox/src/main.ts, packages/viewer/readme.md, packages/viewer/src/modules/batching/BatchObject.ts
Fixed compile errors in sandbox
=> Fixed compile errors in sandbox

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/batching/TextBatch.ts, packages/viewer/src/modules/materials/Materials.ts
The viewer now supports text with no specified material/display style by defining it's own default text null material, similarly to how all the rest of the object types have
- `Materials` now defines it's null text material hash + material
- `TextBatch` now properly computes it's bounds
=> Support for Text with Null Material/DisplayStyle

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/batching/Batcher.ts
Added a check to make sure entire instance sets are considered for hw instancing, and also a check for each instance transform. Normally these aren't needed, but will have to stay in place until we figure out what to do about the object duplication inconsistency between viewer and connectors
=> Blender Instances Fix

packages/frontend-2/components/automation/ViewerFunctionRunItem.vue, packages/frontend-2/components/automation/ViewerResultRowItem.vue, packages/server/modules/automations/helpers/inputTypes.ts
=> fix: allow object result case message to be null

packages/server/modules/automations/index.ts
=> feat: make automate token scope public

packages/viewer-sandbox/src/Sandbox.ts, packages/viewer/src/modules/extensions/measurements/MeasurementsExtension.ts
Added functionality to clear all measurements in the `MeasurementsExtension`
- added `clearMeasurements` function to `MeasurementsExtension`
=> Added clearMeasurements functionality to the measurements extension

packages/viewer/src/modules/LegacyViewer.ts
Handles https://spockle.atlassian.net/browse/WBX-262
=> Highlighting in LegacyViewer

packages/frontend-2/plugins/004-redis.server.ts
=> fix(fe2): redis being initialized even without a valid connection string

packages/viewer-sandbox/src/Sandbox.ts, packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/SpeckleRenderer.ts
Fixes the [jira ticket](https://spockle.atlassian.net/browse/WBX-279) 
- `FilterMaterialOptions` are now preserved when flattening draw groups
=> Coloring issue

packages/frontend-2/components/automation/ViewerResultRowItem.vue, packages/frontend-2/lib/common/helpers/utils.ts, packages/frontend-2/lib/viewer/composables/ui.ts
=> fix(fe):automation result isolation didnt select objects

packages/frontend-2/lib/core/helpers/redis.ts, packages/frontend-2/package.json, packages/frontend-2/plugins/002-rum.ts, packages/frontend-2/plugins/004-redis.server.ts, packages/frontend-2/server/api/status.ts, packages/frontend-2/server/lib/core/helpers/observability.ts, packages/frontend-2/server/middleware/001-logging.ts, packages/frontend-2/server/tsconfig.json, packages/frontend-2/server/utils/logger.ts, packages/server/logging/expressLogging.ts, utils/helm/speckle-server/templates/frontend_2/deployment.yml, utils/helm/speckle-server/templates/redirect.ingress.yml, yarn.lock
=> feat(fe2): proper health probe endpoint - /api/status - [WBX-287]

packages/viewer/src/modules/batching/MeshBatch.ts
Fixes the following issues:
- https://spockle.atlassian.net/browse/WBX-342
- https://spockle.atlassian.net/browse/WBX-341
=> WBX-8 Viewer fixes

packages/dui3/store/hostApp.ts
=> feat(dui3): removes dupe code for receiveResult event

packages/frontend-2/lib/core/helpers/redis.ts, packages/frontend-2/package.json, packages/frontend-2/plugins/002-rum.ts, packages/frontend-2/plugins/004-redis.server.ts, packages/frontend-2/server/api/status.ts, packages/frontend-2/server/lib/core/helpers/observability.ts, packages/frontend-2/server/middleware/001-logging.ts, packages/frontend-2/server/tsconfig.json, packages/frontend-2/server/utils/logger.ts, packages/server/logging/expressLogging.ts, utils/helm/speckle-server/templates/frontend_2/deployment.yml, utils/helm/speckle-server/templates/redirect.ingress.yml, yarn.lock
=> feat: fe2 status check endpoint w/ proper redis cleanup

packages/frontend-2/components/viewer/measurements/Options.vue
It was requested that the "Reset Measurements" button be removed. I have done this. 
-Remove button in pocket portal
=> Remove "Reset Measurements" button

packages/frontend-2/app.vue, packages/frontend-2/components/common/EditableTitleDescription.vue, packages/frontend-2/components/project/model-page/Versions.vue, packages/frontend-2/components/project/page/discussions/Header.vue, packages/frontend-2/components/project/page/models/Header.vue, packages/frontend-2/components/projects/ProjectDashboardCard.vue, packages/frontend-2/components/viewer/PreSetupWrapper.vue, packages/frontend-2/pages/projects/[id]/index.vue, packages/ui-components/src/components/layout/PageTabs.vue
Changes from 1 on 1 with Benjamin, reviewing new project tabs
=> Updates from Benjamin on Project page

packages/frontend-2/components/viewer/AnchoredPoints.vue
Make it clearer that you are following someone or being followed.
- Dark blue outline and top centred. The top centred element can go behind menus on smaller screens but I don't think it matters that much. The current "Stop Following [...]" button is also positioned on top of the Selection Info panel (bug) so we have to find a new place for it.
- Dedicated "Stop" button 
- Not using Vue Portal
=> Make Following clearer

packages/server/modules/accessrequests/tests/streamAccessRequests.spec.ts, packages/server/modules/notifications/services/handlers/mentionedInComment.ts, packages/server/modules/notifications/services/handlers/newStreamAccessRequest.ts, packages/server/modules/notifications/services/handlers/streamAccessRequestApproved.ts, packages/server/modules/serverinvites/services/inviteCreationService.js
I've updated "stream" to "project" in a couple of our emails.
=> Use FE2 language in emails

packages/viewer/src/modules/batching/InstancedMeshBatch.ts, packages/viewer/src/modules/batching/MeshBatch.ts
Fixed a source of hardlocking by infinite while loop.
Unofficially, this would constitute `undead-patch-#3`
=> Hardlock-patch

packages/frontend-2/components/onboarding/checklist/v1.vue
- Add relative, so the close button is in the div
- Only show the "I'll do it later" button when all items haven't been completed.
=> FE2 Onboarding - Fix bugs reported by Matteo

packages/frontend-2/lib/viewer/composables/setup/postSetup.ts, packages/server/modules/cross-server-sync/services/commit.ts, packages/shared/src/core/helpers/utility.ts
=> fix(server): commit import not finishing correctly

packages/ui-components/src/components/layout/GridListToggle.vue
[JIRA TICKET
](https://spockle.atlassian.net/jira/software/c/projects/WBX/issues/WBX-399?filter=myopenissues&jql=project%20%3D%20%22WBX%22%20AND%20assignee%20IN%20%28currentUser%28%29%29%20AND%20statusCategory%20in%20%28%22To%20Do%22%2C%20%22In%20Progress%22%29%20AND%20text%20~%20%22list%22%20ORDER%20BY%20created%20DESC)
- Swap order of grid and list in the component to reflect new default
=> refactor(ui-components): swap order of list and grid toggle to reflect new default

packages/frontend-2/plugins/002-rum.ts
=> fix(fe2): overriding some view names that datadog resolves incorrectly

packages/frontend-2/plugins/002-rum.ts, packages/frontend-2/type-augmentations/vue.d.ts
=> fix(fe2): further datadog view name improvements

packages/frontend-2/components/error/page/ProjectInviteBanner.vue, packages/frontend-2/plugins/002-rum.ts, packages/frontend-2/type-augmentations/window.d.ts
=> fix(fe2): further datadog view name resolution improvements

utils/helm/speckle-server/templates/frontend_2/deployment.yml
Add survicate_workspace_key to helm chart
=> feat(helm): Add survicate_workspace_key to FE2 helm chart

packages/frontend-2/middleware/redirects.global.ts, packages/frontend-2/plugins/survicate.client.ts
=> fix(fe2): survicate preventing the app from loading when adblock is on

.circleci/config.yml, packages/server/package.json, yarn.lock
=> fix: disable rover checks for now

utils/helm/speckle-server/templates/frontend_2/deployment.yml
=> feat: recreate the deployment for FE2 to get around caching issues

packages/frontend-2/server/plugins/prevent404Cache.ts, utils/helm/speckle-server/templates/frontend_2/deployment.yml
=> fix(fe2): prevent 404 asset requests being cached

packages/objectloader/src/index.js, packages/server/modules/cli/commands/download/commit.ts, packages/server/modules/cli/commands/download/project.ts, packages/server/modules/cross-server-sync/services/commit.ts, packages/server/modules/cross-server-sync/services/project.ts
=> fix(server): cross server sync not respecting token

packages/frontend-2/plugins/001-logger.ts, packages/frontend-2/plugins/002-rum.ts
=> feat(fe2): better error tracking to DataDog

packages/preview-service/routes/preview.js
Doing an explicit `resize` before starting the turntable to make sure the projection matrix is updated to the latest container size
=> Fixed preview-image incorrect aspect

README.md
I've simply updated the link to the web app in the README
=> Update link to the web app in the README

packages/viewer/readme.md
=> Update viewer readme file with the new documentation

packages/viewer/src/modules/extensions/SectionTool.ts
=> fix(viewer): broken import to dep

packages/frontend-2/lib/core/composables/error.ts, packages/frontend-2/lib/core/helpers/observability.ts, packages/frontend-2/nuxt.config.ts, packages/frontend-2/plugins/001-logger.ts, packages/frontend-2/plugins/002-rum.ts, packages/frontend-2/type-augmentations/nuxt.d.ts
=> fix(fe2): low level fatal server errors not being logged to RUM

packages/dui3/components/receive/Wizard.vue, packages/dui3/components/send/Wizard.vue
=> Chore (dui3): wizard title for project and model + emit close dialog before await operations

packages/frontend-2/server/plugins/prevent404Cache.ts
=> fix(fe2): index.html 404 being cached

packages/dui3/lib/bindings/definitions/IConfigBinding.ts, packages/dui3/store/config.ts
@oguzhankoral I've simplified the settings part a bit - it's going to be paired up with another PR on the .net side of things (into the dui3/alpha branch). Giving you a heads up as sketchup might need updating if it was using this!
=> feat(dui3): some quick config changes/simplifying things

packages/viewer/src/modules/extensions/DiffExtension.ts
Handles https://linear.app/speckle/issue/WEB-811/make-camera-reset-optional-when-diffing
=> WEB-811 - No re-focus when diffing

packages/ui-components/src/components/layout/Dialog.vue
=> fix(dui3): correctly returns the fallback style

packages/dui3/components/accounts/Menu.vue, packages/dui3/components/header/NavBar.vue, packages/dui3/components/model/ActionsDialog.vue, packages/dui3/components/model/Receiver.vue, packages/dui3/components/model/Sender.vue, packages/dui3/components/receive/Wizard.vue, packages/dui3/components/send/Wizard.vue, packages/dui3/components/wizard/ModelSelector.vue, packages/dui3/components/wizard/ProjectSelector.vue, packages/dui3/pages/test.vue
Hopefully does what it says on the tin.
=> fix(dui3): scrollable dialogs in old chromium (revit)

packages/dui3/components/model/Receiver.vue
Better handling on model receiver cards that expire while the file is closed - theoretically clicking update from the notification button should now always enforce bringing in the latest version down. 
Link to issue: https://www.notion.so/speckle/ce16b30fa1234278800ca9a4d1621c96?v=5670ffc49f4d4155bc6a262c14135cb0&p=49943ae8173b494ebc0cea8fc92e286b&pm=s
=> feat(dui3): fresh update on file open re expired receiver

packages/dui3/lib/bridge/sketchup.ts
=> Fix(dui3): outdated emit call for upload in sketchup bridge

packages/server/modules/core/services/users.js, packages/server/modules/core/tests/users.spec.js
When user signup using OIDC the email was not marked as verified.
=> fix(server): avoid removing verified email from user

packages/dui3/components/model/Receiver.vue, packages/dui3/store/hostApp.ts
Fixes https://spockle.atlassian.net/browse/CNX-9505
=> fix(dui3): receive update shennanigans fixed

packages/frontend-2/pages/projects/[id]/index.vue
- Use isAutomateEnabled to conditionally render Automate tab
=> fix(fe2): Hide automate tab if env is not present or false

packages/frontend-2/lib/projects/composables/automationManagement.ts, packages/server/modules/index.js, utils/helm/speckle-server/templates/frontend_2/deployment.yml
=> fix: nuxt public feature flag env var

packages/frontend-2/components/automate/functions/page/Header.vue
=> Hide "New Function" button

utils/helm/speckle-server/templates/server/deployment.yml, utils/helm/speckle-server/values.schema.json, utils/helm/speckle-server/values.yaml
=> feat(helm): add configurable encryptionKeys path value to helm chart

packages/viewer-sandbox/src/Extensions/ExtendedSelection.ts, packages/viewer/src/index.ts, packages/viewer/src/modules/SpeckleRenderer.ts, packages/viewer/src/modules/batching/Batcher.ts
Fixed some regression introduced in 2.18.16:
- InstancedBatchObject type is now being exported
- Fixed an issue where instances were not having their runtime transformations updated. 
- Fixed an issue where transparency objects were incorrectly casting and receiving shadows
=> WEB-999/Regression fixes

packages/server/modules/core/graph/resolvers/streams.js
=> chore(server): remove whatt log

packages/server/modules/automate/migrations/20240305120620_automate.ts, packages/server/modules/automate/migrations/20240321092858_triggers.ts, packages/server/modules/automate/migrations/20240404075414_revision_active.ts, packages/server/modules/automate/migrations/20240404173455_automation_token.ts, packages/server/modules/automate/migrations/20240507075055_add_function_run_timestamps.ts, packages/server/modules/betaAutomations/migrations/20240304143445_rename_tables.ts, packages/server/modules/core/dbSchema.ts, packages/server/modules/shared/helpers/envHelper.ts
=> chore(server): remove conditional migration flag

packages/frontend-2/components/auth/third-party/LoginBlock.vue, packages/frontend-2/components/developer-settings/SectionHeader.vue, packages/frontend-2/composables/env.ts, packages/frontend-2/pages/developer-settings.vue
=> fix(fe2): using SSR apiOrigin instead of CSR apiOrigin in vue templates

packages/viewer/src/modules/SpeckleRenderer.ts
Handles https://linear.app/speckle/issue/WEB-1066/line-not-clickable-when-scene-volume-has-any-0-value-components. It wasn't the volume 0 component's fault, even though the volume expansion is still not done correctly for 0 component value volumes, but rather improper index value checking
=> WEB-1066: Fixed line selection that didn't work for some lines

packages/dui3/components/report/Item.vue
- move details from tooltip to expandable item
- make details copyclipboardable
=> Feat (dui3): report: move details from tooltip to expandable item

packages/frontend-2/components/automate/automation/CreateDialog.vue
=> fix(fe2): not always jumping to step 2 in Create Automate dialog

packages/frontend/src/main/components/comments/CommentThreadViewer.vue
=> fix(fe1): Undefined 'commentSlideShow' error in CommentThreadViewer.vue

packages/dui3/components/model/Sender.vue, packages/dui3/lib/models/card/send.ts, packages/dui3/store/hostApp.ts
=> https://spockle.atlassian.net/browse/CNX-9427

packages/frontend-2/components/automate/automation/CreateDialog.vue
=> feat(fe2): removing automation creation success step

packages/frontend-2/components/project/page/automations/Tab.vue, packages/frontend-2/pages/functions/[fid].vue, packages/frontend-2/pages/functions/index.vue, packages/frontend-2/pages/projects/[id]/index.vue, packages/frontend-2/pages/projects/[id]/index/automations/[aid].vue
=> fix(fe2): refetch on automate page open

packages/frontend-2/components/automate/automation/CreateDialog.vue, packages/frontend-2/components/automate/automation/create-dialog/FunctionParametersStep.vue, packages/frontend-2/components/form/json/StringControlRenderer.vue, packages/frontend-2/components/project/page/automation/FunctionSettingsDialog.vue, packages/frontend-2/lib/automate/composables/jsonSchema.ts
=> feat(fe2): prevent automation param validation until submit

packages/frontend-2/lib/viewer/composables/setup/postSetup.ts
Quick fix to allow time to troubleshoot issue without affecting hackathon
=> fix(fe2) - Temp fix initial zoom

packages/server/codegen.yml, packages/server/modules/automate/clients/executionEngine.ts, packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/helpers/graphTypes.ts, packages/server/modules/core/graph/generated/graphql.ts
=> feat(fe2): retrieving gh orgs from exec engine

packages/server/modules/automate/clients/executionEngine.ts, packages/server/modules/automate/graph/resolvers/automate.ts
=> feat(fe2): working function release search

packages/server/modules/automate/services/runsManagement.ts
=> fix: do not allow same status override

packages/server/modules/core/services/streams/onboarding.ts
Not sure if this is the best place to update the sample `First Project` description, but adding in model credit to Beijia 
- onboarding
=> chore: updates onboarding to set description of first project

packages/viewer/src/modules/LegacyViewer.ts
=> Enabled outlines for highlight WEB-1081

yarn.lock
=> chore: upgrading deps to fix vulnerabilities

packages/server/assets/serverinvites/typedefs/serverInvites.graphql, packages/server/modules/core/tests/apitokens.spec.ts, packages/server/modules/core/tests/batchCommits.spec.ts, packages/server/modules/core/tests/generic.spec.js, packages/server/modules/core/tests/usersGraphql.spec.ts, packages/server/modules/serverinvites/tests/invites.spec.js, packages/server/modules/shared/authz.ts, packages/server/modules/shared/index.js, packages/server/modules/shared/test/authz.spec.js
=> fix(server): more legible auth errors

packages/server/modules/automate/index.ts, packages/server/modules/automate/services/tracking.ts, packages/server/modules/automate/tests/trigger.spec.ts, packages/server/modules/core/services/users.js
=> feat: optionally add userId to automate backend tracking

packages/dui3/components/model/CardBase.vue
Autocad crashes and also I believe we should have done before.
=> Fix (dui3): Do not highlight on progress

packages/viewer/src/modules/batching/InstancedMeshBatch.ts, packages/viewer/src/modules/batching/PrimitiveBatch.ts
Fixes https://linear.app/speckle/issue/WEB-1104/sum-possible-issues-with-coloring-on-a-particular-stream
=> Fixed WEB-1104: Incorrect coloring

packages/dui3/components/model/ActionsDialog.vue, packages/dui3/components/model/CardBase.vue, packages/dui3/components/model/Sender.vue, packages/dui3/components/report/Base.vue, packages/dui3/store/hostApp.ts
https://spockle.atlassian.net/browse/DUI3-303
=> feat(dui3): keeps report alive post notification dismissal + adds it to the card actions menu if present

.circleci/config.yml, packages/frontend-2/pages/functions/[fid].vue, packages/frontend-2/pages/functions/index.vue, packages/frontend-2/pages/projects/[id]/index/automations.vue
=> fix(fe2): redirect away from fns page if not authenticated

packages/dui3/components/model/Receiver.vue
=> feat(dui3): catches receive

packages/server/modules/core/services/objects.js
=> fix(objects): logger templating

packages/server/modules/core/services/objects.js
=> fix(objects): use the correct speckle_type value on objects

utils/helm/speckle-server/values.yaml
=> feat(objs): adds corresponding values.yaml

packages/server/modules/core/rest/diffDownload.js, packages/server/modules/core/rest/diffUpload.js, packages/server/modules/core/rest/upload.js
=> fix(objects): use proper seq log templating

packages/server/modules/auth/domain/logic.ts, packages/server/modules/auth/domain/types.ts, packages/server/modules/auth/strategies/oidc.js, packages/server/modules/auth/tests/unit/logic.spec.ts
=> Alessandro/web 1094 fix OIDC signup name and organization

packages/frontend-2/lib/projects/composables/previewImage.ts, packages/server/modules/previews/index.js
=> fix(fe2): preview images being cached for too long

packages/server/modules/core/rest/upload.js
=> fix(objects): proper log templating

packages/frontend-2/components/viewer/explorer/StringFilterItem.vue
=> fix: add title to StringFilterItems so full name can be hovered

packages/server/modules/auth/defaultApps.ts, packages/server/modules/index.js
=> fix(server): startup crash if automate not enable due to missing scope for app

packages/server/modules/index.js
=> chore: removing unnecessary automate fix

packages/objectsender/src/utils/Serializer.ts
=> fix: object-sender, allows empty strings and zeros props to be serialized

.circleci/deployment/values/speckle-server.values.yaml, .pre-commit-config.yaml, utils/helm/speckle-server/templates/_helpers.tpl, utils/helm/speckle-server/templates/fileimport_service/deployment.yml, utils/helm/speckle-server/templates/frontend_2/deployment.yml, utils/helm/speckle-server/templates/monitoring/deployment.yml, utils/helm/speckle-server/templates/preview_service/deployment.yml, utils/helm/speckle-server/templates/tests/deployment.yml, utils/helm/speckle-server/templates/webhook_service/deployment.yml, utils/helm/speckle-server/values.schema.json, utils/helm/speckle-server/values.yaml
Logs in CI are now pretty-printed:
It is now possible to have a tilt-deployed local development environment pretty print logs.
=> feat(helm): allow pretty-format logging to be enabled in helm chart

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/batching/Batcher.ts, packages/viewer/src/modules/batching/PrimitiveBatch.ts, packages/viewer/src/modules/materials/Materials.ts
Points and PointClouds are now properly colored when filtering by properties https://linear.app/speckle/issue/WEB-1167/sum-point-filtering-fixes
=> Colored Points by Properties Fix

packages/viewer-sandbox/src/main.ts
=> Fixed sandbox lint error

packages/frontend-2/lib/projects/composables/previewImage.ts, packages/preview-service/routes/preview.js
=> fix(fe2): panoramic previews not triggering on hover

packages/server/modules/shared/index.js
- I need to authorize some operations based on workspace role (admin, member, or guest)
- The current query in `authorizeResolver` assumes a `resourceId` column, but workspaces acl named the relevant column `workspaceId`
- Adds `getUserAclEntry` and changes query logic based on acl table name
=> fix(workspaces): construct acl query based on table name

packages/server/modules/core/tests/integration/user-emails.spec.ts, packages/server/modules/emails/tests/verifications.spec.ts, packages/server/modules/user-emails/constants.ts, packages/server/modules/user-emails/domain/types.ts, packages/server/modules/user-emails/migrations/20240703084247_user-emails.ts
- create a new module for user-emails (I'm not sure if we want it inside another module, anyway we can move it any time)
- create user_emails table
- create UserEmail domain type
=> feat(user-emails): create user emails table and type

packages/objectsender/.npmignore
=> chore(objectsender): configured .npmignore

packages/viewer/rollup.config.js
=> fix(viewer): dev command not working

packages/server/app.ts, packages/server/eslint.config.mjs, packages/server/logging/expressLogging.ts, packages/server/modules/auth/tests/unit/logic.spec.ts, packages/server/modules/core/graph/resolvers/objects.ts, packages/server/modules/core/services/streams/onboarding.ts, packages/server/modules/core/tests/integration/createUser.spec.ts, packages/server/modules/core/tests/streams.spec.ts, packages/server/modules/serverinvites/services/validation.ts
=> chore(core): eslint rule to avoid relative imports

packages/dui3/components/report/Item.vue
=> Feat(dui3): add button for errored objects to see on web

packages/dui3/components/report/Item.vue
Tested...
Sender report 👇
Receiver report 👇
=> Fix(dui3): failed send report item

packages/dui3/components/report/Base.vue
=> Feat(dui3): conversion report filters

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/LegacyViewer.ts, packages/viewer/src/modules/extensions/SelectionExtension.ts, packages/viewer/src/modules/loaders/GeometryConverter.ts, packages/viewer/src/modules/loaders/Speckle/SpeckleConverter.ts, packages/viewer/src/modules/loaders/Speckle/SpeckleGeometryConverter.ts, packages/viewer/src/modules/loaders/Speckle/SpeckleLoader.ts, packages/viewer/src/modules/materials/Materials.ts
Viewer basic implementation for DUI3 render material structure
=> DUI3 render materials implementation

packages/frontend-2/components/automate/function/Card.vue, packages/frontend-2/components/automate/function/create-dialog/DetailsStep.vue, packages/frontend-2/components/form/MarkdownEditor.vue, packages/ui-components/src/components/form/Tags.vue
Quick fix for the reported bug around Create Function Dialog. 
I wasn't able to test this locally, but this should greatly improve the dialog. I'll check it again once it is merged.
=> fix: update create function dialog to match design system

packages/server/modules/workspacesCore/graph/resolvers/workspacesCore.ts
=> fix(workspaces): match workspaces and workspacesCore resolvers

.circleci/config.yml, packages/server/.mocharc.js
=> ci(feature flags): test workspaces

packages/frontend-2/components/error/page/GenericErrorBlock.vue, packages/frontend-2/components/project/model-page/versions/Card.vue, packages/frontend-2/components/project/page/models/Card.vue, packages/frontend-2/lib/common/generated/gql/graphql.ts, packages/frontend-2/lib/core/composables/server.ts, packages/server/modules/cross-server-sync/services/commit.ts
=> feat(fe2): show reqId in error pages

packages/server/modules/cli/commands/db/seed/users.js, packages/server/package.json, yarn.lock
=> chore(seed): fix seed using library to generate unique values

utils/helm/speckle-server/templates/_helpers.tpl, utils/helm/speckle-server/templates/frontend_2/deployment.yml, utils/helm/speckle-server/values.schema.json, utils/helm/speckle-server/values.yaml
=> feat(helm): expose workspace module feature flag

packages/server/modules/workspaces/tests/integration/projects.graph.spec.ts
- I wrote a flaky test
- I made it not flaky
=> fix(workspaces): better logic in workspace project pagination test

packages/dui3/components/common/ProjectModelGroup.vue, packages/dui3/components/model/CardBase.vue, packages/dui3/components/model/Receiver.vue
Semi chaotic video with changes: https://www.loom.com/share/8cbf6c8dcc0c4576b0c13c7a6c7a2c32?sid=11b36792-3071-4f69-8c14-6968fd7d1c75
[CNX-168: UI: Horrible UX on main receive button click](https://linear.app/speckle/issue/CNX-168/ui-horrible-ux-on-main-receive-button-click)
=> feat(dui3): clarifies intent and behaviour of main receive button, and adds some minor styling changes

packages/dui3/plugins/00.bindings.ts
Ralph validated with Graphisoft, this is the way.
=> Fix(dui3): archicad load bridge object

packages/frontend-2/components/settings/Dialog.vue, packages/frontend-2/lib/common/generated/gql/graphql.ts, packages/ui-components/src/components/layout/sidebar/Sidebar.stories.ts, packages/ui-components/src/components/layout/sidebar/menu/group/Item.vue
Adds the three coming soon pages, security, billing and regions
=> Feat: Add coming soon settings pages

packages/frontend-2/lib/common/generated/gql/graphql.ts, packages/server/assets/workspacesCore/typedefs/workspaces.graphql, packages/server/modules/core/graph/generated/graphql.ts, packages/server/modules/cross-server-sync/graph/generated/graphql.ts, packages/server/modules/workspaces/domain/operations.ts, packages/server/modules/workspaces/graph/resolvers/workspaces.ts, packages/server/modules/workspaces/repositories/workspaces.ts, packages/server/test/graphql/generated/graphql.ts
=> feat(workspaceDomains): delete domain

packages/server/assets/workspacesCore/typedefs/workspaces.graphql, packages/server/modules/shared/test/unit/eventBus.spec.ts, packages/server/modules/workspaces/domain/operations.ts, packages/server/modules/workspaces/graph/dataloaders/workspaces.ts, packages/server/modules/workspaces/graph/resolvers/workspaces.ts, packages/server/modules/workspaces/repositories/workspaces.ts, packages/server/modules/workspaces/services/management.ts, packages/server/modules/workspaces/tests/integration/repositories.spec.ts, packages/server/modules/workspaces/tests/unit/services/management.spec.ts
=> feat(workspaces): create domains resolver for workspace

packages/server/assets/core/typedefs/userEmails.graphql, packages/server/modules/core/graph/generated/graphql.ts, packages/server/modules/core/graph/resolvers/userEmails.ts, packages/server/modules/cross-server-sync/graph/generated/graphql.ts, packages/server/modules/emails/services/verification/request.ts, packages/server/test/graphql/generated/graphql.ts
=> feat(emailVerification): add email verification mutation for all emails

packages/dui3/components/model/CardBase.vue
=> Feat(dui3): show model path in model card

packages/server/assets/workspacesCore/typedefs/workspaces.graphql, packages/server/modules/core/graph/generated/graphql.ts, packages/server/modules/cross-server-sync/graph/generated/graphql.ts, packages/server/modules/shared/test/unit/eventBus.spec.ts, packages/server/modules/workspaces/services/management.ts, packages/server/modules/workspaces/tests/integration/repositories.spec.ts, packages/server/modules/workspacesCore/domain/types.ts, packages/server/modules/workspacesCore/migrations/20240808091944_add_workspace_discovery_flag.ts, packages/server/test/graphql/generated/graphql.ts, workspace.code-workspace
=> feat(workspaces): add discoverability flag

packages/dui3/lib/bridge/sketchup.ts
Bilal claims that he will be more happy
=> Chore(dui3): Update sketchup pre-conversion progress text

packages/frontend-2/components/settings/workspaces/Security.vue, packages/server/modules/shared/services/eventBus.ts, packages/server/modules/shared/test/unit/eventBus.spec.ts, packages/server/modules/workspaces/graph/resolvers/workspaces.ts, packages/server/modules/workspaces/services/management.ts, packages/server/modules/workspaces/tests/unit/services/management.spec.ts, packages/server/modules/workspacesCore/domain/types.ts
=> feat(workspace): auto enable discoverability on first domain registration

packages/dui3/components/wizard/list/ModelCard.vue
=> Fix(dui3): truncate model item model path

packages/frontend-2/components/viewer/PreSetupWrapper.vue, packages/frontend-2/components/viewer/Scope.vue, packages/frontend-2/lib/viewer/composables/ui.ts
=> fix(fe2): fixes for too early viewer state init

packages/objectloader/src/index.js
objectloader was caching and retrieving from cache broken Objects API responses
=> fix(objectloader): prevent cache read/write for broken data

.circleci/config.yml, packages/frontend-2/composables/globals.ts, packages/shared/src/environment/index.ts, utils/helm/speckle-server/templates/_helpers.tpl, utils/helm/speckle-server/templates/frontend_2/deployment.yml, utils/helm/speckle-server/values.schema.json, utils/helm/speckle-server/values.yaml
Adds feature flag to be used for the multiple emails FE in settings
=> Feat: Add feature flag for multiple emails

packages/server/modules/core/domain/userEmails/operations.ts, packages/server/modules/core/errors/userEmails.ts, packages/server/modules/core/repositories/userEmails.ts, packages/server/modules/core/tests/integration/userEmails.spec.ts
=> fix(useremails): avoid creating same email twice

packages/server/assets/workspacesCore/typedefs/workspaces.graphql
=> fix(workspaces): allow users to create workspaces

packages/frontend-2/components/viewer/Scope.vue, packages/frontend-2/components/viewer/anchored-point/Thread.vue, packages/frontend-2/lib/common/generated/gql/gql.ts, packages/frontend-2/lib/common/generated/gql/graphql.ts, packages/frontend-2/pages/projects/[id]/models/[modelId]/index.vue
=> fix(fe2): viewer comments not docking to bottom properly

packages/objectloader/src/index.js, packages/objectloader/types/index.d.ts, packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/loaders/Speckle/SpeckleLoader.ts
`object-loader` now has a `getTotalObjectCount` function that can be used autonomously, separate of any loading process. There is an un-ideal aspect of it, where we parse the root object string data in order to get the closure length, but the as an alternative we can either do string gymnastics which might be as inefficient as parsing in the end. Or, make sure we only parse the root object once, regardless where that happens.
Additionally, the `SpeckleLoader` now uses `getTotalObjectCount` to provide correct progress values in `LoaderEvent.LoadProgress` event addressing the reported issue
=> `getTotalObjectCount` implementation for object-loader

packages/server/assets/workspacesCore/typedefs/workspaces.graphql, packages/server/modules/core/graph/generated/graphql.ts, packages/server/modules/cross-server-sync/graph/generated/graphql.ts, packages/server/modules/workspaces/graph/resolvers/workspaces.ts, packages/server/modules/workspacesCore/graph/resolvers/workspacesCore.ts, packages/server/test/graphql/generated/graphql.ts, packages/server/test/graphql/workspaces.ts
=> chore(server): move workspace leave resolver

packages/frontend-2/lib/common/generated/gql/gql.ts, packages/frontend-2/lib/common/generated/gql/graphql.ts, packages/frontend-2/pages/dashboard.vue
There is no empty state yet on the dashboard, this add a card to prompt the user to create their first project.
=> Feat: Add empty state to dashboard

packages/frontend-2/lib/settings/composables/menu.ts
=> feat(multiEmails): add multi email module with feature flag

packages/frontend-2/components/project/page/models/Card.vue, packages/frontend-2/lib/common/generated/gql/graphql.ts
Issue raised by @jsdbroughton 
Before:
After:
=> fix(automate): move automate status circle on project model card

packages/server/assets/workspacesCore/typedefs/workspaces.graphql
=> fix(fe2): remove offending scope from workspaceInvites field

packages/frontend-2/components/auth/WorkspaceInviteHeader.vue, packages/frontend-2/components/workspace/invite/Block.vue
=> feat(fe2): proper unregistered accept/decline support

packages/frontend-2/components/workspace/invite/Block.vue
=> fix(fe2): workspace invite sign out cta fix

packages/viewer/src/modules/SpeckleRenderer.ts, packages/viewer/src/modules/objects/SpeckleInstancedMesh.ts
Fixed an issue where instances would incorrectly use gradient index vertex buffers when multiple instanced groups were involved
=> Instances Gradient Index Buffer Fix

packages/server/modules/gatekeeper/services/validateLicense.ts
=> feat(gatekeeper): allow license bypass in testing envs

packages/frontend-2/components/settings/workspaces/members/InvitesTable.vue, packages/ui-components/src/components/layout/Table.vue
=> fix(fe2): missing tooltips for invite resend/delete

packages/frontend-2/components/project/page/models/Card.vue, packages/ui-components/src/components/form/select/Base.vue
Fixes the z-index issue of the dropdown, has to be 40 due to other z-index used that it should also overlap
=> Fix: Dropdown z-index

packages/frontend-2/components/project/page/models/StructureItem.vue
This is not a confirmed fix, as I was unable to recreate the problem locally, but this implements the same logic as the card view, which did not have this problem.
=> fix(fe2): Use NuxtLink instead of onclick for List Cards

packages/server/modules/automate/services/trigger.ts
=> fix(automate): fix on model version create error log

packages/server/modules/workspaces/graph/resolvers/workspaces.ts
=> fix(workspaces): await authorization

packages/frontend-2/components/project/page/models/StructureItem.vue
Revert changes until better solution is found
=> fix(fe2): Revert changes to structureitem

packages/frontend-2/components/header/NavUserMenu.vue, packages/frontend-2/components/project/model-page/Header.vue, packages/frontend-2/components/project/models/BasicCardView.vue, packages/frontend-2/components/projects/ProjectDashboardCard.vue, packages/frontend-2/components/viewer/Sidebar.vue, packages/ui-components/src/components/layout/sidebar/menu/group/Item.vue
Michal is not available to fully review the Sidebar until later this week. 
There were a few smaller items that I know are wrong, so I have fixed these in this branch, and will follow up with another branch when Michal has had a chance to feedback.
=> refactor(ui-components): Update Sidebar to Designs

packages/dui3/components/common/ProjectModelGroup.vue, packages/dui3/components/header/NavBar.vue, packages/dui3/components/header/UserMenu.vue, packages/dui3/components/model/CardBase.vue, packages/dui3/components/model/Receiver.vue, packages/dui3/components/model/Sender.vue, packages/dui3/pages/index.vue
- adds a beta label in navbar
- removes shadow from menu button
- densifies/declutters a bit the UI (very wip, more of a bandaid)
=> feat: adds beta banner in nav & densification

packages/viewer/src/modules/batching/Batcher.ts
We're now checking for both `undefined` and `null` for color materials. 
`undead-patch` # 8
=> Color material `undead-patch`

packages/frontend-2/components/dashboard/Sidebar.vue, packages/frontend-2/components/error/page/GenericErrorBlock.vue, packages/frontend-2/components/error/page/GenericUnauthorizedBlock.vue
Fixes sidebar being shown when user is not logged in, some small styling updates as well
=> Fix: Dont show sidebar when logged out

packages/frontend-2/components/common/EmptySearchState.vue, packages/frontend-2/components/common/GenericEmptyState.vue, packages/frontend-2/components/workspace/ProjectList.vue
=> Fix: Dont show workspace projects empty state during search

packages/frontend-2/components/auth/WorkspaceInviteHeader.vue, packages/frontend-2/components/project/CardImportFileArea.vue, packages/frontend-2/components/settings/shared/ChangeRoleDialog.vue, packages/frontend-2/components/settings/shared/DeleteUserDialog.vue, packages/frontend-2/components/settings/shared/projects/index.vue, packages/frontend-2/components/settings/user/Developer.vue, packages/frontend-2/components/settings/workspaces/members/MembersTable.vue, packages/frontend-2/components/workspace/invite/Block.vue, packages/frontend-2/lib/common/generated/gql/gql.ts, packages/frontend-2/lib/common/generated/gql/graphql.ts, packages/frontend-2/lib/workspaces/composables/management.ts, packages/ui-components/src/components/global/ToastRenderer.vue
Adds the button to delete a user from a workspace
=> Feat: Added delete user from workspace button

packages/dui3/lib/common/generated/gql/graphql.ts, packages/frontend-2/lib/common/generated/gql/graphql.ts, packages/frontend/src/graphql/generated/graphql.ts, packages/server/assets/blobstorage/typedefs/blobstorage.graphql, packages/server/assets/core/typedefs/server.graphql, packages/server/modules/blobstorage/graph/resolvers/index.ts, packages/server/modules/core/graph/generated/graphql.ts, packages/server/modules/core/services/generic.js, packages/server/modules/core/tests/graph.spec.js, packages/server/modules/cross-server-sync/graph/generated/graphql.ts, packages/server/test/graphql/generated/graphql.ts
It is possible for the limits used to validate appropriate Send Operations to differ between servers.
The connectors should be able to query the server to determine the currently configured limit for that server.
This PR exposes the required data via the ServerInfo query
- ServerInfo object now exposes a configuration object of type `ServerConfiguration`, which includes two additional (read-only) properties
```
configuration {
objectSizeLimitBytes: Int!
objectMultipartUploadSizeLimitBytes: Int!
}
```
- The blobstorage module extends `ServerConfiguration` to include an additional related property, `blobSizeLimitBytes`, and deprecates the existing `blobSizeLimitBytes` directly on `ServerInfo`.
=> feat(graphql/serverinfo): provide maximum object size in bytes

packages/server/logging/loggingHelper.spec.ts, packages/server/logging/loggingHelper.ts, packages/server/modules/core/rest/diffUpload.ts
=> chore(server): convert some files to typescript with minimal changes

packages/frontend-2/components/settings/Dialog.vue, packages/frontend-2/components/settings/workspaces/General/EditAvatar.vue, packages/ui-components/src/components/layout/sidebar/menu/group/Item.vue, packages/ui-components/src/components/user/AvatarEditable.vue
- Fix coming soon labels colors
- Update workspaces icon in settings
- Added basic support for default image (space avatar) for avatar editor, will improve further when updating the design of the component, just to make it functional for now
=> Fix: Change label color for disabled state in MenuGroupItem

packages/dui3/components/form/json/EnumControlRenderer.vue, packages/dui3/components/model/Sender.vue, packages/dui3/components/receive/Wizard.vue, packages/dui3/components/send/FiltersAndSettings.vue, packages/dui3/components/send/Settings.vue, packages/dui3/components/send/Wizard.vue, packages/dui3/pages/index.vue
Fixes/changes: 
- cropping on settings dropdowns in dialog [CNX-345: Settings Dropdown options cropped by dialog](https://linear.app/speckle/issue/CNX-345/settings-dropdown-options-cropped-by-dialog)
- adds settings under foldable section
- only displays settings if there's any present
- unifies arrows [CNX-377: Align Publish/Load button icons](https://linear.app/speckle/issue/CNX-377/align-publishload-button-icons)
- note: also removes model name from change filter dialog to prevent overflow (visible in screenshot below)
EDIT
=> fix(dui3): various other fixes

packages/ui-components/src/components/layout/sidebar/menu/group/Group.vue
=> fix(fe2): Add padding to sidebar sub items too

packages/frontend-2/components/project/page/models/StructureItem.vue
=> fix(fe2) Remove @mouseleave from StructureItem

packages/frontend-2/components/dashboard/ProjectCard.vue
=> Fix: Update dashboard project card styling

packages/server/modules/core/helpers/userHelper.ts
=> fix(users): verified should be a public limited user field

packages/frontend-2/components/common/Card.vue, packages/frontend-2/components/dashboard/Sidebar.vue, packages/frontend-2/components/workspaces/Promo/Banner.vue, packages/frontend-2/components/workspaces/Promo/Page.vue
Updating content provided by Dim for Workspace Explainer. 
Remove conditional from Sidebar to allow users to see Workspaces, even if they have 0 workspaces.
=> feat(fe2): Update Content. Remove check for workspaces.length

packages/server/modules/workspaces/services/invites.ts, packages/server/modules/workspaces/tests/helpers/creation.ts, packages/server/modules/workspaces/tests/integration/invites.graph.spec.ts
=> fix(workspaceInvites): add email policy validation to emails and users too

packages/frontend-2/components/project/PendingFileImportStatus.vue, packages/frontend-2/components/project/page/models/Actions.vue, packages/frontend-2/components/project/page/models/Card.vue
Fix this file upload height to make it flex-1 and hide certain items when logged out
=> Fix: File uploading message height

packages/frontend-2/components/auth/VerificationReminderMenuNotice.vue, packages/frontend-2/components/header/NavNotifications.vue
Slightly tweaking the notifications styling to align a bit nicer
=> Fix: Update notifications styling

packages/frontend-2/components/settings/workspaces/General.vue
Small event name mistake that slipped in
=> Fix: fix event name

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/materials/Materials.ts
Fixed an issue were text with no material would get batched together on the default null text material, however text batching is not implemented and only the first text in batch was rendered
=> GH Text with no material Fix

packages/ui-components/src/components/layout/sidebar/menu/group/Group.vue, packages/ui-components/src/components/layout/sidebar/menu/group/Item.vue
Changes from this video:
https://github.com/user-attachments/assets/74ccb786-859f-4b0a-ac5e-c3f159ba2eed
=> fix(fe2): Updates to settings from Michal's testing

packages/frontend-2/components/form/select/WorkspaceRoles.vue, packages/frontend-2/components/settings/workspaces/members/MembersTable.vue
We should explitcilty check for false, if null its fine
=> Fix: Role input conditional

packages/ui-components/src/components/layout/sidebar/menu/group/Group.vue
caused by SSR-incompatible code
=> fix(fe2): sidebar flashing in post page load

packages/frontend-2/components/project/page/models/Actions.vue
=> fix(fe2): Update HorizontalDirection for model card

packages/server/modules/auth/strategies/azureAd.ts, packages/server/modules/auth/strategies/github.ts, packages/server/modules/auth/strategies/google.ts, packages/server/modules/auth/strategies/local.ts, packages/server/modules/auth/strategies/oidc.ts, packages/server/modules/auth/tests/helpers/registration.ts, packages/server/modules/auth/tests/integration/registration.spec.ts, packages/server/modules/core/services/users.js
=> fix(server): auto-verify on invited server registration

packages/frontend-2/components/workspace/invite/DiscoverableWorkspaceBanner.vue
=> chore(workspaces): update discoverability message

packages/frontend-2/components/workspace/header/Header.vue
=> fix(fe2): workspace header hydration mismatch

packages/server/modules/serverinvites/services/projectInviteManagement.ts
=> fix(workspaceInvites): fix error message

packages/frontend-2/components/settings/workspaces/members/GuestsTable.vue
=> feat(fe2): Add Remove User to guests table

packages/server/modules/workspaces/errors/workspace.ts, packages/server/modules/workspaces/graph/resolvers/workspaces.ts, packages/server/modules/workspaces/services/management.ts, packages/server/modules/workspaces/tests/helpers/creation.ts, packages/server/modules/workspaces/tests/unit/services/management.spec.ts
=> feat(workspaces): do not allow discoverablity if no verified domains

packages/frontend-2/components/workspaces/Promo/Banner.vue, packages/frontend-2/components/workspaces/Promo/Page.vue
=> fix(fe2): Remove check for admin in workspace page create workspace button

packages/server/modules/workspaces/graph/resolvers/workspaces.ts, packages/server/modules/workspaces/tests/integration/workspaces.graph.spec.ts
=> chore(workspaces): fix build

packages/viewer/src/modules/extensions/FilteringExtension.ts
=> WEB-1793: Numeric filters exclude `0` values

packages/frontend-2/components/project/page/models/Card.vue
=> Fix: Fix truncate for project card

packages/frontend-2/components/settings/workspaces/General/LeaveDialog.vue
Like earlier task to do this to delete, we also should redirect home on successfully leaving a workspace
=> fix(fe2): Redirect home on leaving workspace

packages/frontend-2/components/billing/Summary.vue, packages/frontend-2/components/settings/workspaces/Billing.vue, packages/server/modules/workspaces/graph/resolvers/workspaces.ts, packages/server/modules/workspaces/tests/integration/workspaces.graph.spec.ts
=> feat(workspaces): do not discount

packages/frontend-2/components/settings/shared/ChangeRoleDialog.vue, packages/frontend-2/components/settings/workspaces/members/MembersTable.vue
=> Fix: Add non compliancy warning to change role modal

packages/frontend-2/components/settings/user/Developer.vue
Reported by @oguzhankoral in discord:
=> fix(fe2): Fix scope display in developer settings

packages/viewer-sandbox/src/Sandbox.ts, packages/viewer/src/modules/loaders/Speckle/SpeckleConverter.ts
Fixes https://linear.app/speckle/issue/WEB-1816/issues-with-diffing-and-dui3-instances
- `convertInstances` from `SpeckleConverter` now limits it's `walkAsync` calls to it's own subtree (which is the right thing to do)
=> Fixes diffing errors with DUI3 instances

packages/frontend-2/components/projects/DashboardEmptyState.vue
=> Fix: Change new project button copy and text

packages/frontend-2/components/project/page/InviteDialog.vue, packages/frontend-2/components/project/page/team/PermissionSelect.vue, packages/frontend-2/components/project/page/team/dialog/invite-user/ServerUserRow.vue, packages/frontend-2/lib/projects/helpers/components.ts, packages/server/modules/workspaces/services/invites.ts, packages/server/modules/workspaces/tests/integration/invites.graph.spec.ts
=> fix: disallow workspace guests to be invited as project owners

packages/frontend-2/components/project/page/settings/webhooks/Webhooks.vue, packages/tailwind-theme/src/plugin.ts, packages/tailwind-theme/src/preset.ts, packages/ui-components/src/components/form/Switch.vue
Update to new style, as seen here:
https://www.figma.com/design/z9qYUyM3kLH534M19jvCGE/Michal's-library-WIP?node-id=2486-16333&node-type=FRAME&t=6H20EJPyYQ6itPTo-0
=> fix(ui-components): Update switch to match new design system

packages/frontend-2/components/invite/Banner.vue
Removed hover. 
Added border colour
=> fix(fe2): Updating styling of invite banner

packages/server/modules/cli/commands/download/commit.ts, packages/server/modules/cross-server-sync/domain/operations.ts, packages/server/modules/cross-server-sync/services/commit.ts, packages/server/modules/cross-server-sync/services/project.ts
=> chore(server): cross-server-sync IoC Part 1

packages/server/modules/cli/commands/download/project.ts, packages/server/modules/cross-server-sync/domain/operations.ts, packages/server/modules/cross-server-sync/services/onboardingProject.ts, packages/server/modules/cross-server-sync/services/project.ts
=> chore(server): cross-server-sync IoC Part 2

packages/server/modules/core/services/streams/onboarding.ts, packages/server/modules/cross-server-sync/domain/operations.ts, packages/server/modules/cross-server-sync/index.ts, packages/server/modules/cross-server-sync/services/onboardingProject.ts
=> chore(server): cross-server-sync IoC Part 3

packages/frontend-2/components/common/Card.vue, packages/frontend-2/components/workspace/ProjectList.vue, packages/frontend-2/components/workspace/header/Header.vue
=> Feat: Empty state for workspaces

packages/frontend-2/components/workspace/invite/DiscoverableWorkspaceBanner.vue
- We want to shorten in
- Shortens in
[Context](https://discord.com/channels/726756379083145269/1186641309570699304/1282688867689824350)
=> chore(workspaces): shorten discoverable workspace copy

packages/server/modules/apiexplorer/index.ts
=> chore(server): migrate apiexplorer module to ts

packages/frontend-2/components/form/select/WorkspaceRoles.vue, packages/frontend-2/components/settings/shared/ChangeRoleDialog.vue, packages/frontend-2/components/settings/workspaces/members/MembersTable.vue, packages/frontend-2/components/settings/workspaces/members/TableHeader.vue
Add filter to workspace members table to filter on role
=> Feat: add filter for workspace members table

packages/server/modules/emails/domain/operations.ts, packages/server/modules/emails/repositories/index.ts, packages/server/modules/emails/services/verification/request.ts
=> chore(server): emails IoC 3 - deleteOldAndInsertNewVerificationFactory

packages/server/modules/core/dbSchema.ts, packages/server/modules/emails/domain/operations.ts, packages/server/modules/emails/graph/resolvers/index.ts, packages/server/modules/emails/repositories/index.ts, packages/server/modules/emails/services/verification/finalize.ts, packages/server/modules/emails/tests/verifications.spec.ts
=> chore(server): emails IoC 2 - deleteVerificationsFactory

packages/server/modules/emails/graph/resolvers/index.ts, packages/server/modules/emails/services/verification/request.ts, packages/server/modules/emails/tests/verifications.spec.ts
=> chore(server): emails IoC 5 - requestEmailVerificationFactory

packages/server/modules/core/graph/resolvers/userEmails.ts, packages/server/modules/core/services/users.js, packages/server/modules/core/tests/integration/userEmails.graph.spec.ts, packages/server/modules/core/tests/integration/userEmails.spec.ts, packages/server/modules/core/tests/usersGraphql.spec.ts, packages/server/modules/emails/graph/resolvers/index.ts, packages/server/modules/emails/services/verification/request.ts, packages/server/modules/emails/tests/verifications.spec.ts, packages/server/modules/serverinvites/graph/resolvers/serverInvites.ts, packages/server/modules/workspaces/graph/resolvers/workspaces.ts
=> chore(server): emails IoC 6 - sendVerificationEmailFactory

packages/server/modules/emails/domain/operations.ts, packages/server/modules/emails/index.ts, packages/server/modules/emails/services/verification/request.ts
=> chore(server): emails IoC 7 - initializeVerificationOnRegistrationFactory

packages/server/modules/core/graph/resolvers/admin.ts, packages/server/modules/stats/graph/resolvers/stats.ts, packages/server/modules/stats/repositories/index.ts, packages/server/modules/stats/tests/stats.spec.ts
=> chore(server): stats IoC 1 - getTotalStreamCountFactory

packages/server/modules/stats/graph/resolvers/stats.ts, packages/server/modules/stats/repositories/index.ts, packages/server/modules/stats/tests/stats.spec.ts
=> chore(server): stats IoC 2 - getTotalCommitCountFactory

packages/server/modules/stats/graph/resolvers/stats.ts, packages/server/modules/stats/repositories/index.ts, packages/server/modules/stats/tests/stats.spec.ts
=> chore(server): stats IoC 3 - getTotalObjectCountFactory

packages/server/modules/core/graph/resolvers/admin.ts, packages/server/modules/stats/graph/resolvers/stats.ts, packages/server/modules/stats/repositories/index.ts, packages/server/modules/stats/tests/stats.spec.ts
=> chore(server): stats IoC 4 - getTotalUserCountFactory

packages/server/modules/stats/graph/resolvers/stats.ts, packages/server/modules/stats/repositories/index.ts, packages/server/modules/stats/tests/stats.spec.ts
=> chore(server): stats IoC 5 - getStreamHistoryFactory

packages/server/modules/stats/graph/resolvers/stats.ts, packages/server/modules/stats/repositories/index.ts, packages/server/modules/stats/tests/stats.spec.ts
=> chore(server): stats IoC 6 - getCommitHistoryFactory

packages/server/modules/stats/graph/resolvers/stats.ts, packages/server/modules/stats/repositories/index.ts, packages/server/modules/stats/tests/stats.spec.ts
=> chore(server): stats IoC 7 - getObjectHistoryFactory

packages/server/modules/stats/graph/resolvers/stats.ts, packages/server/modules/stats/repositories/index.ts, packages/server/modules/stats/tests/stats.spec.ts
=> chore(server): stats IoC 8 - getUserHistoryFactory

packages/server/modules/accessrequests/repositories/index.ts, packages/server/modules/accessrequests/services/stream.ts
=> chore(server): accessrequests IoC 1 - getPendingAccessRequestsFactory

packages/server/modules/accessrequests/repositories/index.ts, packages/server/modules/accessrequests/services/stream.ts, packages/server/modules/accessrequests/tests/projectAccessRequests.spec.ts, packages/server/modules/accessrequests/tests/streamAccessRequests.spec.ts, packages/server/modules/notifications/services/handlers/newStreamAccessRequest.ts
=> chore(server): accessrequests IoC 2 - getPendingAccessRequestFactory

packages/server/modules/accessrequests/repositories/index.ts, packages/server/modules/accessrequests/services/stream.ts, packages/server/modules/accessrequests/tests/projectAccessRequests.spec.ts, packages/server/modules/accessrequests/tests/streamAccessRequests.spec.ts
=> chore(server): accessrequests IoC 3 - deleteRequestByIdFactory

packages/server/modules/accessrequests/repositories/index.ts, packages/server/modules/accessrequests/services/stream.ts
=> chore(server): accessrequests IoC 4 - createNewRequestFactory

packages/dui3/components/wizard/ModelSelector.vue, packages/dui3/components/wizard/ProjectSelector.vue
=> Fix(dui3): CNX-437 styling create new project/model dialogs

packages/frontend-2/components/invite/Banner.vue, packages/frontend-2/components/workspace/invite/DiscoverableWorkspaceBanner.vue, packages/frontend-2/lib/workspaces/composables/management.ts
Adds event for "Workspace Joined" for discovery banner, invite banner, and email/url invites
=> Feat: Add Workspace Joined event

packages/server/modules/accessrequests/index.ts, packages/server/modules/accessrequests/services/eventListener.ts
=> chore(server): accessrequests IoC 6 - initializeEventListenerFactory

packages/server/modules/accessrequests/domain/operations.ts, packages/server/modules/accessrequests/graph/resolvers/index.ts, packages/server/modules/accessrequests/repositories/index.ts, packages/server/modules/accessrequests/services/stream.ts
=> chore(server): accessrequests IoC 7 - getUserProjectAccessRequestFactory

packages/server/modules/accessrequests/domain/operations.ts, packages/server/modules/accessrequests/graph/resolvers/index.ts, packages/server/modules/accessrequests/repositories/index.ts, packages/server/modules/accessrequests/services/stream.ts, packages/server/modules/accessrequests/tests/projectAccessRequests.spec.ts
=> chore(server): accessrequests IoC 8 - requestProjectAccess

packages/server/modules/accessrequests/domain/operations.ts, packages/server/modules/accessrequests/graph/resolvers/index.ts, packages/server/modules/accessrequests/services/stream.ts, packages/server/modules/accessrequests/tests/streamAccessRequests.spec.ts
=> chore(server): accessrequests IoC 9 - requestStreamAccess

packages/server/modules/accessrequests/domain/operations.ts, packages/server/modules/accessrequests/graph/resolvers/index.ts, packages/server/modules/accessrequests/repositories/index.ts, packages/server/modules/accessrequests/services/stream.ts
=> chore(server): accessrequests IoC 10 - getPendingStreamRequestsFactory

packages/server/modules/accessrequests/domain/operations.ts, packages/server/modules/accessrequests/graph/resolvers/index.ts, packages/server/modules/accessrequests/repositories/index.ts, packages/server/modules/accessrequests/services/stream.ts
=> chore(server): accessrequests IoC 11 - processPendingStreamRequestFactory

packages/server/modules/fileuploads/domain/operations.ts, packages/server/modules/fileuploads/graph/resolvers/fileUploads.ts, packages/server/modules/fileuploads/index.js, packages/server/modules/fileuploads/repositories/fileUploads.ts, packages/server/modules/fileuploads/services/resultListener.ts, packages/server/modules/shared/utils/subscriptions.ts
=> chore(server): fileuploads IoC 1 - listenForImportUpdatesFactory

packages/server/modules/fileuploads/graph/resolvers/fileUploads.ts, packages/server/modules/fileuploads/repositories/fileUploads.ts
=> chore(server): fileuploads IoC 2 - getStreamFileUploadsFactory

packages/server/package.json, yarn.lock
=> chore: update vulnerable body-parser version

packages/server/modules/fileuploads/domain/operations.ts, packages/server/modules/fileuploads/index.js, packages/server/modules/fileuploads/index.ts, packages/server/modules/fileuploads/repositories/fileUploads.ts, packages/server/modules/fileuploads/services/management.ts, packages/server/package.json, yarn.lock
=> chore(server): fileuploads IoC 3 - insertNewUploadAndNotifyFactory

packages/server/modules/blobstorage/index.js, packages/server/modules/blobstorage/repositories/index.ts, packages/server/modules/blobstorage/services.js
=> chore(server): blobstorage IoC 2 - getAllStreamBlobIdsFactory

packages/server/modules/blobstorage/domain/operations.ts, packages/server/modules/blobstorage/domain/operationts.ts, packages/server/modules/blobstorage/domain/types.ts, packages/server/modules/blobstorage/index.js, packages/server/modules/blobstorage/repositories/index.ts, packages/server/modules/blobstorage/services.js, packages/server/modules/blobstorage/services/upload.ts, packages/server/modules/blobstorage/tests/blobstorage.spec.js, packages/server/modules/gendo/services/index.ts
=> chore(server): blobstorage IoC 3 - uploadFileStreamFactory

packages/server/modules/workspaces/services/management.ts
- Caught some leftover/redundant logic from earlier work on roles
- Took a pass at simplifying, confirmed tests passed/behavior stayed the same
=> chore(workspaces): simplify role update logic

packages/server/modules/blobstorage/graph/resolvers/index.ts, packages/server/modules/blobstorage/repositories/index.ts, packages/server/modules/blobstorage/services.js, packages/server/modules/blobstorage/tests/blobstorage.spec.js
=> chore(server): blobstorage IoC 6 - blobCollectionSummaryFactory

packages/server/modules/blobstorage/index.js, packages/server/modules/blobstorage/services.js, packages/server/modules/blobstorage/services/management.ts, packages/server/modules/blobstorage/tests/blobstorage.spec.js, packages/server/modules/gendo/services/index.ts
=> chore(server): blobstorage IoC 7 - getFileStreamFactory

packages/server/modules/blobstorage/domain/operations.ts, packages/server/modules/blobstorage/graph/resolvers/index.ts, packages/server/modules/blobstorage/index.js, packages/server/modules/blobstorage/repositories/index.ts, packages/server/modules/blobstorage/services.js, packages/server/modules/blobstorage/services/management.ts, packages/server/modules/blobstorage/tests/blobstorage.spec.js
=> chore(server): blobstorage IoC 8 - markUploadXXXFactories

packages/server/modules/pwdreset/domain/operations.ts, packages/server/modules/pwdreset/repositories/index.ts, packages/server/modules/pwdreset/rest/index.ts, packages/server/modules/pwdreset/services/finalize.ts, packages/server/modules/pwdreset/services/request.ts
=> chore(server): pwdreset IoC 2 - requestPasswordRecoveryFactory

packages/server/modules/pwdreset/domain/operations.ts, packages/server/modules/pwdreset/repositories/index.ts, packages/server/modules/pwdreset/rest/index.ts, packages/server/modules/pwdreset/services/finalize.ts
=> chore(server): pwdreset IoC 3 - finalizePasswordResetFactory

packages/server/modules/notifications/domain/operations.ts, packages/server/modules/notifications/graph/resolvers/userNotificationPreferences.ts, packages/server/modules/notifications/repositories.ts, packages/server/modules/notifications/services/handlers/activityDigest.ts, packages/server/modules/notifications/services/notificationPreferences.ts, packages/server/modules/notifications/tests/notificationsPreferences.spec.ts
=> chore(server): notifications IoC 1 - getUserNotificationPreferencesFactory

packages/server/modules/notifications/domain/operations.ts, packages/server/modules/notifications/graph/resolvers/userNotificationPreferences.ts, packages/server/modules/notifications/repositories.ts, packages/server/modules/notifications/services/notificationPreferences.ts, packages/server/modules/notifications/tests/notificationsPreferences.spec.ts
=> chore(server): notifications IoC 2 - updateNotificationPreferencesFactory

packages/server/modules/notifications/domain/operations.ts, packages/server/modules/notifications/services/handlers/activityDigest.ts, packages/server/modules/notifications/services/notificationPreferences.ts, packages/server/modules/notifications/tests/activityDigest.spec.ts
=> chore(server): notifications IoC 3 - digestNotificationEmailHandler

packages/server/modules/notifications/services/handlers/mentionedInComment.ts
=> chore(server): notifications IoC 4 - mentionedInCommentHandlerFactory

packages/shared/src/index.ts, packages/shared/src/workspaces/errors/index.ts, packages/shared/src/workspaces/index.ts
Implement workspace slug validation with custom error handling in the shared package.
This includes a reusable validation function, exported regex constants, and a new InvalidWorkspaceSlugError class.
=> feat(shared): Add workspace slug validation and errors

packages/server/modules/previews/domain/operations.ts, packages/server/modules/previews/index.js, packages/server/modules/previews/repository/previews.ts, packages/server/modules/previews/services/management.ts
=> chore(server): previews IoC 2 - getObjectPreviewBufferOrFilepathFactory

packages/server/modules/previews/domain/operations.ts, packages/server/modules/previews/domain/types.ts, packages/server/modules/previews/index.js, packages/server/modules/previews/services/management.ts
=> chore(server): previews IoC 3 - sendObjectPreviewFactory

packages/server/modules/previews/index.js, packages/server/modules/previews/services/resultListener.ts
=> chore(server): previews IoC 5 - listenForPreviewGenerationUpdatesFactory

packages/dui3/app.vue, packages/dui3/components/header/NavBar.vue, packages/dui3/lib/core/composables/updateConnector.ts, packages/dui3/store/hostApp.ts
✅ TESTED on production by small tweak on editing the URL.
**When new version available**
**When up-to-date (as before)**
=> Feat(dui3): CNX-434 allow users to update individual connectors based on

packages/server/modules/auth/domain/operations.ts, packages/server/modules/auth/domain/types.ts, packages/server/modules/auth/graph/resolvers/apps.js, packages/server/modules/auth/repositories/apps.ts, packages/server/modules/auth/services/apps.js, packages/server/modules/auth/tests/apps.spec.js, packages/server/modules/core/helpers/types.ts
=> chore(server): auth IoC 2 - getAllPublicAppsFactory

packages/server/modules/activitystream/domain/operations.ts, packages/server/modules/activitystream/repositories/index.ts, packages/server/modules/activitystream/services/summary.ts
=> [IoC 2] Alessandro/web 943 get active user stream

packages/server/modules/auth/domain/operations.ts, packages/server/modules/auth/domain/types.ts, packages/server/modules/auth/graph/resolvers/apps.js, packages/server/modules/auth/repositories/apps.ts, packages/server/modules/auth/services/apps.js
=> chore(server): auth IoC 3 - getAllAppsCreatedByUserFactory

packages/server/modules/auth/domain/operations.ts, packages/server/modules/auth/domain/types.ts, packages/server/modules/auth/graph/resolvers/apps.js, packages/server/modules/auth/repositories/apps.ts, packages/server/modules/auth/services/apps.js
=> chore(server): auth IoC 4 - getAllAppsAuthorizedByUserFactory

packages/server/modules/auth/domain/operations.ts, packages/server/modules/auth/domain/types.ts, packages/server/modules/auth/graph/resolvers/apps.js, packages/server/modules/auth/repositories/apps.ts, packages/server/modules/auth/services/apps.js, packages/server/modules/auth/tests/apps.spec.js, packages/server/modules/core/tests/apitokens.spec.ts
=> chore(server): auth IoC 5 - createAppFactory

packages/server/modules/automate/domain/operations.ts, packages/server/modules/automate/events/automations.ts, packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/repositories/automations.ts, packages/server/modules/automate/rest/authGithubApp.ts, packages/server/modules/automate/services/authCode.ts, packages/server/modules/automate/services/automationManagement.ts, packages/server/modules/automate/services/functionManagement.ts, packages/server/modules/automate/tests/automations.spec.ts, packages/server/modules/automate/tests/trigger.spec.ts, packages/server/test/speckle-helpers/automationHelper.ts
=> chore(server): automate IoC 1 - createAutomationFactory

packages/server/modules/automate/domain/operations.ts, packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/repositories/automations.ts, packages/server/modules/automate/services/automationManagement.ts, packages/server/modules/automate/services/encryption.ts, packages/server/modules/automate/services/trigger.ts, packages/server/modules/automate/tests/trigger.spec.ts, packages/server/test/speckle-helpers/automationHelper.ts
=> chore(server): automate IoC 2 - createTestAutomationFactory

packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/services/automationManagement.ts, packages/server/modules/automate/services/encryption.ts, packages/server/test/speckle-helpers/automationHelper.ts
=> chore(server): automatie IoC 4 - createAutomationRevisionFactory

packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/index.ts, packages/server/modules/automate/services/encryption.ts, packages/server/modules/automate/services/trigger.ts, packages/server/modules/automate/tests/trigger.spec.ts, packages/server/test/speckle-helpers/automationHelper.ts
=> chore(server): automate IoC 5.5 - encryption service cleanup

packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/rest/authGithubApp.ts, packages/server/modules/automate/services/functionManagement.ts
=> chore(server): automate IoC 6 - functionManagement cleanup

packages/server/modules/automate/domain/operations.ts, packages/server/modules/automate/domain/types.ts, packages/server/modules/automate/events/runs.ts, packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/repositories/automations.ts, packages/server/modules/automate/services/runsManagement.ts, packages/server/modules/automate/tests/trigger.spec.ts
=> chore(server): automate IoC 7 - reportFunctionRunStatusFactory

packages/server/modules/automate/domain/operations.ts, packages/server/modules/automate/domain/types.ts, packages/server/modules/automate/events/automations.ts, packages/server/modules/automate/events/runs.ts, packages/server/modules/automate/index.ts, packages/server/modules/automate/repositories/automations.ts, packages/server/modules/automate/services/subscriptions.ts
=> chore(server): automate IoC 8 - subscriptions service

packages/server/modules/automate/domain/operations.ts, packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/index.ts, packages/server/modules/automate/repositories/automations.ts, packages/server/modules/automate/services/tracking.ts, packages/server/modules/automate/services/trigger.ts, packages/server/modules/automate/tests/trigger.spec.ts
=> chore(server): automate IoC 9 - setupRunFinishedTrackingFactory

packages/server/modules/automate/domain/operations.ts, packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/repositories/automations.ts, packages/server/modules/automate/services/trigger.ts, packages/server/modules/automate/tests/trigger.spec.ts
=> chore(server): automate IoC 11 - manuallyTriggerAutomationFactory

packages/server/modules/automate/domain/operations.ts, packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/index.ts, packages/server/modules/automate/repositories/automations.ts, packages/server/modules/automate/services/trigger.ts, packages/server/modules/automate/tests/trigger.spec.ts, packages/server/modules/core/loaders.ts
=> chore(server): automate IoC 12 - createTestAutomationRunFactory

packages/server/modules/automate/domain/operations.ts, packages/server/modules/automate/repositories/automations.ts, packages/server/modules/automate/rest/logStream.ts, packages/server/modules/shared/authz.ts
=> chore(server): automate IoC 13 - logStream API

packages/server/modules/automate/domain/operations.ts, packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/repositories/automations.ts, packages/server/modules/automate/services/runsManagement.ts, packages/server/modules/automate/tests/trigger.spec.ts, packages/server/modules/core/loaders.ts
=> chore(server): automate IoC 14 - dataloaders

.circleci/config.yml, packages/shared/src/environment/index.ts, utils/helm/speckle-server/templates/_helpers.tpl, utils/helm/speckle-server/templates/frontend_2/deployment.yml, utils/helm/speckle-server/values.schema.json, utils/helm/speckle-server/values.yaml
=> feat(workspaces): add workspace sso feature flag

packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/repositories/automations.ts
=> chore(server): automate IoC 15 - Automation.runs

packages/server/modules/automate/graph/resolvers/automate.ts, packages/server/modules/automate/repositories/automations.ts
=> chore(server): automate IoC 16 - Project.automations

packages/server/modules/automate/repositories/automations.ts, packages/server/modules/core/loaders.ts
=> chore(server): automate IoC 17 - getAutomationRunsTriggersFactory

packages/server/modules/comments/domain/operations.ts, packages/server/modules/comments/domain/types.ts, packages/server/modules/comments/events/emitter.ts, packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/helpers/types.ts, packages/server/modules/comments/repositories/comments.ts, packages/server/modules/comments/services/commentTextService.ts, packages/server/modules/comments/services/index.ts, packages/server/modules/comments/services/management.ts, packages/server/modules/comments/tests/comments.graph.spec.js, packages/server/modules/comments/tests/comments.spec.js, packages/server/modules/core/services/streams/clone.ts
=> chore(server): comments IoC 1 - createComment

packages/server/modules/comments/domain/operations.ts, packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/repositories/comments.ts, packages/server/modules/comments/services/index.ts, packages/server/modules/comments/services/management.ts, packages/server/modules/comments/tests/comments.spec.js
=> chore(server): comments IoC 2 - createCommentReplyFactory

packages/viewer-sandbox/src/main.ts, packages/viewer/src/modules/loaders/Speckle/SpeckleConverter.ts
Fixes an issue where the converter would fail to convert display values that were not directly renderable objects (like Breps). Issue originally reported here https://speckle.community/t/visualisation-error-in-the-new-web-speckle-app/13803/4
=> Breps as `displayValue`

packages/frontend-2/components/settings/workspaces/members/GuestsTable.vue, packages/frontend-2/lib/settings/composables/menu.ts
=> Feat: Enable billing page for members

packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/services/index.ts, packages/server/modules/comments/tests/comments.spec.js
=> chore(server): comments IoC 4 - archiveCommentFactory

packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/repositories/comments.ts, packages/server/modules/comments/services/index.ts, packages/server/modules/comments/tests/comments.spec.js, packages/server/modules/core/loaders.ts
=> chore(server): comments IoC 6 - index service remaining

packages/server/modules/activitystream/services/commentActivity.ts, packages/server/modules/comments/domain/operations.ts, packages/server/modules/comments/domain/types.ts, packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/repositories/comments.ts, packages/server/modules/comments/services/data.ts, packages/server/modules/core/loaders.ts, packages/server/modules/core/services/commit/viewerResources.ts
=> chore(server): comments IoC 7 - convertLegacyDataToStateFactory

packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/services/management.ts
=> chore(server): comments IoC 8 - authorize(Project)CommentAccessFactory

packages/server/modules/cli/commands/download/commit.ts, packages/server/modules/cli/commands/download/project.ts, packages/server/modules/comments/domain/operations.ts, packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/services/management.ts, packages/server/modules/cross-server-sync/index.ts, packages/server/modules/cross-server-sync/services/commit.ts
=> chore(server): comments IoC 10 - createCommentReplyAndNotifyFactory

packages/server/modules/comments/domain/operations.ts, packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/services/management.ts
=> chore(server): comments IoC 11 editCommentAndNotifyFactory

packages/server/modules/comments/domain/operations.ts, packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/services/management.ts
=> chore(server): comments IoC 12 - archiveCommentAndNotifyFactory

packages/server/modules/comments/index.ts, packages/server/modules/comments/services/notifications.ts
=> chore(server): comments IoC 13 - notifyUsersOnCommentEventsFactory

packages/server/modules/comments/domain/operations.ts, packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/repositories/comments.ts, packages/server/modules/comments/services/retrieval.ts
=> chore(server): comments IoC 14 - getPaginatedCommitCommentsFactory

packages/server/modules/comments/domain/operations.ts, packages/server/modules/comments/graph/resolvers/comments.ts, packages/server/modules/comments/repositories/comments.ts, packages/server/modules/comments/services/retrieval.ts
=> chore(server): comments IoC 15 - getPaginatedBranchCommentsFactory

packages/server/modules/comments/domain/operations.ts, packages/server/modules/comments/repositories/comments.ts, packages/server/modules/core/loaders.ts
=> chore(server): comments IoC 17 - remaining dataloaders

packages/frontend-2/components/project/page/team/PermissionSelect.vue
Remove the hover effects from the permission select.
=> fix(fe2): Remove hover effect for permission select

packages/server/modules/activitystream/domain/operations.ts, packages/server/modules/activitystream/graph/resolvers/activity-new.ts, packages/server/modules/activitystream/repositories/index.ts, packages/server/modules/activitystream/services/index.js
=> ActivityStream IoC 1 getActivityCountByStreamId

packages/server/modules/activitystream/domain/operations.ts, packages/server/modules/activitystream/graph/resolvers/activity.js, packages/server/modules/activitystream/repositories/index.ts, packages/server/modules/activitystream/services/index.js
=> Activitystream Ioc 2 getActivityCountUserId

packages/server/modules/activitystream/domain/operations.ts, packages/server/modules/activitystream/graph/resolvers/activity.js, packages/server/modules/activitystream/repositories/index.ts, packages/server/modules/activitystream/services/index.js
=> Activitystream IoC 4 getActivityCountByResourceId

packages/server/modules/activitystream/domain/operations.ts, packages/server/modules/activitystream/graph/resolvers/activity.js, packages/server/modules/activitystream/repositories/index.ts, packages/server/modules/activitystream/services/index.js
=> Activitystream IoC 5 getUserTimeline

packages/server/modules/activitystream/domain/operations.ts, packages/server/modules/activitystream/graph/resolvers/activity-new.ts, packages/server/modules/activitystream/graph/resolvers/activity.js, packages/server/modules/activitystream/repositories/index.ts, packages/server/modules/activitystream/services/index.js
=> Activitystream IoC 3 getTimelineCount
